import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {registerHooks} from 'node:module';
import {linkedin} from '../src/research';
registerHooks({resolve(s,c,n){if(s==='cloudflare:workers')return {url:'data:text/javascript,export class DurableObject {constructor(ctx,env){this.ctx=ctx;this.env=env}}',shortCircuit:true};return n(s,c);}});
const {Workspace}=await import('../src/workspace');
const admin:any={id:'admin',role:'admin',tenant:'test',name:'Admin',staffId:null};
const mapper:any={...admin,id:'mapper',role:'researcher',staffId:'s'};
const peer:any={...mapper,id:'peer',staffId:'p'};
const partner:any={...admin,id:'partner',role:'partner'};
const members=[{id:'admin',role:'admin',status:'active',name:'Admin'},{id:'mapper',role:'researcher',status:'active',name:'Mapper',staff_id:'s'},{id:'peer',role:'researcher',status:'active',name:'Peer',staff_id:'p'},{id:'partner',role:'partner',status:'active',name:'Partner'}];
function fixture(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');const ctx:any={storage:{sql:{exec(q:string,...p:any[]){if(!p.length&&q.includes('CREATE TABLE')){db.exec(q);return {toArray:()=>[]};}return {toArray:()=>db.prepare(q).all(...p)};}},transactionSync(fn:any){db.exec('BEGIN');try{const v=fn();db.exec('COMMIT');return v;}catch(e){db.exec('ROLLBACK');throw e;}}}};const w=new Workspace(ctx,{});db.exec("INSERT INTO staff VALUES('s','Mapper'),('p','Peer');INSERT INTO teams VALUES('t','Blue');INSERT INTO team_members VALUES('t','s'),('t','p');INSERT INTO searches(id,client,title,partner_id) VALUES('r','Synthetic','One','partner'),('r2','Synthetic','Two','partner');");const run=(a:any,b:any)=>w.research(a,b,members);const state=()=>w.state(admin);const rec=async(id:string)=>(await state()).research.records.find(r=>r.id===id)!;return {db,w,run,state,rec};}
async function setup(f:ReturnType<typeof fixture>,role='r'){if(role==='r')await f.run(admin,{action:'team-reviewer',team_id:'t',reviewer_id:'peer'});const d=await f.run(admin,{action:'strategy-save',role_id:role,content:'Synthetic strategy'});await f.run(admin,{action:'strategy-approve',...await f.rec(d.id!)});const t=await f.run(admin,{action:'company-save',role_id:role,name:'Synthetic Co',scope:'Relevant leaders',team_id:'t',owner_id:'mapper'});return t.id!;}
const item={first_name:'Synthetic',last_name:'Person',name:'Synthetic Person',title:'Leader',url:'https://www.linkedin.com/in/synthetic-person/?tracking=1',rationale:'Relevant leadership evidence'};
async function mapping(f:ReturnType<typeof fixture>,target:string,role='r'){const v=await f.run(mapper,{action:'mapping-add',role_id:role,target_id:target,items:[item]});return v.ids![0];}
test('candidate shared across roles, mappings unique per role, failed batch fully rolls back',async()=>{const f=fixture(),t=await setup(f),id=await mapping(f,t);const t2=await setup(f,'r2');await mapping(f,t2,'r2');let s=await f.state();assert.equal(s.research.records.filter(r=>r.kind==='candidate').length,1);assert.equal(s.research.records.filter(r=>r.kind==='mapping').length,2);await assert.rejects(f.run(mapper,{action:'mapping-add',role_id:'r',target_id:t,items:[{...item,url:'https://www.linkedin.com/in/another-synthetic'},item]}),/already mapped/);s=await f.state();assert.equal(s.research.records.filter(r=>r.kind==='candidate').length,1);assert.equal(s.entries.length,0);assert.equal((await f.rec(id)).status,'Draft');f.db.close();});
test('two-stage reviews enforce owner and order, derive results once, preserve history',async()=>{const f=fixture(),t=await setup(f),id=await mapping(f,t);await f.run(mapper,{action:'mapping-submit',...await f.rec(id)});let r=await f.rec(id);await assert.rejects(f.run(mapper,{...r,action:'mapping-review',decision:'Approve'}),/Self-review/);await assert.rejects(f.run(partner,{...r,action:'mapping-review',decision:'Approve'}),/another person/);await f.run(peer,{...r,action:'mapping-review',decision:'Approve'});await assert.rejects(f.run(peer,{...r,action:'mapping-review',decision:'Approve'}),/changed/);await f.run(partner,{...await f.rec(id),action:'mapping-review',decision:'Approve'});let s=await f.state();assert.deepEqual([s.entries[0].mapped,s.entries[0].peer,s.entries[0].partner],[1,1,1]);await f.run(admin,{...await f.rec(id),action:'mapping-reopen',notes:'New evidence'});await f.run(mapper,{...await f.rec(id),action:'mapping-edit',rationale:'Updated evidence'});await f.run(mapper,{...await f.rec(id),action:'mapping-submit'});s=await f.state();assert.equal(s.entries[0].mapped,1);assert.equal(s.entries[0].partner,0);assert.equal(s.research.events.filter(e=>e.action==='mapping-review').length,2);assert.equal((await f.rec(id)).cycle,2);f.db.close();});
test('rejection requires reason, returned mappings retain review evidence',async()=>{const f=fixture(),t=await setup(f),id=await mapping(f,t);await f.run(mapper,{...await f.rec(id),action:'mapping-submit'});await assert.rejects(f.run(peer,{...await f.rec(id),action:'mapping-review',decision:'Reject',notes:'Wrong fit'}),/rejection reason/);await f.run(peer,{...await f.rec(id),action:'mapping-review',decision:'Needs information',notes:'Explain scope'});assert.equal((await f.rec(id)).status,'Needs information');await f.run(mapper,{...await f.rec(id),action:'mapping-submit'});assert.equal((await f.state()).entries[0].mapped,1);f.db.close();});
test('brief publication is approved-only and anonymous links are disabled',async()=>{const f=fixture();const d=await f.run(admin,{action:'brief-save',role_id:'r',content:'Candidate-safe description'});await assert.rejects(f.run(admin,{...await f.rec(d.id),action:'brief-publish'}),/Approve/);await f.run(admin,{...await f.rec(d.id),action:'brief-approve'});await f.run(admin,{...await f.rec(d.id),action:'brief-publish'});await f.run(admin,{...await f.rec(d.id),action:'brief-save',content:'Unpublished revision'});assert.equal(JSON.parse(f.db.prepare('SELECT data FROM role_publications').get()!.data as string).content,'Candidate-safe description');assert.equal(await f.w.publicBrief('legacy-token'),null);await f.run(admin,{...await f.rec(d.id),action:'brief-unpublish'});assert.equal(f.db.prepare('SELECT * FROM role_publications').all().length,0);await assert.rejects(f.run(mapper,{...await f.rec(d.id),action:'brief-publish'}),/permission/);f.db.close();});
test('claims are race-safe and self-review defaults require reassignment',async()=>{const f=fixture(),t=await setup(f);await f.run(admin,{...await f.rec(t),action:'company-save',owner_id:''});let company=await f.rec(t);await f.run(mapper,{...company,action:'company-claim'});await assert.rejects(f.run(peer,{...company,action:'company-claim'}),/changed/);const id=await mapping(f,t);await assert.rejects(f.run(admin,{...await f.rec(id),action:'mapping-reassign',reviewer_id:'mapper'}),/Self-review/);await assert.rejects(f.run(mapper,{...await f.rec(id),action:'mapping-reassign',reviewer_id:'peer'}),/permission/);f.db.close();});
test('manual output cutover blocks double counting and preserves historical rows',async()=>{const f=fixture();const date=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());f.db.prepare("INSERT INTO assignments(id,search_id,team_id,work_date) VALUES('a','r','t',?)").run(date);f.db.exec("INSERT INTO entries(id,assignment_id,staff_id,mapped) VALUES('e','a','s',3)");const d=await f.run(admin,{action:'strategy-save',role_id:'r',content:'Strategy'});await assert.rejects(f.run(admin,{...await f.rec(d.id!),action:'strategy-approve'}),/manual output/);f.db.exec("UPDATE assignments SET work_date='2025-01-01'");await f.run(admin,{...await f.rec(d.id!),action:'strategy-approve'});assert.equal((await f.state()).entries[0].mapped,3);f.db.prepare("INSERT INTO assignments(id,search_id,team_id,work_date) VALUES('b','r','t',?)").run(date);f.db.exec("INSERT INTO entries(id,assignment_id,staff_id) VALUES('new','b','s')");await assert.rejects(f.w.mutate(admin,'entry',{id:'new',version:1,mapped:5}),/candidate-derived/);f.db.close();});
test('foreign records, invalid links, readonly actors and inactive reviewers are rejected',async()=>{const f=fixture();await assert.rejects(f.run(admin,{action:'strategy-save',role_id:'foreign',content:'No'}),/not found/);await assert.rejects(f.run({...admin,role:'founder'},{action:'strategy-save',role_id:'r',content:'No'}),/read-only/);await assert.rejects(f.run(admin,{action:'team-reviewer',team_id:'t',reviewer_id:'foreign'}),/active workspace/);for(const u of ['javascript:alert(1)','https://linkedin.com.evil.test/in/a','https://user:pass@linkedin.com/in/a','https://linkedin.com/company/a'])assert.throws(()=>linkedin(u));assert.equal(linkedin(item.url),'https://www.linkedin.com/in/synthetic-person');f.db.close();});
test('batch submission rolls back every row on stale versions and review batch keeps individual events',async()=>{const f=fixture(),t=await setup(f);const result=await f.run(mapper,{action:'mapping-add',role_id:'r',target_id:t,items:[item,{...item,name:'Other',url:'https://www.linkedin.com/in/other-synthetic'}]});const ids=result.ids!;await assert.rejects(f.run(mapper,{action:'mapping-batch',operation:'mapping-submit',items:[{id:ids[0],version:1},{id:ids[1],version:99}]}),/changed/);assert.equal((await f.rec(ids[0])).status,'Draft');await f.run(mapper,{action:'mapping-batch',operation:'mapping-submit',items:ids.map((id:string)=>({id,version:1}))});await f.run(peer,{action:'mapping-batch',operation:'mapping-review',decision:'Approve',items:ids.map((id:string)=>({id,version:2}))});const state=await f.state();assert.equal(state.entries[0].mapped,2);assert.equal(state.entries[0].peer,2);assert.equal(state.research.events.filter(e=>e.action==='mapping-review').length,2);f.db.close();});
test('candidate-linked plan cannot be removed even when original manual entry is empty',async()=>{const f=fixture(),t=await setup(f),id=await mapping(f,t);await f.run(mapper,{...await f.rec(id),action:'mapping-submit'});const date=(await f.rec(id)).work_date;const {weekDays}=await import('../src/planning');await f.w.mutate(admin,'week-plan',{search_id:'r',team_id:'t',roster_version:0,week:date,days:weekDays(date).map(d=>({date:d,enabled:d===date,target:10}))});const state=await f.state();const a=state.assignments[0];assert.equal(state.entries.find(e=>e.source==='candidates')?.assignment_id,a.id);await assert.rejects(f.w.mutate(admin,'week-plan',{search_id:'r',team_id:'t',roster_version:0,week:date,days:weekDays(date).map(d=>({date:d,enabled:false,id:d===date?a.id:undefined,version:d===date?a.version:undefined}))}),/Candidate work/);f.db.close();});
test('research screens render empty and populated role states without requiring real accounts',async()=>{const React=await import('react');const {renderToStaticMarkup}=await import('react-dom/server');const {ResearchPanel}=await import('../src/ResearchPanel');const f=fixture(),t=await setup(f);await mapping(f,t);const state=await f.state();for(const view of ['Role repository','My Work','Workflow Monitor'])for(const tab of ['Role brief','Search strategy','Target companies','Candidate mappings','Results']){const html=renderToStaticMarkup(React.createElement(ResearchPanel,{data:{...state,people:members},api:async()=>({}),reload:async()=>{},view,initialRole:'r',initialTab:tab,onDirty:()=>{}}));assert.ok(html.includes('research-panel'));assert.ok(!html.includes('NaN'));}f.db.close();});
const {default:worker}=await import('../src/worker');
test('anonymous brief endpoint is closed and research routes use authoritative member tenant',async()=>{const f=fixture();const env:any={IDENTITY:{getByName:()=>({authenticate:async()=>admin,members:async(t:string)=>{assert.equal(t,'test');return members;}})},WORKSPACE:{getByName:(t:string)=>{assert.equal(t,'test');return f.w;}}};const res=await worker.fetch(new Request('https://app.example.com/api/public-brief?workspace=test&token='+('a'.repeat(72))),env);assert.equal(res.status,404);const mutation=await worker.fetch(new Request('https://app.example.com/api/research',{method:'POST',headers:{Origin:'https://app.example.com','X-Workspace':'foreign'},body:JSON.stringify({action:'strategy-save',role_id:'r',content:'Strategy'})}),env);assert.equal(mutation.status,200);const forbidden=await worker.fetch(new Request('https://app.example.com/api/research',{method:'POST',headers:{Origin:'https://evil.example'},body:'{}'}),env);assert.equal(forbidden.status,403);f.db.close();});
test('future cutover preserves today counts and blocks early candidate submission',async()=>{const f=fixture();await f.run(admin,{action:'team-reviewer',team_id:'t',reviewer_id:'peer'});const d=await f.run(admin,{action:'strategy-save',role_id:'r',content:'Strategy'});const future=new Date(Date.now()+3*86400000).toISOString().slice(0,10);await f.run(admin,{...await f.rec(d.id),action:'strategy-approve',cutover:future});const t=await f.run(admin,{action:'company-save',role_id:'r',name:'Synthetic',team_id:'t',owner_id:'mapper'});const id=await mapping(f,t.id);await assert.rejects(f.run(mapper,{...await f.rec(id),action:'mapping-submit'}),/submissions open/);assert.equal((await f.rec(id)).status,'Draft');assert.equal((await f.state()).entries.length,0);f.db.close();});
test('company master metadata is reusable; role targets can be created before strategy or assignment',async()=>{const f=fixture();const c=await f.run(admin,{action:'company-master',name:'Reusable Co',company_type:'Services',industries:'Healthcare, Retail',offerings:'AI, Data',specialties:'AI, AI',geographies:'US',website:'https://example.com'});let company=await f.rec(c.id);assert.deepEqual(company.specialties,['AI']);const t=await f.run(admin,{action:'company-save',role_id:'r',company_id:c.id});let target=await f.rec(t.id);assert.equal(target.team_id,'');assert.equal(target.priority,'');assert.equal(target.scope,'');assert.equal(target.strategy_revision,null);await f.run(admin,{...company,action:'company-master',name:'Renamed Co',industries:'Healthcare',offerings:'AI'});assert.equal((await f.rec(c.id)).name,'Renamed Co');await assert.rejects(f.run(admin,{...company,action:'company-master',name:'Stale'}),/changed/);await assert.rejects(f.run(admin,{action:'company-save',role_id:'r',company_id:c.id}),/already/);await f.run(admin,{...target,action:'company-save',team_id:'t',owner_id:'mapper',category:'AI firms'});target=await f.rec(t.id);assert.equal(target.company_id,c.id);assert.equal(target.category,'AI firms');assert.equal(target.owner_id,'mapper');await assert.rejects(f.run(mapper,{action:'company-master',name:'Unauthorized'}),/permission/);f.db.close();});
test('bulk company selection is atomic and independent of role strategy approval',async()=>{const f=fixture();const a=await f.run(admin,{action:'company-master',name:'A'}),b=await f.run(admin,{action:'company-master',name:'B'});await assert.rejects(f.run(admin,{action:'company-batch',role_id:'r',company_ids:[a.id,'foreign']}),/not found/);assert.equal((await f.state()).research.records.filter(r=>r.kind==='target').length,0);await f.run(admin,{action:'company-batch',role_id:'r',company_ids:[a.id,b.id],category:'Consulting'});assert.equal((await f.state()).research.records.filter(r=>r.kind==='target').length,2);f.db.close();});
test('two-person teams auto-pair in both directions without a reviewer default',async()=>{const f=fixture(),t=await setup(f);f.db.exec("DELETE FROM research_records WHERE kind='team-reviewer'");const id=await mapping(f,t);await f.run(mapper,{...await f.rec(id),action:'mapping-submit'});assert.equal((await f.rec(id)).reviewer_id,'peer');const other=await f.run(admin,{action:'company-save',role_id:'r',name:'Other company',team_id:'t',owner_id:'peer'});const m=await f.run(peer,{action:'mapping-add',role_id:'r',target_id:other.id,items:[{...item,url:'https://www.linkedin.com/in/peer-candidate'}]});await f.run(peer,{...await f.rec(m.ids[0]),action:'mapping-submit'});assert.equal((await f.rec(m.ids[0])).reviewer_id,'mapper');f.db.close();});
test('pairings and reassignments reject outsiders and departed peer cannot review',async()=>{const f=fixture(),t=await setup(f),id=await mapping(f,t);f.db.exec("INSERT INTO staff VALUES('x','Outside');INSERT INTO teams VALUES('outside','Outside');INSERT INTO team_members VALUES('outside','x')");const outsider={id:'outsider',role:'researcher',status:'active',staff_id:'x',name:'Outside'};const ms=[...members,outsider];await assert.rejects(f.w.research(admin,{action:'peer-route',team_id:'t',staff_id:'s',reviewer_id:'outsider'},ms),/same team/);await assert.rejects(f.w.research(admin,{...await f.rec(id),action:'mapping-reassign',reviewer_id:'outsider'},ms),/same team/);await f.run(admin,{action:'peer-route',team_id:'t',staff_id:'s',reviewer_id:'peer'});await assert.rejects(f.run(admin,{action:'peer-route',team_id:'t',staff_id:'s',reviewer_id:'mapper'}),/Self-review/);await f.run(mapper,{...await f.rec(id),action:'mapping-submit'});f.db.exec("DELETE FROM team_members WHERE team_id='t' AND staff_id='p'");await assert.rejects(f.run(peer,{...await f.rec(id),action:'mapping-review',decision:'Approve'}),/same team/);f.db.close();});
test('new daily, company and team screens render; reviewer options exclude self',async()=>{const React=await import('react');const {renderToStaticMarkup}=await import('react-dom/server');const {DailyWork}=await import('../src/DailyWork');const {CompanyUniverse}=await import('../src/CompanyUniverse');const {PeerSetup}=await import('../src/PeerSetup');const f=fixture(),state={...await f.state(),people:members};const shared={data:state,api:async()=>({}),reload:async()=>{},onDirty:()=>{}};assert.ok(renderToStaticMarkup(React.createElement(DailyWork,{...shared,assignments:[],entries:[],renderEntries:()=>null,onOpen:()=>{}})).includes('Group by'));assert.ok(renderToStaticMarkup(React.createElement(CompanyUniverse,shared)).includes('Service offerings'));const peers=renderToStaticMarkup(React.createElement(PeerSetup,shared));assert.ok(peers.includes('Automatic pairing'));assert.ok(peers.includes('Reviewer for Mapper in Blue'));assert.ok(!peers.includes('value="partner"'));f.db.close();});

test('company import combines repeated rows and tags, protects values, checks preview versions and rolls back conflicts',async()=>{
 const f=fixture();const c=await f.run(admin,{action:'company-master',name:'Example Co',tags:'AI',website:'https://example.com',revenue:'100 USD'});
 const rows=[{name:'Example Co',tags:'ai,Data',website:'https://example.com',revenue:'200 USD'},{name:' Example Co ',tags:'Consulting'},{name:'New Co',tags:'AI'},{name:'New Co',tags:'Services'}];
 const preview=await f.run(admin,{action:'company-import',preview:true,rows});assert.equal(preview.plan.length,2);assert.deepEqual(preview.plan[0].tags,['AI','Data','Consulting']);assert.equal(preview.plan[0].revenue,'100 USD');
 await f.run(admin,{action:'company-import',rows,signature:preview.signature});assert.deepEqual((await f.rec(c.id)).tags,['AI','Data','Consulting']);assert.equal((await f.state()).research.records.filter(r=>r.kind==='company').length,2);
 await assert.rejects(f.run(admin,{action:'company-import',rows,signature:preview.signature}),/changed/);
 await assert.rejects(f.run(mapper,{action:'company-import',preview:true,rows}),/permission/);
 const conflict=[{name:'Newer Co'},{name:'Example Co',website:'https://different.example'}];await assert.rejects(f.run(admin,{action:'company-import',rows:conflict,preview:true}),/conflicting/);assert.equal((await f.state()).research.records.filter(r=>r.kind==='company').length,2);
 const replacement=await f.run(admin,{action:'company-import',rows,overwrite:true,preview:true});assert.equal(replacement.plan[0].revenue,'200 USD');f.db.close();
});
test('wave batches preserve role assignment and roll back on stale targets or cross-role permissions',async()=>{
 const f=fixture();const t=await f.run(admin,{action:'company-save',role_id:'r',name:'One'}),u=await f.run(admin,{action:'company-save',role_id:'r2',name:'Two'});
 await assert.rejects(f.run(admin,{action:'target-waves',wave:2,items:[{id:t.id,version:1},{id:u.id,version:9}]}),/changed/);assert.equal((await f.rec(t.id)).wave,null);
 await f.run(admin,{action:'target-waves',wave:2,items:[{id:t.id,version:1},{id:u.id,version:1}]});assert.equal((await f.rec(t.id)).wave,2);assert.equal((await f.rec(u.id)).role_id,'r2');await assert.rejects(f.run(mapper,{action:'target-waves',wave:1,items:[{id:t.id,version:2}]}),/permission/);f.db.close();
});
test('secure candidate invites require email code, hide tokens, bind roles, expire and revoke sessions',async()=>{
 const f=fixture(),t=await setup(f),mid=await mapping(f,t),candidate=(await f.rec(mid)).candidate_id;
 const d=await f.run(admin,{action:'brief-save',role_id:'r',content:'Approved candidate content'});await f.run(admin,{...await f.rec(d.id),action:'brief-approve'});await f.run(admin,{...await f.rec(d.id),action:'brief-publish'});
 await assert.rejects(f.w.candidateInvite(mapper,{role_id:'r',candidate_id:candidate,email:'synthetic@example.com',days:7}),/permission/);
 await assert.rejects(f.w.candidateInvite(admin,{role_id:'r',candidate_id:'unmapped',email:'synthetic@example.com',days:7}),/mapped/);
 const invitation=await f.w.candidateInvite(admin,{role_id:'r',candidate_id:candidate,email:'synthetic@example.com',days:7});
 assert.ok(!JSON.stringify(await f.state()).includes(invitation.token));assert.ok(!JSON.stringify(await f.w.candidateInvites(admin,'r')).includes('token_hash'));
 await assert.rejects(f.w.candidatePage(invitation.token),/Verify/);
 const c=await f.w.candidateCode({token:invitation.token},'ip');assert.equal(c.email,'synthetic@example.com');
 await assert.rejects(f.w.candidateVerify({token:invitation.token,code:'000000'},'ip'),/Incorrect/);assert.equal(f.db.prepare('SELECT attempts FROM candidate_codes').get()?.attempts,1);
 const session=await f.w.candidateVerify({token:invitation.token,code:c.code},'ip');const page=await f.w.candidatePage(session.token,invitation.token);assert.equal(page.content,'Approved candidate content');assert.equal(page.candidate_name,'Synthetic Person');assert.ok(!JSON.stringify(page).includes('rationale'));
 await assert.rejects(f.w.candidatePage(session.token,'other-invitation'),/Verify/);await assert.rejects(f.w.candidateVerify({token:invitation.token,code:c.code},'ip'),/new verification/);
 await f.w.candidateRevoke(admin,invitation.id);await assert.rejects(f.w.candidatePage(session.token),/Verify/);await assert.rejects(f.w.candidateCode({token:invitation.token},'ip'),/unavailable/);
 const newer=await f.w.candidateInvite(admin,{role_id:'r',candidate_id:candidate,email:'synthetic@example.com',days:7});f.db.prepare('UPDATE candidate_invites SET expires=0 WHERE id=?').run(newer.id);await assert.rejects(f.w.candidateCode({token:newer.token},'ip'),/expired/);f.db.close();
});
test('candidate code attempts are bounded, unpublish blocks sessions and publication snapshots exclude drafts',async()=>{
 const f=fixture(),t=await setup(f),mid=await mapping(f,t),candidate=(await f.rec(mid)).candidate_id;
 const d=await f.run(admin,{action:'brief-save',role_id:'r',content:'Approved text',page:{sections:[{heading:'Role',body:'Approved text'}]}});await f.run(admin,{...await f.rec(d.id),action:'brief-approve'});await f.run(admin,{...await f.rec(d.id),action:'brief-publish'});
 const i=await f.w.candidateInvite(admin,{role_id:'r',candidate_id:candidate,email:'synthetic@example.com',days:1}),c=await f.w.candidateCode({token:i.token},'ip');for(let n=0;n<5;n++)await assert.rejects(f.w.candidateVerify({token:i.token,code:'000000'},'ip'));await assert.rejects(f.w.candidateVerify({token:i.token,code:c.code},'ip'),/new verification/);
 const j=await f.w.candidateInvite(admin,{role_id:'r',candidate_id:candidate,email:'synthetic@example.com',days:1}),code=await f.w.candidateCode({token:j.token},'ip'),s=await f.w.candidateVerify({token:j.token,code:code.code},'ip');
 await f.run(admin,{...await f.rec(d.id),action:'brief-save',page:{sections:[{heading:'Role',body:'Unapproved text'}]}});assert.equal((await f.w.candidatePage(s.token)).page.sections[0].body,'Approved text');
 await f.run(admin,{...await f.rec(d.id),action:'brief-unpublish'});await assert.rejects(f.w.candidatePage(s.token),/Verify/);f.db.close();
});

test('document publication never inherits the role title, client or earlier page fields',async()=>{
 const {layoutDocument,freshDocumentPage}=await import('../src/document-layout');const f=fixture();
 const d=layoutDocument([{text:'Synthetic Alpha role',x:50,y:740,width:400,size:30,bold:true,page:1},{text:'Source-only role requirements and responsibilities.',x:50,y:680,width:450,size:12,bold:false,page:1}]);
 const page=freshDocumentPage(d,'synthetic-alpha.pdf','a'.repeat(64));
 const first=await f.run(admin,{action:'brief-save',role_id:'r',content:'Old unrelated content',page:{sections:[{heading:'Old section',body:'Old unrelated content'}],partner_name:'Old partner'}});
 await f.run(admin,{action:'brief-release',role_id:'r',...await f.rec(first.id),page});
 const published=JSON.parse(f.db.prepare('SELECT data FROM role_publications WHERE role_id=?').get('r')!.data as string);
 assert.equal(published.title,'Synthetic Alpha role');assert.equal(published.client,'');assert.equal(published.page.partner_name,'');assert.ok(!JSON.stringify(published).includes('Old unrelated'));assert.equal(published.page.source_text,undefined);assert.equal((await f.rec(first.id)).status,'Approved');assert.equal((await f.rec(first.id)).published_revision,1);
 const before=await f.rec(first.id);await assert.rejects(f.run(mapper,{action:'brief-release',role_id:'r',...before,page}),/permission/);
 await assert.rejects(f.run(admin,{action:'brief-release',role_id:'r',...before,page:{...page,title:'Unrelated company content'}}),/only wording/);
 assert.equal((await f.rec(first.id)).version,before.version);assert.equal(JSON.parse(f.db.prepare('SELECT data FROM role_publications WHERE role_id=?').get('r')!.data as string).title,'Synthetic Alpha role');f.db.close();
});

test('unaccepted people cannot be assigned or paired; active account is required',async()=>{
 const f=fixture();await setup(f);f.db.exec("INSERT INTO staff VALUES('unlinked','Future Teammate');INSERT INTO team_members VALUES('t','unlinked')");
 await assert.rejects(f.run(admin,{action:'peer-route',team_id:'t',staff_id:'s',reviewer_staff_id:'unlinked'}),/same team/);
 assert.equal(f.db.prepare("SELECT COUNT(*) n FROM team_members WHERE staff_id='unlinked'").get()?.n,0);
 const roster=f.db.prepare("SELECT version FROM team_rosters WHERE team_id='t'").get()!.version;
 await assert.rejects(f.w.mutate(admin,'team-members',{id:'t',version:roster,staff_ids:['s','unlinked']},members),/active researcher/);
 const active=[...members,{id:'future-account',name:'Future',role:'researcher',status:'active',staff_id:'unlinked'}];
 await f.w.mutate(admin,'team-members',{id:'t',version:roster,staff_ids:['s','unlinked']},active);
 await f.w.research(admin,{action:'peer-route',team_id:'t',staff_id:'s',reviewer_staff_id:'unlinked'},active);f.db.close();
});
test('unlinked teammates are hidden from reviewer choices',async()=>{
 const f=fixture();f.db.exec("INSERT INTO staff VALUES('unlinked','Future Teammate');INSERT INTO team_members VALUES('t','unlinked')");
 const React=await import('react'),{renderToStaticMarkup}=await import('react-dom/server'),{PeerSetup}=await import('../src/PeerSetup'),{StaffDirectory}=await import('../src/StaffDirectory');
 const data={...await f.state(),people:members},props={data,api:async()=>({}),reload:async()=>{}};
 const html=renderToStaticMarkup(React.createElement(PeerSetup,props));
 assert.ok(!html.includes('Future Teammate'));assert.ok(html.includes('Reviewer for Mapper in Blue'));
 f.db.close();
});

test('candidate directory enforces LinkedIn uniqueness, requires both names and preserves mapping snapshots on contact edits',async()=>{
 const f=fixture();const c=await f.run(mapper,{action:'candidate-save',first_name:'Alex',last_name:'Example',url:'https://linkedin.com/in/Alex-Example/?trk=synthetic',email:'alex@example.com',phone:'+1 555 0100'});
 const candidate=await f.rec(c.id);assert.equal(candidate.url,'https://www.linkedin.com/in/alex-example');
 await assert.rejects(f.run(mapper,{action:'candidate-save',first_name:'Different',last_name:'Spelling',url:'https://www.linkedin.com/in/alex-example'}),/already exists/);
 await assert.rejects(f.run(mapper,{action:'candidate-save',first_name:'Missing',url:'https://www.linkedin.com/in/missing'}),/last name/);
 const m=await f.run(mapper,{action:'mapping-add',role_id:'r',team_id:'t',items:[{candidate_id:c.id,rationale:'Evidence for role one'}]});
 await f.run(mapper,{...candidate,action:'candidate-save',first_name:'Alexander',email:'updated@example.com'});
 assert.equal((await f.rec(c.id)).email,'updated@example.com');assert.equal((await f.rec(m.ids[0])).name,'Alex Example');assert.equal((await f.rec(m.ids[0])).candidate_id,c.id);
 await assert.rejects(f.run(mapper,{...candidate,action:'candidate-save',first_name:'Stale'}),/changed/);f.db.close();
});
test('one candidate links to multiple roles and researchers with independent mapping attribution and review state',async()=>{
 const f=fixture();await setup(f);await setup(f,'r2');
 const c=await f.run(mapper,{action:'candidate-save',first_name:'Shared',last_name:'Candidate',url:'https://www.linkedin.com/in/shared-person'});
 const one=await f.run(mapper,{action:'mapping-add',role_id:'r',team_id:'t',items:[{candidate_id:c.id,rationale:'Role one fit'}]});
 const two=await f.run(peer,{action:'mapping-add',role_id:'r2',team_id:'t',items:[{candidate_id:c.id,rationale:'Role two fit'}]});
 await f.run(mapper,{...await f.rec(one.ids[0]),action:'mapping-submit'});
 const m1=await f.rec(one.ids[0]),m2=await f.rec(two.ids[0]);assert.equal(m1.status,'Peer review');assert.equal(m2.status,'Draft');assert.equal(m1.candidate_id,m2.candidate_id);assert.equal(m1.mapper_id,'mapper');assert.equal(m2.mapper_id,'peer');assert.notEqual(m1.rationale,m2.rationale);
 await assert.rejects(f.run(peer,{action:'mapping-add',role_id:'r',team_id:'t',items:[{candidate_id:c.id}]}),/already mapped/);
 assert.equal((await f.state()).research.records.filter(r=>r.kind==='candidate').length,1);
 const React=await import('react'),{renderToStaticMarkup}=await import('react-dom/server'),{Candidates}=await import('../src/Candidates');const html=renderToStaticMarkup(React.createElement(Candidates,{data:{...await f.state(),people:members},api:async()=>({}),reload:async()=>{},onDirty:()=>{}}));assert.ok(html.includes('Synthetic'));assert.ok(html.includes('One'));assert.ok(html.includes('Two'));assert.ok(html.includes('Mapped by Mapper'));assert.ok(html.includes('Mapped by Peer'));f.db.close();
});
test('admin plus researcher can map under their own identity; researcher permission and team membership are enforced',async()=>{
 const f=fixture();await setup(f);const dual={...mapper,role:'admin',roles:['admin','researcher','partner']},ms=members.map(m=>m.id==='mapper'?{...m,role:'admin',roles:['admin','researcher','partner']}:m);
 const added=await f.w.research(dual,{action:'mapping-add',role_id:'r',team_id:'t',items:[item]},ms);assert.equal((await f.rec(added.ids[0])).mapper_id,mapper.id);
 await f.w.research(dual,{...await f.rec(added.ids[0]),action:'mapping-submit'},ms);assert.equal((await f.rec(added.ids[0])).reviewer_id,'peer');
 await assert.rejects(f.w.research({...dual,roles:['admin']},{action:'mapping-add',role_id:'r2',team_id:'t',items:[item]},ms),/Researcher role/);
 await assert.rejects(f.run(mapper,{action:'mapping-add',role_id:'r2',team_id:'foreign',items:[item]}),/team you belong/);
 await assert.rejects(f.run({...admin,role:'founder'},{action:'candidate-save',...item}),/read-only/);f.db.close();
});
test('read-only candidate and people screens do not offer sourcing writes; teams are visible without duplicate directories',async()=>{
 const f=fixture(),React=await import('react'),{renderToStaticMarkup}=await import('react-dom/server'),{Candidates}=await import('../src/Candidates'),{TeamsPanel}=await import('../src/TeamsPanel');
 const shared={data:{...await f.state(),actor:{...admin,role:'founder'},people:members},api:async()=>({}),reload:async()=>{},onDirty:()=>{}};
 assert.ok(!renderToStaticMarkup(React.createElement(Candidates,shared)).includes('>Add candidate<'));
 const teams=renderToStaticMarkup(React.createElement(TeamsPanel,{...shared,onAdd:()=>{}}));assert.ok(teams.includes('Blue'));assert.ok(!teams.includes('Edit members'));assert.ok(!teams.includes('Edit researcher'));f.db.close();
});

test('explicit target assignment validates researcher team and preserves existing mappings and coverage',async()=>{
 const f=fixture(),target=await setup(f),mid=await mapping(f,target),before=await f.rec(target);
 await f.run(admin,{...before,action:'target-assign',team_id:'t',owner_id:'peer'});const after=await f.rec(target);
 assert.equal(after.owner_id,'peer');assert.equal(after.company_id,before.company_id);assert.equal(after.scope,before.scope);assert.equal((await f.rec(mid)).mapper_id,'mapper');
 await assert.rejects(f.run(admin,{...before,action:'target-assign',team_id:'t',owner_id:'mapper'}),/changed/);
 await assert.rejects(f.run(mapper,{...after,action:'target-assign',team_id:'t',owner_id:'mapper'}),/permission/);
 await assert.rejects(f.run(admin,{...after,action:'target-assign',team_id:'t',owner_id:'partner'}),/researcher linked/);f.db.close();
});

test('candidate spreadsheet import previews and reuses canonical profiles, with idempotent role mapping',async()=>{
 const f=fixture();const rows=[{first_name:'Test',last_name:'Person',url:'https://linkedin.com/in/bulk-person?trk=x',email:'test@example.com'},{first_name:'Duplicate',last_name:'Person',url:'https://www.linkedin.com/in/bulk-person/'}];
 const b={action:'candidate-import',rows,role_id:'r',team_id:'t'};const p=await f.run(mapper,{...b,preview:true});assert.equal(p.plan[1].status,'Duplicate in file');assert.equal((await f.state()).research.records.length,0);
 const result=await f.run(mapper,{...b,signature:p.signature});assert.deepEqual(result,{created:1,reused:0,mapped:1,skipped:1});
 const c=(await f.state()).research.records.find(r=>r.kind==='candidate')!;assert.equal(c.first_name,'Test');const again=await f.run(mapper,{...b,preview:true});assert.equal(again.plan[0].mapping,'Already mapped');assert.equal((await f.run(mapper,{...b,signature:again.signature})).mapped,0);
 const assign={action:'candidate-assign',candidate_ids:[c.id],role_id:'r2',team_id:'t'};const ap=await f.run(peer,{...assign,preview:true});await f.run(peer,{...assign,signature:ap.signature});const maps=(await f.state()).research.records.filter(r=>r.kind==='mapping');assert.equal(maps.length,2);assert.ok(maps.every(m=>m.status==='Draft'));assert.equal(maps.find(m=>m.role_id==='r2')?.mapper_id,'peer');f.db.close();
});
test('candidate import validates rows, stale previews, permissions and atomic rollback',async()=>{
 const f=fixture(),rows=[{first_name:'New',last_name:'Person',url:'https://linkedin.com/in/new-bulk'}],b={action:'candidate-import',rows};
 await assert.rejects(f.run(admin,{...b,preview:true,rows:[...rows,{...rows[0],url:'bad'}]}),/Row 3/);
 await assert.rejects(f.run({...admin,role:'founder'},{...b,preview:true}),/permission/);
 await assert.rejects(f.run(admin,{...b,role_id:'r',team_id:'t',preview:true}),/Researcher/);
 const p=await f.run(admin,{...b,preview:true});await f.run(admin,{action:'candidate-save',...rows[0]});await assert.rejects(f.run(admin,{...b,signature:p.signature}),/changed/);
 await assert.rejects(f.run(mapper,{action:'candidate-assign',candidate_ids:['foreign'],role_id:'r',team_id:'t',preview:true}),/not found/);
 const old=await f.run(admin,{action:'candidate-save',first_name:'Old',last_name:'Name',url:'https://linkedin.com/in/legacy-bulk'});const raw=f.db.prepare('SELECT data FROM research_records WHERE id=?').get(old.id)!.data as string;const data=JSON.parse(raw);delete data.first_name;f.db.prepare('UPDATE research_records SET data=? WHERE id=?').run(JSON.stringify(data),old.id);
 const batch={action:'candidate-import',rows:[{...rows[0],url:'https://linkedin.com/in/rollback-new'},{first_name:'Old',last_name:'Name',url:data.url}],role_id:'r',team_id:'t'};const pre=await f.run(mapper,{...batch,preview:true});await assert.rejects(f.run(mapper,{...batch,signature:pre.signature}),/first name|First name/);assert.ok(!(await f.state()).research.records.some(r=>r.url==='https://www.linkedin.com/in/rollback-new'));f.db.close();
});

test('accepted account may share a display name with legacy staff or another account without breaking state',async()=>{
 const f=fixture();f.db.exec("INSERT INTO staff VALUES('legacy-duplicate','Same Person');INSERT INTO assignments(id,search_id,team_id,work_date) VALUES('old','r','t','2026-09-01');INSERT INTO entries(id,assignment_id,staff_id,mapped) VALUES('old-entry','old','legacy-duplicate',7)");
 const accepted=[...members,{id:'account-one',name:'Same Person',role:'researcher',status:'active',staff_id:'person:account-one'},{id:'account-two',name:'Same Person',role:'researcher',status:'active',staff_id:'person:account-two'}];
 const state=await f.w.state(admin,accepted);assert.equal(state.staff.filter(s=>s.name==='Same Person').length,3);assert.equal(f.db.prepare("SELECT mapped FROM entries WHERE id='old-entry'").get()?.mapped,7);
 const again=await f.w.state(admin,accepted);assert.equal(again.staff.length,state.staff.length);assert.equal(f.db.prepare("SELECT name FROM staff WHERE id='legacy-duplicate'").get()?.name,'Same Person');
 const version=(again.teams.find(t=>t.id==='t') as any).roster_version;await f.w.mutate(admin,'team-members',{id:'t',version,staff_ids:['person:account-one','person:account-two']},accepted);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM team_members WHERE team_id='t'").get()?.n,2);f.db.close();
});
