import {EmailSettings} from './EmailSettings';
import React,{useEffect,useState} from 'react';
export function AccountSettings({api,onDirty,email,reload}:{email:string;reload:()=>Promise<void>;api:(p:string,b?:unknown)=>Promise<any>;onDirty:(v:boolean)=>void}) {
 const [currentPassword,setCurrent]=useState(''),[newPassword,setNew]=useState(''),[confirmPassword,setConfirm]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const [emailDirty,setEmailDirty]=useState(false);
 const dirty=emailDirty||!!(currentPassword||newPassword||confirmPassword);
 useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty]);
 return <><section className="panel"><h2>Change password</h2><p>This changes your account password across all workspaces. Other signed-in sessions will be signed out.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setMessage('');try{await api('change-password',{currentPassword,newPassword,confirmPassword});setCurrent('');setNew('');setConfirm('');setMessage('Password changed. Other sessions have been signed out.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><label>Current password<input disabled={busy||emailDirty} type="password" required maxLength={128} autoComplete="current-password" value={currentPassword} onChange={e=>setCurrent(e.target.value)}/></label><label>New password (12–128 characters)<input disabled={busy||emailDirty} type="password" required minLength={12} maxLength={128} autoComplete="new-password" value={newPassword} onChange={e=>setNew(e.target.value)}/></label><label>Confirm new password<input disabled={busy||emailDirty} type="password" required minLength={12} maxLength={128} autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirm(e.target.value)}/></label>{error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<button className="primary" disabled={busy||emailDirty}>{busy?'Updating…':'Change password'}</button></form></section><EmailSettings api={api} email={email} reload={reload} disabled={busy||!!(currentPassword||newPassword||confirmPassword)} onDirty={setEmailDirty}/></>;
}
