import React,{useMemo,useState} from 'react';
import {actualCoverage} from './actual-coverage';
import {SortableTable} from './SortableTable';
import {displayDate} from './dates';
type R=Record<string,any>;
export function ActualCoverage({records,role,people,staff,onCandidate}:{records:R[];role:string;people:R[];staff:R[];onCandidate:(id:string)=>void}){
 const coverage=useMemo(()=>actualCoverage(records,role),[records,role]);
 const [query,setQuery]=useState(''),[selected,setSelected]=useState(''),[page,setPage]=useState(0);
 const groups=coverage.groups.filter(g=>g.name.toLowerCase().includes(query.toLowerCase())),detail=coverage.groups.find(g=>g.key===selected);
 return <section className="panel"><h2>Actual coverage</h2><p>All candidates linked to this search, including companies outside the target list. Company counts do not depend on assignments or research waves.</p><div className="sheet-toolbar"><strong>{coverage.total} candidates</strong><span>{coverage.companies} companies</span><span>{coverage.unknown} candidates with company not recorded</span></div><p className="fine">Uses the company recorded on the mapping. {coverage.fallback} candidates use their current profile company because no mapping company was recorded. All statuses are included; this is not a sourcing-throughput measure.</p><label>Find company<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Company name"/></label><div className="table-scroll"><SortableTable stateKey={'actual-coverage-'+role} className="sheet-table"><thead><tr><th>Company</th><th>Target list</th><th>Candidates</th><th>Share</th><th>Approved</th><th>Pending review</th><th>Rejected</th><th>Other / not reviewed</th></tr></thead><tbody>{groups.map(g=><tr key={g.key}><td><button className="text-button" onClick={()=>{setSelected(g.key);setPage(0);}}>{g.name}</button></td><td>{g.onTarget===null?'—':g.onTarget?'On target list':'Outside target list'}</td><td>{g.total}</td><td data-sort-value={g.share}>{(g.share*100).toFixed(1)}%</td><td>{g.approved}</td><td>{g.pending}</td><td>{g.rejected}</td><td>{g.other}</td></tr>)}</tbody></SortableTable></div>{!groups.length&&<p>{coverage.total?'No companies match your search.':'No candidates have been linked to this search yet.'}</p>}<p className="fine">Pending review includes team and partner review. Other includes drafts, imported links, needs information and any other status.</p>{detail&&<section aria-label="Company candidates"><div className="section-head"><h3>{detail.name} · {detail.total} candidates</h3><button onClick={()=>setSelected('')}>Close details</button></div><div className="table-scroll"><table className="sheet-table"><thead><tr><th>Candidate</th><th>Mapped by</th><th>Mapping date</th><th>Status</th><th>Company source</th></tr></thead><tbody>{detail.candidates.slice(page*25,(page+1)*25).map((m:R)=><tr key={m.id}><td><button className="text-button" disabled={!m.candidate_id} onClick={()=>onCandidate(m.candidate_id)}>{m.candidateName}</button></td><td>{m.mapper_name||people.find(p=>p.id===m.mapper_id)?.name||staff.find(p=>p.id===m.staff_id)?.name||'Not recorded'}</td><td>{displayDate(m.work_date||m.submitted_at)}</td><td>{m.status||'Not recorded'}</td><td>{detail.key==='unknown'?'Not recorded':m.usedCurrent?'Current candidate profile':'Mapping record'}</td></tr>)}</tbody></table></div><div className="row-actions"><button disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1} of {Math.ceil(detail.total/25)}</span><button disabled={(page+1)*25>=detail.total} onClick={()=>setPage(page+1)}>Next</button></div></section>}</section>;
}
