import {ColumnFilter} from './ColumnFilter';
import {tagCategories,tagOptions,candidateSearchIndex,canImportCandidates} from './candidate-tags';
import {Candidate360} from './Candidate360';
import {candidateColumns,candidateRoleCounts,directoryRows,directoryPage} from './candidate-directory';
import {InlineMapping} from './InlineMapping';
import {CandidateBatch} from './CandidateBatch';
import React,{useEffect,useState,useMemo} from 'react';
import {canPlan,hasRole} from './domain';
import {linkedin} from './research';
type R=Record<string,any>;
type Shared={data:R;api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;onDirty:(v:boolean)=>void};
export function MappingForm({data,api,reload,onClose,initialRole='',targetId='',candidate,onCandidate=()=>{}}:{data:R;api:Shared['api'];reload:Shared['reload'];onClose:()=>void;initialRole?:string;targetId?:string;candidate?:R;onCandidate?:(id:string)=>void}) {
 const records:R[]=data.research?.records||[],target=records.find(r=>r.id===targetId),myTeams=data.teams.filter((t:R)=>data.team_members.some((m:R)=>m.team_id===t.id&&m.staff_id===data.actor.staffId));
 const [role,setRole]=useState(target?.role_id||initialRole),[team,setTeam]=useState(target?.team_id||(myTeams.length===1?myTeams[0].id:''));
 return <section className="panel"><div className="section-head"><h3>Add candidate mapping</h3><button onClick={onClose}>Close entry</button></div>{!initialRole&&!target&&<label>Search<select value={role} onChange={e=>setRole(e.target.value)}><option value="">Choose search</option>{data.searches.map((s:R)=><option key={s.id} value={s.id}>{s.client} — {s.title}</option>)}</select></label>}{!target&&myTeams.length>1&&<label>Research team for this search<select value={team} onChange={e=>setTeam(e.target.value)}><option value="">Choose your team</option>{myTeams.map((t:R)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}{!myTeams.length?<p>Ask your planner to add your active researcher account to a team.</p>:<InlineMapping key={role+team} data={data} role={role} team={team} api={api} reload={reload} onCandidate={onCandidate} initialCandidate={candidate}/>}</section>;
}
export function CandidateProfile({data,id,api,reload,onBack,onDirty,onRole}:{data:R;id:string;api:Shared['api'];reload:Shared['reload'];onBack:()=>void;onDirty:(v:boolean)=>void;onRole?:(id:string)=>void}){
 const records:R[]=data.research?.records||[],c=records.find(r=>r.id===id&&r.kind==='candidate'),[form,setForm]=useState<R|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[detailDirty,setDetailDirty]=useState(false);const canEdit=canPlan(data.actor)||hasRole(data.actor,'data_quality')||hasRole(data.actor,'researcher')||hasRole(data.actor,'partner')||hasRole(data.actor,'engagement');
 useEffect(()=>{onDirty(!!form||detailDirty);return()=>onDirty(false);},[!!form,detailDirty]);
 if(!c)return <section className="panel"><button onClick={onBack}>Back to candidates</button><p>Candidate not found.</p></section>;
 return <section className="panel candidate-profile candidate-vignettes"><div className="section-head profile-hero"><div className="profile-identity"><div className="profile-avatar" aria-hidden="true">{c.name.split(/\s+/).map((n:string)=>n[0]).slice(0,2).join('')}</div><div><h2>{c.name}</h2><p>{[c.title,c.company].filter(Boolean).join(' · ')}</p><div className="profile-contact-line"><span>{c.url?<a href={c.url} target="_blank" rel="noreferrer">LinkedIn profile</a>:'LinkedIn · Not recorded'}</span><span>Email · {c.email||'Not recorded'}</span><span>Phone · {c.phone||'Not recorded'}</span></div></div></div><div className="profile-header-actions"><button onClick={()=>{if((!form&&!detailDirty)||confirm('Discard profile edits?'))onBack();}}>Back to candidates</button>{canEdit&&<button disabled={detailDirty||!!form} onClick={()=>setForm({...c})}>Edit profile</button>}</div></div>{form?<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('research',{...form,action:'candidate-save'});await reload();setForm(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><div className="candidate-fields">{['first_name','last_name','email','phone','title','company'].map(k=><label key={k}>{({first_name:'First name',last_name:'Last name',email:'Email',phone:'Phone',title:'Current title',company:'Current company'} as R)[k]}<input required={['first_name','last_name'].includes(k)} type={k==='email'?'email':'text'} list={k==='company'?'profile-companies':undefined} disabled={busy} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value,company_id:k==='company'?'':form.company_id,create_company:false})}/></label>)}</div><label>Potential to be a client<select value={form.potential_client===undefined?'':String(form.potential_client)} onChange={e=>setForm({...form,potential_client:e.target.value===''?undefined:e.target.value==='true'})}><option value="">Not recorded</option><option value="true">Yes</option><option value="false">No</option></select></label><datalist id="profile-companies">{records.filter(r=>r.kind==='company').map(r=><option key={r.id} value={r.name}/>)}</datalist>{form.company&&!records.some(r=>r.kind==='company'&&r.name.toLowerCase().trim()===form.company.toLowerCase().trim())&&<label className="checkbox"><input type="checkbox" checked={!!form.create_company} onChange={e=>setForm({...form,create_company:e.target.checked})}/>Also add this company to the company master</label>}<div className="row-actions"><button className="primary" disabled={busy}>Save profile</button><button type="button" disabled={busy} onClick={()=>setForm(null)}>Cancel</button></div></form>:null}{error&&<p className="error" role="alert">{error}</p>}<Candidate360 key={c.id} data={data} candidate={c} onSearch={onRole} api={api} reload={reload} onDirty={setDetailDirty}/></section>;
}
export function Candidates({data,api,reload,onDirty,onOpen,onCandidate}:Shared&{onOpen?:(id:string)=>void;onCandidate?:(id:string)=>void}) {
 const [batch,setBatch]=useState<'import'|'assign'|null>(null),[selected,setSelected]=useState<string[]>([]);
 const [query,setQuery]=useState(''),[edit,setEdit]=useState<R|null>(null),[mapping,setMapping]=useState<R|null>(null),[searchLinks,setSearchLinks]=useState<R|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const records:R[]=data.research?.records||[],candidates=records.filter(r=>r.kind==='candidate'),canEdit=canPlan(data.actor)||hasRole(data.actor,'data_quality')||hasRole(data.actor,'researcher')||hasRole(data.actor,'partner')||hasRole(data.actor,'engagement');
 useEffect(()=>{onDirty(!!edit||!!mapping||!!batch);return()=>onDirty(false);},[!!edit,!!mapping,!!batch]);
 const [filters,setFilters]=useState<Record<string,string>>({}),[sort,setSort]=useState('first_name'),[descending,setDescending]=useState(false),[page,setPage]=useState(0),[pageSize,setPageSize]=useState(100);
 const roleCounts=useMemo(()=>candidateRoleCounts(records),[records]);
 const searchIndex=useMemo(()=>candidateSearchIndex(records,data.searches,data.research.events),[records,data.searches,data.research.events]);
 const visible=useMemo(()=>directoryRows(candidates,query,filters,sort,descending,roleCounts,searchIndex,records),[records,query,filters,sort,descending,roleCounts,searchIndex]);
 const paged=directoryPage(visible,page,pageSize),researcher=hasRole(data.actor,'researcher');
 const changeSort=(key:string)=>{setDescending(sort===key?!descending:false);setSort(key);setPage(0);};
 const sortHeading=(key:string,label:string)=><th key={key} scope="col" aria-sort={sort===key?(descending?'descending':'ascending'):'none'}><button className="column-sort" onClick={()=>changeSort(key)}>{label} <span aria-hidden="true">{sort===key?(descending?'↓':'↑'):'↕'}</span></button></th>;
 return <section className="panel candidate-directory">
 <div className="section-head"><div><p className="fine">{candidates.length.toLocaleString()} candidates · Open a name to view the profile.</p></div>{<div className="row-actions">{canImportCandidates(data.actor)&&<button onClick={()=>setBatch('import')}>Import Excel</button>}<button className="primary" onClick={()=>{setError('');setEdit({first_name:'',last_name:'',url:'',email:'',phone:''});}}>Add candidate</button></div>}</div>
 <div className="sheet-toolbar"><label className="candidate-search">Find candidate<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} placeholder="Search profiles, notes, tags, evidence and searches…"/></label>{(query||Object.values(filters).some(Boolean))&&<button onClick={()=>{setQuery('');setFilters({});setPage(0);}}>Clear filters</button>}</div>
 <div className="sheet-toolbar candidate-tag-filters">{tagCategories.map(c=><div key={c.key}><span className="fine">{c.label}</span><ColumnFilter label={c.label} options={tagOptions(records,c.key)} selected={filters['tag:'+c.key]?JSON.parse(filters['tag:'+c.key]):null} onChange={v=>{setFilters({...filters,['tag:'+c.key]:v===null?'':JSON.stringify(v)});setPage(0);}}/></div>)}<div><span className="fine">Searches</span><ColumnFilter label="mapped searches" options={data.searches.map((s:R)=>s.id+' · '+s.client+' — '+s.title)} selected={filters.searches?data.searches.filter((s:R)=>JSON.parse(filters.searches).includes(s.id)).map((s:R)=>s.id+' · '+s.client+' — '+s.title):null} onChange={v=>{setFilters({...filters,searches:v===null?'':JSON.stringify(v.map(x=>x.split(' · ')[0]))});setPage(0);}}/></div><label>Search coverage<select value={filters.unmapped||''} onChange={e=>{setFilters({...filters,unmapped:e.target.value});setPage(0);}}><option value="">All candidates</option><option value="yes">No mapped searches</option></select></label><label>Potential client<select value={filters.potential_client||''} onChange={e=>{setFilters({...filters,potential_client:e.target.value});setPage(0);}}><option value="">All</option><option value="true">Yes</option><option value="false">No</option><option value="undefined">Not recorded</option></select></label></div>
 {researcher&&<div className="row-actions candidate-bulk"><button disabled={!selected.length} onClick={()=>setBatch('assign')}>Assign selected to search ({selected.length})</button>{selected.length>0&&<><button onClick={()=>setSelected([])}>Clear selection</button><span className="fine">{selected.length} selected across pages and filters</span></>}</div>}
 <div className="table-scroll"><table className="sheet-table candidate-directory-table"><thead><tr>{researcher&&<th scope="col" className="candidate-select-column">Select</th>}{candidateColumns.map(([key,label])=>sortHeading(key,label))}{sortHeading('roles','Searches')}<th>Tags</th></tr><tr className="column-filters">{researcher&&<th/>}{candidateColumns.map(([key,label])=><th key={key}><input type="search" aria-label={'Filter '+label.toLowerCase()} placeholder={'Find '+label.toLowerCase()} value={filters[key]||''} onChange={e=>{setFilters({...filters,[key]:e.target.value});setPage(0);}}/></th>)}<th/><th/></tr></thead>
 <tbody>{paged.rows.map(c=><tr key={c.id}>{researcher&&<td><input type="checkbox" aria-label={'Select '+c.name} checked={selected.includes(c.id)} onChange={e=>setSelected(e.target.checked?[...selected,c.id]:selected.filter(id=>id!==c.id))}/></td>}<td><button className="text-button" onClick={()=>onCandidate?.(c.id)}>{c.first_name||c.name}</button></td><td><button className="text-button" onClick={()=>onCandidate?.(c.id)}>{c.last_name||'—'}</button></td><td title={c.company}>{c.company||'—'}</td><td>{c.url?<a className="linkedin-icon" href={c.url} aria-label={'LinkedIn profile of '+c.name} title="Open LinkedIn profile" target="_blank" rel="noreferrer">in</a>:<span title="LinkedIn not recorded">—</span>}</td><td><button className="text-button" aria-label={'View '+(roleCounts.get(c.id)||0)+' mapped searches for '+c.name} onClick={()=>setSearchLinks(c)}>{roleCounts.get(c.id)||0} searches</button></td><td><div className="tag-icons">{tagCategories.filter(t=>c.tag_values?.[t.key]?.length).map(t=><span key={t.key} title={t.label+': '+c.tag_values[t.key].join(', ')} aria-label={t.label+': '+c.tag_values[t.key].join(', ')}>{t.icon}</span>)}{!!c.tags?.length&&<span title={'Legacy tags: '+c.tags.join(', ')}>#</span>}</div></td></tr>)}</tbody></table></div>
 {!visible.length&&<p className="sheet-empty">{candidates.length?'No candidates match. Try a different name or clear the filters.':'No candidates yet. Add a candidate or import Excel to get started.'}</p>}
 <div className="candidate-pagination"><span role="status">{paged.start}–{paged.end} of {visible.length.toLocaleString()} candidates{visible.length!==candidates.length?` (${candidates.length.toLocaleString()} total)`:''}</span><label>Rows per page<select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(0);}}>{[25,50,100].map(n=><option key={n} value={n}>{n}</option>)}</select></label><div className="row-actions"><button disabled={!paged.page} onClick={()=>setPage(paged.page-1)}>Previous</button><span>Page {paged.page+1} of {paged.pages}</span><button disabled={paged.page+1>=paged.pages} onClick={()=>setPage(paged.page+1)}>Next</button></div></div>

 {searchLinks&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Mapped searches"><div className="section-head"><h2>{searchLinks.name} · Searches</h2><button onClick={()=>setSearchLinks(null)}>Close</button></div>{data.searches.filter((s:R)=>records.some(r=>r.kind==='mapping'&&r.candidate_id===searchLinks.id&&r.role_id===s.id)).map((s:R)=><div className="work-row" key={s.id}><button className="text-button" onClick={()=>onOpen?.(s.id)}>{s.external_id||s.id} · {s.client} — {s.title}</button></div>)}{!roleCounts.get(searchLinks.id)&&<p>No mapped searches. Select this candidate in the directory to create a mapping draft.</p>}</section></div>}
 {batch&&<CandidateBatch data={data} api={api} reload={reload} ids={batch==='assign'?selected:undefined} onClose={()=>{setBatch(null);setSelected([]);}}/>}
 {mapping&&<MappingForm data={data} api={api} reload={reload} candidate={mapping} onCandidate={id=>onCandidate?.(id)} onClose={()=>setMapping(null)}/>}
 {edit&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="candidate-title"><div className="section-head"><h2 id="candidate-title">{edit.id?'Edit candidate':'New candidate'}</h2><button disabled={busy} onClick={()=>setEdit(null)}>Cancel</button></div><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('research',{...edit,action:'candidate-save'});await reload();setEdit(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>{['first_name','last_name','url','email','phone','title','company'].map(k=><label key={k}>{({first_name:'First name',last_name:'Last name',url:'LinkedIn profile',email:'Email (optional)',phone:'Phone (optional)',title:'Current title (optional)',company:'Current company (optional)'} as R)[k]}<input required={['first_name','last_name','url'].includes(k)} type={k==='email'?'email':k==='url'?'url':'text'} readOnly={k==='url'&&!!edit.id} value={edit[k]||''} disabled={busy} onChange={e=>setEdit({...edit,[k]:e.target.value})}/></label>)}<p className="fine">LinkedIn identifies the candidate. Name and contact corrections keep the same candidate and preserve previous mapping/review snapshots.</p>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Saving…':'Save candidate'}</button></form></section></div>}
 </section>;
}
