import {summarizeTranscript} from './transcript-summary';
import {stageDays} from './engagement-pipeline';
import React,{useEffect,useState} from 'react';
import {canPlan,hasRole} from './domain';
import {interactionTypes,engagementRows,engagementAssignees} from './engagement-domain';
import {displayDate,displayDateTime} from './dates';
type R=Record<string,any>;
const historyLabel=(action:string)=>({
 'mapping-add':'Candidate mapped','mapping-edit':'Mapping updated','mapping-submit':'Mapping submitted for review','mapping-review':'Mapping reviewed','mapping-reopen':'Sourcing review reopened','engagement-update':'Engagement updated','engagement-interview-save':'Interview updated','engagement-start-sequence':'Outreach sequence started'
 } as Record<string,string>)[action]||action.replace(/^mapping-/, 'Sourcing · ').replace(/^engagement-/, 'Engagement · ').replaceAll('-',' ');
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());
export function Candidate360({data,candidate,api,reload,onDirty,onSearch}:any){
 const [tab,setTab]=useState('Candidate notes'),[edit,setEdit]=useState<R|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[files,setFiles]=useState<R[]>([]),[scope,setScope]=useState(''),[category,setCategory]=useState('Resume');
 const [expanded,setExpanded]=useState<string[]>([]),[full,setFull]=useState<string[]>([]),[page,setPage]=useState(0);
 const toggle=(id:string)=>setExpanded(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const collapse=()=>{setExpanded([]);setFull([]);};
 const records:R[]=data.research.records,editable=canPlan(data.actor)||['researcher','partner','engagement'].some(r=>hasRole(data.actor,r as any));
 const maps=records.filter(r=>r.kind==='mapping'&&r.candidate_id===candidate.id),journeys=engagementRows(records,data.searches).filter(r=>r.candidate_id===candidate.id);
 useEffect(()=>{onDirty(!!edit||busy);return()=>onDirty(false);},[!!edit,busy]);
 useEffect(()=>{if(tab==='Attachments'||tab==='Assessments')api('research',{action:'candidate-file-list',candidate_id:candidate.id}).then(setFiles).catch((e:Error)=>setError(e.message));},[tab,candidate.id]);
 async function act(body:R){setBusy(true);setError('');try{await api('research',body);await reload();setEdit(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const label=(id:string)=>{const s=data.searches.find((r:R)=>r.id===id);return s?`${s.client} · ${s.title}`:'General profile';};
 const events=records.filter(r=>r.kind==='candidate-activity'&&r.candidate_id===candidate.id&&(!scope||r.role_id===scope));
 const history=data.research.events.filter((e:R)=>[...maps,...records.filter(r=>r.kind==='engagement'&&r.candidate_id===candidate.id)].some(r=>r.id===e.record_id&&(!scope||r.role_id===scope)));
 const notes=events.filter(e=>e.type!=='Assessment link').sort((a,b)=>String(b.occurred_on).localeCompare(String(a.occurred_on))||String(b.created_at).localeCompare(String(a.created_at)));
 const historical=[...history].sort((a:R,b:R)=>String(b.created_at).localeCompare(String(a.created_at)));
 const list=tab==='History'?historical:notes, lastPage=Math.max(0,Math.ceil(list.length/10)-1),safePage=Math.min(page,lastPage);
 const pager=<div className="profile-pagination"><span>{list.length?`${safePage*10+1}–${Math.min((safePage+1)*10,list.length)} of ${list.length}`:'0 records'}</span><button disabled={!safePage} onClick={()=>{setPage(safePage-1);collapse();}}>Previous</button><button disabled={safePage>=lastPage} onClick={()=>{setPage(safePage+1);collapse();}}>Next</button></div>;
 return <section className="candidate-360"><div className="section-head"><div className="candidate-tags">{(candidate.tags||[]).map((t:string)=><span className="profile-tag" key={t}>{t}</span>)}</div>{editable&&<button onClick={()=>setEdit({mode:'tags',tags:(candidate.tags||[]).join(', ')})}>Edit tags</button>}</div><div className="research-tabs">{['Candidate notes','Searches','Attachments','Assessments','History'].map(t=><button key={t} className={tab===t?'primary':''} onClick={()=>{setTab(t);setPage(0);collapse();}}>{t}</button>)}</div>{error&&<p className="error" role="alert">{error}</p>}
 {['Candidate notes','History'].includes(tab)&&<>
 <div className="sheet-toolbar profile-note-toolbar"><label>Search context<select value={scope} onChange={e=>{setScope(e.target.value);setPage(0);collapse();}}><option value="">All searches and general notes</option>{maps.map(m=><option key={m.id} value={m.role_id}>{label(m.role_id)}</option>)}</select></label><div className="row-actions"><button disabled={!expanded.length&&!full.length} onClick={collapse}>Collapse all</button>{editable&&tab==='Candidate notes'&&<button className="primary" onClick={()=>setEdit({mode:'note',type:'Note',role_id:scope,occurred_on:today(),notes:'',url:''})}>Add candidate note</button>}</div></div>
 {tab==='Candidate notes'?<div className="profile-notes">{notes.slice(safePage*10,safePage*10+10).map(e=>{const open=expanded.includes(e.id),summary=e.type==='Transcript'?(e.transcript_summary||summarizeTranscript(e.notes)):[];return <article className={'profile-note '+(e.type==='Transcript'?'transcript-note':'')} key={e.id}><button className="profile-note-heading" aria-expanded={open} onClick={()=>toggle(e.id)}><span><span className="note-type">{e.type}</span><span className="note-date">{displayDate(e.occurred_on)} · {data.people.find((p:R)=>p.id===e.actor_id)?.name||'Former member'}</span><span className="note-preview">{String(e.notes||'').slice(0,160)}</span><small>{label(e.role_id)}</small></span><span aria-hidden="true">{open?'−':'+'}</span></button>{open&&<div className="profile-note-body">{e.type==='Transcript'?<><div className="transcript-summary"><h3>Automatic summary</h3><p className="fine">Selected excerpts from the transcript. Review against the full text.</p><ul>{summary.map((line:string,i:number)=><li key={i}>{line}</li>)}</ul></div><button aria-expanded={full.includes(e.id)} onClick={()=>setFull(v=>v.includes(e.id)?v.filter(x=>x!==e.id):[...v,e.id])}>{full.includes(e.id)?'Hide':'Read'} full transcript</button>{full.includes(e.id)&&<div className="full-transcript preserve-text">{e.notes}</div>}</>:<p className="preserve-text">{e.notes}</p>}{e.url&&<a href={e.url} target="_blank" rel="noreferrer">Open linked record</a>}</div>}</article>;})}{!notes.length&&<div className="profile-empty">No candidate notes yet. Add a conversation, feedback, or transcript here.</div>}</div>:<div className="profile-history">{historical.slice(safePage*10,safePage*10+10).map((e:R)=><article className="profile-note" key={e.id}><button className="profile-note-heading" aria-expanded={expanded.includes(e.id)} onClick={()=>toggle(e.id)}><span><span className="note-type">{historyLabel(e.action)}</span><span className="note-date">{displayDateTime(e.created_at)}</span></span><span aria-hidden="true">{expanded.includes(e.id)?'−':'+'}</span></button>{expanded.includes(e.id)&&<div className="profile-note-body"><p>{data.people.find((p:R)=>p.id===e.actor)?.name||'Former member'} · {e.data.after?.status||e.data.after?.stage||''}</p>{e.data.notes&&<p className="preserve-text">{e.data.notes}</p>}</div>}</article>)}{!historical.length&&<p className="profile-empty">No sourcing or engagement history yet.</p>}</div>}{pager}</>}
 {tab==='Searches'&&<div className="table-scroll"><table className="sheet-table"><thead><tr><th>Search / engagement partner</th><th>Sourcing</th><th>Engagement</th><th>Search engagement members / stage age</th></tr></thead><tbody>{maps.map(m=>{const j=journeys.find(j=>j.mapping_id===m.id),s=data.searches.find((s:R)=>s.id===m.role_id);return <tr key={m.id}><td>{onSearch?<button className="profile-search-link" onClick={()=>onSearch(m.role_id)}>{label(m.role_id)}</button>:label(m.role_id)}<small>{s?.partner||'Partner not assigned'}</small></td><td>{m.status==='Peer review'?'Team review':m.status}</td><td>{j?j.search_closed?'Search closed · outreach stopped':j.approved?j.stage:'Paused — sourcing reopened':'Awaiting partner approval'}</td><td>{engagementAssignees(records,m.role_id).map(id=>data.people.find((p:R)=>p.id===id)?.name||'Former member').join(', ')||'Search not assigned'}<small>{j?.recommended_on&&`Recommended to client: ${displayDate(j.recommended_on)} · `}{j&&(stageDays(j)===null?'Stage age unknown':`${stageDays(j)} days in stage`)}</small></td></tr>;})}</tbody></table></div>}
 {(tab==='Attachments'||tab==='Assessments')&&<><div className="sheet-toolbar">{editable&&<>{tab==='Attachments'&&<label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{['Resume','Candidate information','Transcript','Email exchange','Recording','Other'].map(v=><option key={v}>{v}</option>)}</select></label>}<label>Upload file · up to 5 MB<input type="file" disabled={busy} accept=".pdf,.doc,.docx,.txt,.eml,.mp3,.m4a,.wav,.xlsx,.xls" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setError('');if(f.size>5*1024*1024){setError('Choose a file up to 5 MB.');return;}setBusy(true);try{const base64=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(new Error('File could not be read.'));r.readAsDataURL(f);});await api('research',{action:'candidate-file-save',candidate_id:candidate.id,name:f.name,category:tab==='Assessments'?'Assessment':category,base64});setFiles(await api('research',{action:'candidate-file-list',candidate_id:candidate.id}));}catch(e:any){setError(e.message);}finally{setBusy(false);e.target.value='';}}}/></label></>}</div>{files.filter(f=>tab==='Assessments'?f.category==='Assessment':f.category!=='Assessment').map(f=><div className="work-row" key={f.id}><span><strong>{f.name}</strong><small>{f.category} · {displayDateTime(f.created_at)}</small></span><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const result=await api('research',{action:'candidate-file-read',candidate_id:candidate.id,file_id:f.id});const bytes=Uint8Array.from(atob(result.base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:'application/octet-stream'})),a=document.createElement('a');a.href=url;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>Download</button></div>)}{!files.some(f=>tab==='Assessments'?f.category==='Assessment':f.category!=='Assessment')&&<p className="profile-empty">{tab==='Assessments'?'No assessments uploaded. Upload the completed Excel assessment here.':'No attachments yet.'}</p>}{tab==='Attachments'&&<p className="fine">Files are stored as supplied. Paste a transcript in Candidate notes for an automatic excerpt summary.</p>}</>}
 {tab==='Assessments'&&<><p className="fine">Assessment files and links are kept separately from candidate notes. A dedicated assessment module will come later.</p>{editable&&<button onClick={()=>setEdit({mode:'note',type:'Assessment link',role_id:'',occurred_on:today(),notes:'',url:''})}>Link assessment</button>}{records.filter(r=>r.kind==='candidate-activity'&&r.candidate_id===candidate.id&&r.type==='Assessment link').map(r=><div className="work-row" key={r.id}><a href={r.url} target="_blank" rel="noreferrer">{r.notes}</a><small>{displayDate(r.occurred_on)}</small></div>)}</>}
 {edit&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Candidate information"><div className="section-head"><h2>{edit.mode==='tags'?'Candidate tags':'Add candidate note'}</h2><button disabled={busy} onClick={()=>{if(confirm('Discard unsaved changes?'))setEdit(null);}}>Cancel</button></div><form onSubmit={e=>{e.preventDefault();act(edit.mode==='tags'?{action:'candidate-tags',candidate_id:candidate.id,candidate_version:candidate.version,tags:edit.tags}:{...edit,action:'candidate-note',candidate_id:candidate.id});}}>{edit.mode==='tags'?<label>Tags, separated by commas<input value={edit.tags} onChange={e=>setEdit({...edit,tags:e.target.value})}/></label>:<><label>Type<select value={edit.type} onChange={e=>setEdit({...edit,type:e.target.value})}>{interactionTypes.map(t=><option key={t}>{t}</option>)}</select></label><label>Search context<select value={edit.role_id} onChange={e=>setEdit({...edit,role_id:e.target.value})}><option value="">General candidate profile</option>{maps.map(m=><option key={m.id} value={m.role_id}>{label(m.role_id)}</option>)}</select></label><label>Date of interaction<input type="date" required value={edit.occurred_on} onChange={e=>setEdit({...edit,occurred_on:e.target.value})}/></label><label>Notes / feedback / transcript<textarea required rows={7} maxLength={50000} value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label>{edit.type==='Transcript'&&<div className="transcript-summary"><h3>Automatic summary preview</h3><p className="fine">Selected source excerpts, generated locally. The full transcript is preserved.</p><ul>{summarizeTranscript(edit.notes).map((line,i)=><li key={i}>{line}</li>)}</ul></div>}<label>Source or assessment link<input type="url" required={edit.type==='Assessment link'} value={edit.url} onChange={e=>setEdit({...edit,url:e.target.value})}/></label></>}{error&&<p className="error">{error}</p>}<button disabled={busy} className="primary">Save</button></form></section></div>}
 </section>;
}
