import {hasPermission} from './access-policy';
import {createHash,randomBytes,randomInt} from 'node:crypto';
import {hasRole,Actor,canPlan,requireThat,text} from './domain';
type DB={rows:(q:string,...p:any[])=>any[];audit:(a:Actor,k:string,id:string,old:any,next:any)=>void};
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
const secret=()=>Buffer.from(randomBytes(32)).toString('hex');
export const candidateSchema=`
CREATE TABLE IF NOT EXISTS role_publications(role_id TEXT PRIMARY KEY,data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS candidate_invites(id TEXT PRIMARY KEY,role_id TEXT NOT NULL,candidate_id TEXT NOT NULL,name TEXT NOT NULL,email TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,expires INTEGER NOT NULL,revoked INTEGER NOT NULL DEFAULT 0,created_by TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS candidate_codes(invite_id TEXT PRIMARY KEY,code_hash TEXT NOT NULL,expires INTEGER NOT NULL,attempts INTEGER NOT NULL,sent_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS candidate_sessions(token_hash TEXT PRIMARY KEY,invite_id TEXT NOT NULL,expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS candidate_limits(key TEXT PRIMARY KEY,count INTEGER NOT NULL,expires INTEGER NOT NULL);
`;
export function manageRole(db:DB,a:Actor,role:string){const s=db.rows('SELECT * FROM searches WHERE id=?',role)[0];requireThat(s,'Role not found.',404);requireThat(hasPermission(a,'search.jd'),'Role management permission required.',403);return s;}
export function candidateLimit(db:DB,key:string,max:number){const now=Date.now(),r=db.rows('SELECT * FROM candidate_limits WHERE key=?',key)[0];if(!r||r.expires<now)db.rows('INSERT OR REPLACE INTO candidate_limits VALUES(?,?,?)',key,1,now+3600e3);else {requireThat(r.count<max,'Too many requests. Try again in an hour.',429);db.rows('UPDATE candidate_limits SET count=count+1 WHERE key=?',key);}db.rows('DELETE FROM candidate_limits WHERE expires<?',now);}
function invitation(db:DB,token:string){const i=db.rows('SELECT * FROM candidate_invites WHERE token_hash=? AND revoked=0 AND expires>?',hash(token),Date.now())[0];requireThat(i&&db.rows('SELECT role_id FROM role_publications WHERE role_id=?',i.role_id).length,'This invitation is unavailable or expired. Contact your XQtiv partner.',404);return i;}
export function createCandidateInvite(db:DB,a:Actor,b:any){manageRole(db,a,b.role_id);requireThat(db.rows('SELECT role_id FROM role_publications WHERE role_id=?',b.role_id).length,'Publish the approved page before inviting candidates.');const r=db.rows("SELECT data FROM research_records WHERE kind='mapping' AND role_id=? AND json_extract(data,'$.candidate_id')=?",b.role_id,b.candidate_id)[0];requireThat(r,'Select a candidate mapped to this role.');const email=text(b.email,254).toLowerCase();requireThat(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),'Enter the candidate’s email address.');const days=Number(b.days);requireThat(Number.isInteger(days)&&days>=1&&days<=30,'Choose an expiry from 1 to 30 days.');candidateLimit(db,'invite:'+a.id,100);const raw=secret(),id=crypto.randomUUID(),name=JSON.parse(r.data).name,expires=Date.now()+days*86400e3;
 db.rows('UPDATE candidate_invites SET revoked=1 WHERE role_id=? AND candidate_id=?',b.role_id,b.candidate_id);
 db.rows('INSERT INTO candidate_invites VALUES(?,?,?,?,?,?,?,0,?,?)',id,b.role_id,b.candidate_id,name,email,hash(raw),expires,a.id,new Date().toISOString());db.audit(a,'candidate-invite',id,null,{role_id:b.role_id,candidate_id:b.candidate_id,expires});return {id,token:raw,email,name,expires};}
export function listCandidateInvites(db:DB,a:Actor,role:string){manageRole(db,a,role);return db.rows('SELECT id,role_id,candidate_id,name,email,expires,revoked,created_at FROM candidate_invites WHERE role_id=? ORDER BY created_at DESC',role);}
export function revokeCandidateInvite(db:DB,a:Actor,id:string){const r=db.rows('SELECT role_id FROM candidate_invites WHERE id=?',id)[0];requireThat(r,'Invitation not found.',404);manageRole(db,a,r.role_id);db.rows('UPDATE candidate_invites SET revoked=1 WHERE id=?',id);db.rows('DELETE FROM candidate_sessions WHERE invite_id=?',id);db.rows('DELETE FROM candidate_codes WHERE invite_id=?',id);db.audit(a,'candidate-revoke',id,null,{revoked:true});return {ok:true};}
export function requestCandidateCode(db:DB,b:any,ip:string){candidateLimit(db,'code-ip:'+ip,20);const i=invitation(db,String(b.token||''));candidateLimit(db,'code-invite:'+i.id,3);const previous=db.rows('SELECT sent_at FROM candidate_codes WHERE invite_id=?',i.id)[0];requireThat(!previous||previous.sent_at<Date.now()-60000,'Wait one minute before requesting another code.',429);const code=String(randomInt(100000,1000000));db.rows('INSERT OR REPLACE INTO candidate_codes VALUES(?,?,?,?,?)',i.id,hash(i.id+':'+code),Date.now()+600e3,0,Date.now());return {email:i.email,code,id:i.id};}
export function verifyCandidateCode(db:DB,b:any,ip:string){candidateLimit(db,'verify-ip:'+ip,40);const i=invitation(db,String(b.token||'')),c=db.rows('SELECT * FROM candidate_codes WHERE invite_id=?',i.id)[0];requireThat(c&&c.expires>Date.now()&&c.attempts<5,'Request a new verification code.',401);db.rows('UPDATE candidate_codes SET attempts=attempts+1 WHERE invite_id=?',i.id);requireThat(hash(i.id+':'+String(b.code))===c.code_hash,'Incorrect verification code.',401);db.rows('DELETE FROM candidate_codes WHERE invite_id=?',i.id);db.rows('DELETE FROM candidate_sessions WHERE expires<?',Date.now());const raw=secret();db.rows('INSERT INTO candidate_sessions VALUES(?,?,?)',hash(raw),i.id,Math.min(i.expires,Date.now()+8*3600e3));return {token:raw};}
export function candidatePage(db:DB,session:string,token?:string){const r=db.rows('SELECT i.* FROM candidate_sessions s JOIN candidate_invites i ON i.id=s.invite_id WHERE s.token_hash=? AND s.expires>? AND i.expires>? AND i.revoked=0',hash(session),Date.now(),Date.now())[0];requireThat(r&&(!token||r.token_hash===hash(token)),'Verify your invitation to view this role.',401);const p=db.rows('SELECT data FROM role_publications WHERE role_id=?',r.role_id)[0];requireThat(p,'This page is no longer published.',404);return {...JSON.parse(p.data),candidate_name:r.name};}

