import {workbookSearchRows} from './search-import';
import {LinkedInIcon} from './LinkedInIcon';
import {SearchPicker} from './SearchPicker';
import {SortableTable} from './SortableTable';
import React,{useState} from 'react';
import {hasRole} from './domain';
import {candidateRows} from './candidate-import';
type R=Record<string,any>;
export function CandidateBatch({data,api,reload,ids,onClose}:{data:R;api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;ids?:string[];onClose:()=>void}){
 const [importSearches,setImportSearches]=useState<R[]>([]);
 const [rows,setRows]=useState<R[]>([]),[role,setRole]=useState(''),[preview,setPreview]=useState<R|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState<R|null>(null);
 const linkedWorkbook=!ids&&(importSearches.length>0||rows.some(r=>r.search_number));
 const body={action:ids?'candidate-assign':'candidate-import',candidate_ids:ids,rows,role_id:role};
 async function run(save=false){setBusy(true);setError('');try{const r=await api(linkedWorkbook?'mutate':'research',linkedWorkbook?{kind:'search-import',rows:importSearches,candidates:rows,preview:!save,signature:preview?.signature}:{...body,preview:!save,signature:preview?.signature});if(save){setDone(r);await reload();}else setPreview(linkedWorkbook?{...r,searchPlan:r.plan,plan:r.candidates}:r);}catch(e:any){setError(e.message);setPreview(null);}finally{setBusy(false);}}
 return <div className="modal-backdrop"><section className="modal research-modal" role="dialog" aria-modal="true" aria-labelledby="batch-title"><div className="section-head"><h2 id="batch-title">{ids?'Assign selected candidates':'Import candidates from Excel'}</h2><button disabled={busy} onClick={onClose}>{done?'Done':'Cancel'}</button></div>{done?<p role="status">Saved: {done.created} new candidates, {done.mapped} mapping drafts{done.count!==undefined?`, ${done.count} searches imported`:``}. Existing profiles and mappings were preserved.</p>:<>
 {!ids&&<><p>Use the Candidates sheet. Required: First Name, Last Name and LinkedIn URL. Supply XQtiv Search ID to link candidates to searches. Up to 500 candidates per workbook.</p><a href="/templates/xqtiv-search-candidate-import.xlsx" download>Download search and candidate template</a><label>Excel workbook<input type="file" accept=".xlsx" disabled={busy} onChange={async e=>{const f=e.target.files?.[0];setRows([]);setImportSearches([]);setPreview(null);setError('');if(!f)return;setBusy(true);try{if(f.size>10*1024*1024)throw Error('Choose a file under 10 MB.');const {default:read}=await import('read-excel-file/browser');const wb=await read(f),sheet=wb.find(w=>w.sheet.toLowerCase()==='candidates')||wb[0];setRows(candidateRows(sheet?.data||[]));setImportSearches(workbookSearchRows(wb.find(w=>w.sheet.toLowerCase()==='searches')?.data||[]));}catch(e:any){setError(e.message);}finally{setBusy(false);}}}/></label>{!!rows.length&&<p>{rows.length} rows loaded.</p>}</>}
 {!linkedWorkbook&&(hasRole(data.actor,'researcher')?<><SearchPicker label={ids?'Assign to search':'Assign to search (optional)'} searches={data.searches} value={role} disabled={busy} onChange={id=>{setRole(id);setPreview(null);}} allowAll={!ids}/></>:<p>Import candidates here. Enable the Researcher role to record role mappings.</p>)}
 {!linkedWorkbook&&role&&<p className="fine">Candidates are linked to this search as drafts. Team allocation is managed separately in Weekly plan. Existing role mappings are skipped. Add candidate-specific fit evidence before submitting for team review. Their current companies are added to target companies automatically. Target coverage can be set later; actual coverage increases only after partner approval.</p>}
 {preview&&preview.searchPlan?.length>0&&<div className="sheet-scroll"><table className="sheet-table"><thead><tr><th>XQtiv Search ID</th><th>Search</th><th>Client</th><th>Import</th></tr></thead><tbody>{preview.searchPlan.map((s:R,i:number)=><tr key={i}><td>{s.search_number??'Auto'}</td><td>{s.title}</td><td>{s.client}</td><td>{s.result}</td></tr>)}</tbody></table></div>}{preview&&<div className="table-scroll" style={{maxHeight:350}}><SortableTable stateKey="CandidateBatch.table1" className="sheet-table"><thead><tr>{linkedWorkbook&&<th>XQtiv Search ID</th>}<th>Candidate</th><th>Import</th><th>Search mapping</th></tr></thead><tbody>{preview.plan.map((r:R,i:number)=><tr key={i}>{linkedWorkbook&&<td>{r.search_number}</td>}<td><LinkedInIcon url={r.url} name={[r.first_name,r.last_name].join(' ')}/>{r.first_name} {r.last_name}</td><td>{r.status==='Peer review'?'Team review':r.status}</td><td>{r.mapping}</td></tr>)}</tbody></SortableTable></div>}
 {error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy||(!ids&&!rows.length)||!!(ids&&!role)} onClick={()=>run(!!preview)}>{busy?'Working…':preview?'Confirm and save':'Preview changes'}</button>
 </>}</section></div>;
}
