import React,{useState} from 'react';
import {hasRole} from './domain';
import {candidateRows} from './candidate-import';
type R=Record<string,any>;
export function CandidateBatch({data,api,reload,ids,onClose}:{data:R;api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;ids?:string[];onClose:()=>void}){
 const [rows,setRows]=useState<R[]>([]),[role,setRole]=useState(''),[team,setTeam]=useState(''),[preview,setPreview]=useState<R|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState<R|null>(null);
 const body={action:ids?'candidate-assign':'candidate-import',candidate_ids:ids,rows,role_id:role,team_id:team};
 const teams=data.teams.filter((t:R)=>data.team_members.some((m:R)=>m.team_id===t.id&&m.staff_id===data.actor.staffId));
 async function run(save=false){setBusy(true);setError('');try{const r=await api('research',{...body,preview:!save,signature:preview?.signature});if(save){setDone(r);await reload();}else setPreview(r);}catch(e:any){setError(e.message);setPreview(null);}finally{setBusy(false);}}
 return <div className="modal-backdrop"><section className="modal research-modal" role="dialog" aria-modal="true" aria-labelledby="batch-title"><div className="section-head"><h2 id="batch-title">{ids?'Assign selected candidates':'Import candidates from Excel'}</h2><button disabled={busy} onClick={onClose}>{done?'Done':'Cancel'}</button></div>{done?<p role="status">Saved: {done.created} new candidates, {done.reused} existing candidates reused, {done.mapped} mapping drafts created, {done.skipped} duplicate file rows skipped.</p>:<>
 {!ids&&<><p>Upload .xlsx, first worksheet, with a header row. Required: <strong>First Name, Last Name, LinkedIn URL</strong>. Optional: Email, Phone, Title, Company, Rationale. Maximum 500 rows / 5 MB per upload.</p><p className="fine">Existing LinkedIn profiles are reused without overwriting their details. Correct existing details using Edit candidate.</p><button onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['First Name,Last Name,LinkedIn URL,Email,Phone,Title,Company,Rationale\r\n'],{type:'text/csv'}));a.download='candidate-import-template.csv';a.click();URL.revokeObjectURL(a.href);}}>Download column template</button><p className="fine">Open the CSV template in Excel, fill it in, and save as .xlsx. Format phone numbers as text to preserve leading zeros.</p><label>Excel workbook<input type="file" accept=".xlsx" disabled={busy} onChange={async e=>{const f=e.target.files?.[0];setRows([]);setPreview(null);setError('');if(!f)return;setBusy(true);try{if(f.size>5*1024*1024)throw Error('Choose a file under 5 MB.');const {default:read}=await import('read-excel-file/browser');setRows(candidateRows((await read(f))[0]?.data||[]));}catch(e:any){setError(e.message);}finally{setBusy(false);}}}/></label>{!!rows.length&&<p>{rows.length} rows loaded.</p>}</>}
 {hasRole(data.actor,'researcher')?<><label>Assign to role {ids?'':'(optional)'}<select disabled={busy} value={role} onChange={e=>{setRole(e.target.value);setPreview(null);}}><option value="">{ids?'Choose role':'Import to candidate directory only'}</option>{data.searches.map((s:R)=><option key={s.id} value={s.id}>{s.client} — {s.title}</option>)}</select></label>{role&&<label>Your research team<select disabled={busy} value={team} onChange={e=>{setTeam(e.target.value);setPreview(null);}}><option value="">Choose team</option>{teams.map((t:R)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}</>:<p>Import candidates here. Enable the Researcher role and join a team to record role mappings.</p>}
 {role&&<p className="fine">Mappings are attributed to you and saved as drafts. Existing role mappings are skipped. Add candidate-specific fit evidence before submitting for team review. These are direct mappings, without target-company coverage credit.</p>}
 {preview&&<div className="table-scroll" style={{maxHeight:350}}><table className="sheet-table"><thead><tr><th>Candidate</th><th>LinkedIn</th><th>Import</th><th>Role mapping</th></tr></thead><tbody>{preview.plan.map((r:R,i:number)=><tr key={i}><td>{r.first_name} {r.last_name}</td><td>{r.url}</td><td>{r.status==='Peer review'?'Team review':r.status}</td><td>{r.mapping}</td></tr>)}</tbody></table></div>}
 {error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy||(!ids&&!rows.length)||!!(ids&&!role)||!!(role&&!team)} onClick={()=>run(!!preview)}>{busy?'Working…':preview?'Confirm and save':'Preview changes'}</button>
 </>}</section></div>;
}
