import {stageDays} from './engagement-pipeline';
import React,{useEffect,useState} from 'react';
import {canPlan,hasRole} from './domain';
import {interactionTypes,engagementRows,engagementAssignees} from './engagement-domain';
import {displayDate,displayDateTime} from './dates';
type R=Record<string,any>;
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());
export function Candidate360({data,candidate,api,reload,onDirty}:any){
 const [tab,setTab]=useState('Timeline'),[edit,setEdit]=useState<R|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[files,setFiles]=useState<R[]>([]),[scope,setScope]=useState(''),[category,setCategory]=useState('Resume');
 const records:R[]=data.research.records,editable=canPlan(data.actor)||['researcher','partner','engagement'].some(r=>hasRole(data.actor,r as any));
 const maps=records.filter(r=>r.kind==='mapping'&&r.candidate_id===candidate.id),journeys=engagementRows(records,data.searches).filter(r=>r.candidate_id===candidate.id);
 useEffect(()=>{onDirty(!!edit||busy);return()=>onDirty(false);},[!!edit,busy]);
 useEffect(()=>{if(tab==='Documents')api('research',{action:'candidate-file-list',candidate_id:candidate.id}).then(setFiles).catch((e:Error)=>setError(e.message));},[tab,candidate.id]);
 async function act(body:R){setBusy(true);setError('');try{await api('research',body);await reload();setEdit(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const label=(id:string)=>{const s=data.searches.find((r:R)=>r.id===id);return s?`${s.client} · ${s.title}`:'General profile';};
 const events=records.filter(r=>r.kind==='candidate-activity'&&r.candidate_id===candidate.id&&(!scope||r.role_id===scope));
 const history=data.research.events.filter((e:R)=>[...maps,...records.filter(r=>r.kind==='engagement'&&r.candidate_id===candidate.id)].some(r=>r.id===e.record_id&&(!scope||r.role_id===scope)));
 return <section className="candidate-360"><div className="section-head"><div className="candidate-tags">{(candidate.tags||[]).map((t:string)=><span className="badge" key={t}>{t}</span>)}</div>{editable&&<button onClick={()=>setEdit({mode:'tags',tags:(candidate.tags||[]).join(', ')})}>Edit tags</button>}</div><div className="research-tabs">{['Timeline','Search journeys','Documents','Assessments'].map(t=><button key={t} className={tab===t?'primary':''} onClick={()=>setTab(t)}>{t}</button>)}</div>{error&&<p className="error" role="alert">{error}</p>}
 {tab==='Timeline'&&<><div className="sheet-toolbar"><label>Search context<select value={scope} onChange={e=>setScope(e.target.value)}><option value="">All interactions</option>{maps.map(m=><option key={m.id} value={m.role_id}>{label(m.role_id)}</option>)}</select></label>{editable&&<button onClick={()=>setEdit({mode:'note',type:'Note',role_id:scope,occurred_on:today(),notes:'',url:''})}>Add interaction or note</button>}</div><div className="candidate-timeline">{events.sort((a,b)=>b.occurred_on.localeCompare(a.occurred_on)||b.created_at.localeCompare(a.created_at)).map(e=><details key={e.id}><summary><strong>{e.type}</strong> · {displayDate(e.occurred_on)} · {data.people.find((p:R)=>p.id===e.actor_id)?.name||'Former member'}<small>{label(e.role_id)}{e.to_stage&&` · ${e.from_stage} → ${e.to_stage}`}</small><span className="timeline-preview">{e.notes.slice(0,160)}</span></summary><p className="preserve-text">{e.notes}</p>{e.days_in_previous_stage!=null&&<p className="fine">Previous stage: {e.days_in_previous_stage} days</p>}{e.url&&<a href={e.url} target="_blank" rel="noreferrer">Open linked record</a>}</details>)}{!events.length&&<p className="fine">No notes or interactions recorded yet.</p>}</div><details><summary>Sourcing and engagement history ({history.length})</summary><div className="candidate-timeline">{history.map((e:R)=><details key={e.id}><summary>{e.action.replaceAll('mapping-','Sourcing · ').replaceAll('engagement-','Engagement · ')} · {displayDateTime(e.created_at)}</summary><p>{data.people.find((p:R)=>p.id===e.actor)?.name||'Former member'} · {e.data.after?.status||e.data.after?.stage||''}</p>{e.data.notes&&<p>{e.data.notes}</p>}</details>)}</div></details></>}
 {tab==='Search journeys'&&<div className="table-scroll"><table className="sheet-table"><thead><tr><th>Search / engagement partner</th><th>Sourcing</th><th>Engagement</th><th>Search engagement members / stage age</th></tr></thead><tbody>{maps.map(m=>{const j=journeys.find(j=>j.mapping_id===m.id),s=data.searches.find((s:R)=>s.id===m.role_id);return <tr key={m.id}><td>{label(m.role_id)}<small>{s?.partner||'Partner not assigned'}</small></td><td>{m.status==='Peer review'?'Team review':m.status}</td><td>{j?j.search_closed?'Search closed · outreach stopped':j.approved?j.stage:'Paused — sourcing reopened':'Awaiting partner approval'}</td><td>{engagementAssignees(records,m.role_id).map(id=>data.people.find((p:R)=>p.id===id)?.name||'Former member').join(', ')||'Search not assigned'}<small>{j&&(stageDays(j)===null?'Stage age unknown':`${stageDays(j)} days in stage`)}</small></td></tr>;})}</tbody></table></div>}
 {tab==='Documents'&&<><div className="sheet-toolbar">{editable&&<><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{['Resume','Candidate information','Transcript','Email exchange','Recording','Assessment','Other'].map(v=><option key={v}>{v}</option>)}</select></label><label>Upload file · up to 5 MB<input type="file" disabled={busy} accept=".pdf,.doc,.docx,.txt,.eml,.mp3,.m4a,.wav" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setError('');if(f.size>5*1024*1024){setError('Choose a file up to 5 MB.');return;}setBusy(true);try{const base64=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(new Error('File could not be read.'));r.readAsDataURL(f);});await api('research',{action:'candidate-file-save',candidate_id:candidate.id,name:f.name,category,base64});setFiles(await api('research',{action:'candidate-file-list',candidate_id:candidate.id}));}catch(e:any){setError(e.message);}finally{setBusy(false);e.target.value='';}}}/></label></>}</div>{files.map(f=><div className="work-row" key={f.id}><span><strong>{f.name}</strong><small>{f.category} · {displayDateTime(f.created_at)}</small></span><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const result=await api('research',{action:'candidate-file-read',candidate_id:candidate.id,file_id:f.id});const bytes=Uint8Array.from(atob(result.base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:'application/octet-stream'})),a=document.createElement('a');a.href=url;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>Download</button></div>)}{!files.length&&<p>No documents yet.</p>}<p className="fine">Recordings and transcripts are stored as supplied. Automatic transcription is not enabled.</p></>}
 {tab==='Assessments'&&<><p className="fine">Link completed assessments here. The assessment module can connect to these profiles later.</p>{editable&&<button onClick={()=>setEdit({mode:'note',type:'Assessment link',role_id:'',occurred_on:today(),notes:'',url:''})}>Link assessment</button>}{records.filter(r=>r.kind==='candidate-activity'&&r.candidate_id===candidate.id&&r.type==='Assessment link').map(r=><div className="work-row" key={r.id}><a href={r.url} target="_blank" rel="noreferrer">{r.notes}</a><small>{displayDate(r.occurred_on)}</small></div>)}</>}
 {edit&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Candidate information"><div className="section-head"><h2>{edit.mode==='tags'?'Candidate tags':'Add interaction or note'}</h2><button disabled={busy} onClick={()=>{if(confirm('Discard unsaved changes?'))setEdit(null);}}>Cancel</button></div><form onSubmit={e=>{e.preventDefault();act(edit.mode==='tags'?{action:'candidate-tags',candidate_id:candidate.id,candidate_version:candidate.version,tags:edit.tags}:{...edit,action:'candidate-note',candidate_id:candidate.id});}}>{edit.mode==='tags'?<label>Tags, separated by commas<input value={edit.tags} onChange={e=>setEdit({...edit,tags:e.target.value})}/></label>:<><label>Type<select value={edit.type} onChange={e=>setEdit({...edit,type:e.target.value})}>{interactionTypes.map(t=><option key={t}>{t}</option>)}</select></label><label>Search context<select value={edit.role_id} onChange={e=>setEdit({...edit,role_id:e.target.value})}><option value="">General candidate profile</option>{maps.map(m=><option key={m.id} value={m.role_id}>{label(m.role_id)}</option>)}</select></label><label>Date of interaction<input type="date" required value={edit.occurred_on} onChange={e=>setEdit({...edit,occurred_on:e.target.value})}/></label><label>Notes / feedback / transcript<textarea required rows={7} maxLength={50000} value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label><label>Source or assessment link<input type="url" required={edit.type==='Assessment link'} value={edit.url} onChange={e=>setEdit({...edit,url:e.target.value})}/></label></>}{error&&<p className="error">{error}</p>}<button disabled={busy} className="primary">Save</button></form></section></div>}
 </section>;
}
