import {FilterPopover} from './FilterPopover';
import React,{useState} from 'react';
import {matchesFilter,toggleFilterValue} from './filter-values';
export function ColumnFilter({label,options,selected,onChange,floating=false,optionLabel=(v:string)=>v||'(Blank)',searchText=(v:string)=>v}:{label:string;options:string[];selected:string[]|null;onChange:(v:string[]|null)=>void;floating?:boolean;optionLabel?:(v:string)=>string;searchText?:(v:string)=>string}) {
 const [query,setQuery]=useState('');
 const shown=options.filter(v=>matchesFilter(searchText(v)||optionLabel(v),query));
 const summary=selected===null?'All':!selected.length?'None':selected.length===1?optionLabel(selected[0]):`${optionLabel(selected[0])} +${selected.length-1}`;
 const content=<><input type="search" aria-label={`Find ${label} options`} placeholder="Find values…" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&query.trim()&&shown.length===1){e.preventDefault();onChange(toggleFilterValue(selected,shown[0],true));}}}/><div className="row-actions"><button type="button" onClick={()=>{onChange(null);setQuery('');}}>Clear filter</button>{query.trim()&&<button type="button" disabled={!shown.length} onClick={()=>onChange(shown)}>Use matching values</button>}</div><p className="fine">{selected===null?'No filter applied. Choose values below.':`${selected.length} filter value${selected.length===1?'':'s'} selected.`}</p><div className="filter-options">{shown.map(v=><label className="checkbox" key={v}><input type="checkbox" checked={selected?.includes(v)||false} onChange={e=>onChange(toggleFilterValue(selected,v,e.target.checked))}/>{optionLabel(v)}</label>)}{!shown.length&&<p>No matching values</p>}</div></>;
 return floating?<FilterPopover label={`Filter ${label}`} summary={summary}>{content}</FilterPopover>:<details className="column-filter"><summary aria-label={`Filter ${label}`}>{summary} <span aria-hidden="true">▾</span></summary><div className="filter-menu">{content}</div></details>;
}
