import {hasPermission} from './access-policy';
import {CompanyClassification} from './CompanyClassification';
import React from 'react';
import {CompanyWebsiteLookup} from './CompanyWebsiteLookup';
import {employeeBands,revenueBands} from './company-directory';
type R=Record<string,any>;
export function CompanyProfile({edit,setEdit,records,api,busy,error,onSave,onClose,readOnly=false}:{edit:R;setEdit:React.Dispatch<React.SetStateAction<R|null>>;records:R[];api:(p:string,b?:unknown)=>Promise<any>;busy:boolean;error:string;onSave:(b:R)=>void;onClose:()=>void;readOnly?:boolean}){
 return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Company profile"><div className="section-head"><h2>Company profile</h2><button disabled={busy} onClick={onClose}>{readOnly?'Close':'Back to companies'}</button></div><form onSubmit={e=>{e.preventDefault();onSave(edit);}}><fieldset disabled={readOnly||busy} className="company-profile-fields"><label>Company name<input required maxLength={200} value={edit.name||''} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><div className="company-edit-grid"><CompanyClassification edit={edit} setEdit={setEdit} records={records}/>{[['employee_band','Company size',employeeBands],['revenue_band','Revenue (USD)',revenueBands]].map(([key,label,bands])=><label key={String(key)}>{String(label)}<select value={edit[String(key)]||''} onChange={e=>setEdit({...edit,[String(key)]:e.target.value})}><option value="">Not recorded</option>{(bands as string[]).map(v=><option key={v}>{v}</option>)}</select></label>)}</div><label>Website<input type="url" placeholder="https://www.example.com" value={edit.website||''} onChange={e=>setEdit({...edit,website:e.target.value})}/></label>{!readOnly&&<CompanyWebsiteLookup edit={edit} setEdit={setEdit} api={api}/> }</fieldset>{error&&<p role="alert" className="error">{error}</p>}{!readOnly&&<button disabled={busy} className="primary">{busy?'Saving…':'Save company'}</button>}</form></section></div>;
}

