import {hasRole,canPlan,canPartnerReview,roleList,roleLabel} from './domain';
import {companySearchTerms,matchCompany} from './company-search';
import {CompanyEnrichment} from './CompanyEnrichment';
import {CompanyImport} from './CompanyImport';
import React,{useEffect,useState} from 'react';
type R=Record<string,any>;
const attributes=[['tags','Relevant tags'],['company_type','Company type'],['industries','Industries'],['offerings','Service offerings'],['specialties','Specialties'],['geographies','Geographies']];
export function CompanyUniverse({data,api,reload,onDirty,initialRole='',onOpen}:{initialRole?:string;onOpen?:(id:string)=>void;data:R;api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;onDirty:(v:boolean)=>void}){
 const [importing,setImporting]=useState(false),[wave,setWave]=useState('1'),[mode,setMode]=useState<'any'|'all'>('any'),[onlySelected,setOnlySelected]=useState(false);
 const [query,setQuery]=useState(''),[filters,setFilters]=useState<R>({}),[sort,setSort]=useState('name'),[desc,setDesc]=useState(false),[selected,setSelected]=useState<string[]>([]),[edit,setEdit]=useState<R|null>(null),[role,setRole]=useState(initialRole),[category,setCategory]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const records:R[]=data.research?.records||[],companies=records.filter(r=>r.kind==='company'),targets=records.filter(r=>r.kind==='target'),planner=canPlan(data.actor);
 const values=(c:R,key:string)=>Array.isArray(c[key])?c[key]:(c[key]?[c[key]]:[]);
 const terms=companySearchTerms(query),canChoose=planner||hasRole(data.actor,'partner'),canAssign=planner||hasRole(data.actor,'partner')&&data.searches.some((s:R)=>s.id===role&&s.partner_id===data.actor.id);
 const visible=companies.filter(c=>matchCompany(c,terms,mode).matches&&(!onlySelected||selected.includes(c.id))&&attributes.every(([key])=>!filters[key]||values(c,key).includes(filters[key]))).sort((a,b)=>String(a[sort]||'').localeCompare(String(b[sort]||''))*(desc?-1:1));
 const inRole=(id:string)=>targets.some(t=>t.role_id===role&&t.company_id===id);
 useEffect(()=>{onDirty(!!edit||importing);return()=>onDirty(false);},[!!edit,importing]);
 useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(edit||importing){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f);},[!!edit,importing]);
 async function save(b:R){setBusy(true);setError('');setNotice('');try{const r=await api('research',b);await reload();setEdit(null);setSelected([]);setNotice(b.action==='company-batch'?`${r.saved.length} companies added to the role. Assign teams and researchers in its Target companies tab.`:'Company saved.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const chosen=companies.filter(c=>selected.includes(c.id)&&!inRole(c.id)).map(c=>c.id);
 return <section className="panel company-master"><div className="section-head"><div><h2>Company universe</h2><p className="fine">Reusable company profiles across all roles. Categories, priorities and researcher assignments belong to each role’s target list.</p></div>{planner&&<button onClick={()=>setImporting(true)}>Import Excel</button>}{planner&&<button className="primary" onClick={()=>setEdit({action:'company-master'})}>Add company</button>}</div><div className="sheet-toolbar company-filters"><label className="search-filter">Search companies by keywords<input value={query} placeholder="Show me companies in utilities and energy" onChange={e=>setQuery(e.target.value)}/></label><label>Match<select value={mode} onChange={e=>setMode(e.target.value as 'any'|'all')}><option value="any">Any keyword</option><option value="all">All keywords</option></select></label><button onClick={()=>{setQuery('');setFilters({});setOnlySelected(false);}}>Show all companies</button></div><p className="fine">{terms.length?'Searching for: '+terms.join(', '):'Showing all companies'}. Searches stored names, industries, tags, offerings and specialties, including common terms such as energy / renewables. No external company data is inferred.</p><details><summary>Additional metadata filters</summary><div className="sheet-toolbar">{attributes.map(([key,label])=><label key={key}>{label}<select value={filters[key]||''} onChange={e=>setFilters({...filters,[key]:e.target.value})}><option value="">All</option>{[...new Set(companies.flatMap(c=>values(c,key)))].sort().map(v=><option key={v}>{v}</option>)}</select></label>)}</div></details>

 {canChoose&&<section className="company-assignment"><div className="assignment-main"><label>Destination role<select value={role} onChange={e=>{setRole(e.target.value);setSelected(selected.filter(id=>!targets.some(t=>t.role_id===e.target.value&&t.company_id===id)));}}><option value="">Choose client and role</option>{data.searches.filter((s:R)=>planner||s.partner_id===data.actor.id).map((s:R)=><option key={s.id} value={s.id}>{s.client} — {s.title}</option>)}</select></label><button className="primary" disabled={!role||!canAssign||!chosen.length||chosen.length>100||busy} onClick={()=>save({action:'company-batch',role_id:role,company_ids:chosen,category,wave})}>{busy?'Adding…':`Add ${chosen.length} companies to role`}</button></div><details><summary>Optional: research wave and strategy subcategory</summary><div className="sheet-toolbar"><label>Strategy subcategory<input value={category} onChange={e=>setCategory(e.target.value)}/></label><label>Research wave<input type="number" min={1} max={99} value={wave} onChange={e=>setWave(e.target.value)}/></label></div></details></section>}
 <div className="company-selection"><p><strong>{visible.length}</strong> companies shown <span>·</span> <strong>{chosen.length}</strong> selected for assignment</p>{canChoose&&<div className="row-actions"><button className={onlySelected?'selected-toggle active':'selected-toggle'} aria-pressed={onlySelected} onClick={()=>setOnlySelected(!onlySelected)}>{onlySelected?'Showing selected only':'Show selected only'}</button><button disabled={!selected.length} onClick={()=>setSelected([])}>Clear selection</button></div>}</div><p className="fine">Check companies below, choose a destination role, then click Add companies. Selections stay checked across searches; up to 100 per batch.</p>
 {error&&!edit&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice">{notice} {role&&onOpen&&<button onClick={()=>onOpen(role)}>Open role target companies</button>}</p>}<div className="sheet-scroll"><table className="sheet-table"><thead><tr><th>{canChoose&&<input type="checkbox" aria-label="Select visible companies" checked={visible.some(c=>!inRole(c.id))&&visible.filter(c=>!inRole(c.id)).every(c=>selected.includes(c.id))} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,...visible.filter(c=>!inRole(c.id)).map(c=>c.id)])].slice(0,100):selected.filter(id=>!visible.some(c=>c.id===id)))}/>}</th>{[['name','Company'],...attributes].map(([k,label])=><th key={k}><button onClick={()=>{setSort(k);setDesc(sort===k?!desc:false);}}>{label} {sort===k?(desc?'↓':'↑'):''}</button></th>)}<th>Roles / action</th></tr></thead><tbody>{visible.map(c=><tr key={c.id}><td>{canChoose&&<input type="checkbox" aria-label={'Select '+c.name} disabled={!!role&&inRole(c.id)||selected.length>=100&&!selected.includes(c.id)} checked={selected.includes(c.id)} onChange={e=>setSelected(e.target.checked?[...selected,c.id]:selected.filter(id=>id!==c.id))}/>}</td><td><strong>{c.name}</strong>{terms.length>0&&<small>Matches: {matchCompany(c,terms,mode).matched.join(', ')}</small>}{c.linkedin&&<small><a href={c.linkedin} target="_blank" rel="noreferrer">LinkedIn</a></small>}{c.revenue&&<small>{c.revenue} {c.revenue_year}</small>}{c.website&&<small><a href={c.website} target="_blank" rel="noreferrer">Website</a></small>}</td>{attributes.map(([key])=><td key={key}>{values(c,key).join(', ')||'—'}</td>)}<td>{targets.filter(t=>t.company_id===c.id).length} roles {role&&inRole(c.id)&&<small>Already in selected role</small>}{planner&&<button onClick={()=>setEdit({...c,action:'company-master',...Object.fromEntries(attributes.map(([k])=>[k,values(c,k).join(', ')]))})}>Edit profile</button>}</td></tr>)}</tbody></table>{!visible.length&&<p>No companies match. Try another keyword, clear the additional filters, or import companies with the relevant metadata.</p>}</div>
 {importing&&<CompanyImport api={api} reload={reload} close={()=>setImporting(false)}/>}
 {edit&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Company profile"><div className="section-head"><h2>Company profile</h2><button disabled={busy} onClick={()=>{if(confirm('Discard this form?'))setEdit(null);}}>Cancel</button></div><form onSubmit={e=>{e.preventDefault();save(edit);}}><p className="fine">Only the name is required. Use comma-separated tags for industries, offerings, specialties and geographies. Add metadata as you learn more.</p>{[['name','Company name'],...attributes,['website','Website (https://)'],['linkedin','LinkedIn company URL'],['revenue','Revenue (include currency)'],['revenue_year','Revenue year'],['revenue_source','Revenue source'],['notes','Notes']].map(([k,label])=><label key={k}>{label}<input required={k==='name'} value={edit[k]||''} onChange={e=>setEdit({...edit,[k]:e.target.value})}/></label>)}<CompanyEnrichment edit={edit} setEdit={setEdit} api={api}/>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Saving…':'Save company'}</button></form></section></div>}
 </section>;
}
