import {CompanyWebsite} from './CompanyWebsite';
import {companyCoverage} from './company-coverage';
import {hasRole,canPlan} from './domain';
import {CompanyImport} from './CompanyImport';
import {ColumnFilter} from './ColumnFilter';
import {EditableTagSelect} from './EditableTagSelect';
import {tagOptions} from './candidate-tags';
import {companyColumns,companyValues,companyDirectoryRows,employeeBands,revenueBands} from './company-directory';
import {directoryPage} from './candidate-directory';
import React,{useEffect,useState} from 'react';
type R=Record<string,any>;
export function CompanyUniverse({data,api,reload,onDirty,initialRole='',onOpen,embedded=false}:{initialRole?:string;embedded?:boolean;onOpen?:(id:string)=>void;data:R;api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;onDirty:(v:boolean)=>void}){
 const [linkedOnly,setLinkedOnly]=useState(embedded);
 const [importing,setImporting]=useState(false),[query,setQuery]=useState(''),[filters,setFilters]=useState<Record<string,string[]|null>>({}),[sort,setSort]=useState('name'),[desc,setDesc]=useState(false),[page,setPage]=useState(0),[size,setSize]=useState(100);
 const [selected,setSelected]=useState<string[]>([]),[edit,setEdit]=useState<R|null>(null),[role,setRole]=useState(initialRole),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const records:R[]=data.research?.records||[],companies=records.filter(r=>r.kind==='company'),targets=records.filter(r=>r.kind==='target'),planner=canPlan(data.actor),canChoose=planner||hasRole(data.actor,'partner');
 const coverageView=embedded&&linkedOnly;
 const targetFor=(id:string)=>targets.find(t=>t.role_id===initialRole&&t.company_id===id);
 const options=(key:string)=>key==='industries'?tagOptions(records,'industry'):key==='employee_band'?employeeBands:key==='revenue_band'?[...new Set([...revenueBands,...companies.flatMap(c=>companyValues(c,key))])]:[...new Set(companies.flatMap(c=>companyValues(c,key)))].sort((a,b)=>a.localeCompare(b));
 const visible=companyDirectoryRows(linkedOnly?companies.filter(c=>targets.some(t=>t.role_id===initialRole&&t.company_id===c.id)):companies,query,filters,sort,desc),paged=directoryPage(visible,page,size),inSearch=(id:string)=>targets.some(t=>t.role_id===role&&t.company_id===id),chosen=selected.filter(id=>!inSearch(id));
 useEffect(()=>{onDirty(!!edit||importing);return()=>onDirty(false);},[!!edit,importing]);
 async function save(b:R){setBusy(true);setError('');try{await api('research',b.action==='company-master'&&!b.id&&initialRole?{...b,action:'company-master-and-target',role_id:initialRole}:b);await reload();setEdit(null);setSelected([]);if(embedded)setLinkedOnly(true);setNotice(b.action==='company-batch'?'Companies added to search.':'Company saved.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <section className="panel company-master spreadsheet-directory company-directory">
  <div className="section-head"><p className="fine">{embedded?<strong>{linkedOnly?'Search target companies':'Companies'} · </strong>:null}{visible.length.toLocaleString()} companies{visible.length!==companies.length?` / ${companies.length.toLocaleString()} total`:''}</p><div className="row-actions">{embedded&&canChoose&&<button onClick={()=>{setLinkedOnly(!linkedOnly);setPage(0);setSelected([]);}}>{linkedOnly?'Add from Companies':'Back to search targets'}</button>}{planner&&<><button onClick={()=>setImporting(true)}>Import Excel</button><button className="primary" onClick={()=>{setError('');setEdit({action:'company-master',industries:[]});}}>{initialRole?'Add company to search':'Add company'}</button></>}</div></div>
  <div className="sheet-toolbar"><label className="search-filter">Find companies<input type="search" value={query} placeholder="Name, industry, sector or keywords…" onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label>{(query||Object.values(filters).some(v=>v!==null))&&<button onClick={()=>{setQuery('');setFilters({});setPage(0);}}>Clear filters</button>}{!!selected.length&&<><span className="fine">{selected.length} selected</span><button onClick={()=>setSelected([])}>Clear selection</button></>}</div>
  {canChoose&&selected.length>0&&<div className="sheet-toolbar company-assignment"><label>Destination search<select disabled={!!initialRole} value={role} onChange={e=>setRole(e.target.value)}><option value="">Choose search</option>{data.searches.filter((s:R)=>planner||s.partner_id===data.actor.id).map((s:R)=><option key={s.id} value={s.id}>{s.client} — {s.title}</option>)}</select></label><button disabled={busy||!role||!chosen.length||chosen.length>100||!data.searches.some((s:R)=>s.id===role&&(planner||s.partner_id===data.actor.id))} onClick={()=>save({action:'company-batch',role_id:role,company_ids:chosen})}>Add {chosen.length} to search</button></div>}
  {error&&!edit&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status" className="fine">{notice} {role&&onOpen&&<button onClick={()=>onOpen(role)}>Open search</button>}</p>}
  <div className="table-scroll"><table className="sheet-table company-directory-table"><thead><tr>{canChoose&&<th className="company-selection-column" aria-label="Company selection"/>}{companyColumns.map(([key,label])=><th key={key} aria-sort={sort===key?(desc?'descending':'ascending'):'none'}><button className="column-sort" onClick={()=>{setSort(key);setDesc(sort===key?!desc:false);setPage(0);}}>{label} {sort===key?(desc?'↓':'↑'):'↕'}</button></th>)}{coverageView&&<><th>Target coverage</th><th>Actual coverage</th></>}</tr><tr className="column-filters">{canChoose&&<th/>}<th/>{companyColumns.slice(1).map(([key,label])=><th key={key}><ColumnFilter floating label={label} options={['',...options(key)]} selected={filters[key]??null} onChange={v=>{setFilters({...filters,[key]:v});setPage(0);}}/></th>)}{coverageView&&<><th/><th/></>}</tr></thead><tbody>{paged.rows.map(c=><tr key={c.id}>{canChoose&&<td><input type="checkbox" aria-label={'Select '+c.name} checked={selected.includes(c.id)} disabled={selected.length>=100&&!selected.includes(c.id)} onChange={e=>setSelected(e.target.checked?[...selected,c.id]:selected.filter(id=>id!==c.id))}/></td>}<td>{planner?<button className="text-button" title="Edit company" onClick={()=>{setError('');setEdit({...c,action:'company-master'});}}>{c.name}</button>:c.name}<CompanyWebsite company={c} workspace={data.actor.tenant}/></td>{companyColumns.slice(1).map(([key])=><td key={key} title={companyValues(c,key).join(', ')}>{companyValues(c,key).join(', ')||'—'}</td>)}{coverageView&&<><td>{canChoose&&(planner||data.searches.some((r:R)=>r.id===initialRole&&r.partner_id===data.actor.id))?<button className="text-button" onClick={()=>setEdit({...targetFor(c.id),action:'target-coverage',notes:''})}>{targetFor(c.id)?.expected??'Set target'}</button>:targetFor(c.id)?.expected??'Not set'}</td><td>{companyCoverage(targetFor(c.id)!,records).actual}</td></>}</tr>)}</tbody></table></div>
  {!visible.length&&<p className="sheet-empty">No matching companies.</p>}
  <div className="candidate-pagination"><span role="status">{paged.start}–{paged.end} of {visible.length.toLocaleString()} companies</span><label>Rows per page<select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(0);}}>{[25,50,100].map(n=><option key={n}>{n}</option>)}</select></label><div className="row-actions"><button disabled={!paged.page} onClick={()=>setPage(paged.page-1)}>Previous</button><span>Page {paged.page+1} of {paged.pages}</span><button disabled={paged.page+1>=paged.pages} onClick={()=>setPage(paged.page+1)}>Next</button></div></div>
  {importing&&<CompanyImport roleId={initialRole} api={api} reload={reload} close={()=>setImporting(false)}/>}
  {edit?.action==='target-coverage'&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Target coverage"><h2>Target coverage · {edit.name}</h2><form onSubmit={e=>{e.preventDefault();save(edit);}}><label>Expected candidates<input required type="number" min={0} step={1} value={edit.expected??''} onChange={e=>setEdit({...edit,expected:e.target.value})}/></label><p>Actual coverage: {companyCoverage(edit,records).actual} partner-approved candidates</p><label>Reason for revision<textarea required={targetFor(edit.company_id)?.expected!=null} value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label>{error&&<p role="alert" className="error">{error}</p>}<div className="row-actions"><button type="button" disabled={busy} onClick={()=>setEdit(null)}>Cancel</button><button disabled={busy} className="primary">Save target</button></div></form></section></div>}
  {edit&&edit.action!=='target-coverage'&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Company profile"><div className="section-head"><h2>Company profile</h2><button disabled={busy} onClick={()=>{if(confirm('Discard this form?'))setEdit(null);}}>Cancel</button></div><form onSubmit={e=>{e.preventDefault();save(edit);}}><label>Company name<input required maxLength={200} value={edit.name||''} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><div className="company-edit-grid"><EditableTagSelect label="Industry" multiple value={companyValues(edit,'industries')} options={options('industries')} onChange={industries=>setEdit({...edit,industries})}/>{['sector','subsector'].map(key=><EditableTagSelect key={key} label={key==='sector'?'Sector':'Subsector'} value={companyValues(edit,key)} options={options(key)} onChange={v=>setEdit({...edit,[key]:v[0]||''})}/>)}{[['employee_band','Company size',employeeBands],['revenue_band','Revenue (USD)',revenueBands]].map(([key,label,bands])=><label key={String(key)}>{String(label)}<select value={edit[String(key)]||''} onChange={e=>setEdit({...edit,[String(key)]:e.target.value})}><option value="">Not recorded</option>{(bands as string[]).map(v=><option key={v}>{v}</option>)}</select></label>)}</div><details className="company-other-details"><summary>Other company details</summary>{[['aliases','Known aliases'],['website','Website'],['linkedin','LinkedIn'],['revenue','Known revenue details'],['revenue_year','Revenue year'],['revenue_source','Revenue source'],['notes','Notes'],['tags','Other tags'],['company_type','Company type'],['offerings','Service offerings'],['specialties','Specialties'],['geographies','Geographies']].map(([key,label])=><label key={key}>{label}<input value={Array.isArray(edit[key])?edit[key].join(', '):edit[key]||''} onChange={e=>setEdit({...edit,[key]:e.target.value})}/></label>)}</details>{error&&<p role="alert" className="error">{error}</p>}<button disabled={busy} className="primary">{busy?'Saving…':'Save company'}</button></form></section></div>}
 </section>;
}
