import React,{useState} from 'react';
import {tagFields,scalarFields} from './company-import';
const fields=['name',...tagFields,...scalarFields];
const aliases:Record<string,string>={company:'name','company name':'name','relevant tags':'tags','company type':'company_type',industry:'industries','service offerings':'offerings',specialty:'specialties',geography:'geographies','linkedin url':'linkedin','web page':'website','revenue size':'revenue','revenue year':'revenue_year','revenue source':'revenue_source'};
export function CompanyImport({api,reload,close}:{api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;close:()=>void}) {
 const [file,setFile]=useState<File|null>(null),[sheet,setSheet]=useState(''),[sheets,setSheets]=useState<string[]>([]),[table,setTable]=useState<any[][]>([]),[header,setHeader]=useState(0),[map,setMap]=useState<Record<string,number>>({}),[preview,setPreview]=useState<any>(null),[overwrite,setOverwrite]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 function headers(rows:any[][],n:number){setHeader(n);const m:Record<string,number>={};(rows[n]||[]).forEach((v,i)=>{const s=String(v||'').trim().toLowerCase(),k=aliases[s]||s;if(fields.includes(k))m[k]=i;});setMap(m);setPreview(null);}
 async function read(f:File,s?:string){setBusy(true);setError('');setPreview(null);try{if(!/\.xlsx$/i.test(f.name))throw new Error('Upload an .xlsx workbook. Save older .xls files as .xlsx first.');if(f.size>10e6)throw new Error('Use an Excel file under 10 MB.');const excel=await import('read-excel-file/browser');const workbook=await excel.default(f);const names=workbook.map(s=>s.sheet);setSheets(names);const chosen=s||names[0];setSheet(chosen);const rows=workbook.find(s=>s.sheet===chosen)!.data;if(rows.length>1100)throw new Error('Use up to 1,000 data rows per upload.');setTable(rows);headers(rows,rows.findIndex(r=>r.some(v=>['company','company name','name'].includes(String(v||'').toLowerCase().trim())))<0?0:rows.findIndex(r=>r.some(v=>['company','company name','name'].includes(String(v||'').toLowerCase().trim()))));}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const rows=table.slice(header+1).filter(r=>r.some(v=>v!==null&&String(v).trim())).map(r=>Object.fromEntries(fields.map(k=>[k,map[k]===undefined?'':String(r[map[k]]??'')])));
 return <div className="modal-backdrop"><section className="modal research-modal" role="dialog" aria-modal="true" aria-label="Import companies"><div className="section-head"><h2>Import companies from Excel</h2><button disabled={busy} onClick={close}>Close</button></div><p>Upload .xlsx files with up to 1,000 rows. Repeated companies combine their tags. Blank cells never erase existing information.</p><input aria-label="Company spreadsheet" type="file" accept=".xlsx" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f){setFile(f);read(f);}}}/>{!!table.length&&<><div className="sheet-toolbar"><label>Worksheet<select value={sheet} onChange={e=>file&&read(file,e.target.value)}>{sheets.map(s=><option key={s}>{s}</option>)}</select></label><label>Header row<input type="number" min={1} max={table.length} value={header+1} onChange={e=>headers(table,Math.max(0,Math.min(table.length-1,Number(e.target.value)-1)))}/></label></div><div className="import-columns">{fields.map(k=><label key={k}>{k.replaceAll('_',' ')}{k==='name'?' *':''}<select value={map[k]??''} onChange={e=>{setMap({...map,[k]:e.target.value===''?undefined as any:Number(e.target.value)});setPreview(null);}}><option value="">Not provided</option>{(table[header]||[]).map((v,i)=><option key={i} value={i}>Column {i+1}: {String(v||'Unnamed')}</option>)}</select></label>)}</div><label><input type="checkbox" checked={overwrite} onChange={e=>{setOverwrite(e.target.checked);setPreview(null);}}/> Replace populated profile fields with nonblank spreadsheet values (tags are always combined)</label><button disabled={busy||map.name===undefined} onClick={async()=>{setBusy(true);setError('');try{setPreview({...await api('research',{action:'company-import',preview:true,rows,overwrite}),rows,overwrite});}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>Preview {rows.length} rows</button></>}{preview&&<><h3>{preview.plan.filter((c:any)=>!c.existingId).length} new · {preview.plan.filter((c:any)=>c.existingId).length} matched</h3><div className="sheet-scroll"><table className="sheet-table"><thead><tr><th>Result</th><th>Company</th><th>Combined tags</th><th>Website</th><th>Revenue</th></tr></thead><tbody>{preview.plan.map((c:any,i:number)=><tr key={i}><td>{c.existingId?'Merge':'Add'}</td><td>{c.name}</td><td>{tagFields.flatMap(k=>c[k]).join(', ')}</td><td>{c.website}</td><td>{c.revenue} {c.revenue_year}</td></tr>)}</tbody></table></div><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await api('research',{action:'company-import',rows:preview.rows,overwrite:preview.overwrite,signature:preview.signature});await reload();close();}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>Save {preview.plan.length} companies</button></>}{busy&&<p role="status">Processing…</p>}{error&&<p className="error" role="alert">{error}</p>}</section></div>;
}
