import {CompanyEnrichment} from './CompanyEnrichment';
import {CompanyImport} from './CompanyImport';
import React,{useEffect,useState} from 'react';
type R=Record<string,any>;
const attributes=[['tags','Relevant tags'],['company_type','Company type'],['industries','Industries'],['offerings','Service offerings'],['specialties','Specialties'],['geographies','Geographies']];
export function CompanyUniverse({data,api,reload,onDirty}:{data:R;api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;onDirty:(v:boolean)=>void}){
 const [importing,setImporting]=useState(false),[wave,setWave]=useState('1');
 const [query,setQuery]=useState(''),[filters,setFilters]=useState<R>({}),[sort,setSort]=useState('name'),[desc,setDesc]=useState(false),[selected,setSelected]=useState<string[]>([]),[edit,setEdit]=useState<R|null>(null),[role,setRole]=useState(''),[category,setCategory]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const records:R[]=data.research?.records||[],companies=records.filter(r=>r.kind==='company'),targets=records.filter(r=>r.kind==='target'),planner=['admin','planner'].includes(data.actor.role);
 const values=(c:R,key:string)=>Array.isArray(c[key])?c[key]:(c[key]?[c[key]]:[]);
 const visible=companies.filter(c=>[c.name,...attributes.flatMap(([key])=>values(c,key))].join(' ').toLowerCase().includes(query.toLowerCase())&&attributes.every(([key])=>!filters[key]||values(c,key).includes(filters[key]))).sort((a,b)=>String(a[sort]||'').localeCompare(String(b[sort]||''))*(desc?-1:1));
 const inRole=(id:string)=>targets.some(t=>t.role_id===role&&t.company_id===id);
 useEffect(()=>{onDirty(!!edit||importing);return()=>onDirty(false);},[!!edit,importing]);
 useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(edit||importing){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f);},[!!edit,importing]);
 async function save(b:R){setBusy(true);setError('');setNotice('');try{const r=await api('research',b);await reload();setEdit(null);setSelected([]);setNotice(b.action==='company-batch'?`${r.saved.length} companies added to the role. Assign teams and researchers in its Target companies tab.`:'Company saved.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const chosen=visible.filter(c=>selected.includes(c.id)&&!inRole(c.id)).map(c=>c.id);
 return <section className="panel company-master"><div className="section-head"><div><h2>Company universe</h2><p className="fine">Reusable company profiles across all roles. Categories, priorities and researcher assignments belong to each role’s target list.</p></div>{planner&&<button onClick={()=>setImporting(true)}>Import Excel</button>}{planner&&<button className="primary" onClick={()=>setEdit({action:'company-master'})}>Add company</button>}</div><div className="sheet-toolbar"><label>Find company or metadata<input value={query} onChange={e=>setQuery(e.target.value)}/></label>{attributes.map(([key,label])=><label key={key}>{label}<select value={filters[key]||''} onChange={e=>setFilters({...filters,[key]:e.target.value})}><option value="">All</option>{[...new Set(companies.flatMap(c=>values(c,key)))].sort().map(v=><option key={v}>{v}</option>)}</select></label>)}</div>
 {planner&&<div className="sheet-toolbar"><label>Add selected to role<select value={role} onChange={e=>{setRole(e.target.value);setSelected([]);}}><option value="">Choose role</option>{data.searches.map((s:R)=><option key={s.id} value={s.id}>{s.client} — {s.title}</option>)}</select></label><label>Strategy subcategory (optional)<input value={category} onChange={e=>setCategory(e.target.value)} placeholder="e.g. AI consulting firms"/></label><label>Research wave<input type="number" min={1} max={99} value={wave} onChange={e=>setWave(e.target.value)}/></label><button disabled={!role||!chosen.length||busy} onClick={()=>save({action:'company-batch',role_id:role,company_ids:chosen,category,wave})}>Add {chosen.length||''} selected companies</button></div>}
 {error&&!edit&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice">{notice}</p>}<div className="sheet-scroll"><table className="sheet-table"><thead><tr><th>{planner&&<input type="checkbox" aria-label="Select visible companies" checked={visible.some(c=>!inRole(c.id))&&visible.filter(c=>!inRole(c.id)).every(c=>selected.includes(c.id))} onChange={e=>setSelected(e.target.checked?visible.filter(c=>!inRole(c.id)).slice(0,100).map(c=>c.id):[])}/>}</th>{[['name','Company'],...attributes].map(([k,label])=><th key={k}><button onClick={()=>{setSort(k);setDesc(sort===k?!desc:false);}}>{label} {sort===k?(desc?'↓':'↑'):''}</button></th>)}<th>Roles / action</th></tr></thead><tbody>{visible.map(c=><tr key={c.id}><td>{planner&&<input type="checkbox" aria-label={'Select '+c.name} disabled={!!role&&inRole(c.id)} checked={selected.includes(c.id)} onChange={e=>setSelected(e.target.checked?[...selected,c.id]:selected.filter(id=>id!==c.id))}/>}</td><td><strong>{c.name}</strong>{c.linkedin&&<small><a href={c.linkedin} target="_blank" rel="noreferrer">LinkedIn</a></small>}{c.revenue&&<small>{c.revenue} {c.revenue_year}</small>}{c.website&&<small><a href={c.website} target="_blank" rel="noreferrer">Website</a></small>}</td>{attributes.map(([key])=><td key={key}>{values(c,key).join(', ')||'—'}</td>)}<td>{targets.filter(t=>t.company_id===c.id).length} roles {role&&inRole(c.id)&&<small>Already in selected role</small>}{planner&&<button onClick={()=>setEdit({...c,action:'company-master',...Object.fromEntries(attributes.map(([k])=>[k,values(c,k).join(', ')]))})}>Edit profile</button>}</td></tr>)}</tbody></table>{!visible.length&&<p>Add companies to build your master list, then filter by their metadata.</p>}</div>
 {importing&&<CompanyImport api={api} reload={reload} close={()=>setImporting(false)}/>}
 {edit&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Company profile"><div className="section-head"><h2>Company profile</h2><button disabled={busy} onClick={()=>{if(confirm('Discard this form?'))setEdit(null);}}>Cancel</button></div><form onSubmit={e=>{e.preventDefault();save(edit);}}><p className="fine">Only the name is required. Use comma-separated tags for industries, offerings, specialties and geographies. Add metadata as you learn more.</p>{[['name','Company name'],...attributes,['website','Website (https://)'],['linkedin','LinkedIn company URL'],['revenue','Revenue (include currency)'],['revenue_year','Revenue year'],['revenue_source','Revenue source'],['notes','Notes']].map(([k,label])=><label key={k}>{label}<input required={k==='name'} value={edit[k]||''} onChange={e=>setEdit({...edit,[k]:e.target.value})}/></label>)}<CompanyEnrichment edit={edit} setEdit={setEdit} api={api}/>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Saving…':'Save company'}</button></form></section></div>}
 </section>;
}
