import React,{useState} from 'react';
import {dailyRows,dailyGroups} from './daily-view';
type R=Record<string,any>;
export function DailyWork({data,assignments,entries,renderEntries,onOpen}:{data:R;assignments:R[];entries:R[];renderEntries:(e:R[])=>React.ReactNode;onOpen:(id:string)=>void}){
 const key=`daily-view:${data.actor.tenant}:${data.actor.id}`;
 const [prefs,setPrefs]=useState(()=>{try{return {group:'team',sort:'date',descending:true,...JSON.parse(localStorage.getItem(key)||'{}')}}catch{return {group:'team',sort:'date',descending:true}}});
 const [team,setTeam]=useState(''),[partner,setPartner]=useState(''),[query,setQuery]=useState(''),[expanded,setExpanded]=useState<string[]>([]);
 const change=(p:R)=>{const next={...prefs,...p};setPrefs(next);try{localStorage.setItem(key,JSON.stringify(next));}catch{}};
 const rows=dailyRows(data,assignments,entries),visible=rows.filter(r=>(!team||r.team_id===team)&&(!partner||r.partnerName===partner)&&(!query||[r.role,r.client,r.researchers].join(' ').toLowerCase().includes(query.toLowerCase()))),groups=dailyGroups(visible,prefs.group,prefs.sort,prefs.descending);
 const cols=[['date','Date'],['team','Team'],['client','Client'],['search_number','Search ID'],['role','Search'],['partnerName','Partner'],['target','Target'],['mapped','Mapped'],['peer','Peer'],['partner','Approved'],['personDays','Researcher-days']];
 return <section className="panel daily-work"><div className="sheet-toolbar"><label>Group by<select value={prefs.group} onChange={e=>change({group:e.target.value})}>{[['team','Team'],['date','Date'],['week','Week (Mon–Sun)'],['client','Client'],['role','Role'],['partnerName','Partner'],['none','No grouping']].map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Team<select value={team} onChange={e=>setTeam(e.target.value)}><option value="">All teams</option>{data.teams.map((t:R)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Partner<select value={partner} onChange={e=>setPartner(e.target.value)}><option value="">All partners</option>{[...new Set(rows.map(r=>r.partnerName))].sort().map(p=><option key={p}>{p}</option>)}</select></label><label>Find<input placeholder="Client, role or researcher" value={query} onChange={e=>setQuery(e.target.value)}/></label><span className="fine">{visible.length} work rows · Click a header to sort. Your layout is remembered.</span></div>
 <div className="sheet-scroll"><table className="sheet-table daily-grid"><thead><tr><th>People</th>{cols.map(([k,label])=><th key={k} aria-sort={prefs.sort===k?(prefs.descending?'descending':'ascending'):'none'}><button onClick={()=>change({sort:k,descending:prefs.sort===k?!prefs.descending:false})}>{label} {prefs.sort===k?(prefs.descending?'↓':'↑'):''}</button></th>)}<th>Progress</th></tr></thead><tbody>{groups.map(g=><React.Fragment key={g.label}>{prefs.group!=='none'&&<tr className="daily-group"><th colSpan={13}>{prefs.group==='week'?'Week of ':''}{g.label}<span>{g.rows.length} rows · {g.totals.mapped} mapped · {g.totals.partner} approved · {g.totals.personDays} researcher-days</span></th></tr>}{g.rows.map(r=><React.Fragment key={r.id}><tr><td><button aria-expanded={expanded.includes(r.id)} title={r.researchers} onClick={()=>setExpanded(expanded.includes(r.id)?expanded.filter(id=>id!==r.id):[...expanded,r.id])}>{expanded.includes(r.id)?'Hide researchers':`Show ${new Set(r.entries.map((e:R)=>e.staff_id)).size} researcher${new Set(r.entries.map((e:R)=>e.staff_id)).size===1?'':'s'}`} </button></td><td>{r.date}</td><td>{r.team}</td><td>{r.client}</td><td>{r.search_number??'—'}</td><td><button className="text-button" onClick={()=>onOpen(r.search_id)}>{r.role}</button></td><td>{r.partnerName}</td><td>{r.target??'—'}</td><td>{r.hasOutput?r.mapped:'—'}</td><td>{r.entries.some((e:R)=>e.peer!==null)?r.peer:'—'}</td><td>{r.entries.some((e:R)=>e.partner!==null)?r.partner:'—'}</td><td>{r.personDays}</td><td>{r.target>0?<><progress max={r.target} value={Math.min(r.partner,r.target)}/><small>{Math.round(r.partner/r.target*100)}%</small></>:r.hasOutput?'Work recorded':'Planned'}</td></tr>{expanded.includes(r.id)&&<tr><td colSpan={13}><div className="daily-people">{renderEntries(r.entries)}{!r.entries.length&&<p>No researchers assigned.</p>}{r.notes&&<p>{r.notes}</p>}</div></td></tr>}</React.Fragment>)}</React.Fragment>)}</tbody></table>{!visible.length&&<p>No work matches these filters.</p>}</div><p className="fine">Targets are approved candidates. Researcher-days count each person/date once when output is recorded, including zero. Group totals deduplicate people working on several roles that day.</p></section>;
}
