import {SearchStatusMultiFilter,matchesSearchStatuses} from './SearchFilters';
import {ResearchPanel} from './ResearchPanel';
import React,{useEffect,useMemo,useState,useRef} from 'react';
import {Eye,ChartLine} from '@phosphor-icons/react';
import {IconAction} from './IconAction';
import {LinkedInIcon} from './LinkedInIcon';
import {SortableTable} from './SortableTable';
import {Popup} from './Popup';
import {displayDate} from './dates';
import {SearchMultiFilter} from './SearchMultiFilter';
import {monitorPeriods,monitorRange,sourcingMonitorRows} from './sourcing-monitor';
import {hoursPerPersonDay} from './sourcing-settings';
type R=Record<string,any>;
const num=(n:number|null)=>n===null?'—':Number(n.toFixed(1)).toLocaleString();
const pct=(n:number|null)=>n===null?'—':num(n*100)+'%';
function Rate({value,pending=false,target=false}:{value:number|null;pending?:boolean;target?:boolean}){return <span className={'monitor-rate '+(value===null?'neutral':pending?'amber':value>=(target?1:.7)?'green':value<.4?'red':'amber')} title={pending?'Provisional: some mapped profiles are not yet decided':target?'Approved ÷ team approval target':'Approved ÷ mapped; green ≥70%, red <40%, amber between'}>{pending&&value===0?'Pending':pct(value)}{pending&&<small>Review pending</small>}</span>;}
function Trend({title,rows,series,onDay}:{title:string;rows:R[];series:{key:string;label:string;color:string}[];onDay:(date:string)=>void}){
 const max=Math.max(1,...rows.flatMap(r=>series.map(s=>Number(r[s.key]||0)))),x=(i:number)=>45+(rows.length===1?260:i*520/(rows.length-1)),y=(n:number)=>150-120*n/max;
 return <section className="monitor-chart"><h3>{title}</h3><div className="monitor-chart-legend">{series.map(s=><span key={s.key}><i style={{background:s.color}}/>{s.label}</span>)}</div>{!rows.length?<p>No dated activity yet.</p>:<svg viewBox="0 0 610 185" role="img" aria-label={title+' by mapping date'}><title>{title}. Select a day to inspect its activity.</title>{[0,.5,1].map(f=><g key={f}><line x1="45" x2="565" y1={y(max*f)} y2={y(max*f)} stroke="#e1e7ef"/><text x="38" y={y(max*f)+4} textAnchor="end">{num(max*f)}</text></g>)}{series.map(s=><g key={s.key}><polyline fill="none" stroke={s.color} strokeWidth="2.5" points={rows.map((r,i)=>`${x(i)},${y(r[s.key]||0)}`).join(' ')}/>{rows.map((r,i)=><circle key={r.date} cx={x(i)} cy={y(r[s.key]||0)} r="4" fill={s.color}><title>{displayDate(r.date)} · {s.label}: {num(r[s.key]||0)}</title></circle>)}</g>)}{rows.map((r,i)=><rect key={r.date} x={x(i)-Math.min(14,250/rows.length)} y="22" width={Math.min(28,500/rows.length)} height="135" fill="transparent" tabIndex={0} role="button" aria-label={'Show '+displayDate(r.date)} onClick={()=>onDay(r.date)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onDay(r.date);}}}><title>{displayDate(r.date)} · Mapped {r.mapped} · Approved {r.approved} · Hours {num(r.hours)}</title></rect>)}<text x="45" y="175">{displayDate(rows[0].date)}</text><text x="565" y="175" textAnchor="end">{displayDate(rows.at(-1)!.date)}</text></svg>}</section>;
}
export function DeliveryMonitor({data,initialRoles=null,initialState={},onStateChange,onOpen,onCandidate,api,reload,onDirty}: {data:R;api?:(p:string,b?:unknown)=>Promise<any>;reload?:()=>Promise<void>;onDirty?:(v:boolean)=>void;initialState?:R;onStateChange?:(state:R)=>void;initialView?:'daily'|'pipeline';initialRoles?:string[]|null;onOpen:(id:string,tab:string,mapping?:string)=>void;onCandidate:(id:string)=>void;onAllocate?:(id:string,date:string)=>void}){
 const [mapping,setMapping]=useState<R|null>(null);const cohortScroll=useRef(0);
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());
 const [roles,setRoles]=useState<string[]|null>(initialState.roles??initialRoles),[team,setTeam]=useState(initialState.team||''),[attention,setAttention]=useState(initialState.attention||false),[query,setQuery]=useState(initialState.query||''),[searchId,setSearchId]=useState(initialState.searchId||''),[period,setPeriod]=useState(initialState.period||'all'),[from,setFrom]=useState(initialState.from||''),[to,setTo]=useState(initialState.to||''),[day,setDay]=useState(''),[cohort,setCohort]=useState<{title:string;items:R[]}|null>(null);
 const [statuses,setStatuses]=useState<string[]|null>(initialState.statuses??null);
 const availableSearches=useMemo(()=>data.searches.filter((s:R)=>matchesSearchStatuses(s,statuses)),[data.searches,statuses]);
 const selectedRoles=useMemo(()=>availableSearches.filter((s:R)=>roles===null||roles.includes(s.id)).map((s:R)=>s.id),[availableSearches,roles]);
 const range=monitorRange(period,today,from,to);
 useEffect(()=>{onStateChange?.({view:'daily',roles,statuses,team,attention,query,searchId,period,from,to});},[roles,statuses,team,attention,query,searchId,period,from,to]);
 const rows=useMemo(()=>sourcingMonitorRows(data,selectedRoles,range.from,range.to,today,team),[data,selectedRoles,range.from,range.to,today,team]);
 const shown=rows.filter(r=>(!attention||r.attention.length)&&[r.role,r.client,r.search_number].join(' ').toLowerCase().includes(query.toLowerCase())),search=rows.find(r=>r.id===searchId);
 const candidates=new Map((data.research?.records||[]).filter((r:R)=>r.kind==='candidate').map((r:R)=>[r.id,r])),people=new Map((data.staff||[]).map((p:R)=>[p.id,p.name]));
 const openSearch=(id:string)=>{setSearchId(id);setDay('');setPeriod('all');};
 const count=(r:R,key:string,items:string,label:string)=><button className="text-button monitor-count" disabled={!r[key]} onClick={()=>{cohortScroll.current=0;setCohort({title:label,items:r[items]});}}>{r[key]}</button>;
 const daily=search?.daily.filter((r:R)=>(!range.from||r.date>=range.from)&&r.date<=range.to)||[];
 const selectedDay=daily.find((r:R)=>r.date===day),persons=selectedDay?.researchers||search?.periodResearchers||[];
 const personTable=<div className="monitor-table-scroll"><SortableTable stateKey="monitor.researchers.v2" className="sheet-table monitor-detail-table"><thead><tr><th>Researcher</th><th>Effort hours</th><th>Mapped</th><th>Share of mappings</th><th>Approved</th><th>Share of approvals</th><th>Quality</th><th>Pending</th><th>Attention</th></tr></thead><tbody>{persons.map((p:R)=>{const peers=persons.filter((o:R)=>o.id!==p.id&&o.hours>0),peerRate=peers.length?peers.reduce((n:number,o:R)=>n+o.mapped,0)/peers.reduce((n:number,o:R)=>n+o.hours,0):null;const low=p.hours>0&&peerRate!==null&&p.mapped/p.hours<peerRate*.5;return <tr key={p.id}><th scope="row">{p.name}</th><td>{num(p.hours)}</td><td>{count(p,'mapped','mappings','Mapped by '+p.name)}</td><td data-sort-value={p.mappingShare}>{pct(p.mappingShare)}</td><td>{count(p,'approved','approvedMappings','Approved profiles mapped by '+p.name)}</td><td data-sort-value={p.approvalShare}>{pct(p.approvalShare)}</td><td data-sort-value={p.quality}><Rate value={p.quality} pending={p.provisional}/></td><td>{count(p,'waiting','waitingMappings','Pending profiles mapped by '+p.name)}</td><td>{p.mapped>=5&&!p.provisional&&p.quality<.4?<span className="monitor-note red">Approval ratio below 40%</span>:low?<span className="monitor-note amber" title="Mappings per effort hour are less than half the other researchers in this search and selected period. Estimated effort; inspect context before drawing conclusions.">Mapping pace below peers</span>:p.provisional?<span className="monitor-note amber">Awaiting decisions</span>:'—'}</td></tr>;})}</tbody></SortableTable>{!persons.length&&<p className="sheet-empty">No researcher activity in this period.</p>}</div>;
 return <section className="panel delivery-monitor cumulative-monitor">
 {!search?<><div className="sheet-toolbar"><label>Find search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ID, name or client"/></label><SearchStatusMultiFilter searches={data.searches} value={statuses} onChange={setStatuses}/><SearchMultiFilter searches={availableSearches} value={roles===null?null:selectedRoles} onChange={setRoles}/><label>Team<select value={team} onChange={e=>setTeam(e.target.value)}><option value="">All teams</option>{data.teams.map((t:R)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="checkbox"><input type="checkbox" checked={attention} onChange={e=>setAttention(e.target.checked)}/>Needs attention only</label><span className="fine">Through {displayDate(today)}</span></div>
 <div className="monitor-table-scroll"><SortableTable stateKey="monitor.overview.v2" className="sheet-table monitor-overview"><colgroup><col style={{width:65}}/><col style={{width:230}}/>{Array.from({length:10},(_,i)=><col key={i} style={{width:i===8?105:78}}/>)}<col style={{width:220}}/><col style={{width:45}}/></colgroup><thead><tr><th>Search ID</th><th>Search / client</th><th>Days since first map</th><th>Effort hours</th><th>Maps / person-day</th><th>Mapped</th><th>Approved</th><th>Approval target to date</th><th>Throughput</th><th>Quality</th><th>Pending</th><th>Days since last map</th><th>Attention</th><th>Actions</th></tr></thead><tbody>{shown.map(r=><tr key={r.id} onDoubleClick={()=>openSearch(r.id)}><td>{r.search_number??'—'}</td><th scope="row"><button className="monitor-search-link" onClick={()=>openSearch(r.id)}>{r.role}</button><small>{r.client}</small></th><td>{r.daysSinceFirstMap??'—'}</td><td>{num(r.hours)}</td><td>{num(r.mappingsPerPersonDay)}</td><td>{count(r,'mapped','mappings',r.role+' · All mapped')}</td><td>{count(r,'approved','approvedMappings',r.role+' · Approved')}</td><td>{r.target??'—'}{r.targetIncomplete&&<small>Incomplete</small>}</td><td data-sort-value={r.throughput}><Rate value={r.throughput} target pending={r.provisional}/></td><td data-sort-value={r.quality}><Rate value={r.quality} pending={r.provisional}/></td><td>{count(r,'waiting','waitingMappings',r.role+' · Pending review')}{r.oldestPending>0&&<small>Oldest {r.oldestPending}d</small>}</td><td>{r.idleDays??'—'}</td><td>{r.attention.map((a:R)=><button key={a.key} className={'monitor-note '+a.tone} title={a.action} onClick={()=>a.items?setCohort({title:r.role+' · '+a.action,items:a.items}):openSearch(r.id)}>{a.cause}</button>)}{!r.attention.length&&<span className="monitor-note neutral">{r.mapped?'No flags':'Not started'}</span>}</td><td><IconAction label="Daily progress" accessibleLabel={'Daily progress for '+r.role} onClick={()=>openSearch(r.id)}><ChartLine size={19}/></IconAction></td></tr>)}</tbody></SortableTable>{!shown.length&&<p className="sheet-empty">No searches match these filters.</p>}</div></>:<>
 <div className="section-head"><h2>{search.role}<small>{search.client}</small></h2><button onClick={()=>{setSearchId('');setDay('');}}>All searches</button></div>
 <div className="sheet-toolbar"><label>Mapping period<select value={period} onChange={e=>{setPeriod(e.target.value);setDay('');}}>{monitorPeriods.map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label>{period==='custom'&&<><label>From<input type="date" max={range.to} value={from} onChange={e=>{setFrom(e.target.value);setDay('');}}/></label><label>Through<input type="date" min={from} max={today} value={to||today} onChange={e=>{setTo(e.target.value);setDay('');}}/></label></>}<span className="fine">Approvals attributed to mapping date · US Eastern</span></div>
 <div className="monitor-kpis">{[['Mapped',search.period.mapped],['Approved',search.period.approved],['Team target',search.period.target??'—'],['Throughput',search.period.provisional&&!search.period.approved?'Pending':pct(search.period.throughput)],['Quality',search.period.provisional&&!search.period.approved?'Pending':pct(search.period.quality)],['Effort hours',num(search.period.hours)]].map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>
 <div className="monitor-charts"><Trend title="Cumulative approvals against plan" rows={daily} series={[{key:'cumulativeTarget',label:'Target through each day',color:'#94a3b8'},{key:'cumulativeApproved',label:'Approved from mappings',color:'#16976e'}]} onDay={setDay}/><Trend title="Daily mapping and approval results" rows={daily} series={[{key:'mapped',label:'Mapped',color:'#2865c7'},{key:'approved',label:'Approved from these mappings',color:'#16976e'}]} onDay={setDay}/><Trend title="Daily quality (%)" rows={daily.filter((r:R)=>r.mapped).map((r:R)=>({...r,qualityPercent:r.quality*100}))} series={[{key:'qualityPercent',label:'Approved ÷ mapped (pending is provisional)',color:'#9862c7'}]} onDay={setDay}/></div>
 <div className="monitor-table-scroll"><SortableTable stateKey="monitor.days.v2" className="sheet-table monitor-detail-table"><thead><tr><th>Mapping date</th><th>Researchers</th><th>Effort hours</th><th>Team target</th><th>Mapped</th><th>Approved</th><th>Throughput</th><th>Quality</th><th>Pending</th></tr></thead><tbody>{[...daily].reverse().map((r:R)=><tr key={r.date} className={day===r.date?'monitor-selected':''} onDoubleClick={()=>setDay(r.date)}><th scope="row" data-sort-value={r.date}><button className="text-button" aria-pressed={day===r.date} onClick={()=>setDay(day===r.date?'':r.date)}>{displayDate(r.date)}</button></th><td>{r.researchers.map((p:R)=>p.name).join(', ')||'—'}</td><td>{num(r.hours)}</td><td>{r.target??'—'}</td><td>{count(r,'mapped','mappings',displayDate(r.date)+' · Mapped')}</td><td>{count(r,'approved','approvedMappings',displayDate(r.date)+' · Approved')}</td><td data-sort-value={r.throughput}><Rate value={r.throughput} target pending={r.provisional}/></td><td data-sort-value={r.quality}><Rate value={r.quality} pending={r.provisional}/></td><td>{count(r,'waiting','waitingMappings',displayDate(r.date)+' · Pending')}</td></tr>)}</tbody></SortableTable>{!daily.length&&<p className="sheet-empty">No dated activity in this period.</p>}</div>
 {!!search.unknownMappingDates&&<p className="fine">{search.unknownMappingDates} historical mappings have no mapping date. They remain in cumulative totals and are excluded from daily charts.</p>}
 <div className="section-head"><h3>{selectedDay?'Researchers · '+displayDate(day):'Researchers · selected period'}</h3>{selectedDay&&<button onClick={()=>setDay('')}>Show whole period</button>}</div>{personTable}
 </>}
 <details className="metric-definitions"><summary>Metric definitions & alert rules</summary><p>Quality = current partner-approved profiles ÷ mapped profiles. Throughput = approved ÷ team approval target. Targets are summed per team per planned day through today; future days are excluded. Researchers have contribution shares, not individual targets. Approvals stay with the original mapping date and earlier days update as reviews arrive.</p><p>Pending profiles make ratios provisional. Low-quality alerts require at least 5 mappings, all decided and at least 3 days old. Target shortfalls use targets at least 3 days old and wait for outstanding decisions in that cohort. Other inspection flags: review pending over 3 days, at least 200 effort hours, below 10 mappings per active researcher-day after 3 researcher-days, or over 100 days since first mapping. These flags prompt review; they do not establish an employee rating or client interest.</p><p>Effort is estimated from allocated person-days × {hoursPerPersonDay(data)} hours, excluding PTO and applying recorded corrections. Maps per person-day uses distinct researcher/date pairs with effort or mappings; undated or unattributed mappings are excluded from that average. Daily charts show work dates, including planned days with no output. Cumulative chart values include activity before a selected custom period and approvals known now, not historical approval snapshots.</p></details>
 {mapping&&api&&reload&&<ResearchPanel key={mapping.id} modalOnly onModalClose={()=>setMapping(null)} data={data} api={api} reload={reload} onDirty={onDirty||(()=>{})} view="Search repository" initialRole={mapping.role_id} initialMapping={mapping.id} onCandidate={onCandidate}/>}
 {cohort&&!mapping&&<Popup title={cohort.title} onClose={()=>setCohort(null)}><div className="sheet-scroll" ref={node=>{if(node)node.scrollTop=cohortScroll.current;}} onScroll={e=>{cohortScroll.current=e.currentTarget.scrollTop;}}><SortableTable stateKey="SourcingMonitor.cohort" className="sheet-table"><thead><tr><th>Candidate</th><th>Status</th><th>Researcher</th><th>Mapped</th><th>Action</th></tr></thead><tbody>{cohort.items.map(original=>{const m=(data.research?.records||[]).find((r:R)=>r.kind==='mapping'&&r.id===original.id)||original;const c=candidates.get(m.candidate_id) as R|undefined;return <tr key={m.id}><td><LinkedInIcon url={c?.url||m.url} name={c?.name||m.name}/><button className="text-button" onClick={()=>onCandidate(m.candidate_id)}>{c?.name||m.name||'Candidate unavailable'}</button></td><td>{m.status==='Peer review'?'Team review':m.status}</td><td>{String(people.get(m.staff_id)||'Unattributed')}</td><td data-sort-value={m.created_at||m.work_date}>{displayDate(m.created_at||m.work_date)}</td><td><IconAction label="View mapping" onClick={()=>setMapping(m)}><Eye size={18}/></IconAction></td></tr>})}</tbody></SortableTable></div></Popup>}
 </section>;
}
