import React,{useState} from 'react';
export function EmailSettings({api,email,reload,disabled,onDirty}:{api:(p:string,b?:unknown)=>Promise<any>;email:string;reload:()=>Promise<void>;disabled:boolean;onDirty:(v:boolean)=>void}) {
 const [next,setNext]=useState(''),[password,setPassword]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[current,setCurrent]=useState(email);
 function change(nextValue:string,passwordValue:string,codeValue:string){setNext(nextValue);setPassword(passwordValue);setCode(codeValue);onDirty(!!(nextValue||passwordValue||codeValue));}
 async function request(){setBusy(true);setError('');setMessage('');try{const r=await api('change-email/request',{email:next,currentPassword:password});setSent(r.email);setPassword('');setCode('');setMessage('Code sent to '+r.email+'. Enter it below within 10 minutes.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <section className="panel"><h2>Change sign-in email</h2><p>Current email: <strong>{current}</strong>. The change applies across all your workspaces. Verify your current password and the new email address; your work history stays linked to you.</p>
 <form onSubmit={e=>{e.preventDefault();request();}}><label>New sign-in email<input type="email" required maxLength={254} disabled={busy||disabled} value={next} onChange={e=>change(e.target.value,password,code)}/></label><label>Current password<input type="password" required maxLength={128} autoComplete="current-password" disabled={busy||disabled} value={password} onChange={e=>change(next,e.target.value,code)}/></label><button disabled={busy||disabled}>{busy?'Working…':sent?'Send a new code':'Send verification code'}</button>{sent&&<p className="fine">For another code, re-enter your password. Wait at least one minute between requests.</p>}</form>
 {sent&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await api('change-email/confirm',{code});setCurrent(r.email);setSent('');change('','','');setMessage('Sign-in email changed. Use '+r.email+' next time. Other sessions have been signed out.'+(r.notificationStatus!=='accepted'?' Notification to the old email could not be confirmed.':''));await reload();}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><label>Verification code sent to {sent}<input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required autoComplete="one-time-code" disabled={busy||disabled} value={code} onChange={e=>change(next,password,e.target.value)}/></label><button className="primary" disabled={busy||disabled}>Verify and change email</button></form>}
 <button type="button" disabled={busy||disabled} onClick={()=>{change('','','');setSent('');setError('');setMessage('');}}>Clear form</button>{error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 </section>;
}
