import React,{useEffect,useState} from 'react';
import {canPlan,hasRole} from './domain';
import {engagementRows,engagementStages,defaultSequence,interactionTypes} from './engagement';
import {displayDate} from './dates';
import {RolePicker} from './RolePicker';
import {teamColor} from './team-colors';
type R=Record<string,any>;
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());
export function Engagement({data,api,reload,onDirty,onCandidate,mine=false}:any){
 const [view,setView]=useState(mine?'My queue':'Pipeline'),[role,setRole]=useState(''),[teamFilter,setTeamFilter]=useState(''),[query,setQuery]=useState(''),[edit,setEdit]=useState<R|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[showClosed,setShowClosed]=useState(false),[closedSearches,setClosedSearches]=useState(false),[page,setPage]=useState(0);
 const records:R[]=data.research.records,teams=records.filter(r=>r.kind==='engagement-team'),people=data.people.filter((p:R)=>hasRole(p,'engagement')),rows=engagementRows(records,data.searches),search=data.searches.find((s:R)=>s.id===role),planner=canPlan(data.actor),manager=planner||hasRole(data.actor,'partner')&&search?.partner_id===data.actor.id;
 useEffect(()=>{onDirty(!!edit);return()=>onDirty(false);},[!!edit]);
 useEffect(()=>setPage(0),[role,teamFilter,query,view,showClosed,closedSearches]);
 async function act(body:R){setBusy(true);setError('');try{await api('research',body);await reload();setEdit(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const name=(id:string)=>data.people.find((p:R)=>p.id===id)?.name||'Unassigned';
 const candidate=(r:R)=>records.find(c=>c.kind==='candidate'&&c.id===r.candidate_id);
 const roleName=(id:string)=>{const s=data.searches.find((s:R)=>s.id===id);return s?`${s.client} · ${s.title}`:'Search';};
 const canManage=(r:R)=>planner||hasRole(data.actor,'partner')&&data.searches.find((s:R)=>s.id===r.role_id)?.partner_id===data.actor.id;
 const isLead=(r:R)=>hasRole(data.actor,'engagement')&&teams.some(t=>t.id===r.team_id&&t.lead_id===data.actor.id&&t.member_ids.includes(data.actor.id));
 const canWork=(r:R)=>canManage(r)||isLead(r)||hasRole(data.actor,'engagement')&&r.owner_id===data.actor.id&&teams.some(t=>t.id===r.team_id&&t.member_ids.includes(data.actor.id));
 const visible=rows.filter(r=>(closedSearches||!r.search_closed)&&(!role||r.role_id===role)&&(!teamFilter||r.team_id===teamFilter)&&(!query||[candidate(r)?.name,candidate(r)?.company].join(' ').toLowerCase().includes(query.toLowerCase()))&&(view!=='My queue'||r.owner_id===data.actor.id)&&(showClosed||!['Placed','Candidate declined','Client rejected'].includes(r.stage))).sort((a,b)=>(a.due_date||'9999').localeCompare(b.due_date||'9999'));
 const open=(r:R,mode:string)=>{setError('');setEdit({...r,mode,notes:'',occurred_on:today(),start_date:today(),next_action:r.search_closed?'':r.next_action||'',due_date:r.search_closed?'':r.due_date||''});};
 const actions=(r:R)=><div className="engagement-card-actions">{r.approved&&!r.search_closed&&(canManage(r)||isLead(r))&&<button onClick={()=>open(r,'assign')}>{r.owner_id?'Reassign':'Assign'}</button>}{r.approved&&canWork(r)&&<button onClick={()=>open(r,'work')}>Update</button>}</div>;
 const status=(r:R)=>r.search_closed?'Search closed · outreach stopped':!r.approved?'Paused · sourcing reopened':r.stage;
 return <section className="panel engagement-workspace"><div className="research-tabs">{(mine?['My queue']:['Pipeline','My queue','Teams']).map(t=><button key={t} className={view===t?'primary':''} onClick={()=>setView(t)}>{t}</button>)}</div>{error&&!edit&&<p className="error" role="alert">{error}</p>}
 {view==='Teams'?<><div className="section-head"><div><h2>Engagement teams</h2><p className="fine">Separate from sourcing teams. Enable Engagement in People & access before adding a member.</p></div>{planner&&<button onClick={()=>setEdit({mode:'team',name:'',member_ids:[],lead_id:''})}>Add engagement team</button>}</div>{teams.map(t=><div className="work-row" key={t.id}><span><strong style={{color:teamColor(t.name,t.id)}}>{t.name}</strong><small>Lead: {name(t.lead_id)} · {t.member_ids.map(name).join(', ')}</small></span>{planner&&<button onClick={()=>setEdit({...t,mode:'team'})}>Edit team</button>}</div>)}{!teams.length&&<p>No engagement teams configured yet.</p>}</>:<><div className="sheet-toolbar"><RolePicker searches={data.searches} value={role} onChange={setRole} allowAll/><label>Engagement team<select value={teamFilter} onChange={e=>setTeamFilter(e.target.value)}><option value="">All teams</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Find candidate<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="checkbox"><input type="checkbox" checked={showClosed} onChange={e=>setShowClosed(e.target.checked)}/>Include closed outcomes</label><label className="checkbox"><input type="checkbox" checked={closedSearches} onChange={e=>setClosedSearches(e.target.checked)}/>Include closed searches</label>{role&&manager&&<button onClick={()=>{const old=records.find(r=>r.kind==='engagement-sequence'&&r.role_id===role);setEdit({...old,mode:'sequence',role_id:role,steps:old?.steps||defaultSequence});}}>Configure outreach sequence</button>}</div>
 <p className="fine">{visible.length} candidates · Partner-approved sourcing handoffs{search?` · Engagement partner: ${search.partner||'Not assigned'}`:''}. Outreach is sent through your existing channels; record activity here.</p>
 {view==='Pipeline'&&role?<div className="engagement-board">{engagementStages.filter(s=>showClosed||!['Placed','Candidate declined','Client rejected'].includes(s)).map(stage=>{const items=visible.filter(r=>r.stage===stage);return <section className="engagement-column" key={stage}><h3>{stage} <span>{items.length}</span></h3>{items.slice(0,50).map(r=>{const c=candidate(r),t=teams.find(t=>t.id===r.team_id);return <article className="engagement-card" key={r.mapping_id}><button className="text-button" onClick={()=>onCandidate(c?.id)}>{c?.name}</button><small>{c?.company} · {c?.title}</small>{r.search_closed&&<p className="fine">Search closed · outreach stopped</p>}{!r.approved&&<p className="error">Sourcing reopened · engagement paused</p>}<span className="plan-team-badge" style={{'--team-color':teamColor(t?.name||'',t?.id||'')} as React.CSSProperties}>{t?.name||'Awaiting team assignment'}</span><small>{name(r.owner_id)}</small>{r.next_action&&<p>{r.next_action}<small className={r.due_date<today()?'error':''}>{displayDate(r.due_date)}</small></p>}{actions(r)}</article>;})}{items.length>50&&<p className="fine">Showing 50. Narrow the candidate filter to see more.</p>}</section>;})}</div>:<><p className="fine">{view==='Pipeline'?'Choose a search for its Kanban board.':'Your assigned candidates, ordered by next action date. Overdue actions appear first.'}</p><div className="table-scroll"><table className="sheet-table"><thead><tr><th>Candidate / search</th><th>Stage</th><th>Engagement team / owner</th><th>Next action</th><th>Due</th><th>Action</th></tr></thead><tbody>{visible.slice(page*25,page*25+25).map(r=><tr key={r.mapping_id}><td><button className="text-button" onClick={()=>onCandidate(r.candidate_id)}>{candidate(r)?.name}</button><small>{roleName(r.role_id)}</small></td><td>{status(r)}</td><td>{teams.find(t=>t.id===r.team_id)?.name||'Awaiting team assignment'}<small>{name(r.owner_id)}</small></td><td>{r.next_action||'Set next action'}</td><td className={r.due_date&&r.due_date<today()?'error':''}>{r.due_date?displayDate(r.due_date):'—'}</td><td>{actions(r)}</td></tr>)}</tbody></table></div><div className="candidate-pagination"><button disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><span>{visible.length} candidates · Page {page+1} of {Math.max(1,Math.ceil(visible.length/25))}</span><button disabled={(page+1)*25>=visible.length} onClick={()=>setPage(page+1)}>Next</button></div></>}{!visible.length&&<p>No candidates match this view. Partner-approved candidates enter the engagement queue automatically.</p>}</>}
 {edit&&<div className="modal-backdrop"><section className="modal engagement-modal" role="dialog" aria-modal="true" aria-label="Engagement editor"><div className="section-head"><h2>{({team:'Engagement team',assign:'Assign engagement owner',work:'Candidate engagement',sequence:'Outreach sequence'} as R)[edit.mode]}</h2><button disabled={busy} onClick={()=>{if(confirm('Discard unsaved changes?'))setEdit(null);}}>Close</button></div>{edit.mapping_id&&<p><strong>{candidate(edit)?.name}</strong><small>{roleName(edit.role_id)} · Engagement partner: {data.searches.find((s:R)=>s.id===edit.role_id)?.partner||'Not assigned'}</small></p>}
 {edit.mode==='team'&&<form onSubmit={e=>{e.preventDefault();act({...edit,action:'engagement-team-save'});}}><label>Team name<input required value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><fieldset><legend>Engagement members</legend>{people.map((p:R)=><label className="checkbox" key={p.id}><input type="checkbox" checked={edit.member_ids.includes(p.id)} onChange={e=>setEdit({...edit,member_ids:e.target.checked?[...edit.member_ids,p.id]:edit.member_ids.filter((id:string)=>id!==p.id),lead_id:!e.target.checked&&edit.lead_id===p.id?'':edit.lead_id})}/>{p.name}</label>)}{!people.length&&<p>Enable Engagement on the appropriate accounts in People & access first.</p>}</fieldset><label>Team lead<select required value={edit.lead_id} onChange={e=>setEdit({...edit,lead_id:e.target.value})}><option value="">Choose lead</option>{people.filter((p:R)=>edit.member_ids.includes(p.id)).map((p:R)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="primary" disabled={busy}>Save team</button></form>}
 {edit.mode==='assign'&&<form onSubmit={e=>{e.preventDefault();act({...edit,action:'engagement-assign'});}}><label>Engagement team<select required value={edit.team_id||''} onChange={e=>setEdit({...edit,team_id:e.target.value,owner_id:''})}><option value="">Choose team</option>{teams.filter(t=>canManage(edit)||t.id===edit.team_id).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Engagement owner<select required value={edit.owner_id||''} onChange={e=>setEdit({...edit,owner_id:e.target.value})}><option value="">Choose member</option>{people.filter((p:R)=>teams.find(t=>t.id===edit.team_id)?.member_ids.includes(p.id)).map((p:R)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button disabled={busy} className="primary">Save assignment</button></form>}
 {edit.mode==='sequence'&&<form onSubmit={e=>{e.preventDefault();act({...edit,action:'engagement-sequence-save'});}}><p className="fine">Days are counted from the prior completed step; the first delay is from the start date. Changes apply to newly started sequences.</p>{edit.steps.map((s:R,i:number)=><div className="sequence-row" key={i}><strong>{i+1}</strong><label>Step<input required value={s.label} onChange={e=>setEdit({...edit,steps:edit.steps.map((v:R,j:number)=>j===i?{...v,label:e.target.value}:v)})}/></label><label>Channel<select value={s.channel} onChange={e=>setEdit({...edit,steps:edit.steps.map((v:R,j:number)=>j===i?{...v,channel:e.target.value}:v)})}>{interactionTypes.filter(t=>!['Note','Transcript','Assessment link'].includes(t)).map(t=><option key={t}>{t}</option>)}</select></label><label>Days<input type="number" min="0" max="365" required value={s.delay} onChange={e=>setEdit({...edit,steps:edit.steps.map((v:R,j:number)=>j===i?{...v,delay:Number(e.target.value)}:v)})}/></label><button type="button" onClick={()=>setEdit({...edit,steps:edit.steps.filter((_:R,j:number)=>j!==i)})}>Remove</button></div>)}<div className="row-actions"><button type="button" onClick={()=>setEdit({...edit,steps:[...edit.steps,{label:'Follow-up',channel:'Phone call',delay:3}]})}>Add step</button><button className="primary" disabled={busy}>Save sequence</button></div></form>}
 {edit.mode==='work'&&<>{edit.search_closed&&<p className="notice">Search closed. You can record feedback and outcomes; outreach is stopped.</p>}<form onSubmit={e=>{e.preventDefault();act({...edit,action:'engagement-update'});}}><label>Hiring stage<select value={edit.stage} onChange={e=>setEdit({...edit,stage:e.target.value})}>{engagementStages.map(s=><option key={s}>{s}</option>)}</select></label><label>Activity date<input type="date" required value={edit.occurred_on} onChange={e=>setEdit({...edit,occurred_on:e.target.value})}/></label><label>Feedback / outcome<textarea rows={3} value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label><div className="candidate-fields"><label>Next action<input value={edit.next_action} onChange={e=>setEdit({...edit,next_action:e.target.value})}/></label><label>Due date<input type="date" required={!!edit.next_action} value={edit.due_date} onChange={e=>setEdit({...edit,due_date:e.target.value})}/></label></div><button className="primary" disabled={busy}>Save update</button></form><hr/><h3>Outreach sequence</h3>{edit.sequence?.[edit.step_index]?<><p>Step {edit.step_index+1} of {edit.sequence.length}: <strong>{edit.sequence[edit.step_index].label}</strong></p><p className="fine">Sequences run only while Contacting. Record the activity date and outcome above, then complete this step. The next follow-up date is calculated automatically.</p><button disabled={busy||edit.search_closed||!edit.notes||edit.stage!=='Contacting'} onClick={()=>act({...edit,action:'engagement-complete-step'})}>Complete step & schedule next</button></>:<><label>Sequence start date<input type="date" value={edit.start_date} onChange={e=>setEdit({...edit,start_date:e.target.value})}/></label><button disabled={busy||edit.search_closed} onClick={()=>act({...edit,action:'engagement-start-sequence'})}>Start outreach sequence</button></>}<p className="fine">Open the candidate profile to add call notes, transcripts, email exchanges and documents.</p></>}
 {error&&<p className="error" role="alert">{error}</p>}</section></div>}
 </section>;
}
