import React,{useRef,useEffect,useState} from 'react';
import {useViewState} from './ViewState';
import {SortableTable} from './SortableTable';
import {LinkedInIcon} from './LinkedInIcon';
import {SearchStatusFilter,matchesSearchStatus} from './SearchFilters';
import {SearchPicker} from './SearchPicker';
import {engagementAssignees} from './engagement-domain';
import {pipelineStages,funnelGroups,funnelColors,stageDays} from './engagement-pipeline';
import {searchEngagementRows,searchEngagementActivity} from './engagement-workspace';
type R=Record<string,any>;
type Props={data:any;role:string;setRole:(id:string)=>void;mine:boolean;now:number;canWork:(r:R)=>boolean;open:(r:R,target?:string)=>void;onCandidate:(id:string)=>void;onInterviews?:(id:string)=>void;onAssignments:(role:string)=>void;onAllAssignments?:()=>void};
export function EngagementSearchWorkspace({data,role,setRole,mine,now,canWork,open,onCandidate,onInterviews,onAssignments,onAllAssignments}:Props){
 const records:R[]=data.research.records,searches:R[]=data.searches;
 const [searchQuery,setSearchQuery]=useViewState('Engagement.searchQuery',''),[status,setStatus]=useViewState('Engagement.searchStatus','open'),[scope,setScope]=useViewState('Engagement.scope',mine?'mine':'all');
 const [query,setQuery]=useViewState('Engagement.candidateQuery',''),[group,setGroup]=useViewState('Engagement.group','all'),[layout,setLayout]=useViewState('Engagement.workspaceLayout','List'),[tab,setTab]=useViewState('Engagement.workspaceTab','Candidates'),[focus,setFocus]=useViewState('Engagement.focus',''),[attention,setAttention]=useViewState('Engagement.workspaceAttention',false);
 const [activeOnly,setActiveOnly]=useViewState('Engagement.activeOnly',false);
 const [dragging,setDragging]=useState('');
 const [showEmpty,setShowEmpty]=useViewState('Engagement.showEmpty',false);
 const detail=useRef<HTMLElement>(null);
 useEffect(()=>{if(!focus)return;const previous=document.activeElement as HTMLElement;const handle=(e:KeyboardEvent)=>{if(e.key==='Escape'){setFocus('');return;}if(e.key!=='Tab')return;const items=Array.from(detail.current?.querySelectorAll<HTMLElement>('button,a[href],input,select,textarea,[tabindex="0"]')||[]);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}};document.addEventListener('keydown',handle);return()=>{document.removeEventListener('keydown',handle);previous?.focus();};},[focus]);
 const board=useRef<HTMLDivElement>(null),all=searchEngagementRows(records,searches,now),search=searches.find(s=>s.id===role),rows=all.filter(r=>r.role_id===role),stages=pipelineStages(records);
 const candidate=(id:string)=>records.find(r=>r.kind==='candidate'&&r.id===id),name=(id:string)=>data.people.find((p:R)=>p.id===id)?.name||'Former member';
 const matches=(values:any[],q:string)=>q.trim().toLowerCase().split(/\s+/).every(t=>values.join(' ').toLowerCase().includes(t));
 const visible=rows.filter(r=>matches([candidate(r.candidate_id)?.name,candidate(r.candidate_id)?.company,candidate(r.candidate_id)?.title],query)&&(group==='all'||r.group===group)&&(!activeOnly||r.active)&&(!attention||r.attention));
 const selectSearch=(id:string)=>{setQuery('');setGroup('all');setAttention(false);setActiveOnly(false);setFocus('');setTab('Candidates');setRole(id);};
 const drillDown=(id:string,bucket:string)=>{selectSearch(id);setLayout('List');setActiveOnly(bucket==='active');setAttention(bucket==='attention');setGroup(bucket==='placed'?'Placed':'all');};
 const focused=rows.find(r=>r.mapping_id===focus),activities=searchEngagementActivity(records,role),focusedActivities=focused?searchEngagementActivity(records,role,focused.candidate_id):[];
 const identity=(r:R)=><><button className="text-button" onClick={()=>setFocus(r.mapping_id)}>{candidate(r.candidate_id)?.name||'Candidate unavailable'}</button><LinkedInIcon url={candidate(r.candidate_id)?.url} name={candidate(r.candidate_id)?.name}/><small>{[candidate(r.candidate_id)?.title,candidate(r.candidate_id)?.company].filter(Boolean).join(' · ')}</small></>;
 const timeline=(items:R[])=><div className="engagement-timeline">{items.map(a=><article key={a.id}><div><button className="text-button" onClick={()=>{const r=rows.find(r=>r.candidate_id===a.candidate_id);if(r)setFocus(r.mapping_id);}}>{candidate(a.candidate_id)?.name||'Candidate unavailable'}</button><LinkedInIcon url={candidate(a.candidate_id)?.url} name={candidate(a.candidate_id)?.name}/><small>{a.occurred_on||a.created_at?.slice(0,10)} · {name(a.actor_id)} · {a.type}</small></div>{a.to_stage&&<p className="fine">{a.from_stage&&a.from_stage!==a.to_stage?`${a.from_stage} → `:''}{a.to_stage}</p>}<p className="engagement-note">{a.notes}</p></article>)}{!items.length&&<p className="fine">No activity recorded for this search yet.</p>}</div>;
 if(!search)return <><div className="section-head"><p className="fine">Open a search to see its candidates, engagement stages and activity.</p>{onAllAssignments&&<button onClick={onAllAssignments}>Manage assignments</button>}</div><div className="sheet-toolbar"><label>Find a search<input type="search" placeholder="Search name or client" value={searchQuery} onChange={e=>setSearchQuery(e.target.value)}/></label><SearchStatusFilter searches={searches} value={status} onChange={setStatus}/><div className="research-tabs" aria-label="Search ownership">{['all','mine'].map(v=><button key={v} aria-pressed={scope===v} className={scope===v?'primary':''} onClick={()=>setScope(v)}>{v==='all'?'All searches':'Assigned to me'}</button>)}</div></div><div className="table-scroll"><SortableTable stateKey="Engagement.searchOverviewSort" className="sheet-table"><thead><tr><th>Search</th><th>Status</th><th>Candidates</th><th>Active</th><th>Needs attention</th><th>Placed</th><th>Assigned members</th></tr></thead><tbody>{searches.filter(s=>matchesSearchStatus(s,status)&&matches([s.title,s.client],searchQuery)&&(scope==='all'||engagementAssignees(records,s.id).includes(data.actor.id))).map(s=>{const items=all.filter(r=>r.role_id===s.id);return <tr key={s.id}><td><button className="text-button" onClick={()=>selectSearch(s.id)}>{s.title}</button><small>{s.client}</small></td><td>{s.status||'Not set'}</td>{[['all','Candidates',items.length],['active','Active',items.filter(r=>r.active).length],['attention','Needs attention',items.filter(r=>r.attention).length],['placed','Placed',items.filter(r=>r.group==='Placed').length]].map(([bucket,label,count])=><td key={bucket} data-sort-value={count}><button className="text-button" aria-label={`${label} for ${s.title}: ${count}`} onClick={()=>drillDown(s.id,String(bucket))}>{count}</button></td>)}<td>{engagementAssignees(records,s.id).map(name).join(', ')||'Unassigned'}</td></tr>;})}</tbody></SortableTable></div></>;
 return <>
  <div className="engagement-context-bar"><button className="text-button" onClick={()=>selectSearch('')}>← Engagement dashboard</button><SearchPicker searches={searches} value={role} onChange={selectSearch}/><details className="compact-menu"><summary>Search actions</summary><div className="compact-menu-content"><button onClick={()=>onAssignments(role)}>View assignments / funnels</button>{onInterviews&&<button onClick={()=>onInterviews(role)}>Interview tracker</button>}</div></details></div>
  {mine&&<h2>{search.title}</h2>}
  <div className="research-tabs engagement-workspace-tabs" aria-label="Search engagement views">{['Candidates','Activity'].map(v=><button key={v} aria-pressed={tab===v} className={tab===v?'primary':''} onClick={()=>setTab(v)}>{v} <span>{v==='Candidates'?rows.length:activities.length}</span></button>)}</div>
  {tab==='Activity'?timeline(activities):<>
   <div className="engagement-funnel-strip" aria-label="Filter by funnel">{['all','Sourcing',...funnelGroups].map(g=><button key={g} aria-pressed={group===g} className={group===g?'selected':''} onClick={()=>setGroup(g)}>{g==='all'?'All candidates':g} <strong>{g==='all'?rows.length:rows.filter(r=>r.group===g).length}</strong></button>)}</div>
   <div className="sheet-toolbar"><label>Find candidate<input type="search" placeholder="Name, company or title" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="checkbox"><input type="checkbox" checked={activeOnly} onChange={e=>setActiveOnly(e.target.checked)}/>Active only</label><label className="checkbox"><input type="checkbox" checked={attention} onChange={e=>setAttention(e.target.checked)}/>Needs attention</label><span className="fine" role="status">{visible.length} of {rows.length} candidates</span><div className="research-tabs" aria-label="Candidate layout">{['List','Kanban'].map(v=><button key={v} aria-pressed={layout===v} className={layout===v?'primary':''} onClick={()=>setLayout(v)}>{v}</button>)}</div>{(query||group!=='all'||attention||activeOnly)&&<button className="text-button" onClick={()=>{setQuery('');setGroup('all');setAttention(false);setActiveOnly(false);}}>Clear filters</button>}</div>
   {layout==='List'?<div className="table-scroll"><SortableTable stateKey="Engagement.workspaceCandidatesSort" className="sheet-table engagement-candidate-table"><thead><tr><th>Candidate</th><th>Stage</th><th>Assigned to</th><th>Next action</th><th>Days in stage</th><th>Action</th></tr></thead><tbody>{visible.map(r=><tr key={r.mapping_id}><td>{identity(r)}</td><td>{r.stage}{!r.approved&&<small>{r.pending?r.sourcing_status:'Paused · sourcing reopened'}</small>}</td><td>{r.members.map(name).join(', ')||'Unassigned'}</td><td>{r.next_action}{r.attention&&<small className="error">{stageDays(r,now)} days in stage · {stages.find(s=>s.id===r.stage_id)?.threshold} day threshold</small>}</td><td data-sort-value={r.pending?null:stageDays(r,now)}>{r.pending?'—':stageDays(r,now)??'Unknown'}</td><td><button onClick={()=>setFocus(r.mapping_id)}>View</button></td></tr>)}</tbody></SortableTable></div>:<><div className="board-navigation"><label className="checkbox"><input type="checkbox" checked={showEmpty} onChange={e=>setShowEmpty(e.target.checked)}/>Show empty stages</label><div className="row-actions"><button aria-label="Scroll to earlier stages" onClick={()=>board.current?.scrollBy({left:-600,behavior:'smooth'})}>← Earlier</button><button aria-label="Scroll to later stages" onClick={()=>board.current?.scrollBy({left:600,behavior:'smooth'})}>Later →</button></div></div><div ref={board} className="engagement-board" role="region" aria-label="Search candidate Kanban" tabIndex={0}>{[{id:'pending-sourcing',label:'Awaiting sourcing approval',group:'Sourcing'},...stages,...visible.filter(r=>!r.pending&&!stages.some(s=>s.id===r.stage_id)).map(r=>({id:r.stage_id,label:r.stage,group:r.group})).filter((s,i,a)=>a.findIndex(x=>x.id===s.id)===i)].filter(s=>(group==='all'||s.group===group)&&(showEmpty||visible.some(r=>r.stage_id===s.id))).map(s=><section className="engagement-column" key={s.id} onDragOver={e=>{if(dragging&&s.id!=='pending-sourcing')e.preventDefault();}} onDrop={e=>{e.preventDefault();const row=visible.find(r=>r.mapping_id===dragging);setDragging('');if(row&&s.id!=='pending-sourcing'&&row.stage_id!==s.id)open(row,s.id);}} style={{borderTopColor:(funnelColors as R)[s.group]||'#718096'}}><div className="engagement-stage-heading"><small>{s.group}</small><h3>{s.label}<span>{visible.filter(r=>r.stage_id===s.id).length}</span></h3></div>{visible.filter(r=>r.stage_id===s.id).map(r=><article className="engagement-card" key={r.mapping_id} draggable={canWork(r)&&!r.search_closed} onDragStart={e=>{e.dataTransfer.setData('text/plain',r.mapping_id);setDragging(r.mapping_id);}} onDragEnd={()=>setDragging('')}>{identity(r)}<p className="fine">{r.next_action}</p><small>{r.members.map(name).join(', ')||'Unassigned'}{r.attention?` · ${stageDays(r,now)} days in stage / ${stages.find(s=>s.id===r.stage_id)?.threshold} day threshold`:''}</small><button className="text-button" onClick={()=>setFocus(r.mapping_id)}>View activity →</button></article>)}</section>)}</div></>}
   {!visible.length&&<p className="fine">No candidates match this view.</p>}
  </>}
  {focused&&<div className="engagement-detail-backdrop" onClick={()=>setFocus('')}><aside ref={detail} className="engagement-detail" role="dialog" aria-modal="true" aria-label="Candidate engagement" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setFocus('');}}><div className="section-head"><h2>{candidate(focused.candidate_id)?.name}</h2><button autoFocus onClick={()=>setFocus('')}>Close</button></div><LinkedInIcon url={candidate(focused.candidate_id)?.url} name={candidate(focused.candidate_id)?.name}/><p className="fine">{search.title} · {candidate(focused.candidate_id)?.company}</p><p><strong>{focused.stage}</strong></p><p>Next action: {focused.next_action}</p>{focused.attention&&<p className="error">Needs attention: {stageDays(focused,now)} days in stage · {stages.find(s=>s.id===focused.stage_id)?.threshold} day threshold</p>}<p className="fine">Assigned to: {focused.members.map(name).join(', ')||'Unassigned'}</p><div className="row-actions">{canWork(focused)&&<button className="primary" onClick={()=>{setFocus('');open(focused);}}>Record activity / move stage</button>}<button onClick={()=>onCandidate(focused.candidate_id)}>Full candidate profile</button></div><h3>Activity in this search</h3>{timeline(focusedActivities)}</aside></div>}
 </>;
}
