import {SearchStatusFilter,FunnelFilter,matchesSearchStatus,matchesFunnel} from './SearchFilters';
import {candidateMatches,pipelineUsesList} from './interviews';
import React,{useEffect,useState} from 'react';
import {canPlan,hasRole} from './domain';
import {engagementRows,engagementAssignees} from './engagement-domain';
import {pipelineStages,pipelineConfig,resolvedStage,stageDays,stageOverdue,isActiveStage,isLateStage,funnelGroups,funnelColors} from './engagement-pipeline';
import {SearchPicker} from './SearchPicker';
import {teamColor} from './team-colors';
type R=Record<string,any>;
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());
export function Engagement({data,api,reload,onDirty,onCandidate,onInterviews,mine=false,section='Pipeline',initialRole='',initialMapping='',initialStage=''}:any){
 const [role,setRole]=useState(initialRole),[query,setQuery]=useState(''),[edit,setEdit]=useState<R|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[layout,setLayout]=useState('Board'),[funnel,setFunnel]=useState('active'),[attention,setAttention]=useState(false),[searchStatus,setSearchStatus]=useState('open'),[dragging,setDragging]=useState('');
 const records:R[]=data.research.records,teams=records.filter(r=>r.kind==='engagement-team'),people=data.people.filter((p:R)=>hasRole(p,'engagement')),rows=engagementRows(records,data.searches),search=data.searches.find((s:R)=>s.id===role),planner=canPlan(data.actor),stages=pipelineStages(records);
 const [now,setNow]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{onDirty(!!edit||busy);return()=>onDirty(false);},[!!edit,busy]);
 const name=(id:string)=>data.people.find((p:R)=>p.id===id)?.name||'Former member';
 const candidate=(r:R)=>records.find(c=>c.kind==='candidate'&&c.id===r.candidate_id);
 const roleName=(id:string)=>{const s=data.searches.find((s:R)=>s.id===id);return s?`${s.client} · ${s.title}`:'Search';};
 const canManage=(r:R)=>planner||hasRole(data.actor,'partner')&&data.searches.find((s:R)=>s.id===r.role_id)?.partner_id===data.actor.id;
 const assignees=(id:string)=>engagementAssignees(records,id);
 const canWork=(r:R)=>r.approved&&(canManage(r)||hasRole(data.actor,'engagement')&&assignees(r.role_id).includes(data.actor.id));
 const assignSearch=(id:string)=>{const old=records.find(r=>r.kind==='engagement-assignment'&&r.role_id===id);setError('');setEdit({...old,role_id:id,mode:'assign',member_ids:old?.member_ids||[]});};
 async function act(body:R){setBusy(true);setError('');try{await api('research',body);await reload();setEdit(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const open=(r:R,target=r.stage_id)=>{if(!canWork(r)||busy)return;setError('');setEdit({...r,mode:'work',stage_id:target,notes:'',recommended_on:r.recommended_on||'',occurred_on:today(),pipeline_version:pipelineConfig(records)?.version||0});};
 useEffect(()=>{if(initialMapping){const row=rows.find(r=>r.mapping_id===initialMapping);if(row)open(row,initialStage||row.stage_id);}},[initialMapping]);
 const base=rows.filter(r=>matchesSearchStatus(data.searches.find((s:R)=>s.id===r.role_id),searchStatus)&&(!role||r.role_id===role)&&(!mine||assignees(r.role_id).includes(data.actor.id)));
 const visible=base.filter(r=>{const s=resolvedStage(r,stages);return candidateMatches(candidate(r),query)&&matchesFunnel(s.group,funnel)&&(!attention||stageOverdue(r,s,now));}).sort((a,b)=>(stageDays(b,now)??-1)-(stageDays(a,now)??-1));
 const useList=pipelineUsesList(layout,role,query);
 const boardStages=[...stages,...visible.map(r=>resolvedStage(r,stages)).filter((s,i,all)=>!stages.some(x=>x.id===s.id)&&all.findIndex(x=>x.id===s.id)===i)].filter(s=>matchesFunnel(s.group,funnel));
 const age=(r:R)=>{const s=resolvedStage(r,stages),days=stageDays(r,now);return <span className={stageOverdue(r,s,now)?'stage-age overdue':'stage-age'}>{days===null?'Stage age unknown':`${days} ${days===1?'day':'days'} in stage`}{stageOverdue(r,s,now)?` · ${s.threshold}d threshold`:''}</span>;};
 const moveButtons=(r:R)=><div className="engagement-card-actions">{canWork(r)&&<button onClick={()=>open(r)}>Move / add note</button>}</div>;
 return <section className="panel engagement-workspace">{error&&!edit&&<p className="error" role="alert">{error}</p>}
 {section==='Search assignments'?<><p className="fine">Assign a search to one or more engagement members. They share all its candidates.</p><div className="table-scroll"><table className="sheet-table"><thead><tr><th>Search</th><th>Engagement partner</th><th>Engagement members</th><th>Action</th></tr></thead><tbody>{data.searches.map((s:R)=><tr key={s.id}><td>{roleName(s.id)}<small>Search status (CRM): {s.status}</small></td><td>{s.partner||'Not assigned'}</td><td>{assignees(s.id).map(name).join(', ')||'Not assigned'}</td><td>{canManage({role_id:s.id})&&<button onClick={()=>assignSearch(s.id)}>Assign search</button>}</td></tr>)}</tbody></table></div></>:section==='Teams'?<><div className="section-head"><div><h2>Engagement teams</h2><p className="fine">Separate from sourcing teams. Enable Engagement in People & access before adding a member.</p></div>{planner&&<button onClick={()=>setEdit({mode:'team',name:'',member_ids:[],lead_id:''})}>Add engagement team</button>}</div>{teams.map(t=><div className="work-row" key={t.id}><span><strong style={{color:teamColor(t.name,t.id)}}>{t.name}</strong><small>Lead: {name(t.lead_id)} · {t.member_ids.map(name).join(', ')}</small></span>{planner&&<button onClick={()=>setEdit({...t,mode:'team'})}>Edit team</button>}</div>)}{!teams.length&&<p>No engagement teams configured yet.</p>}</>:<>
 <div className="sheet-toolbar"><SearchPicker searches={data.searches.filter((s:R)=>matchesSearchStatus(s,searchStatus))} value={role} onChange={setRole} allowAll/><label>Find candidate<input placeholder="Type a name, company or email" type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><FunnelFilter value={funnel} onChange={setFunnel}/><label className="checkbox"><input type="checkbox" checked={attention} onChange={e=>setAttention(e.target.checked)}/>Over threshold</label><SearchStatusFilter searches={data.searches} value={searchStatus} onChange={value=>{setSearchStatus(value);if(search&&!matchesSearchStatus(search,value))setRole('');}}/><div className="research-tabs">{['Board','List'].map(v=><button key={v} className={layout===v?'primary':''} onClick={()=>setLayout(v)}>{v}</button>)}</div></div>
 {search&&<div className="engagement-search-heading"><strong>{search.client} · {search.title}</strong><small>Search status (CRM): {search.status||'Not set'} · Partner: {search.partner||'Not assigned'} · Engagement: {assignees(role).map(name).join(', ')||'Search not assigned'}</small>{onInterviews&&<button onClick={()=>onInterviews(role)}>Interview tracker</button>}</div>}
 <div className="engagement-metrics">{[['Active',base.filter(r=>isActiveStage(resolvedStage(r,stages))).length],['Late stage',base.filter(r=>isLateStage(resolvedStage(r,stages))).length],['Over threshold',base.filter(r=>isActiveStage(resolvedStage(r,stages))&&stageOverdue(r,resolvedStage(r,stages),now)).length],['Placed',base.filter(r=>resolvedStage(r,stages).group==='Placed').length]].map(([label,count])=><span key={label}><strong>{count}</strong> {label}</span>)}</div>
 <p className="fine" role="status">{visible.length} matching candidates{query.trim()?' · Search results shown as a list':''} · Current filters apply.{!role?' Choose a search for its Kanban board.':''}</p>{query&&<button className="text-button" onClick={()=>{setFunnel('all');setAttention(false);setSearchStatus('all');}}>Search all engagement stages and search statuses</button>}
 {!useList?<><p className="fine">Drag a candidate to a stage, then add a note to confirm. Move / add note also works with keyboard or touch.</p><div className="engagement-board">{boardStages.map(stage=>{const items=visible.filter(r=>r.stage_id===stage.id),over=items.filter(r=>stageOverdue(r,stage,now)).length;return <section className={'engagement-column'+(dragging?' drop-enabled':'')} key={stage.id} aria-label={`${stage.label} stage`} style={{borderTopColor:funnelColors[stage.group]}} onDragOver={e=>{if(dragging)e.preventDefault();}} onDrop={e=>{e.preventDefault();const r=visible.find(r=>r.mapping_id===dragging);setDragging('');if(r&&r.stage_id!==stage.id)open(r,stage.id);}}><small className="funnel-label" style={{color:funnelColors[stage.group]}}>{stage.group}</small><h3>{stage.label}<span>{items.length}</span></h3>{stage.threshold>0&&<small className={over?'error':''}>{stage.threshold}d threshold{over?` · ${over} over`:''}</small>}{items.map(r=>{const c=candidate(r);return <article className="engagement-card" key={r.mapping_id} draggable={canWork(r)&&!r.search_closed&&!edit&&!busy} onDragStart={e=>{e.dataTransfer.setData('text/plain',r.mapping_id);e.dataTransfer.effectAllowed='move';setDragging(r.mapping_id);}} onDragEnd={()=>setDragging('')}><button className="text-button" onClick={()=>onCandidate(c?.id)}>{c?.name}</button><small>{c?.company}{c?.title?` · ${c.title}`:''}</small>{age(r)}{r.search_closed&&<small>Search closed</small>}{!r.approved&&<small className="error">Sourcing reopened · paused</small>}{moveButtons(r)}</article>;})}</section>;})}</div></>:<div className="table-scroll"><table className="sheet-table"><thead><tr><th>Candidate / search</th><th>Engagement stage</th><th>Funnel</th><th>Days in stage ↓</th><th>Action</th></tr></thead><tbody>{visible.map(r=>{const s=resolvedStage(r,stages);return <tr key={r.mapping_id}><td><button className="text-button" onClick={()=>onCandidate(r.candidate_id)}>{candidate(r)?.name}</button><small>{roleName(r.role_id)}</small></td><td>{s.label}{!r.approved&&<small>Paused · sourcing reopened</small>}</td><td><span style={{color:funnelColors[s.group]}}>{s.group}</span></td><td>{age(r)}</td><td>{moveButtons(r)}</td></tr>;})}</tbody></table></div>}
 {!visible.length&&<p className="fine">No candidates match these filters.</p>}
 </>}
 {edit&&<div className="modal-backdrop"><section className="modal engagement-modal" role="dialog" aria-modal="true" aria-label="Engagement editor"><div className="section-head"><h2>{({team:'Engagement team',assign:'Assign search',work:'Move candidate / add note'} as R)[edit.mode]}</h2><button disabled={busy} onClick={()=>{if(!edit.notes||confirm('Discard unsaved changes?'))setEdit(null);}}>Cancel</button></div>
 {edit.mode==='team'&&<form onSubmit={e=>{e.preventDefault();act({...edit,action:'engagement-team-save'});}}><label>Team name<input required value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><fieldset><legend>Engagement members</legend>{people.map((p:R)=><label className="checkbox" key={p.id}><input type="checkbox" checked={edit.member_ids.includes(p.id)} onChange={e=>setEdit({...edit,member_ids:e.target.checked?[...edit.member_ids,p.id]:edit.member_ids.filter((id:string)=>id!==p.id),lead_id:!e.target.checked&&edit.lead_id===p.id?'':edit.lead_id})}/>{p.name}</label>)}{!people.length&&<p>Enable Engagement on the appropriate accounts in People & access first.</p>}</fieldset><label>Team lead<select required value={edit.lead_id} onChange={e=>setEdit({...edit,lead_id:e.target.value})}><option value="">Choose lead</option>{people.filter((p:R)=>edit.member_ids.includes(p.id)).map((p:R)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="primary" disabled={busy}>Save team</button></form>}
 {edit.mode==='assign'&&<form onSubmit={e=>{e.preventDefault();act({...edit,action:'engagement-search-assign'});}}><p><strong>{roleName(edit.role_id)}</strong></p><p className="fine">All selected members can work on every partner-approved candidate for this search. Changes apply to current and future handoffs.</p><fieldset><legend>Engagement members</legend>{people.map((p:R)=><label className="checkbox" key={p.id}><input type="checkbox" checked={edit.member_ids.includes(p.id)} onChange={e=>setEdit({...edit,member_ids:e.target.checked?[...edit.member_ids,p.id]:edit.member_ids.filter((id:string)=>id!==p.id)})}/><span>{p.name}<small>{teams.filter(t=>t.member_ids.includes(p.id)).map(t=>t.name).join(', ')||'No engagement team configured'}</small></span></label>)}{!people.length&&<p>Enable Engagement on the appropriate accounts in People & access first.</p>}</fieldset><p className="fine">Clear all selections to leave the search unassigned.</p><button disabled={busy} className="primary">Save search assignment</button></form>}
 {edit.mode==='work'&&<form onSubmit={e=>{e.preventDefault();act({...edit,action:'engagement-update'});}}><p><strong>{candidate(edit)?.name}</strong><small>{roleName(edit.role_id)}</small></p><p className="fine">Current: {rows.find(r=>r.mapping_id===edit.mapping_id)?.stage} · {age(edit)}</p>{edit.search_closed&&<p className="notice">Search closed. Record notes or move to an exited / placed outcome.</p>}<label>Engagement stage<select value={edit.stage_id} onChange={e=>setEdit({...edit,stage_id:e.target.value})}>{!stages.some(s=>s.id===edit.stage_id)&&<option value={edit.stage_id}>{edit.stage}</option>}{stages.map(s=><option key={s.id} value={s.id}>{s.group} · {s.label}</option>)}</select></label><label>Date recommended to client<input type="date" value={edit.recommended_on} required={edit.stage_id==='recommended'} onChange={e=>setEdit({...edit,recommended_on:e.target.value})}/></label><p className="fine">Enter the actual recommendation date; it is independent of the stage move.</p><label>Activity date<input type="date" required value={edit.occurred_on} onChange={e=>setEdit({...edit,occurred_on:e.target.value})}/></label><label>What happened / reason for moving<textarea autoFocus required rows={4} value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label><p className="fine">Stage age starts when this move is saved. The activity date dates your note.</p><button className="primary" disabled={busy}>{busy?'Saving…':'Save update'}</button></form>}
 {error&&<p className="error" role="alert">{error}</p>}</section></div>}
 </section>;
}
