import React,{useEffect,useState} from 'react';
import {nextActivity} from './engagement-daily';
import {pipelineConfig,pipelineStages,funnelGroups,funnelColors,PipelineStage} from './engagement-pipeline';
export function EngagementAdmin(props:any){
 const {data,api,reload,onDirty}=props,config=pipelineConfig(data.research.records);
 const [draft,setDraft]=useState<PipelineStage[]|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[version,setVersion]=useState(0);
 useEffect(()=>{onDirty(!!draft||busy);return()=>onDirty(false);},[!!draft,busy]);
 const stages=draft||pipelineStages(data.research.records);
 const change=(i:number,patch:Partial<PipelineStage>)=>setDraft(stages.map((s,n)=>n===i?{...s,...patch}:s));
 const shift=(i:number,delta:number)=>{const next=[...stages];[next[i],next[i+delta]]=[next[i+delta],next[i]];setDraft(next);};
 async function save(){setError('');setBusy(true);try{await api('research',{action:'engagement-pipeline-save',id:config?.id,version,stages:draft});await reload();setDraft(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <section className="panel engagement-workspace"><div className="section-head"><div><h2>Engagement pipeline</h2><p className="fine">Outreach follows the configured order. Engaged channels are alternatives: all lead to Initial Screening Call. Thresholds set when the next activity is due. 0 turns scheduling off; Placed and Exited have no threshold.</p></div>{!draft&&<button onClick={()=>{setVersion(config?.version||0);setDraft(stages.map(s=>({...s})));}}>Edit pipeline</button>}</div>{error&&<p className="error" role="alert">{error}</p>}<div className="table-scroll"><table className="sheet-table pipeline-config"><thead><tr><th>#</th><th>Stage</th><th>Action to reach this stage</th><th>Funnel group</th><th>Threshold (days)</th>{draft&&<th>Order / remove</th>}</tr></thead><tbody>{stages.map((s,i)=><tr key={s.id}><td>{i+1}</td><td>{draft?<input aria-label={`Stage ${i+1} name`} value={s.label} onChange={e=>change(i,{label:e.target.value})}/>:s.label}{s.group==='Engaged'&&<small className="fine">Next: {stages.find(x=>x.id===nextActivity(s,stages).target)?.label||'Screening stage not configured'}</small>}</td><td>{draft?<input aria-label={`Stage ${i+1} action`} value={s.action_label||''} onChange={e=>change(i,{action_label:e.target.value})}/>:s.action_label}</td><td>{draft?<select aria-label={`Stage ${i+1} group`} value={s.group} disabled={s.id==='assigned'} onChange={e=>change(i,{group:e.target.value})}>{funnelGroups.map(g=><option key={g}>{g}</option>)}</select>:<span style={{color:funnelColors[s.group]}}>{s.group}</span>}</td><td>{draft?<input aria-label={`Stage ${i+1} threshold`} type="number" min="0" max="365" disabled={['Placed','Exited'].includes(s.group)} value={['Placed','Exited'].includes(s.group)?0:s.threshold} onChange={e=>change(i,{threshold:Number(e.target.value)})}/>:s.threshold||'Off'}</td>{draft&&<td><div className="row-actions"><button aria-label={`Move stage ${i+1} up`} disabled={i<=1||busy} onClick={()=>shift(i,-1)}>↑</button><button aria-label={`Move stage ${i+1} down`} disabled={i<1||i===stages.length-1||busy} onClick={()=>shift(i,1)}>↓</button><button disabled={i<1||busy} onClick={()=>setDraft(stages.filter((_,n)=>n!==i))}>Remove</button></div></td>}</tr>)}</tbody></table></div>{draft&&<div className="row-actions"><button disabled={busy} onClick={()=>setDraft([...stages,{id:crypto.randomUUID(),label:'',group:'Outreach',threshold:0}])}>Add stage</button><button className="primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save pipeline'}</button><button disabled={busy} onClick={()=>{setDraft(null);setError('');}}>Cancel</button></div>}<p className="fine">Active excludes Exited and Placed. Late stage includes Shortlist and Client Process. Names and thresholds update everywhere; historical notes retain the labels used at the time. Move candidates out before removing an occupied stage.</p></section>;
}
