import React,{useState} from 'react';
import {funnelGroups,funnelColors} from './engagement-pipeline';
type Person={id:string;name:string};
export function EngagementAssignmentGrid({people,assignments,onChange,disabled=false}:{people:Person[];assignments:Record<string,string[]>;onChange:(value:Record<string,string[]>)=>void;disabled?:boolean}){
 const [memberDescending,setMemberDescending]=useState(false),[groupSort,setGroupSort]=useState<boolean|null>(null);
 const members=[...people].sort((a,b)=>(memberDescending?-1:1)*a.name.localeCompare(b.name,undefined,{sensitivity:'base',numeric:true})||a.id.localeCompare(b.id));
 const groups=groupSort===null?funnelGroups:[...funnelGroups].sort((a,b)=>(groupSort?-1:1)*a.localeCompare(b));
 return <div className="table-scroll"><table className="sheet-table engagement-assignment-grid"><thead><tr><th scope="col" aria-sort={groupSort===null?'none':groupSort?'descending':'ascending'}><button type="button" className="table-sort-heading" onClick={()=>setGroupSort(groupSort===null?false:!groupSort)}>Funnel group <span aria-hidden="true">{groupSort===null?'↕':groupSort?'↓':'↑'}</span></button></th><th scope="col" aria-sort={memberDescending?'descending':'ascending'}><button type="button" className="table-sort-heading" title="Sort member names in each funnel" onClick={()=>setMemberDescending(!memberDescending)}>Engagement members <span aria-hidden="true">{memberDescending?'↓':'↑'}</span></button></th></tr></thead><tbody>{groups.map(group=><tr key={group}><th scope="row" style={{color:funnelColors[group]}}>{group}</th><td><div className="funnel-assignee-options">{members.map(p=><label className="checkbox" key={p.id}><input type="checkbox" disabled={disabled} aria-label={group+' — '+p.name} checked={(assignments[group]||[]).includes(p.id)} onChange={e=>onChange({...assignments,[group]:e.target.checked?[...(assignments[group]||[]),p.id]:(assignments[group]||[]).filter(id=>id!==p.id)})}/><span>{p.name}</span></label>)}</div></td></tr>)}</tbody></table></div>;
}
