import {useViewState} from './ViewState';
import {LinkedInIcon} from './LinkedInIcon';
import {SortableTable} from './SortableTable';
import React,{useEffect,useState} from 'react';
import {canPlan,hasRole} from './domain';
import {dailyEngagementRows} from './engagement-daily';
import {engagementSearchClosed,engagementAssignees} from './engagement-domain';
import {SearchStatusFilter,matchesSearchStatus} from './SearchFilters';
import {displayDate,displayDateTime} from './dates';
type R=Record<string,any>;
export function EngagementDaily({data,onWork,onCandidate,onSearch}:any){
 const [now,setNow]=useState(Date.now()),[scope,setScope]=useViewState('EngagementDaily.scope','mine'),[status,setStatus]=useViewState('EngagementDaily.status','open'),[query,setQuery]=useViewState('EngagementDaily.query',''),[selected,setSelected]=useViewState('EngagementDaily.selected',''),[bucket,setBucket]=useViewState('EngagementDaily.bucket','active'),[page,setPage]=useViewState('EngagementDaily.page',0);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer);},[]);
 const records:R[]=data.research.records,actor=data.actor,manager=canPlan(actor),name=(id:string)=>data.people.find((p:R)=>p.id===id)?.name||'Former member';
 const searches=data.searches.filter((s:R)=>matchesSearchStatus(s,status)&&(!query||`${s.client} ${s.title}`.toLowerCase().includes(query.toLowerCase()))&&(scope==='all'||manager||s.partner_id===actor.id||engagementAssignees(records,s.id).includes(actor.id)));
 const rows=dailyEngagementRows(records,data.searches,now).filter(r=>searches.some((s:R)=>s.id===r.role_id)&&(scope==='all'||manager||data.searches.find((s:R)=>s.id===r.role_id)?.partner_id===actor.id||r.members.includes(actor.id)));
 const coming=records.filter(r=>(scope==='all'||manager||data.searches.find((s:R)=>s.id===r.role_id)?.partner_id===actor.id||engagementAssignees(records,r.role_id,'Top Funnel').includes(actor.id))&&r.kind==='mapping'&&r.status==='Partner review'&&searches.some((s:R)=>s.id===r.role_id&&!engagementSearchClosed(s.status)));
 const matches=(r:R,key:string)=>key==='due'?r.due:key==='overdue'?r.overdue:key==='new'?r.newToday&&r.active:key==='placed'?r.group==='Placed':key==='unscheduled'?r.active&&(!r.threshold||r.days===null):r.active;
 const open=(id:string,key:string)=>{setSelected(id);setBucket(key);setPage(0);};
 const relevant=searches.filter((s:R)=>rows.some(r=>r.role_id===s.id)||coming.some(r=>r.role_id===s.id)).sort((a:R,b:R)=>rows.filter(r=>r.role_id===b.id&&r.overdue).length-rows.filter(r=>r.role_id===a.id&&r.overdue).length||a.client.localeCompare(b.client));
 const items=bucket==='coming'?coming.filter(r=>r.role_id===selected):rows.filter(r=>r.role_id===selected&&matches(r,bucket));
 const safePage=Math.min(page,Math.max(0,Math.ceil(items.length/25)-1));
 const titles:Record<string,string>={active:'Active candidates',overdue:'Overdue',due:'Due today',new:'New handoffs today',coming:'Awaiting sourcing partner approval',unscheduled:'Threshold off / age unknown',placed:'Placed'};
 const candidate=(r:R)=>records.find(c=>c.kind==='candidate'&&c.id===r.candidate_id);
 return <section className="panel engagement-daily"><div className="sheet-toolbar"><label>Searches<select value={scope} onChange={e=>{setScope(e.target.value);setSelected('');}}><option value="mine">{manager?'All searches I manage':'My assigned searches'}</option><option value="all">All searches (view)</option></select></label><label>Find search<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Client or search name"/></label><SearchStatusFilter searches={data.searches} value={status} onChange={value=>{setStatus(value);setSelected('');}}/></div>
 <div className="daily-counts">{[['overdue','Overdue'],['due','Due today'],['new','New today'],['coming','Coming from sourcing']].map(([key,label])=><div key={key} className={'daily-count '+key+(rows.some(r=>matches(r,key))?(['due','overdue'].includes(key)?' has-attention':key==='new'?' has-new':''):'')}><strong>{key==='coming'?coming.length:rows.filter(r=>matches(r,key)).length}</strong><span>{label}</span></div>)}</div>
 <div className="table-scroll"><SortableTable stateKey="EngagementDaily.table1" className="sheet-table daily-searches"><thead><tr><th>Search / engagement members</th><th>Active</th><th>New today</th><th>Overdue</th><th>Due today</th><th>Coming soon</th><th>Unscheduled</th><th>Placed</th></tr></thead><tbody>{relevant.map((s:R)=>{const own=rows.filter(r=>r.role_id===s.id),ids=engagementAssignees(records,s.id);return <tr key={s.id}><td><button className="text-button" onClick={()=>onSearch?onSearch(s.id):open(s.id,'active')}><strong>{s.client} · {s.title}</strong></button><small>{ids.length?ids.map(name).join(', '):'Engagement resources not assigned'}</small></td>{['active','new','overdue','due','coming','unscheduled','placed'].map(key=>{const n=key==='coming'?coming.filter(r=>r.role_id===s.id).length:own.filter(r=>matches(r,key)).length;return <td key={key}><button className={key==='placed'?'daily-placed':'text-button'+(n>0?(['due','overdue'].includes(key)?' due-count':key==='new'?' new-count':''):'')} disabled={!n} aria-label={`${titles[key]} for ${s.title}: ${n}`} onClick={()=>open(s.id,key)}>{n}</button></td>;})}</tr>;})}</tbody></SortableTable></div>{!relevant.length&&<p>No engagement work or upcoming sourcing handoffs match these searches.</p>}
 {selected&&searches.some((s:R)=>s.id===selected)&&<section className="daily-detail"><div className="section-head"><div><h3>{data.searches.find((s:R)=>s.id===selected)?.title}</h3><p className="fine">{titles[bucket]} · {items.length} {items.length===1?'candidate':'candidates'}</p></div><div className="row-actions">{onSearch&&<button onClick={()=>onSearch(selected)}>Open search workspace</button>}<button onClick={()=>setSelected('')}>Close list</button></div></div><div className="table-scroll"><SortableTable stateKey="EngagementDaily.table2" page={safePage} pageSize={25} onPageChange={setPage} className="sheet-table"><thead><tr><th>Candidate</th><th>Current stage</th><th>Next activity</th><th>Stage age / due</th><th>Action</th></tr></thead><tbody>{items.map((r:R)=>{const canWork=bucket!=='coming'&&(manager||hasRole(actor,'partner')&&data.searches.find((s:R)=>s.id===r.role_id)?.partner_id===actor.id||hasRole(actor,'engagement')&&r.members.includes(actor.id));return <tr key={r.mapping_id||r.id}><td><button className="text-button" onClick={()=>onCandidate(r.candidate_id)}>{candidate(r)?.name||r.name}</button><LinkedInIcon url={candidate(r)?.url} name={candidate(r)?.name||r.name}/><small>{candidate(r)?.company}</small></td><td><span className={r.group==='Placed'?'daily-placed':''}>{r.stage||'Partner review'}</span></td><td>{bucket==='coming'?'Await sourcing approval':r.label}</td><td>{bucket==='coming'?'Not yet handed off':<><span className={r.overdue?'error':''}>{r.days===null?'Age unknown':`${r.days} days`}{r.overdue?' · Overdue':r.due?' · Due today':''}</span><small>{r.due_at?displayDateTime(r.due_at):r.active?'Threshold off / age unknown':'Complete / exited'}</small></>}</td><td>{canWork&&r.active&&<button onClick={()=>onWork(r.role_id,r.mapping_id,r.target||r.stage_id)}>Record activity</button>}</td></tr>;})}</tbody></SortableTable></div><div className="mapping-pagination"><span>25 per page · Page {safePage+1}</span><button disabled={!safePage} onClick={()=>setPage(safePage-1)}>Previous</button><button disabled={(safePage+1)*25>=items.length} onClick={()=>setPage(safePage+1)}>Next</button></div>{!items.length&&<p>No candidates in this group.</p>}</section>}
 </section>;
}

