import {StrategyEvidence} from './StrategyEvidence';
import {exactCompany,suggestedCompanies} from './company-match';
import React,{useEffect,useId,useState} from 'react';
import {linkedin} from './research';
type R=Record<string,any>;
export function InlineMapping({data,role,team,api,reload,onCandidate,onDirty,initialCandidate}:{data:R;role:string;team:string;api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;onCandidate:(id:string)=>void;onDirty?:(v:boolean)=>void;initialCandidate?:R}){
 const [form,setForm]=useState({first_name:'',last_name:'',url:initialCandidate?.url||'',company:''}),[evidence,setEvidence]=useState<R>({}),[rationale,setRationale]=useState(''),[create,setCreate]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const records:R[]=data.research?.records||[],companies=records.filter(r=>r.kind==='company'),listId=useId(),criteria=records.find(r=>r.kind==='strategy'&&r.role_id===role)?.active_criteria||[];
 let candidate:R|undefined;try{candidate=records.find(r=>r.kind==='candidate'&&r.url===linkedin(form.url));}catch{}
 const companyName=candidate?.company||form.company,normalize=(v:string)=>v.trim().toLowerCase().replace(/\s+/g,' '),company=exactCompany(companies,companyName);
 const duplicate=candidate&&records.some(r=>r.kind==='mapping'&&r.role_id===role&&r.candidate_id===candidate.id);
 useEffect(()=>{onDirty?.(Object.values(form).some(Boolean)||!!rationale||Object.keys(evidence).length>0);return()=>onDirty?.(false);},[form,rationale,evidence]);
 return <section className="inline-mapping"><h3>New mapping</h3><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setNotice('');try{await api('research',{action:'mapping-inline',...form,rationale,evidence,company:company?.name||companyName,company_id:company?.id,create_company:create,candidate_version:candidate?.version,role_id:role,team_id:team});await reload();setForm({first_name:'',last_name:'',url:'',company:''});setCreate(false);setEvidence({});setRationale('');setNotice('Mapping and fit evidence saved as a draft. Submit it for team review when ready.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><div className="inline-mapping-fields">{(['first_name','last_name','url'] as const).map(k=><label key={k}>{k==='first_name'?'First name':k==='last_name'?'Last name':'LinkedIn profile URL'}<input required type={k==='url'?'url':'text'} disabled={busy||!!candidate&&k!=='url'} value={k==='url'?form.url:candidate?.[k]||form[k]} placeholder={k==='url'?'https://www.linkedin.com/in/…':undefined} onChange={e=>{setForm({...form,[k]:e.target.value});setCreate(false);setNotice('');}}/></label>)}<label>Current company<input list={listId} disabled={busy||!!candidate} value={companyName} placeholder="Start typing a company" onChange={e=>{setForm({...form,company:e.target.value});setCreate(false);}}/><datalist id={listId}>{companies.map(c=><option key={c.id} value={c.name}/>)}</datalist></label></div>
 {!candidate&&companyName&&!company&&<div className="company-suggestions" role="listbox" aria-label="Matching companies">{suggestedCompanies(companies,companyName).map(c=><button type="button" role="option" aria-selected={false} key={c.id} onClick={()=>{setForm({...form,company:c.name});setCreate(false);}}>{c.name}{c.aliases?.length?' · '+(Array.isArray(c.aliases)?c.aliases.join(', '):c.aliases):''}</button>)}</div>}
 {!!companyName&&!company&&<button type="button" disabled={busy||create} onClick={()=>setCreate(true)}>{create?`Will add “${companyName}” on save`:`Add “${companyName}” as a new company`}</button>}
 {candidate&&<p className="fine">Existing candidate: <button type="button" className="text-button" onClick={()=>onCandidate(candidate!.id)}>{candidate.name} — open profile</button>. Name and company come from their shared profile.</p>}
 {duplicate&&<p className="notice">Already mapped to this role. Use the existing mapping below.</p>}{error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <label className="mapping-fit-overview">Overall fit <span className="fine">(optional while drafting)</span><textarea rows={2} value={rationale} onChange={e=>setRationale(e.target.value)} placeholder="Summarize why this candidate is relevant to the search."/></label><StrategyEvidence criteria={criteria} value={evidence} onChange={setEvidence}/>{role&&!criteria.length&&<p className="fine">No approved fit criteria for this search yet. Add your overall fit summary above.</p>}<button className="primary" disabled={busy||!team||!role||!!duplicate||!!companyName&&!company&&!create}>{busy?'Saving…':'Save mapping draft'}</button>
 </form></section>;
}
