import {useViewState} from './ViewState';
import {LinkedInIcon} from './LinkedInIcon';
import {SortableTable} from './SortableTable';
import {SearchStatusFilter,matchesSearchStatus} from './SearchFilters';
import React,{useEffect,useState} from 'react';
import {PencilSimple} from '@phosphor-icons/react';
import {canPlan,hasRole} from './domain';
import {engagementRows,engagementAssignees} from './engagement-domain';
import {pipelineStages,pipelineConfig,resolvedStage} from './engagement-pipeline';
import {candidateMatches,interviewStatuses,interviewOutcomes,interviewTone,inInterviewTracker} from './interviews';
import {SearchPicker} from './SearchPicker';
import {displayDate} from './dates';
type R=Record<string,any>;
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());
export function InterviewTracker({data,api,reload,onDirty,onCandidate,initialRole=''}:any){
 const [role,setRole]=useViewState('InterviewTracker.role',initialRole),[client,setClient]=useViewState('InterviewTracker.client',''),[query,setQuery]=useViewState('InterviewTracker.query',''),[all,setAll]=useViewState('InterviewTracker.all',false),[searchStatus,setSearchStatus]=useViewState('InterviewTracker.searchStatus','open'),[sort,setSort]=useViewState('InterviewTracker.sort',{key:'candidate',direction:1}),[edit,setEdit]=useState<R|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[roundCount,setRoundCount]=useViewState('InterviewTracker.roundCount',1);
 const records:R[]=data.research.records,stages=pipelineStages(records),rows=engagementRows(records,data.searches),clients:string[]=Array.from(new Set<string>(data.searches.map((s:R)=>s.client))).sort();
 useEffect(()=>{onDirty(!!edit||busy);return()=>onDirty(false);},[!!edit,busy]);
 const search=(id:string)=>data.searches.find((s:R)=>s.id===id),candidate=(r:R)=>records.find(c=>c.kind==='candidate'&&c.id===r.candidate_id);
 const canEdit=(r:R)=>r.approved&&(canPlan(data.actor)||hasRole(data.actor,'partner')&&search(r.role_id)?.partner_id===data.actor.id||hasRole(data.actor,'engagement')&&engagementAssignees(records,r.role_id,resolvedStage(r,stages).group).includes(data.actor.id));
 const visible=rows.filter(r=>(!role||r.role_id===role)&&(!client||search(r.role_id)?.client===client)&&matchesSearchStatus(search(r.role_id),searchStatus)&&candidateMatches(candidate(r),query)&&(all||inInterviewTracker(r,resolvedStage(r,stages).group)));
 const outcome=(r:R)=>['Placed','Exited'].includes(resolvedStage(r,stages).group)?r.stage:(r.interviews||[]).filter((i:R)=>i.outcome!=='Pending').sort((a:R,b:R)=>b.number-a.number)[0]?.outcome||(['Placed','Exited'].includes(resolvedStage(r,stages).group)?r.stage:'Pending');
 const value=(r:R,key:string)=>key==='candidate'?candidate(r)?.name:key==='client'?search(r.role_id)?.client:key==='search'?search(r.role_id)?.title:key==='recommended'?r.recommended_on:key==='stage'?r.stage:key==='outcome'?outcome(r):(()=>{const i=r.interviews?.find((i:R)=>'round'+i.number===key);return i?[i.outcome==='Pending'?i.status:i.outcome,i.date||''].join(' '):'Not started';})();
 const sorted=[...visible].sort((a,b)=>String(value(a,sort.key)||'').localeCompare(String(value(b,sort.key)||''),undefined,{numeric:true,sensitivity:'base'})*sort.direction||String(a.mapping_id).localeCompare(String(b.mapping_id)));
 const heading=(key:string,label:string)=><th key={key} aria-sort={sort.key===key?(sort.direction===1?'ascending':'descending'):'none'}><button className="text-button" onClick={()=>setSort({key,direction:sort.key===key?-sort.direction:1})}>{label}{sort.key===key?(sort.direction===1?' ↑':' ↓'):''}</button></th>;
 const count=Math.max(roundCount,...visible.flatMap(r=>(r.interviews||[]).map((v:R)=>v.number))),numbers=Array.from({length:count},(_,i)=>i+1);
 const open=(r:R,number?:number)=>{if(!canEdit(r))return;const existing=r.interviews?.find((i:R)=>i.number===number);setError('');setEdit({...r,mode:number?'round':'recommendation',recommended_on:r.recommended_on||'',notes:'',occurred_on:today(),pipeline_version:pipelineConfig(records)?.version||0,interview:number?{number,status:'Not started',outcome:'Pending',date:'',interviewer:'',decision_on:'',...existing}:null});};
 async function save(e:React.FormEvent){e.preventDefault();if(!edit)return;setBusy(true);setError('');try{await api('research',{...edit,action:edit.mode==='round'?'engagement-interview-save':'engagement-update'});await reload();setEdit(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const updateRound=(patch:R)=>setEdit(edit?{...edit,interview:{...edit.interview,...patch}}:null);
 return <section className="panel engagement-workspace interview-tracker"><div className="sheet-toolbar"><label>Client<select value={client} onChange={e=>{setClient(e.target.value);setRole('');}}><option value="">All clients</option>{clients.map(c=><option key={c}>{c}</option>)}</select></label><SearchPicker searches={data.searches.filter((s:R)=>(!client||s.client===client)&&matchesSearchStatus(s,searchStatus))} value={role} onChange={setRole} allowAll/><label>Find candidate<input type="search" placeholder="Name, company or email" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="checkbox"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>Include candidates awaiting recommendation</label><SearchStatusFilter searches={data.searches} value={searchStatus} onChange={value=>{setSearchStatus(value);if(role&&!matchesSearchStatus(search(role),value))setRole('');}}/><button disabled={roundCount>=50} onClick={()=>setRoundCount(Math.min(50,count+1))}>Show another round</button></div>
 <p className="fine" role="status">{visible.length} candidates · Client and search status come from the search. Recommendation dates are entered manually.</p><div className="interview-legend"><span className="round-state progressing">Progressing</span><span className="round-state awaiting">Completed · awaiting feedback</span><span className="round-state scheduled">Scheduled</span><span className="round-state rejected">Rejected</span><span className="round-state neutral">Not started / cancelled</span></div>
 <div className="table-scroll interview-grid"><SortableTable stateKey="InterviewTracker.table1" className="sheet-table"><thead><tr>{heading('candidate','Candidate')}{heading('client','Client')}{heading('search','Search')}{heading('recommended','Recommended to client')}{heading('stage','Engagement stage')}{heading('outcome','Outcome')}{numbers.map(n=>heading('round'+n,'R'+n))}</tr></thead><tbody>{sorted.map(r=>{return <tr key={r.mapping_id}><td><button className="text-button" onClick={()=>onCandidate(r.candidate_id)}>{candidate(r)?.name}</button><LinkedInIcon url={candidate(r)?.url} name={candidate(r)?.name}/><small>{candidate(r)?.company}</small></td><td>{search(r.role_id)?.client}</td><td>{search(r.role_id)?.title}</td><td><span className="recommendation-cell">{r.recommended_on?displayDate(r.recommended_on):'Not recorded'}{canEdit(r)&&<button className="icon-button" title="Edit recommendation" aria-label={`Edit recommendation for ${candidate(r)?.name}`} onClick={()=>open(r)}><PencilSimple size={16}/></button>}</span></td><td>{r.stage}{!r.approved&&<small>Paused · sourcing reopened</small>}</td><td>{outcome(r)}{(r.interviews||[]).filter((i:R)=>i.outcome==='Rejected').map((i:R)=><small key={i.number}>R{i.number} · {displayDate(i.decision_on||i.date)}</small>)}</td>{numbers.map(n=>{const round=r.interviews?.find((i:R)=>i.number===n),content=round?<><strong>{round.outcome==='Pending'?round.status:round.outcome}</strong>{round.outcome==='Pending'&&round.status==='Completed'&&<small>Awaiting feedback</small>}{round.date&&<small>{displayDate(round.date)}</small>}{round.interviewer&&<small>{round.interviewer}</small>}{round.decision_on&&round.outcome!=='Pending'&&<small>Outcome: {displayDate(round.decision_on)}</small>}</>:<span>Not started</span>;return <td key={n}><button className={'interview-cell '+(round?interviewTone(round):'neutral')} disabled={!canEdit(r)} aria-label={`Edit ${candidate(r)?.name} round ${n}`} onClick={()=>open(r,n)}>{content}</button>{round?.feedback&&<details className="round-feedback"><summary>Feedback</summary><p>{round.feedback}</p></details>}</td>;})}</tr>;})}</tbody></SortableTable></div>{!visible.length&&<p className="notice">No candidates match. Include candidates awaiting recommendation to record their client recommendation date.</p>}
 {edit&&<div className="modal-backdrop"><section className="modal engagement-modal" role="dialog" aria-modal="true" aria-label="Interview tracker editor"><div className="section-head"><h2>{edit.mode==='round'?`Interview round ${edit.interview.number}`:'Client recommendation'}</h2><button disabled={busy} onClick={()=>{if(!edit.notes||confirm('Discard unsaved changes?'))setEdit(null);}}>Cancel</button></div><p><strong>{candidate(edit)?.name}</strong><small>Client: {search(edit.role_id)?.client} · {search(edit.role_id)?.title}</small><small>Search status (CRM): {search(edit.role_id)?.status}</small></p><form onSubmit={save}><label>Date recommended to client<input type="date" value={edit.recommended_on} required={edit.stage_id==='recommended'} onChange={e=>setEdit({...edit,recommended_on:e.target.value})}/></label><label>Engagement stage<select value={edit.stage_id} onChange={e=>setEdit({...edit,stage_id:e.target.value})}>{!stages.some(s=>s.id===edit.stage_id)&&<option value={edit.stage_id}>{edit.stage}</option>}{stages.map(s=><option value={s.id} key={s.id}>{s.group} · {s.label}</option>)}</select></label>{edit.mode==='round'&&<><div className="candidate-fields"><label>Interview status<select value={edit.interview.status} onChange={e=>updateRound({status:e.target.value,...(e.target.value!=='Completed'?{outcome:'Pending',decision_on:''}:{})})}>{interviewStatuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Interview date<input type="date" value={edit.interview.date} required={['Scheduled','Completed'].includes(edit.interview.status)} onChange={e=>updateRound({date:e.target.value})}/></label></div><label>Interviewer(s)<input value={edit.interview.interviewer} onChange={e=>updateRound({interviewer:e.target.value})}/></label><div className="candidate-fields"><label>Round outcome<select value={edit.interview.outcome} onChange={e=>{const outcome=e.target.value;setEdit({...edit,stage_id:outcome==='Rejected'&&stages.some(s=>s.id==='client-rejected')?'client-rejected':edit.stage_id,interview:{...edit.interview,outcome,...(outcome!=='Pending'?{status:'Completed'}:{decision_on:''})}});}}>{interviewOutcomes.map(s=><option key={s}>{s}</option>)}</select></label><label>Outcome date<input type="date" value={edit.interview.decision_on} required={edit.interview.outcome!=='Pending'} onChange={e=>updateRound({decision_on:e.target.value})}/></label></div>{edit.interview.feedback&&<details><summary>Previously recorded feedback</summary><p className="preserve-text">{edit.interview.feedback}</p></details>}</>}
 <label>Note date<input required type="date" value={edit.occurred_on} onChange={e=>setEdit({...edit,occurred_on:e.target.value})}/></label><label>{edit.mode==='round'?'Interview feedback / reason for update':'Recommendation note / reason for correction'}<textarea required rows={3} value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label><p className="fine">Dates are entered manually. Completed does not mean successful; choose Progressing when the candidate advances. Saving an interview does not change the CRM search status.</p>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy} className="primary">{busy?'Saving…':'Save update'}</button></form></section></div>}
 </section>;
}
