import React,{useEffect,useState} from 'react';
import {hasRole,canPartnerReview} from './domain';
import {InlineMapping} from './InlineMapping';
type R=Record<string,any>;
export function MyWork({data,api,reload,onDirty,onCandidate,onOpen}:{data:R;api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;onDirty:(v:boolean)=>void;onCandidate:(id:string)=>void;onOpen:(role:string,tab:string)=>void}){
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date()),[date,setDate]=useState(today),[opened,setOpened]=useState(''),[mappingDirty,setMappingDirty]=useState(false),[workTab,setWorkTab]=useState('mappings'),[other,setOther]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notes,setNotes]=useState<R>({});
 const actor=data.actor,records:R[]=data.research?.records||[],maps=records.filter(r=>r.kind==='mapping'),targets=records.filter(r=>r.kind==='target'),plans=data.assignments.filter((a:R)=>a.work_date===date&&data.entries.some((e:R)=>e.assignment_id===a.id&&e.staff_id===actor.staffId));
 const pairs=new Map<string,R>();for(const a of plans)pairs.set(a.search_id+':'+a.team_id,{role:a.search_id,team:a.team_id,target:a.target,planned:true});
 if(other)for(const r of [...targets.filter(t=>t.owner_id===actor.id),...maps.filter(m=>m.mapper_id===actor.id)]){const key=r.role_id+':'+r.team_id;if(!pairs.has(key))pairs.set(key,{role:r.role_id,team:r.team_id,planned:false});}
 const dirty=mappingDirty||Object.entries(notes).some(([id,value])=>{const r=records.find(r=>r.id===id);return r&&value!==(r.kind==='mapping'?r.rationale||'':r.notes||'');});
 useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty]);
 const review=maps.filter(m=>m.status==='Peer review'&&m.reviewer_id===actor.id||m.status==='Partner review'&&canPartnerReview(actor)&&data.searches.some((s:R)=>s.id===m.role_id&&s.partner_id===actor.id));
 async function act(b:R){setError('');setBusy(true);try{await api('research',b);await reload();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <div className="research-panel role-first-work"><section className="panel"><div className="section-head"><div><h2>My planned work</h2><p>Start with a role, add candidate mappings, and mark company research complete when you finish.</p></div><label hidden={!!opened}>Work date<input type="date" value={date} onChange={e=>{if(e.target.value){if((opened||dirty)&&!confirm('Change date and discard unsaved work?'))return;setDate(e.target.value);setOpened('');}}}/></label></div><button hidden={!!opened} aria-pressed={other} onClick={()=>setOther(!other)}>{other?'Show planned roles only':'Include other roles on my plate'}</button>{error&&<p className="error" role="alert">{error}</p>}{!pairs.size&&<p>No roles are planned for you on this date. Ask your planner to assign you in Weekly Assignment, or include other roles on your plate.</p>}
 {data.timeOff?.some((r:R)=>r.staff_id===actor.staffId&&r.work_date===date&&r.pto)&&<p className="fine">You are on PTO for this date. Person-days are zero. Change PTO in Weekly Plan if needed.</p>}
 {[...pairs.entries()].filter(([key])=>!opened||key===opened).map(([key,p])=>{const role=data.searches.find((s:R)=>s.id===p.role),team=data.teams.find((t:R)=>t.id===p.team),mine=maps.filter(m=>m.role_id===p.role&&m.mapper_id===actor.id&&m.team_id===p.team),companies=targets.filter(t=>t.role_id===p.role&&t.owner_id===actor.id&&t.team_id===p.team),eligible=data.team_members.some((m:R)=>m.team_id===p.team&&m.staff_id===actor.staffId)&&hasRole(actor,'researcher');return <section className="planned-role" key={key}><div className="section-head"><div><h3>{role?.client} — {role?.title}</h3><p>{team?.name||'Team not assigned'} · {p.planned?`Team target: ${p.target??'Not set'}`:'Not planned for this date'} · {mine.filter(m=>m.work_date===date).length} submitted on this date</p></div><button onClick={()=>{if(dirty&&!confirm('Discard unfinished mapping or coverage notes and return to my roles?'))return;setNotes({});setMappingDirty(false);setWorkTab('mappings');setOpened(opened===key?'':key);}}>{opened===key?'← Back to my roles':'Work on role'}</button></div>{opened===key&&<>
 <div className="research-tabs work-tabs" aria-label="Role work sections"><button className={workTab==='mappings'?'primary':''} aria-pressed={workTab==='mappings'} onClick={()=>setWorkTab('mappings')}>Candidate mappings ({mine.length})</button><button className={workTab==='coverage'?'primary':''} aria-pressed={workTab==='coverage'} onClick={()=>setWorkTab('coverage')}>Company coverage ({companies.length})</button></div><div hidden={workTab!=='mappings'} className="work-mappings">
 {eligible?<InlineMapping data={data} role={p.role} team={p.team} api={api} reload={reload} onCandidate={onCandidate} onDirty={setMappingDirty}/>:<p>You need active Researcher access and membership in this team to add mappings.</p>}
 <section className="work-section mapping-section"><h3>My candidate mappings</h3><div className="table-scroll"><table className="sheet-table"><thead><tr><th>Candidate</th><th>Company</th><th>Review status</th><th>Fit evidence / action</th></tr></thead><tbody>{mine.map(m=>{const c=records.find(r=>r.id===m.candidate_id);return <tr key={m.id}><td><button className="text-button" onClick={()=>onCandidate(m.candidate_id)}>{c?.name||m.name}</button></td><td>{c?.company||m.company||'Not recorded'}</td><td>{m.status}</td><td>{['Draft','Needs information'].includes(m.status)?<div className="row-actions"><input aria-label={'Fit evidence for '+m.name} value={notes[m.id]??m.rationale??''} onChange={e=>setNotes({...notes,[m.id]:e.target.value})}/><button disabled={busy||!(notes[m.id]??m.rationale)} onClick={()=>act({action:'mapping-edit',id:m.id,version:m.version,rationale:notes[m.id]??m.rationale})}>Save evidence</button><button disabled={busy||!m.rationale||(notes[m.id]!==undefined&&notes[m.id]!==m.rationale)} onClick={()=>act({action:'mapping-submit',id:m.id,version:m.version})}>Submit for peer review</button></div>:<button onClick={()=>onOpen(p.role,'Candidate mappings')}>Open review history</button>}</td></tr>;})}</tbody></table></div>{!mine.length&&<p>Add your first candidate using the row above.</p>}
 </section></div><section hidden={workTab!=='coverage'} className="work-section coverage-section"><h3>Companies on my plate</h3><p className="fine">Work in any order. Add coverage notes, then mark done or record no relevant talent. Both count as completed coverage; neither approves candidates.</p><div className="table-scroll"><table className="sheet-table"><thead><tr><th>Company</th><th>Mappings</th><th>Coverage</th><th>Update coverage</th></tr></thead><tbody>{companies.map(t=><tr key={t.id}><td>{records.find(r=>r.id===t.company_id)?.name||t.name}</td><td>{maps.filter(m=>m.target_id===t.id).length}</td><td>{t.status}</td><td><div className="row-actions"><input aria-label={'Coverage notes for '+t.name} placeholder="Coverage notes" value={notes[t.id]??t.notes??''} onChange={e=>setNotes({...notes,[t.id]:e.target.value})}/><button disabled={busy||!eligible||!(notes[t.id]??t.notes)} onClick={()=>act({action:'company-progress',id:t.id,version:t.version,status:['Completed','No relevant talent'].includes(t.status)?'In progress':'Completed',notes:notes[t.id]??t.notes})}>{['Completed','No relevant talent'].includes(t.status)?'Reopen research':'Mark company done'}</button>{!['Completed','No relevant talent'].includes(t.status)&&<button disabled={busy||!eligible||!(notes[t.id]??t.notes)} onClick={()=>act({action:'company-progress',id:t.id,version:t.version,status:'No relevant talent',notes:notes[t.id]??t.notes})}>No relevant talent found</button>}</div></td></tr>)}</tbody></table></div>{!companies.length&&<p>No companies on your plate yet. Choosing a company when mapping adds it to the role if it is not already there.</p>}
 </section></>}</section>;})}</section>
 <section hidden={!!opened} className="panel"><h2>Reviews waiting for me ({review.length})</h2>{review.map(m=><div className="work-row" key={m.id}><span>{m.name} · {data.searches.find((s:R)=>s.id===m.role_id)?.title} · {m.status}</span><button onClick={()=>onOpen(m.role_id,'Candidate mappings')}>Review candidates</button></div>)}{!review.length&&<p>No reviews waiting.</p>}</section></div>;
}
