import {hasPermission,assignedRoleName,RoleDefinition} from './access-policy';
import {IconAction} from './IconAction';
import {PencilSimple} from '@phosphor-icons/react';
import {SortableTable} from './SortableTable';
import {WorkspaceReset} from './WorkspaceReset';
import React,{useEffect,useState} from 'react';
import {hasRole,roleList} from './domain';
type R=Record<string,any>;
export function PeoplePanel({data,api,reload,onDirty,roleFilter='',onRoleFilterChange=()=>{},children}:{roleFilter?:string;onRoleFilterChange?:(role:string)=>void;children?:React.ReactNode;data:R;api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;onDirty:(v:boolean)=>void}) {
 const [members,setMembers]=useState<R[]>([]),[invitations,setInvitations]=useState<R[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[edit,setEdit]=useState<R|null>(null),[busy,setBusy]=useState(false),[link,setLink]=useState('');
 const [definitions,setDefinitions]=useState<RoleDefinition[]>([]);
 const [teamFilter,setTeamFilter]=useState(''),[peoplePage,setPeoplePage]=useState(0);
 useEffect(()=>{setPeoplePage(0);setTeamFilter('');setQuery('');},[roleFilter]);
 const label=(id:string)=>assignedRoleName(id,definitions);
 const [resetDirty,setResetDirty]=useState(false);
 const owner=hasRole(data.actor,'super_admin');
 async function read(){const [d,catalog]=await Promise.all([api('staff-directory'),api('roles')]);setDefinitions(catalog.roles);setMembers(d.members);setInvitations(d.invitations);setLoaded(true);}
 useEffect(()=>{read().catch(e=>setError(e.message));},[data]);
 useEffect(()=>{onDirty(!!edit||busy||resetDirty);return()=>onDirty(false);},[!!edit,busy,resetDirty]);
 function manage(m:R,researcher=false){setError('');setEdit({...m,kind:'member',roles:[...new Set([...roleList(m),...(researcher?['researcher']:[])])]});}
 function invite(staff?:R){setLink('');setMessage('');setError('');setEdit({kind:'invite',name:staff?.name||'',email:staff?.email||'',staff_id:staff?.id,roles:staff?['researcher']:[]});}
 const match=(p:R)=>[p.name,p.email,...roleList(p).map(label)].join(' ').toLowerCase().includes(query.toLowerCase())&&(!roleFilter||roleList(p).includes(roleFilter));
 const visibleMembers=members.filter(m=>match(m)&&(!teamFilter||(teamFilter==='unassigned'?!data.team_members.some((t:R)=>t.staff_id===m.staff_id):data.team_members.some((t:R)=>t.staff_id===m.staff_id&&t.team_id===teamFilter))));
 const page=Math.min(peoplePage,Math.max(0,Math.ceil(visibleMembers.length/50)-1));
 async function mutate(body:R){setBusy(true);setError('');try{await api('mutate',body);await reload();await read();setEdit(null);setMessage('Researcher record updated.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <div><section className="panel"><div className="section-head team-directory-toolbar"><label>Find people<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPeoplePage(0);}} placeholder="Name, email or role"/></label><label>Role<select value={roleFilter} onChange={e=>onRoleFilterChange(e.target.value)}><option value="">All roles</option><option value="super_admin">Super Admin</option>{definitions.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Team<select value={teamFilter} onChange={e=>{setTeamFilter(e.target.value);setPeoplePage(0);}}><option value="">All teams</option><option value="unassigned">No sourcing team</option>{data.teams.map((t:R)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{hasPermission(data.actor,'users.profile')&&<button disabled={busy} onClick={()=>{setError('');setEdit({kind:'staff',name:'',email:''});}}>Add researcher without login</button>}{hasPermission(data.actor,'users.invite')&&<button className="primary" disabled={!loaded||busy} onClick={()=>invite()}>Invite person</button>}</div>
 {error&&!edit&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{link&&<p className="source-note">Private invitation link: <a href={link}>{link}</a></p>}
 {!loaded?<p>Loading workspace accounts…</p>:<div className="table-scroll"><SortableTable page={page} pageSize={50} onPageChange={setPeoplePage} stateKey="PeoplePanel.table1" className="sheet-table people-access-table"><thead><tr><th>Person</th><th>Sign-in email</th><th>Roles</th><th>Research team</th><th>Access</th><th>Actions</th></tr></thead><tbody>{visibleMembers.map(m=><tr key={m.id}><td><strong>{m.name}</strong>{m.id===data.actor.id&&<small>You are signed in as this person</small>}</td><td>{m.email}</td><td>{roleList(m).map(label).join(', ')}</td><td>{data.team_members.filter((t:R)=>t.staff_id===m.staff_id).map((t:R)=>data.teams.find((team:R)=>team.id===t.team_id)?.name).join(', ')||'No team'}</td><td>{m.status==='active'?'Active':'Access revoked'}</td><td><IconAction label="Edit person & roles" accessibleLabel={`Edit person and roles for ${m.name}`} disabled={busy||!hasPermission(data.actor,'users.profile')&&!hasPermission(data.actor,'users.access')||hasRole(m,'super_admin')&&!owner} onClick={()=>manage(m)}><PencilSimple size={17}/></IconAction>{hasRole(m,'super_admin')&&!owner&&<small>Super-admin managed</small>}</td></tr>)}</tbody></SortableTable></div>}
 {loaded&&<div className="people-results"><span>{visibleMembers.length} {visibleMembers.length===1?'person':'people'}{roleFilter?' · '+label(roleFilter):''}</span>{visibleMembers.length>50&&<><span>{page*50+1}–{Math.min((page+1)*50,visibleMembers.length)}</span><button disabled={page===0} onClick={()=>setPeoplePage(page-1)}>Previous</button><button disabled={(page+1)*50>=visibleMembers.length} onClick={()=>setPeoplePage(page+1)}>Next</button></>}</div>}
 {loaded&&!visibleMembers.length&&<p>No people match these filters.</p>}
 </section>
 {loaded&&<section className="panel"><h3>Researchers without login</h3><div className="table-scroll"><SortableTable stateKey="PeoplePanel.unlinked" className="sheet-table"><thead><tr><th>Researcher</th><th>Researcher ID</th><th>Contact email</th><th>Access</th><th>Actions</th></tr></thead><tbody>{data.staff.filter((s:R)=>!members.some(m=>m.staff_id===s.id)&&(!roleFilter||roleFilter==='researcher')&&[s.name,s.email].join(' ').toLowerCase().includes(query.toLowerCase())).map((s:R)=><tr key={s.id}><td>{s.name}{!!s.archived&&<small>Archived</small>}</td><td><small>{s.id}</small></td><td>{s.email||'—'}</td><td>{invitations.some(i=>i.staff_id===s.id)?'Invitation pending':'No login'}</td><td><div className="row-actions">{hasPermission(data.actor,'users.profile')&&<IconAction label="Edit researcher" onClick={()=>setEdit({...s,kind:'staff'})}><PencilSimple size={17}/></IconAction>}{hasPermission(data.actor,'users.invite')&&!s.archived&&<button disabled={busy} onClick={()=>invite(s)}>{invitations.some(i=>i.staff_id===s.id)?'Replace invitation':'Invite'}</button>}</div></td></tr>)}</tbody></SortableTable></div></section>}
 {children}
 <details className="panel"><summary>Pending invitations ({invitations.length})</summary>{!invitations.length&&<p>No pending invitations.</p>}{invitations.filter(match).map(i=><div className="work-row" key={i.id}><strong>{i.name}</strong><span>{i.email} · {roleList(i).map(label).join(', ')}</span><button disabled={busy||hasRole(i,'super_admin')&&!owner} onClick={async()=>{setBusy(true);setError('');try{await api('invitations/cancel',{id:i.id});await read();setMessage('Invitation cancelled. Its link no longer works.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>Cancel invitation</button></div>)}</details>
 {owner&&<WorkspaceReset api={api} reload={reload} onDirty={setResetDirty}/>}
 {edit&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="person-title"><div className="section-head"><h2 id="person-title">{edit.kind==='member'?'Edit person & roles':edit.kind==='invite'?'Invite new person':edit.id?'Edit researcher':'Add researcher without login'}</h2><button disabled={busy} onClick={()=>setEdit(null)}>Cancel</button></div><form onSubmit={async e=>{e.preventDefault();if(edit.kind==='staff'){await mutate({kind:edit.id?'staff-edit':'staff',id:edit.id,version:edit.version,name:edit.name,email:edit.email});return;}setBusy(true);setError('');setLink('');try{if(edit.kind==='member'){await api(hasPermission(data.actor,'users.access')?'members/update':'members/profile',edit);setMessage('Person and roles updated.');}else{const r=await api('invite',{...edit,staffId:edit.staff_id});setLink(r.url);setMessage(r.emailStatus==='accepted'?'Invitation created and accepted by the email provider.':'Invitation created. Email delivery was not confirmed; use the private link.');}setEdit(null);await reload();await read();}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>
 <label>Name<input required maxLength={100} disabled={busy} value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>{edit.kind==='staff'?'Contact email (optional)':'Sign-in email'}<input type="email" required={edit.kind!=='staff'} readOnly={edit.kind==='member'} disabled={busy} value={edit.email||''} onChange={e=>setEdit({...edit,email:e.target.value})}/></label>
 {edit.kind==='staff'&&<p className="fine">No account or invitation is created. Historical mappings and performance use this researcher record.</p>}{edit.kind==='member'&&<p className="fine">The person changes their sign-in email through Account settings, with verification. Name changes here apply to this workspace.</p>}
 {edit.kind!=='staff'&&(edit.kind==='invite'||hasPermission(data.actor,'users.access'))&&<><fieldset className="person-role-choices" disabled={busy}><legend>Roles</legend>{[...(owner?['super_admin']:[]),...definitions.filter(r=>!r.retired||edit.roles.includes(r.id)).map(r=>r.id)].map(r=><label className="person-role-choice" key={r}><input type="checkbox" disabled={definitions.find(d=>d.id===r)?.retired&&!edit.roles.includes(r)} checked={edit.roles.includes(r)} onChange={e=>setEdit({...edit,roles:e.target.checked?[...edit.roles,r]:edit.roles.filter((v:string)=>v!==r)})}/><span>{label(r)}{r==='super_admin'&&<small>Only a Super Admin can assign this role.</small>}</span></label>)}</fieldset>{edit.roles.includes('researcher')&&<p className="fine">Researcher is a role on this account. Once active, this person can be added to teams and assigned work.</p>}{edit.kind==='member'&&<label>Workspace access<select disabled={busy||edit.id===data.actor.id} value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}><option value="active">Active</option><option value="revoked">Revoked</option></select></label>}</>}
 {error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy||edit.kind!=='staff'&&!edit.roles.length}>{busy?'Saving…':edit.kind==='invite'?'Send invitation':edit.kind==='staff'?'Save researcher':'Save person'}</button>
 </form></section></div>}
 </div>;
}

