import {IconAction} from './IconAction';
import {PencilSimple} from '@phosphor-icons/react';
import {SortableTable} from './SortableTable';
import {WorkspaceReset} from './WorkspaceReset';
import React,{useEffect,useState} from 'react';
import {hasRole,roleList,roleLabel,roles} from './domain';
type R=Record<string,any>;
export function PeoplePanel({data,api,reload,onDirty}:{data:R;api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;onDirty:(v:boolean)=>void}) {
 const [members,setMembers]=useState<R[]>([]),[invitations,setInvitations]=useState<R[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[edit,setEdit]=useState<R|null>(null),[adding,setAdding]=useState(false),[busy,setBusy]=useState(false),[link,setLink]=useState('');
 const owner=hasRole(data.actor,'super_admin');
 async function read(){const d=await api('staff-directory');setMembers(d.members);setInvitations(d.invitations);setLoaded(true);}
 useEffect(()=>{read().catch(e=>setError(e.message));},[data]);
 useEffect(()=>{onDirty(!!edit||adding);return()=>onDirty(false);},[!!edit,adding]);
 function manage(m:R,researcher=false){setError('');setAdding(false);setEdit({...m,kind:'member',roles:[...new Set([...roleList(m),...(researcher?['researcher']:[])])]});}
 function invite(s?:R){setError('');setAdding(false);setEdit({kind:'invite',name:s?.name||'',email:s?.email||'',staff_id:s?.id||'',roles:['researcher']});}
 const match=(p:R)=>[p.name,p.email,...roleList(p)].join(' ').toLowerCase().includes(query.toLowerCase());
 async function mutate(body:R){setBusy(true);setError('');try{await api('mutate',body);await reload();await read();setEdit(null);setMessage('Researcher record updated.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <div><section className="panel"><div className="section-head team-directory-toolbar"><label>Find people<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, email or role"/></label><button className="primary" disabled={!loaded||busy} onClick={()=>{setAdding(true);setError('');setLink('');}}>Add person</button></div>
 {error&&!edit&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{link&&<p className="source-note">Private invitation link: <a href={link}>{link}</a></p>}
 {!loaded?<p>Loading workspace accounts…</p>:<div className="table-scroll"><SortableTable stateKey="PeoplePanel.table1" className="sheet-table people-access-table"><thead><tr><th>Person</th><th>Sign-in email</th><th>Roles</th><th>Research team</th><th>Access</th><th>Actions</th></tr></thead><tbody>{members.filter(match).map(m=><tr key={m.id}><td><strong>{m.name}</strong>{m.id===data.actor.id&&<small>You are signed in as this person</small>}</td><td>{m.email}</td><td>{roleList(m).map(roleLabel).join(', ')}</td><td>{data.team_members.filter((t:R)=>t.staff_id===m.staff_id).map((t:R)=>data.teams.find((team:R)=>team.id===t.team_id)?.name).join(', ')||'No team'}</td><td>{m.status==='active'?'Active':'Access revoked'}</td><td><IconAction label="Edit person & roles" accessibleLabel={`Edit person and roles for ${m.name}`} disabled={busy||hasRole(m,'super_admin')&&!owner} onClick={()=>manage(m)}><PencilSimple size={17}/></IconAction>{hasRole(m,'super_admin')&&!owner&&<small>Super-admin managed</small>}</td></tr>)}</tbody></SortableTable></div>}
 </section>
 <details className="panel"><summary>Pending invitations ({invitations.length})</summary>{!invitations.length&&<p>No pending invitations.</p>}{invitations.filter(match).map(i=><div className="work-row" key={i.id}><strong>{i.name}</strong><span>{i.email} · {roleList(i).map(roleLabel).join(', ')}</span><button disabled={busy||hasRole(i,'super_admin')&&!owner} onClick={async()=>{setBusy(true);setError('');try{await api('invitations/cancel',{id:i.id});await read();setMessage('Invitation cancelled. Its link no longer works.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>Cancel invitation</button></div>)}</details>
 <details className="panel"><summary>What each role can do</summary><p>Permissions combine when someone has more than one role. Everyone can read searches, candidates, companies, plans, team rosters and progress within this workspace.</p><SortableTable stateKey="PeoplePanel.table2" className="sheet-table"><thead><tr><th>Role</th><th>Edit / manage access</th></tr></thead><tbody><tr><td>Super admin</td><td>All administration, including super-admin access. At least one must remain active.</td></tr><tr><td>Admin</td><td>People and roles except super admins; integrations, team setup, planning and search management.</td></tr><tr><td>Planner</td><td>Plans, team membership and reviewer pairing, companies and search setup.</td></tr><tr><td>Partner</td><td>Manage assigned searches and complete assigned partner reviews.</td></tr><tr><td>Researcher</td><td>Add candidates, create own mappings, submit work and review another teammate’s assigned mappings.</td></tr><tr><td>Engagement</td><td>Join separate engagement teams, manage assigned candidate outreach, record interactions and enrich candidate profiles.</td></tr><tr><td>Data quality analyst</td><td>Import candidates from Excel, maintain profiles and standardized tags. Sourcing assignment and review still require their own permissions.</td></tr><tr><td>Founder</td><td>Read-only oversight and add candidates; additional roles enable editing.</td></tr></tbody></SortableTable><p className="fine">Admin access does not impersonate a researcher. Add Researcher to do sourcing under your own name. Team leads record collective team review, including their own mappings. Assigned partners may complete their own formal partner review.</p></details>
 {owner&&<WorkspaceReset api={api} reload={reload} onDirty={onDirty}/>}
 {adding&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="add-person-title"><div className="section-head"><h2 id="add-person-title">Start with an existing person</h2><button onClick={()=>setAdding(false)}>Cancel</button></div><p>Enable Researcher on an existing account instead of creating a second person.</p><label>Find an existing account<input value={query} onChange={e=>setQuery(e.target.value)}/></label>{members.filter(match).map(m=><div className="work-row" key={m.id}><span><strong>{m.name}</strong><small>{m.email} · {roleList(m).map(roleLabel).join(', ')}</small></span><button disabled={hasRole(m,'super_admin')&&!owner} onClick={()=>manage(m,true)}>{hasRole(m,'researcher')?'Already a researcher — edit':'Enable Researcher'}</button></div>)}<hr/><p>Not in the list? Invite a genuinely new person.</p><button className="primary" onClick={()=>invite()}>Invite new person</button></section></div>}
 {edit&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="person-title"><div className="section-head"><h2 id="person-title">{edit.kind==='member'?'Edit person & roles':edit.kind==='invite'?'Invite new person':'Edit unlinked researcher'}</h2><button disabled={busy} onClick={()=>setEdit(null)}>Cancel</button></div><form onSubmit={async e=>{e.preventDefault();if(edit.kind==='staff'){await mutate({kind:'staff-edit',id:edit.id,version:edit.version,name:edit.name,email:edit.email});return;}setBusy(true);setError('');setLink('');try{if(edit.kind==='member'){await api('members/update',edit);setMessage('Person and roles updated.');}else{const r=await api('invite',{...edit,staffId:edit.staff_id});setLink(r.url);setMessage(r.emailStatus==='accepted'?'Invitation created and accepted by the email provider.':'Invitation created. Email delivery was not confirmed; use the private link.');}setEdit(null);await reload();await read();}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>
 <label>Name<input required maxLength={100} disabled={busy} value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>{edit.kind==='staff'?'Contact email (optional)':'Sign-in email'}<input type="email" required={edit.kind!=='staff'} readOnly={edit.kind==='member'} disabled={busy} value={edit.email||''} onChange={e=>setEdit({...edit,email:e.target.value})}/></label>
 {edit.kind==='member'&&<p className="fine">The person changes their sign-in email through Account settings, with verification. Name changes here apply to this workspace.</p>}
 {edit.kind!=='staff'&&<><fieldset disabled={busy}><legend>Roles — select all that apply</legend>{roles.filter(r=>r!=='super_admin'||owner).map(r=><label className="checkbox" key={r}><input type="checkbox" checked={edit.roles.includes(r)} onChange={e=>setEdit({...edit,roles:e.target.checked?[...edit.roles,r]:edit.roles.filter((v:string)=>v!==r)})}/>{roleLabel(r)}</label>)}</fieldset>{edit.roles.includes('researcher')&&<p className="fine">Researcher is a role on this account. Once active, this person can be added to teams and assigned work.</p>}{edit.kind==='member'&&<label>Workspace access<select disabled={busy||edit.id===data.actor.id} value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}><option value="active">Active</option><option value="revoked">Revoked</option></select></label>}</>}
 {error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy||edit.kind!=='staff'&&!edit.roles.length}>{busy?'Saving…':edit.kind==='invite'?'Send invitation':'Save person'}</button>
 </form></section></div>}
 </div>;
}
