import {effectiveEffort} from './planned-effort';
import React,{useState} from 'react';
import {RoleMultiFilter} from './RoleMultiFilter';
import {performanceMetrics,searchAge,recentWeeks,PerformanceFilter} from './performance';
import {effectiveDecision} from './search-decisions';
import {compareTableValues} from './table-sort';
import {CoverageMetrics} from './CoverageMetrics';
import {canPlan,hasRole} from './domain';
type R=Record<string,any>;
const num=(n:number|null)=>n===null?'—':Number(n.toFixed(2)).toLocaleString();
const percent=(n:number|null)=>n===null?'—':`${Math.round(n*100)}%`;
export function Performance({data,api,reload,onDirty,onDecision}:{data:R;api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;onDirty:(v:boolean)=>void;onDecision:(id:string)=>void}){
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());
 const [view,setView]=useState('people'),[group,setGroup]=useState('researcher'),[roles,setRoles]=useState<string[]|null>(null),[team,setTeam]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[expanded,setExpanded]=useState(''),[sort,setSort]=useState({key:'mapped',descending:true}),[matrix,setMatrix]=useState(false),[measure,setMeasure]=useState('throughput');
 const dirty=false;
 const f:PerformanceFilter={from,to,roles,team},records=data.research?.records||[],selectedRoles=data.searches.filter((s:R)=>roles===null||roles.includes(s.id));
 const metrics=(patch:Partial<PerformanceFilter>={})=>performanceMetrics(data,{...f,...patch});
 const rows:R[]=view==='searches'?selectedRoles.map((s:R)=>({id:s.id,name:s.client+' · '+s.title,...metrics({roles:[s.id]}),...searchAge(s,records,today),decision:effectiveDecision(data.priorities,s.id,today)?.disposition||'Not decided'})):(group==='researcher'?data.staff:data.teams.filter((t:R)=>!team||t.id===team)).map((p:R)=>({id:p.id,name:p.name,...metrics(group==='researcher'?{staff:p.id}:{team:p.id})})).filter((r:R)=>r.mapped||r.days||r.missing);
 rows.sort((a,b)=>compareTableValues(a[sort.key],b[sort.key],sort.descending)||a.name.localeCompare(b.name));
 const cols=view==='searches'?[['name','Client / search'],['age','Age (days)'],['decision','Decision'],['days','Person-days'],['mapped','Mapped'],['approved','Approved'],['yield','Approved/day']]:[['name',group==='researcher'?'Researcher':'Team'],['days','Person-days'],['mapped','Mapped'],['throughput','Mapped/day'],['quality','Quality'],['yield','Approved/day'],['pending','Awaiting review']];
 const heading=(key:string,title:string)=><th scope="col" aria-sort={sort.key===key?(sort.descending?'descending':'ascending'):'none'}><button className="table-sort-heading" onClick={()=>setSort({key,descending:sort.key===key?!sort.descending:false})}>{title}<span aria-hidden="true">{sort.key===key?(sort.descending?'↓':'↑'):'↕'}</span></button></th>;
 const cell=(r:R,k:string)=>k==='quality'?<>{percent(r.quality)}<small>{r.reviewed} decided</small></>:k==='days'?<>{num(r.days)}<small>{num(r.plannedDays)} from plan{r.exceptionDays>0&&` · ${num(r.exceptionDays)} previously recorded`}</small>{r.missing>0&&<small>{r.missing} work entries without allocated effort</small>}</>:k==='decision'?<span className={'badge priority-'+r.decision.toLowerCase()}>{r.decision}</span>:typeof r[k]==='number'||r[k]===null?num(r[k]):r[k];
 const summary=metrics(),weeks=recentWeeks(today);
 function exportCSV(){const fields=['name','days','hours','mapped','approved','reviewed','quality','throughput','yield','pending','returned','missing','plannedDays','exceptionDays'];const csv=[fields,...rows.map(r=>fields.map(k=>r[k]??''))].map(row=>row.map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='performance.csv';a.click();URL.revokeObjectURL(a.href);}
 function breakdown(id:string){const patch:Partial<PerformanceFilter>=view==='searches'?{roles:[id]}:group==='researcher'?{staff:id}:{team:id};const items=view==='searches'?data.staff:selectedRoles;return <><table className="sheet-table"><thead><tr><th>{view==='searches'?'Researcher':'Search'}</th><th>Person-days</th><th>Mapped</th><th>Mapped/day</th><th>Quality</th><th>Approved</th><th>Share of mappings</th><th>Share of approvals</th></tr></thead><tbody>{items.map((p:R)=>{const m=metrics({...patch,...(view==='searches'?{staff:p.id}:{roles:[p.id]})}),total=metrics(patch);if(!m.mapped&&!m.days&&!m.missing)return null;return <tr key={p.id}><td>{p.name||p.client+' · '+p.title}</td><td>{num(m.days)}{m.missing>0&&<small>Effort incomplete</small>}</td><td>{m.mapped}</td><td>{num(m.throughput)}</td><td>{percent(m.quality)}<small>{m.reviewed} decided</small></td><td>{m.approved}</td><td>{total.mapped?percent(m.mapped/total.mapped):'—'}</td><td>{total.approved?percent(m.approved/total.approved):'—'}</td></tr>})}</tbody></table></>;}
 function searchDetail(id:string){const s=data.searches.find((r:R)=>r.id===id),age=searchAge(s,records,today),m=metrics({roles:[id]});const dates=[...new Set<string>([...records.filter((r:R)=>r.kind==='mapping'&&r.submitted_at&&r.role_id===id).map((r:R)=>r.work_date),...effectiveEffort(data).filter((r:R)=>r.search_id===id).map((r:R)=>r.work_date)])].filter(d=>d&&(!from||d>=from)&&(!to||d<=to)).sort().reverse();return <><div className="delivery-summary"><span>CRM: {s.status}</span><span>First mapping: {age.first||'None'}</span><span>{num(age.sinceFirst)} days since first mapping</span><span>{m.activeDays} active sourcing days</span><span>{num(m.hours)} estimated hours</span><span>{num(m.perActiveDay)} mapped / active day</span><span>{percent(m.approvalRatio)} approved / all mapped</span><span>{m.returned} returned / on hold</span></div><h3>Recent weekly yield</h3><table className="sheet-table"><thead><tr><th>Period</th><th>Person-days</th><th>Mapped</th><th>Approved</th><th>Approved/day</th></tr></thead><tbody>{[['This week to date',weeks.current],['Last full week',weeks.previous]].map(([label,period])=>{const p=period as {from:string;to:string},r=metrics({...p,roles:[id]});return <tr key={label as string}><td>{label as string}<small>{p.from} – {p.to}</small></td><td>{num(r.days)}{r.missing>0&&<small>Effort incomplete</small>}</td><td>{r.mapped}</td><td>{r.approved}</td><td>{num(r.yield)}</td></tr>})}</tbody></table><h3>Researcher contributions</h3>{breakdown(id)}<details><summary>Results by work date</summary><div className="sheet-scroll"><table className="sheet-table"><thead><tr><th>Date</th><th>Person-days</th><th>Mapped</th><th>Peer approved</th><th>Partner approved</th><th>Quality</th></tr></thead><tbody>{dates.map(d=>{const r=metrics({roles:[id],from:d,to:d});return <tr key={d}><td>{d}</td><td>{num(r.days)}</td><td>{r.mapped}</td><td>{r.peerApproved}</td><td>{r.approved}</td><td>{percent(r.quality)}<small>{r.reviewed} decided</small></td></tr>})}</tbody></table></div></details><details><summary>Company research coverage</summary><CoverageMetrics data={data} role={id} from={from} to={to}/></details>{(canPlan(data.actor)||hasRole(data.actor,'partner'))&&<button onClick={()=>onDecision(id)}>Review sourcing decision</button>}</>;}
 return <section className="panel performance-panel"><div className="research-tabs"><button disabled={dirty} className={view==='people'?'primary':''} onClick={()=>{setView('people');setExpanded('');setSort({key:'mapped',descending:true});}}>Researcher performance</button><button disabled={dirty} className={view==='searches'?'primary':''} onClick={()=>{setView('searches');setExpanded('');setMatrix(false);setSort({key:'days',descending:true});}}>Search effort & yield</button></div><div className="sheet-toolbar performance-controls"><RoleMultiFilter searches={data.searches} value={roles} onChange={setRoles} disabled={dirty}/><label>Team<select value={team} onChange={e=>setTeam(e.target.value)}><option value="">All teams</option>{data.teams.map((t:R)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Through<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label>{view==='people'&&<><label>Compare<select value={group} onChange={e=>{setGroup(e.target.value);setExpanded('');}}><option value="researcher">Researchers</option><option value="team">Teams</option></select></label><button aria-pressed={matrix} onClick={()=>setMatrix(!matrix)}>{matrix?'Show table':'Show matrix'}</button></>}<button onClick={exportCSV}>Export CSV</button></div><div className="delivery-summary"><span>{num(summary.days)} person-days (plan-based)</span><span>{summary.mapped} mappings</span><span>{summary.approved} approved</span><span>{summary.pending} awaiting review</span>{summary.missing>0&&<span>{summary.missing} work entries without allocated effort</span>}</div>
 {matrix?<><label className="performance-measure">Measure<select value={measure} onChange={e=>setMeasure(e.target.value)}><option value="throughput">Mapped per person-day</option><option value="quality">Quality</option><option value="days">Person-days</option><option value="yield">Approved per person-day</option></select></label><div className="sheet-scroll"><table className="sheet-table performance-matrix"><thead><tr><th>Client / search</th>{rows.map(r=><th key={r.id}>{r.name}</th>)}</tr></thead><tbody>{selectedRoles.map((s:R)=><tr key={s.id}><th>{s.client}<small>{s.title}</small></th>{rows.map(r=>{const m=metrics({roles:[s.id],...(group==='researcher'?{staff:r.id}:{team:r.id})});return <td key={r.id}>{measure==='quality'?percent(m.quality):num((m as R)[measure])}{measure==='quality'&&<small>{m.reviewed} decided</small>}{m.missing>0&&<small>Effort incomplete</small>}</td>})}</tr>)}</tbody></table></div></>:<div className="sheet-scroll"><table className="sheet-table performance-table"><thead><tr>{cols.map(([k,t])=>heading(k,t))}<th>Details</th></tr></thead><tbody>{rows.map(r=><React.Fragment key={r.id}><tr>{cols.map(([k])=><td key={k}>{cell(r,k)}</td>)}<td><button aria-expanded={expanded===r.id} onClick={()=>setExpanded(expanded===r.id?'':r.id)}>{expanded===r.id?'Close':'Expand'}</button></td></tr>{expanded===r.id&&<tr><td colSpan={cols.length+1}><div className="performance-detail">{view==='searches'?searchDetail(r.id):breakdown(r.id)}</div></td></tr>}</React.Fragment>)}</tbody></table>{!rows.length&&<p>No work in this selection.</p>}</div>}
 <details className="metric-definitions"><summary>Metric definitions</summary><ul>
 <li><strong>Mapped:</strong> Submitted candidate mappings. Drafts are excluded.</li>
 <li><strong>Quality:</strong> Partner-approved ÷ final decisions (Approved + Rejected, including peer rejections). The “decided” count shows the sample size.</li>
 <li><strong>Awaiting review:</strong> Candidates waiting for peer or partner review. Pending, returned and on-hold candidates do not reduce the quality percentage.</li>
 <li><strong>Person-days:</strong> Planned allocations through today. A researcher’s day is divided equally across their allocated searches and teams, including days with no mappings.</li>
 <li><strong>PTO:</strong> Time off recorded in Weekly Plan contributes zero person-days. Future plans are excluded; earlier recorded effort corrections are preserved.</li>
 <li><strong>Mapped/day and approved/day:</strong> Mappings or partner approvals ÷ person-days. A dash means the rate cannot be calculated—for example, work has no allocated effort.</li>
 <li><strong>Estimated hours:</strong> Person-days × 8.</li>
 <li><strong>Search age:</strong> Calendar days since the recorded search start, including paused time. “Days since first mapping” starts at the first submitted mapping’s work date.</li>
 <li><strong>Active sourcing days:</strong> Distinct work dates with allocated effort or submitted mappings. These are days, not individual sessions.</li>
 <li><strong>Reporting period:</strong> Quality and approvals show the current outcomes of candidates mapped during the selected period, rather than approvals made during that period.</li>
 </ul></details>

 </section>;
}
