import {useViewState} from './ViewState';
import {Popup} from './Popup';
import {SortableTable} from './SortableTable';
import {displayDate,displayDateTime} from './dates';
import {sourcingProgressRows} from './delivery-monitor';
import {IconAction} from './IconAction';
import {Eye} from '@phosphor-icons/react';
import {LinkedInIcon} from './LinkedInIcon';
import {effectiveEffort} from './planned-effort';
import React,{useState} from 'react';
import {SearchMultiFilter} from './SearchMultiFilter';
import {performanceCandidates,performanceMetrics,searchAge,recentWeeks,performancePeriod,performanceAllocationGaps,PerformanceFilter} from './performance';
import {effectiveDecision} from './search-decisions';
import {compareTableValues} from './table-sort';
import {CoverageMetrics} from './CoverageMetrics';
import {canPlan,hasRole} from './domain';
type R=Record<string,any>;
const num=(n:number|null)=>n===null?'—':Number(n.toFixed(2)).toLocaleString();
const percent=(n:number|null)=>n===null?'—':`${Math.round(n*100)}%`;
export function Performance({data,api,reload,onDirty,onDecision,onOpen}:{data:R;api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;onDirty:(v:boolean)=>void;onDecision:(id:string)=>void;onOpen?:(role:string,mapping:string)=>void}){
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());
 const [detailTab,setDetailTab]=useViewState('Performance.detailTab','overview'),[contributionView,setContributionView]=useViewState('Performance.contributionView',false);
 const [view,setView]=useViewState('Performance.view','people'),[group,setGroup]=useViewState('Performance.group','researcher'),[roles,setRoles]=useViewState<string[]|null>('Performance.roles',null),[team,setTeam]=useViewState('Performance.team',''),[from,setFrom]=useViewState('Performance.from',''),[to,setTo]=useViewState('Performance.to',''),[expanded,setExpanded]=useViewState('Performance.expanded',''),[sort,setSort]=useViewState('Performance.sort',{key:'mapped',descending:true}),[matrix,setMatrix]=useViewState('Performance.matrix',false),[measure,setMeasure]=useViewState('Performance.measure','throughput');
 const [period,setPeriod]=useViewState('Performance.period',from||to?'custom':'30'),[focus,setFocus]=useViewState('Performance.focus','all');
 const [showGaps,setShowGaps]=useState(false),[gapSubject,setGapSubject]=useState('');
 const openGaps=(id='')=>{setGapSubject(id);setShowGaps(true);};
 const [cohort,setCohort]=useState<{title:string;items:R[];current:boolean}|null>(null);
 const firstDate=[...(data.assignments||[]),...(data.effort||[]),...(data.research?.records||[])].map((r:R)=>r.work_date).filter((d:string)=>d&&d<=today).sort()[0]||today;
 const range=performancePeriod(period,today,firstDate,from,to);
 const dirty=false;
 const f:PerformanceFilter={...range,roles,team},records=data.research?.records||[],selectedRoles=data.searches.filter((s:R)=>roles===null||roles.includes(s.id));
 const metrics=(patch:Partial<PerformanceFilter>={})=>performanceMetrics(data,{...f,...patch});
 const patchFor=(id:string):Partial<PerformanceFilter>=>view==='searches'?{roles:[id]}:group==='researcher'?{staff:id}:{team:id};
 const openCandidates=(title:string,statuses:string[]|null=null,id='',current=false)=>setCohort({title,items:performanceCandidates(data,{...f,...(id?patchFor(id):{})},statuses,current),current});
 const plans=sourcingProgressRows(data,roles,range.from,range.to,today).filter(r=>!team||r.team_id===team);
 const planFor=(id:string)=>{const items=plans.filter(r=>r.search_id===id);return {shortfall:items.reduce((n,r)=>n+r.shortfall,0),due:items.reduce((n,r)=>n+r.dueTarget,0),approved:items.reduce((n,r)=>n+r.partner,0),days:items.reduce((n,r)=>n+r.days,0),missing:items.some(r=>r.missingDueTarget)};};
 const currentReviews=performanceCandidates(data,f,['Peer review','Partner review'],true),currentReturns=performanceCandidates(data,f,['Needs information'],true);
 const behindSearches=new Set(plans.filter(r=>r.shortfall>0).map(r=>r.search_id));
 const rows:R[]=view==='searches'?selectedRoles.map((s:R)=>({id:s.id,name:s.client+' · '+s.title,...metrics({roles:[s.id]}),...searchAge(s,records,today),decision:effectiveDecision(data.priorities,s.id,today)?.disposition||'Not decided'})):(group==='researcher'?data.staff:data.teams.filter((t:R)=>!team||t.id===team)).map((p:R)=>({id:p.id,name:p.name,...metrics(group==='researcher'?{staff:p.id}:{team:p.id})})).filter((r:R)=>r.mapped||r.days||r.missing);
 rows.forEach(r=>{r.totalDays=view==='searches'?planFor(r.id).days:0;});
 rows.sort((a,b)=>compareTableValues(a[sort.key],b[sort.key],sort.descending)||a.name.localeCompare(b.name));
 const filteredRows=rows.filter(r=>focus==='all'||focus==='behind'&&behindSearches.has(r.id)||focus==='pending'&&r.pending>0||focus==='missing'&&r.missing>0||focus==='no-output'&&r.days>0&&!r.mapped||focus==='approved'&&r.approved>0);
 const cols=view==='searches'?[['name','Client / search'],['totalDays','Person-days to date'],['days','Person-days in period'],['mapped','Submitted'],['approved','Approved'],['pending','With reviewers'],['quality','Approval rate']]:[['name',group==='researcher'?'Researcher':'Team'],['days','Person-days in period'],['mapped','Submitted'],['approved','Approved'],['pending','With reviewers'],['quality','Approval rate']];
 const heading=(key:string,title:string)=><th scope="col" aria-sort={sort.key===key?(sort.descending?'descending':'ascending'):'none'}><button className="table-sort-heading" onClick={()=>setSort({key,descending:sort.key===key?!sort.descending:false})}>{title}<span aria-hidden="true">{sort.key===key?(sort.descending?'↓':'↑'):'↕'}</span></button></th>;
 const cell=(r:R,k:string)=>k==='name'?<button className="text-button performance-subject" onClick={()=>{setExpanded(r.id);setDetailTab('overview');}}><strong>{r.name}</strong></button>:k==='quality'?<>{percent(r.quality)}<small>{r.reviewed} final decisions</small></>:['days','totalDays'].includes(k)?num(r[k]):['mapped','approved','pending'].includes(k)?<button className={'text-button performance-value '+(r[k]>0?(k==='approved'?'positive':k==='pending'?'attention':''):'')} aria-label={`${k==='mapped'?'Submitted':k==='approved'?'Approved':'With reviewers'} candidates for ${r.name}: ${r[k]}`} onClick={()=>openCandidates(`${r.name} · ${k==='mapped'?'Submitted':k==='approved'?'Approved':'With reviewers'}`,k==='mapped'?null:k==='approved'?['Approved']:['Peer review','Partner review'],r.id)}>{r[k]}</button>:num(r[k]);
 const summary=metrics(),weeks=recentWeeks(today),gaps=performanceAllocationGaps(data,f);
 const shownGaps=gaps.filter(g=>!gapSubject||(view==='searches'?g.role_id===gapSubject:group==='researcher'?g.staff_id===gapSubject:g.team_id===gapSubject));
 const focusLabels:Record<string,string>={all:'Results for selected period',behind:'Searches behind plan today',pending:'Awaiting review',missing:'Allocation gaps','no-output':'Allocated, no submissions',approved:'Approved output'};
 const candidateDialog=cohort&&<Popup title={cohort.title} onClose={()=>setCohort(null)}><p className="performance-period">{cohort.current?`Current status · ${displayDate(today)} · All submission dates`:`Submitted ${displayDate(range.from)} – ${displayDate(range.to)} · Current outcomes`}</p><div className="sheet-scroll"><SortableTable stateKey="Performance.candidates" className="sheet-table delivery-pipeline"><thead><tr><th>Candidate</th><th>Search</th><th>Researcher</th><th>Next action</th><th>Submitted</th><th>Action</th></tr></thead><tbody>{cohort.items.map(m=>{const c=records.find((r:R)=>r.kind==='candidate'&&r.id===m.candidate_id),s=data.searches.find((r:R)=>r.id===m.role_id);return <tr key={m.id}><td><div className="monitor-candidate-name"><span className="monitor-linkedin-slot"><LinkedInIcon url={c?.url||m.url} name={c?.name||m.name}/></span><strong>{c?.name||m.name||'Candidate unavailable'}</strong></div></td><td><strong>{s?.title||'Search unavailable'}</strong></td><td>{data.staff.find((r:R)=>r.id===m.staff_id)?.name||'Unassigned'}</td><td>{m.status==='Peer review'?'Team reviewer: review candidate':m.status==='Partner review'?'Partner: review candidate':m.status==='Needs information'?'Researcher: respond to feedback':m.status==='Rejected'?'Researcher: examine rejection feedback':m.status==='Hold'?'Review hold decision':m.status}</td><td data-sort-value={m.submitted_at}>{displayDateTime(m.submitted_at)}</td><td>{onOpen&&<IconAction label="Open candidate review" onClick={()=>onOpen(m.role_id,m.id)}><Eye size={17}/></IconAction>}</td></tr>})}</tbody></SortableTable>{!cohort.items.length&&<p>No candidates in this selection.</p>}</div></Popup>;
 const allocationDialog=showGaps&&<Popup title="Allocation gaps" onClose={()=>setShowGaps(false)}><p className="performance-period">{displayDate(range.from)} – {displayDate(range.to)}</p><div className="sheet-scroll"><SortableTable stateKey="Performance.allocationGaps" className="sheet-table"><thead><tr><th>Work date</th><th>Researcher</th><th>Search / team</th><th>Submitted</th><th>Allocation issue</th><th>Action</th></tr></thead><tbody>{shownGaps.map(g=><tr key={g.id}><td data-sort-value={g.work_date}>{displayDate(g.work_date)}</td><td>{data.staff.find((p:R)=>p.id===g.staff_id)?.name||'Unknown researcher'}</td><td><strong>{data.searches.find((s:R)=>s.id===g.role_id)?.title||'Unknown search'}</strong><small>{data.teams.find((t:R)=>t.id===g.team_id)?.name||'No team'}</small></td><td>{g.mapped}</td><td><span className="performance-value attention">{g.reason}</span></td><td><button onClick={()=>onDecision(g.role_id)}>Review plan</button></td></tr>)}</tbody></SortableTable></div></Popup>;
 function exportCSV(){const fields=['name','days','hours','mapped','approved','reviewed','quality','throughput','yield','pending','returned','missing','plannedDays','exceptionDays'];const csv=[fields,...filteredRows.map(r=>fields.map(k=>r[k]??''))].map(row=>row.map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='performance.csv';a.click();URL.revokeObjectURL(a.href);}
 function breakdown(id:string){const patch:Partial<PerformanceFilter>=view==='searches'?{roles:[id]}:group==='researcher'?{staff:id}:{team:id};const items=view==='searches'?data.staff:selectedRoles,total=metrics(patch);const visible=items.map((p:R)=>({p,m:metrics({...patch,...(view==='searches'?{staff:p.id}:{roles:[p.id]})})})).filter(({m}:any)=>m.mapped||m.days||m.missing);return <><div className="performance-block-heading"><div><h3>{view==='searches'?'Researcher contributions':'Results by search'}</h3></div><label>Show<select value={contributionView?'share':'performance'} onChange={e=>setContributionView(e.target.value==='share')}><option value="performance">Effort &amp; quality</option><option value="share">Contribution share</option></select></label></div><div className="sheet-scroll"><SortableTable stateKey="Performance.table1" className="sheet-table"><thead><tr><th>{view==='searches'?'Researcher':'Search'}</th>{(contributionView?['Mapped','Share of mappings','Approved','Share of approvals']:['Person-days','Mapped','Mapped/day','Quality','Approved']).map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{visible.map(({p,m}:any)=><tr key={p.id}><td><strong>{p.name||p.client}</strong>{p.title&&<small>{p.title}</small>}</td>{contributionView?<><td>{m.mapped}</td><td>{total.mapped?percent(m.mapped/total.mapped):'—'}</td><td>{m.approved}</td><td>{total.approved?percent(m.approved/total.approved):'—'}</td></>:<><td>{num(m.days)}{m.missing>0&&<small>Effort incomplete</small>}</td><td>{m.mapped}</td><td>{num(m.throughput)}</td><td>{percent(m.quality)}<small>{m.reviewed} decided</small></td><td>{m.approved}</td></>}</tr>)}</tbody></SortableTable></div>{!visible.length&&<p className="performance-empty">No work recorded in this selection.</p>}</>;}
 function weeklyYield(id:string){return <><div className="performance-block-heading"><div><h3>Recent weekly yield</h3></div></div><div className="sheet-scroll"><SortableTable stateKey="Performance.table2" className="sheet-table"><thead><tr><th>Period</th><th>Person-days</th><th>Mapped</th><th>Approved</th><th>Approved/day</th></tr></thead><tbody>{[['This week to date',weeks.current],['Last full week',weeks.previous]].map(([label,period])=>{const p=period as {from:string;to:string},r=metrics({...p,roles:[id]});return <tr key={label as string}><td><strong>{label as string}</strong><small>{displayDate(p.from)} – {displayDate(p.to)}</small></td><td>{num(r.days)}{r.missing>0&&<small>Effort incomplete</small>}</td><td>{r.mapped}</td><td>{r.approved}</td><td>{num(r.yield)}</td></tr>})}</tbody></SortableTable></div></>;}
 function dailyResults(id:string){const dates=[...new Set<string>([...records.filter((r:R)=>r.kind==='mapping'&&r.submitted_at&&r.role_id===id).map((r:R)=>r.work_date),...effectiveEffort(data).filter((r:R)=>r.search_id===id).map((r:R)=>r.work_date)])].filter(d=>d&&d>=range.from&&d<=range.to).sort().reverse();return <><div className="performance-block-heading"><div><h3>Results by work date</h3></div></div><div className="sheet-scroll performance-daily-scroll"><SortableTable stateKey="Performance.table3" className="sheet-table"><thead><tr><th>Date</th><th>Person-days</th><th>Mapped</th><th>Team approved</th><th>Partner approved</th><th>Quality</th></tr></thead><tbody>{dates.map(d=>{const r=metrics({roles:[id],from:d,to:d});return <tr key={d}><td data-sort-value={d}>{displayDate(d)}</td><td>{num(r.days)}</td><td>{r.mapped}</td><td>{r.peerApproved}</td><td>{r.approved}</td><td>{percent(r.quality)}<small>{r.reviewed} decided</small></td></tr>})}</tbody></SortableTable></div>{!dates.length&&<p className="performance-empty">No activity in this period.</p>}</>;}
 const selected=rows.find(r=>r.id===expanded);
 if(selected){const s=view==='searches'?data.searches.find((r:R)=>r.id===expanded):null;const tabs=view==='searches'?[['overview','Overview'],['breakdown','Researchers'],['daily','Work dates'],['coverage','Company coverage']]:[['overview','Overview'],['breakdown','By search']];
 return <section className="panel performance-panel performance-focus"><header className="performance-focus-header"><button onClick={()=>setExpanded('')}>Back to {view==='searches'?'search effort':'researcher performance'}</button><div><p className="performance-kicker">{view==='searches'?'SEARCH EFFORT & YIELD':group==='team'?'TEAM PERFORMANCE':'RESEARCHER PERFORMANCE'}</p><h2>{s?s.client:selected.name}</h2>{s&&<p className="performance-focus-title">{s.title}</p>}<p className="performance-period">{displayDate(range.from)} – {displayDate(range.to)} · {team?data.teams.find((t:R)=>t.id===team)?.name:'All teams'}{view==='people'&&' · '+(roles===null?'All searches':selectedRoles.length+' selected searches')}</p></div>{s&&(canPlan(data.actor)||hasRole(data.actor,'partner'))&&<button onClick={()=>onDecision(expanded)}>Review sourcing decision</button>}</header>
 <div className={'performance-key-metrics'+(detailTab!=='overview'?' performance-key-metrics-compact':'')}>{[['Person-days',num(selected.days),'Plan-based effort'],['Mapped / day',num(selected.throughput),selected.mapped+' mappings'],['Quality',percent(selected.quality),selected.reviewed+' final decisions'],['Approved / day',num(selected.yield),selected.approved+' approvals']].map(([label,value,note])=><div key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>)}</div>
 {selected.missing>0&&<p className="performance-data-note"><button className="text-button" onClick={()=>openGaps(selected.id)}>{selected.missing} allocation gaps · Review dates and researchers</button></p>}
 <nav className="performance-detail-tabs" aria-label="Performance detail sections">{tabs.map(([key,label])=><button key={key} aria-pressed={detailTab===key} onClick={()=>setDetailTab(key)}>{label}</button>)}</nav>
 <div className="performance-detail-body">{detailTab==='overview'&&<><div className="performance-overview-grid"><section><h3>Output &amp; review</h3><dl><div><dt>Submitted mappings</dt><dd><button className="text-button" onClick={()=>openCandidates("Submitted candidates",null,selected.id)}>{selected.mapped}</button></dd></div><div><dt>Partner approved</dt><dd><button className="text-button" onClick={()=>openCandidates("Approved candidates",["Approved"],selected.id)}>{selected.approved}</button></dd></div><div><dt>Awaiting review</dt><dd><button className="text-button" onClick={()=>openCandidates("Candidates with reviewers",["Peer review","Partner review"],selected.id)}>{selected.pending}</button></dd></div><div><dt>Returned / on hold</dt><dd><button className="text-button" onClick={()=>openCandidates("Returned / on hold",["Needs information","Hold"],selected.id)}>{selected.returned}</button></dd></div></dl></section><section><h3>{s?'Search context':'Effort context'}</h3><dl>{(s?[['CRM status',s.status||'Not set'],['Sourcing decision',selected.decision],['Search age',num(selected.age)+' days'],['First mapping',selected.first?displayDate(selected.first):'None'],['Days since first mapping',num(selected.sinceFirst)]]:[['Person-days from plan',num(selected.plannedDays)],['Previously recorded effort',num(selected.exceptionDays)],['Estimated hours',num(selected.hours)],['Active sourcing days',selected.activeDays]]).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section></div>
 {s?weeklyYield(expanded):<div className="performance-next-detail"><button onClick={()=>setDetailTab('breakdown')}>View results by search</button></div>}
 {s&&<details className="performance-supporting"><summary>Supporting measures</summary><dl><div><dt>Active sourcing days</dt><dd>{selected.activeDays}</dd></div><div><dt>Estimated hours</dt><dd>{num(selected.hours)}</dd></div><div><dt>Mapped / active day</dt><dd>{num(selected.perActiveDay)}</dd></div><div><dt>Approved / all mapped</dt><dd>{percent(selected.approvalRatio)}</dd></div></dl></details>}</>}
 {detailTab==='breakdown'&&breakdown(expanded)}{detailTab==='daily'&&dailyResults(expanded)}{detailTab==='coverage'&&<><div className="performance-block-heading"><h3>Company research coverage</h3></div><CoverageMetrics data={data} role={expanded} from={range.from} to={range.to}/></>}</div>
 {candidateDialog}{allocationDialog}</section>;
 }

 return <section className="panel performance-panel"><div className="research-tabs"><button disabled={dirty} className={view==='people'?'primary':''} onClick={()=>{setView('people');setFocus('all');setExpanded('');setSort({key:'mapped',descending:true});}}>Researcher performance</button><button disabled={dirty} className={view==='searches'?'primary':''} onClick={()=>{setView('searches');setFocus('all');setExpanded('');setMatrix(false);setSort({key:'days',descending:true});}}>Search effort & yield</button></div><div className="sheet-toolbar performance-controls"><SearchMultiFilter searches={data.searches} value={roles} onChange={setRoles} disabled={dirty}/><label>Team<select value={team} onChange={e=>setTeam(e.target.value)}><option value="">All teams</option>{data.teams.map((t:R)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Period<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="30">Last 30 days</option><option value="week">This week</option><option value="previous">Last week</option><option value="month">This month</option><option value="all">All recorded dates</option><option value="custom">Custom dates</option></select></label><label>From<input type="date" value={range.from} max={range.to} onChange={e=>{if(e.target.value){setFrom(e.target.value);setTo(range.to);setPeriod('custom');}}}/></label><label>Through<input type="date" value={range.to} min={range.from} max={today} onChange={e=>{if(e.target.value){setFrom(range.from);setTo(e.target.value);setPeriod('custom');}}}/></label>{view==='people'&&<><label>Compare<select value={group} onChange={e=>{setGroup(e.target.value);setExpanded('');}}><option value="researcher">Researchers</option><option value="team">Teams</option></select></label><button aria-pressed={matrix} onClick={()=>{setMatrix(!matrix);setFocus('all');}}>{matrix?'Show table':'Show matrix'}</button></>}<button onClick={exportCSV}>Export CSV</button></div><div className="performance-block-heading"><h3>Actions now</h3><span className="performance-period">{displayDate(today)} · All submission dates</span></div><div className="performance-insights" aria-label="Performance priorities">
 <button className={'performance-insight '+(behindSearches.size?'urgent':'neutral')} onClick={()=>{setView('searches');setFocus('behind');setMatrix(false);}}><strong>{behindSearches.size}</strong><span>Searches behind plan</span></button>
 <button className={'performance-insight '+(currentReviews.length?'attention':'neutral')} onClick={()=>openCandidates('Candidates needing a review',['Peer review','Partner review'],'',true)}><strong>{currentReviews.length}</strong><span>Team / partner reviews</span></button>
 <button className={'performance-insight '+(currentReturns.length?'urgent':'neutral')} onClick={()=>openCandidates('Researcher follow-up needed',['Needs information'],'',true)}><strong>{currentReturns.length}</strong><span>Researcher follow-ups</span></button>
 <button className={'performance-insight '+(summary.approved?'positive':'neutral')} onClick={()=>openCandidates('Approved candidates',['Approved'])}><strong>{summary.approved}</strong><span>Approved from selected period</span></button>
 </div>
 <div className="performance-result-heading"><h3>{focusLabels[focus]||'All results'}</h3><span>{displayDate(range.from)} – {displayDate(range.to)}</span>{focus!=='all'&&<button className="text-button" onClick={()=>setFocus('all')}>Show all</button>}{focus==='missing'&&gaps.length>0&&<button onClick={()=>openGaps()}>Review allocation gaps</button>}</div>

 {matrix?<><label className="performance-measure">Measure<select value={measure} onChange={e=>setMeasure(e.target.value)}><option value="throughput">Mapped per person-day</option><option value="quality">Quality</option><option value="days">Person-days</option><option value="yield">Approved per person-day</option></select></label><div className="sheet-scroll"><SortableTable stateKey="Performance.table4" className="sheet-table performance-matrix"><thead><tr><th>Client / search</th>{rows.map(r=><th key={r.id}>{r.name}</th>)}</tr></thead><tbody>{selectedRoles.map((s:R)=><tr key={s.id}><th>{s.client}<small>{s.title}</small></th>{rows.map(r=>{const m=metrics({roles:[s.id],...(group==='researcher'?{staff:r.id}:{team:r.id})});return <td key={r.id}>{measure==='quality'?percent(m.quality):num((m as R)[measure])}{measure==='quality'&&<small>{m.reviewed} decided</small>}{m.missing>0&&<small>Effort incomplete</small>}</td>})}</tr>)}</tbody></SortableTable></div></>:<div className="sheet-scroll"><SortableTable stateKey="Performance.table5" className="sheet-table performance-table"><thead><tr>{cols.map(([k,t])=>heading(k,t))}<th>Next action · current</th></tr></thead><tbody>{filteredRows.map(r=><React.Fragment key={r.id}><tr>{cols.map(([k])=><td key={k}>{cell(r,k)}</td>)}<td><div className="performance-next-actions">{view==='searches'?(()=>{const p=planFor(r.id);return <><span className={'plan-progress '+(p.shortfall?'behind':p.due&&!p.missing?'on-track':p.missing?'incomplete':'neutral')}><strong>{p.shortfall?`${p.shortfall} approvals behind plan`:p.missing?'Target incomplete':p.due?'On track':'No target due yet'}</strong>{p.due>0&&<small>{p.approved} approved · {p.due} due before today</small>}</span>{p.shortfall>0&&<button className="text-button" onClick={()=>onDecision(r.id)}>Review search plan</button>}</>;})():null}{(()=>{const scoped={...f,...patchFor(r.id)},returned=performanceCandidates(data,scoped,['Needs information'],true).length,waiting=performanceCandidates(data,scoped,['Peer review','Partner review'],true).length;return <>{returned>0&&<button className="text-button performance-follow-up" onClick={()=>openCandidates(`${r.name} · Researcher follow-up`,['Needs information'],r.id,true)}>{returned} need researcher follow-up</button>}{waiting>0&&<button className="text-button" onClick={()=>openCandidates(`${r.name} · Reviews to complete`,['Peer review','Partner review'],r.id,true)}>{waiting} need team / partner review</button>}{!returned&&!waiting&&view==='people'&&<span className="performance-period">No review actions pending</span>}</>;})()}</div></td></tr></React.Fragment>)}</tbody></SortableTable>{!filteredRows.length&&<p>No results in this selection.</p>}</div>}
 <details className="performance-supporting"><summary>Data completeness · {gaps.length} allocation gaps</summary>{gaps.length>0?<button onClick={()=>openGaps()}>Allocation gaps: review affected dates</button>:<p>No allocation gaps for submitted work.</p>}</details>
 <details className="metric-definitions"><summary>Metric definitions</summary><ul>
 <li><strong>Mapped:</strong> Submitted candidate mappings. Drafts are excluded.</li>
 <li><strong>Quality:</strong> Partner-approved ÷ final decisions (Approved + Rejected, including team-review rejections). The “decided” count shows the sample size.</li>
 <li><strong>Awaiting review:</strong> Candidates waiting for team or partner review. Pending and returned candidates do not reduce the quality percentage.</li>
 <li><strong>Person-days:</strong> Planned allocations through today. A researcher’s day is divided equally across their allocated searches and teams, including days with no mappings.</li>
 <li><strong>PTO:</strong> Time off recorded in Weekly Plan contributes zero person-days. Future plans are excluded; earlier recorded effort corrections are preserved.</li>
 <li><strong>Mapped/day and approved/day:</strong> Mappings or partner approvals ÷ person-days. A dash means the rate cannot be calculated—for example, work has no allocated effort.</li>
 <li><strong>Estimated hours:</strong> Person-days × 8.</li>
 <li><strong>Search age:</strong> Calendar days since the recorded search start, including paused time. “Days since first mapping” starts at the first submitted mapping’s work date.</li>
 <li><strong>Active sourcing days:</strong> Distinct work dates with allocated effort or submitted mappings. These are days, not individual sessions.</li>
 <li><strong>Reporting period:</strong> Quality and approvals show the current outcomes of candidates mapped during the selected period, rather than approvals made during that period.</li>
 </ul></details>

 {candidateDialog}{allocationDialog}</section>;
}
