import React,{useState,useEffect} from 'react';
import {canPlan} from './domain';
import {displayDate} from './dates';
import {teamColor} from './team-colors';
export function PlanningTasks({data,api,reload,from='',to='',mine=false,roles=null,teamId='',onDirty=()=>{}}:any){
 const [edit,setEdit]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const planner=canPlan(data.actor);
 useEffect(()=>{onDirty(!!edit);return()=>onDirty(false);},[!!edit]);
 const tasks=data.research.records.filter((r:any)=>r.kind==='task'&&(!teamId||r.team_id===teamId)&&(roles===null||roles.includes(r.role_id))&&(!from||r.work_date>=from)&&(!to||r.work_date<=to)&&(!mine||r.owner_id===data.actor.id)).sort((a:any,b:any)=>a.work_date.localeCompare(b.work_date));
 async function save(b:any){setBusy(true);setError('');try{await api('research',b);await reload();setEdit(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <section className="panel"><div className="section-head"><h2>{mine?'My search tasks':'Search preparation & other tasks'}</h2>{planner&&!mine&&<button onClick={()=>setEdit({role_id:'',team_id:'',owner_id:'',work_date:from,task_type:'Role brief',status:'Planned',notes:''})}>Assign task</button>}</div><p className="fine">Briefs, strategy, target-company research and other work count toward plan-based person-days. A person is counted at most once per day across all allocated work.</p>{error&&<p className="error">{error}</p>}<div className="table-scroll"><table className="sheet-table"><thead><tr><th>Date</th><th>Search</th><th>Task</th><th>Assigned to / team</th><th>Status</th><th>Action</th></tr></thead><tbody>{tasks.map((t:any)=>{const s=data.searches.find((s:any)=>s.id===t.role_id),team=data.teams.find((v:any)=>v.id===t.team_id);return <tr key={t.id}><td>{displayDate(t.work_date)}</td><td>{s?.client}<small>{s?.title}</small></td><td>{t.title}<small>{t.notes}</small></td><td style={{borderLeft:`3px solid ${teamColor(team?.name||'',t.team_id)}`}}>{data.people.find((p:any)=>p.id===t.owner_id)?.name||'Former member'}<span className="plan-team-badge" style={{'--team-color':teamColor(team?.name||'',t.team_id)} as React.CSSProperties}>{team?.name}</span></td><td>{planner||t.owner_id===data.actor.id?<select aria-label={'Task status for '+t.title} disabled={busy} value={t.status} onChange={e=>save({action:'task-status',id:t.id,version:t.version,status:e.target.value})}>{['Planned','In progress','Completed','Cancelled'].map(v=><option key={v}>{v}</option>)}</select>:t.status}</td><td>{planner&&<button onClick={()=>setEdit({...t})}>Edit</button>}</td></tr>})}</tbody></table>{!tasks.length&&<p>No tasks in this period.</p>}</div>
 {edit&&<div className="modal-backdrop"><section className="modal"><h2>Assign search task</h2><form onSubmit={e=>{e.preventDefault();save({...edit,action:'task-save'});}}><label>Search<select required value={edit.role_id} disabled={!!edit.id} onChange={e=>setEdit({...edit,role_id:e.target.value})}><option value="">Choose search</option>{data.searches.map((s:any)=><option key={s.id} value={s.id}>{s.client} · {s.title}</option>)}</select></label><label>Task type<select value={edit.task_type} onChange={e=>setEdit({...edit,task_type:e.target.value})}>{['Role brief','Search strategy','Target companies','Sourcing','Other'].map(v=><option key={v}>{v}</option>)}</select></label><label>Task / deliverable<input value={edit.title||''} onChange={e=>setEdit({...edit,title:e.target.value})}/></label><label>Team<select required value={edit.team_id} onChange={e=>setEdit({...edit,team_id:e.target.value,owner_id:''})}><option value="">Choose team</option>{data.teams.map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Team member<select required value={edit.owner_id} onChange={e=>setEdit({...edit,owner_id:e.target.value})}><option value="">Choose person</option>{data.people.filter((p:any)=>data.team_members.some((m:any)=>m.team_id===edit.team_id&&m.staff_id===p.staff_id)).map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Planned date<input type="date" required value={edit.work_date} onChange={e=>setEdit({...edit,work_date:e.target.value})}/></label><label>Notes<textarea value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label>{error&&<p className="error">{error}</p>}<button disabled={busy}>Save task</button><button type="button" disabled={busy} onClick={()=>setEdit(null)}>Cancel</button></form></section></div>}
 </section>;
}
