import {hasRole,canPlan,canPartnerReview,roleList,roleLabel} from './domain';
import {RoleBriefEditor} from './RoleBriefEditor';
import React,{useEffect,useState} from 'react';
import {MappingForm} from './Candidates';
type R=Record<string,any>;
const days=(v:string)=>v?Math.max(0,Math.floor((Date.now()-Date.parse(v))/86400000)):0;
export function PublicBrief(){const [brief,setBrief]=useState<R|null>(null),[error,setError]=useState('');useEffect(()=>{fetch('/api/public-brief'+location.search).then(async r=>{const b=await r.json() as R;if(!r.ok)throw new Error(b.error);setBrief(b);}).catch(e=>setError(e.message));},[]);return <main className="public-brief"><img src="/brand/xqtiv-logo.svg" alt="XQtiv"/><p>ROLE BRIEF</p>{error?<p role="alert">{error}</p>:brief?<><h1>{brief.title}</h1><h2>{brief.client}</h2><p className="document-text">{brief.content}</p><small>Approved version {brief.revision}</small></>:<p>Loading role brief…</p>}</main>;}
export function ResearchPanel({data,api,reload,view,onDirty,initialRole='',initialTab='Target companies',onCompanies}:{onCompanies?:(id:string)=>void;data:R;api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;view:string;onDirty:(v:boolean)=>void;initialRole?:string;initialTab?:string}) {
 const [role,setRole]=useState(initialRole),[tab,setTab]=useState(initialTab),[filter,setFilter]=useState(''),[stage,setStage]=useState(''),[team,setTeam]=useState(''),[owner,setOwner]=useState(''),[category,setCategory]=useState(''),[edit,setEdit]=useState<R|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[detail,setDetail]=useState<R|null>(null);
 const [briefDirty,setBriefDirty]=useState(false);
 const [checked,setChecked]=useState<string[]>([]),[targetChecked,setTargetChecked]=useState<string[]>([]),[wave,setWave]=useState('1');
 const records:R[]=data.research?.records||[],events:R[]=data.research?.events||[],people:R[]=data.people||[],actor=data.actor;
 const searches:R[]=data.searches,teams:R[]=data.teams;
 const byId=(id:string)=>records.find(r=>r.id===id),name=(id:string)=>people.find(p=>p.id===id)?.name||'Unassigned',search=(id:string)=>searches.find(s=>s.id===id);
 const isPlan=canPlan(actor),manager=isPlan||hasRole(actor,'partner')&&search(role)?.partner_id===actor.id;
 const docs=records.filter(r=>r.role_id===role),researchers=people.filter(p=>hasRole(p,'researcher')&&p.staff_id);
 const mine=view==='My Work';
 useEffect(()=>{onDirty(!!edit||briefDirty);return()=>onDirty(false);},[!!edit,briefDirty]);
 useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(edit||briefDirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[!!edit,briefDirty]);
 async function act(b:R,close=true){setBusy(true);setError('');try{await api('research',b);await reload();setChecked([]);if(close)setEdit(null);setDetail(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const start=(b:R)=>{setError('');setEdit(b);};
 const visible=(r:R)=> (!category||(r.kind==='target'?r.category:byId(r.target_id)?.category)===category)&&(!role||r.role_id===role)&&(!team||r.team_id===team)&&(!owner||r.mapper_id===owner||r.owner_id===owner)&&(!stage||r.status===stage)&&(!filter||[r.name,r.title,r.company,search(r.role_id)?.title,search(r.role_id)?.client,r.rationale].join(' ').toLowerCase().includes(filter.toLowerCase()));
 const targets=records.filter(r=>r.kind==='target'&&visible(r)&&(!mine||r.owner_id===actor.id&&!['Completed','No relevant talent'].includes(r.status))).sort((a,b)=>(a.wave||999)-(b.wave||999)||a.name.localeCompare(b.name));
 const mappings=records.filter(r=>r.kind==='mapping'&&visible(r)&&(!mine||(r.mapper_id===actor.id&&['Draft','Needs information','Hold'].includes(r.status))||(r.status==='Peer review'&&r.reviewer_id===actor.id)||(r.status==='Partner review'&&search(r.role_id)?.partner_id===actor.id)));
 const total=records.filter(r=>r.kind==='mapping'&&visible(r)&&r.submitted_at),approved=total.filter(r=>r.status==='Approved'),decided=total.filter(r=>['Approve','Reject'].includes(r.partner_decision)),pending=total.filter(r=>['Peer review','Partner review'].includes(r.status));
 const ratio=(n:number,d:number)=>d?`${Math.round(n/d*100)}%`:'—';
 const btn=(label:string,b:R)=> <button disabled={busy} onClick={()=>act(b)}>{label}</button>;
 const roleActions=(r:R)=>{const canManage=isPlan||hasRole(actor,'partner')&&search(r.role_id)?.partner_id===actor.id;return <>
 {r.owner_id===actor.id&&hasRole(actor,'researcher')&&<button disabled={busy} onClick={()=>start({action:'mapping-add',role_id:r.role_id,target_id:r.id,name:'',title:'',url:'',rationale:'',paste:''})}>Add mappings</button>}
 {!r.owner_id&&hasRole(actor,'researcher')&&btn('Claim',{action:'company-claim',id:r.id,version:r.version})}
 {(canManage||r.owner_id===actor.id)&&<button onClick={()=>start({...r,action:'company-progress'})}>Coverage</button>}
 {canManage&&<><button className="primary" onClick={()=>start({...r,action:'target-assign'})}>Assign researcher</button><button onClick={()=>start({...r,action:'company-save'})}>Company details</button></>}</>;};
 function mappingActions(r:R){const mine=r.mapper_id===actor.id&&hasRole(actor,'researcher'),review=(hasRole(actor,'researcher')&&r.status==='Peer review'&&r.reviewer_id===actor.id)||(canPartnerReview(actor)&&r.status==='Partner review'&&search(r.role_id)?.partner_id===actor.id);return <div className="research-actions">
 <button onClick={()=>setDetail(r)}>Details</button>
 {mine&&['Draft','Needs information'].includes(r.status)&&<button onClick={()=>start({...r,action:'mapping-edit'})}>Edit</button>}
 {mine&&['Draft','Needs information','Hold'].includes(r.status)&&btn('Submit',{action:'mapping-submit',id:r.id,version:r.version})}
 {review&&!mine&&<button className="primary" onClick={()=>start({...r,action:'mapping-review',decision:'Approve',reason:'',notes:''})}>Review</button>}
 {isPlan&&<button onClick={()=>start({...r,action:'mapping-reassign'})}>Reassign peer</button>}
 {(isPlan||hasRole(actor,'partner')&&search(r.role_id)?.partner_id===actor.id)&&['Approved','Rejected'].includes(r.status)&&<button onClick={()=>start({...r,action:'mapping-reopen',notes:''})}>Reopen</button>}
 </div>;}
 function targetTable(){return <div className="sheet-scroll"><table className="sheet-table research-table"><thead><tr><th>Wave / select</th><th>Company</th><th>Team</th><th>Researcher</th><th>Coverage</th><th>Submitted / approved</th><th>Actions</th></tr></thead><tbody>{targets.map(t=>{const ms=records.filter(m=>m.kind==='mapping'&&m.target_id===t.id);return <tr key={t.id}><td>{manager&&<input type="checkbox" aria-label={'Select '+t.name} checked={targetChecked.includes(t.id)} onChange={e=>setTargetChecked(e.target.checked?[...targetChecked,t.id]:targetChecked.filter(id=>id!==t.id))}/>}<strong>{t.wave?'Wave '+t.wave:'—'}</strong></td><td><strong>{byId(t.company_id)?.name||t.name}</strong>{view!=='Role repository'&&<small>{search(t.role_id)?.client} · {search(t.role_id)?.title}</small>}</td><td>{teams.find(v=>v.id===t.team_id)?.name||'Team not set'}</td><td>{t.owner_id?name(t.owner_id):'Researcher not assigned'}</td><td>{t.status}{t.status==='Blocked'&&<small>{t.notes}</small>}</td><td>{ms.filter(m=>m.submitted_at).length} / {ms.filter(m=>m.status==='Approved').length}</td><td><div className="research-actions">{roleActions(t)}</div></td></tr>;})}</tbody></table>{!targets.length&&<p className="sheet-empty">No companies match this view.</p>}</div>;}
 function mappingTable(){return <div className="sheet-scroll"><table className="sheet-table research-table"><thead><tr><th>Select</th><th>Candidate / company</th><th>Role</th><th>Researcher</th><th>Status / waiting</th><th>Next reviewer</th><th>Actions</th></tr></thead><tbody>{mappings.map(m=><tr key={m.id}><td><input type="checkbox" aria-label={"Select "+m.name} checked={checked.includes(m.id)} onChange={e=>setChecked(e.target.checked?[...checked,m.id]:checked.filter(id=>id!==m.id))}/></td><td><a href={m.url} target="_blank" rel="noreferrer">{m.name}</a><small>{m.title} · {m.company}</small></td><td>{search(m.role_id)?.client}<small>{search(m.role_id)?.title}</small></td><td>{name(m.mapper_id)}</td><td><span className={'workflow-status status-'+m.status.toLowerCase().replaceAll(' ','-')}>{m.status}</span><small>{['Peer review','Partner review'].includes(m.status)?`${days(m.stage_at)} days waiting`:''}</small></td><td>{name(m.status==='Partner review'?search(m.role_id)?.partner_id:m.reviewer_id)}</td><td>{mappingActions(m)}</td></tr>)}</tbody></table>{!mappings.length&&<p className="sheet-empty">No mappings match this view.</p>}</div>;}
 function document(kind:string){const d=docs.find(r=>r.kind===kind),title=kind==='brief'?'Role brief':'Search strategy';return <section className="panel"><div className="section-head"><div><h2>{title}</h2><p>{kind==='brief'?'The approved role brief has its own shareable page for candidates and clients. Document-to-page styling will follow your supplied format.':'Define archetypes, titles, methods, geography, company categories, exclusions, assumptions and risks.'}</p></div>{manager&&<button onClick={()=>start({...d,role_id:role,action:kind+'-save',content:d?.draft||''})}>{d?'Edit draft':'Create draft'}</button>}</div>
 {d?<><p>{d.status} · Approved version {d.revision||'—'}{d.cutover&&` · Candidate tracking from ${d.cutover}`}</p><div className="document-text">{d.draft}</div>{d.active&&d.active!==d.draft&&<details><summary>Current approved version {d.revision}</summary><p className="document-text">{d.active}</p></details>}
 <div className="research-actions">{manager&&d.status==='Draft'&&(kind==='strategy'&&!d.cutover?<button onClick={()=>start({...d,action:'strategy-approve',cutover:new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date())})}>Approve and start tracking</button>:btn('Approve this draft',{action:kind+'-approve',id:d.id,version:d.version}))}
 {manager&&kind==='brief'&&d.active&&<button disabled={busy} onClick={()=>start({...d,action:'brief-publish'})}>Publish shareable page</button>}
 {manager&&kind==='brief'&&d.share_token&&btn('Revoke client link',{action:'brief-unpublish',id:d.id,version:d.version})}</div>
 {kind==='brief'&&d.share_token&&<p><a href={'/brief?workspace='+encodeURIComponent(actor.tenant)+'&token='+d.share_token} target="_blank" rel="noreferrer">Open shared brief</a> · <button onClick={()=>navigator.clipboard.writeText(location.origin+'/brief?workspace='+encodeURIComponent(actor.tenant)+'&token='+d.share_token).catch(()=>setError('Open the shared brief and copy its address.'))}>Copy link</button></p>}
 <details><summary>Version and activity history</summary>{events.filter(e=>e.record_id===d.id).map(e=><p key={e.id}>{new Date(e.created_at).toLocaleString()} · {name(e.actor)} · {e.action}<span className="document-text">{e.data.after?.active||e.data.after?.draft}</span></p>)}</details></>:<p>No {title.toLowerCase()} yet.</p>}</section>;}
 return <div className="research-panel">
 <details className="panel"><summary>How to use the research workflow</summary><ol><li>In People & access, enable the Researcher role on the existing person. In Teams, add them to a team. In Teams, choose who reviews each researcher. Two-person teams automatically review each other.</li><li>Open a role. Confirm its engagement partner, save and approve a role brief and search strategy.</li><li>Add target companies with scope and a team. Assign researchers, or let team members claim unassigned companies.</li><li>Researchers add candidates from their company assignments, then submit mappings. Peer approval routes each mapping to the engagement partner.</li><li>Use My Work for actions and Workflow Monitor for bottlenecks. Daily Work and Performance counts update from submitted mappings automatically.</li></ol><p className="fine">Approving the first strategy sets the start date for candidate tracking, US Eastern. Prior manual records remain historical. Adding a LinkedIn URL records a reference; the app does not scrape LinkedIn or send candidates to RecruitCRM.</p></details>
 <div className="sheet-toolbar"><label>Role<select value={role} disabled={!!edit||briefDirty} onChange={e=>{setRole(e.target.value);setCategory('');}}><option value="">{view==='Role repository'?'Choose a role':'All roles'}</option>{searches.map(s=><option key={s.id} value={s.id}>{s.client} — {s.title}</option>)}</select></label><label>Find<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Company, candidate or role"/></label><label>Team<select value={team} onChange={e=>setTeam(e.target.value)}><option value="">All teams</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Person<select value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Everyone</option>{researchers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Strategy subcategory<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All subcategories</option>{[...new Set(records.filter(r=>r.kind==='target'&&(!role||r.role_id===role)).map(r=>r.category).filter(Boolean))].sort().map(c=><option key={c}>{c}</option>)}</select></label><label>Status<select value={stage} onChange={e=>setStage(e.target.value)}><option value="">All statuses</option>{['Not started','In progress','Partially mapped','Completed','No relevant talent','Blocked','Revisit required','Draft','Peer review','Partner review','Approved','Rejected','Hold','Needs information'].map(s=><option key={s}>{s}</option>)}</select></label></div>
 {error&&!edit&&<p className="error" role="alert">{error}</p>}
 {hasRole(actor,'researcher')&&(mine||view==='Role repository'&&tab==='Candidate mappings')&&<div className="row-actions"><button className="primary" onClick={()=>start({action:'mapping-add',role_id:role})}>Add mapping</button><span className="fine">Add a LinkedIn candidate, choose the role and save your mapping.</span></div>}
 {mine&&<section className="panel"><h2>My planned work</h2><div className="sheet-scroll"><table className="sheet-table"><thead><tr><th>Date</th><th>Role</th><th>Team approval target</th><th>My submitted / approved</th></tr></thead><tbody>{data.assignments.filter((a:R)=>(!role||a.search_id===role)&&(!team||a.team_id===team)&&a.work_date>=new Date().toLocaleDateString('en-CA')&&data.entries.some((e:R)=>e.assignment_id===a.id&&e.staff_id===actor.staffId)).map((a:R)=>{const ms=records.filter(m=>m.kind==='mapping'&&m.role_id===a.search_id&&m.team_id===a.team_id&&m.mapper_id===actor.id&&m.work_date===a.work_date);return <tr key={a.id}><td>{a.work_date}</td><td>{search(a.search_id)?.title}</td><td>{a.target??'—'}</td><td>{ms.length} / {ms.filter(m=>m.status==='Approved').length}</td></tr>;})}</tbody></table></div></section>}
 {view==='Role repository'&&role&&<><p className="fine">Engagement partner: <strong>{search(role)?.partner||'Not assigned — set in Searches or Integrations'}</strong></p><div className="research-tabs">{['Role brief','Search strategy','Target companies','Candidate mappings','Results'].map(t=><button className={tab===t?'primary':''} key={t} onClick={()=>{if(t===tab)return;if(briefDirty&&!confirm('Discard unsaved role-page changes?'))return;setBriefDirty(false);setTab(t);setStage('');}}>{t}</button>)}</div></>}
 {view==='Role repository'&&!role?<section className="panel"><h2>One repository for each role</h2><p>Choose a role to define its brief and strategy, list target companies, assign research and review candidate mappings.</p></section>:<>
 {(tab==='Results'&&view==='Role repository')&&<section className="panel"><h2>Candidate-derived results</h2><div className="metrics">{[['Submitted',total.length],['Unique people',new Set(total.map(m=>m.candidate_id)).size],['Approved',approved.length],['Peer approval / decided',ratio(total.filter(m=>m.peer_decision==='Approve').length,total.filter(m=>['Approve','Reject'].includes(m.peer_decision)).length)],['Partner approval / decided',ratio(approved.length,decided.length)],['Awaiting review',pending.length],['Rework / hold',total.filter(m=>['Needs information','Hold'].includes(m.status)).length]].map(([k,v])=><div className="metric" key={k}><p>{k}</p><strong>{v}</strong></div>)}</div><p className="fine">Counts exclude drafts and count resubmissions once. Review waiting is elapsed calendar time, not research effort. Daily targets and mapped/peer/partner totals also appear in Daily Work and the weekly plan.</p>
 <div className="sheet-scroll"><table className="sheet-table"><thead><tr><th>Stage</th><th>Waiting</th><th>Oldest wait</th><th>Average review turnaround</th></tr></thead><tbody>{['Peer review','Partner review'].map(st=>{const q=pending.filter(m=>m.status===st),es=events.filter(e=>e.action==='mapping-review'&&e.data.before?.status===st&&total.some(m=>m.id===e.record_id));return <tr key={st}><td>{st}</td><td>{q.length}</td><td>{q.length?Math.max(...q.map(m=>days(m.stage_at)))+' days':'—'}</td><td>{es.length?(es.reduce((n,e)=>n+(e.data.after?.last_review_hours||0),0)/es.length).toFixed(1)+' hours':'—'}</td></tr>;})}</tbody></table></div></section>}
 {view==='Role repository'&&tab==='Role brief'&&<RoleBriefEditor key={role} data={data} role={role} manager={manager} api={api} reload={reload} onDirty={setBriefDirty}/>}
 {view==='Role repository'&&tab==='Search strategy'&&document('strategy')}
 {(mine||view==='Role repository'&&tab==='Target companies')&&<section className="panel"><div className="section-head"><div><h2>{mine?'My company assignments':'Target companies'}</h2><p className="fine">Complete the agreed scope before marking a company complete—even when it yields no candidates.</p></div>{role&&manager&&onCompanies&&<button className="primary" onClick={()=>onCompanies(role)}>Find & add companies</button>}{role&&(manager||hasRole(actor,'researcher'))&&<button className="primary" onClick={()=>start({action:'company-save',role_id:role,priority:'',team_id:'',owner_id:''})}>Create new target company</button>}</div>{manager&&role&&<div className="sheet-toolbar"><label>Research wave<input type="number" min={1} max={99} value={wave} onChange={e=>setWave(e.target.value)}/></label><button disabled={busy||!targets.some(t=>targetChecked.includes(t.id))} onClick={()=>act({action:'target-waves',wave,items:targets.filter(t=>targetChecked.includes(t.id)).map(t=>({id:t.id,version:t.version}))})}>Set wave for selected</button><span className="fine">Work through wave 1 first, then wave 2. Waves guide sequencing; they do not lock later research.</span></div>}{targetTable()}</section>}
 {(mine||view==='Role repository'&&tab==='Candidate mappings')&&<section className="panel"><h2>{mine?'My drafts, reviews and returned work':'Candidate mappings'}</h2><div className="research-actions">{(hasRole(actor,'researcher')||canPartnerReview(actor))&&<><button disabled={busy||!mappings.some(m=>checked.includes(m.id))} onClick={()=>act({action:'mapping-batch',operation:'mapping-submit',items:mappings.filter(m=>checked.includes(m.id)).map(m=>({id:m.id,version:m.version}))})}>Submit selected</button><button disabled={busy||!mappings.some(m=>checked.includes(m.id))} onClick={()=>start({action:'mapping-batch',operation:'mapping-review',items:mappings.filter(m=>checked.includes(m.id)).map(m=>({id:m.id,version:m.version})),decision:'Approve'})}>Review selected</button><span className="fine">Only visible selected rows are included. A permission or version conflict saves none.</span></>}</div>{mappingTable()}</section>}
 </>}
 {isPlan&&view==='Workflow Monitor'&&<p className="fine">Set teammate reviewer pairings in the Teams tab. Pending reviews can be reassigned on each mapping.</p>}
 {detail&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Mapping details"><div className="section-head"><h2>{detail.name}</h2><button onClick={()=>setDetail(null)}>Close</button></div><p>{detail.title} · {detail.company}</p><a href={detail.url} target="_blank" rel="noreferrer">LinkedIn profile</a><h3>Fit rationale</h3><p className="document-text">{detail.rationale}</p><p>Current status: {detail.status}</p>{detail.last_feedback&&<p>Feedback: {detail.last_feedback}</p>}<h3>Review and change history</h3>{events.filter(e=>e.record_id===detail.id).map(e=><article key={e.id}><strong>{e.action} {e.data.decision||''}</strong><p>{name(e.actor)} · {new Date(e.created_at).toLocaleString()}</p><p>{e.data.reason} {e.data.notes}</p>{e.data.before?.rationale&&<details><summary>Rationale at this step</summary><p>{e.data.before.rationale}</p></details>}</article>)}</section></div>}
 {edit?.action==='mapping-add'&&<MappingForm data={data} api={api} reload={reload} initialRole={edit.role_id} targetId={edit.target_id} onClose={()=>setEdit(null)}/>}
 {edit&&edit.action!=='mapping-add'&&<div className="modal-backdrop"><section className="modal research-modal" role="dialog" aria-modal="true" aria-label="Edit research record"><div className="section-head"><h2>{({'brief-save':'Role brief draft','strategy-save':'Search strategy draft','target-assign':'Assign company researcher','company-save':'Target company','company-progress':'Company coverage','mapping-add':'Add candidate mappings','mapping-edit':'Edit fit rationale','mapping-review':'Review candidate','mapping-reassign':'Reassign peer review','mapping-reopen':'Reopen mapping','team-reviewer':'Designated peer reviewer','brief-publish':'Publish role page','mapping-batch':'Review selected mappings','strategy-approve':'Start candidate tracking'} as R)[edit.action]}</h2><button disabled={busy} onClick={()=>{if(confirm('Discard this open form?'))setEdit(null);}}>Cancel</button></div><form onSubmit={e=>{e.preventDefault();const b={...edit};act(b);}}>
 {['brief-save','strategy-save'].includes(edit.action)&&<><p>{edit.action==='brief-save'?'Write the candidate/client-safe description here. Keep confidential strategy in the Search strategy tab.':'Include objectives, archetypes, target titles and categories, methods, effort split, geography, exclusions, assumptions and risks. On first approval, choose the date when candidate tracking begins. Earlier manual output is preserved.'}</p><label>Content<textarea required rows={15} value={edit.content||''} onChange={e=>setEdit({...edit,content:e.target.value})}/></label></>}
 {edit.action==='strategy-approve'&&<><p>Choose the first day for candidate-derived output (US Eastern). Earlier manual records are preserved. If this role already has manual output today, choose a later date. Researchers can save drafts now, but submit only from the start date.</p><Input label="Candidate tracking start date" k="cutover" type="date" edit={edit} setEdit={setEdit}/></>}
 {edit.action==='brief-publish'&&<p>This creates a link anyone holding it can read. Only approved brief version {edit.revision} is shared. Existing links are revoked when you publish again. Internal strategy, candidates, and notes remain private.</p>}
 {edit.action==='target-assign'&&<><p><strong>{edit.name}</strong> · {search(edit.role_id)?.title}</p><label>Team<select value={edit.team_id||''} onChange={e=>setEdit({...edit,team_id:e.target.value,owner_id:''})}><option value="">No team assigned</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><People label="Researcher responsible for this company" field="owner_id" edit={edit} setEdit={setEdit} people={researchers.filter(p=>data.team_members.some((m:R)=>m.team_id===edit.team_id&&m.staff_id===p.staff_id))}/><p className="fine">Choose the team first, then an active researcher in that team. Assigning a team alone does not assign an individual researcher. Existing candidate mappings keep their original mapper and reviewer.</p></>}
 {edit.action==='company-save'&&<>{!edit.id&&<label>Choose from company universe (optional)<select value={edit.company_id||''} onChange={e=>setEdit({...edit,company_id:e.target.value,name:byId(e.target.value)?.name||''})}><option value="">Enter a new company below</option>{records.filter(r=>r.kind==='company').sort((a,b)=>a.name.localeCompare(b.name)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<Input label="Company name" k="name" edit={edit} setEdit={setEdit}/><label>Team (optional)<select value={edit.team_id||''} onChange={e=>setEdit({...edit,team_id:e.target.value,owner_id:''})}><option value="">Choose team</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{(isPlan||hasRole(actor,'partner')&&search(edit.role_id)?.partner_id===actor.id)&&<People label="Researcher" field="owner_id" edit={edit} setEdit={setEdit} people={researchers.filter(p=>data.team_members.some((m:R)=>m.team_id===edit.team_id&&m.staff_id===p.staff_id))}/>}<label>Priority<select value={edit.priority||''} onChange={e=>setEdit({...edit,priority:e.target.value})}><option value="">No priority</option>{['High','Normal','Low'].map(p=><option key={p}>{p}</option>)}</select></label><Input label="Research wave (1 first, 2 next…)" k="wave" type="number" edit={edit} setEdit={setEdit} optional/><Input label="Expected talent (optional)" k="expected" type="number" edit={edit} setEdit={setEdit} optional/><Input label="Due date (optional)" k="due" type="date" edit={edit} setEdit={setEdit} optional/><Input label="Strategy subcategory (optional)" k="category" edit={edit} setEdit={setEdit} optional/><Input label="Research scope (optional)" k="scope" edit={edit} setEdit={setEdit} optional/><Input label="Target titles (optional)" k="target_titles" edit={edit} setEdit={setEdit} optional/></>}
 {edit.action==='company-progress'&&<><label>Coverage status<select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}>{['Not started','In progress','Partially mapped','Completed','No relevant talent','Blocked','Revisit required'].map(s=><option key={s}>{s}</option>)}</select></label><Input label="Coverage notes or blocker" k="notes" edit={edit} setEdit={setEdit}/></>}
 {edit.action==='mapping-edit'&&<Input label="Fit rationale / additional evidence" k="rationale" edit={edit} setEdit={setEdit}/>}
 {(edit.action==='mapping-review'||edit.action==='mapping-batch')&&<><p>{edit.items&&`${edit.items.length} selected mappings. The same decision and comments apply to all.`}<a href={edit.url} target="_blank" rel="noreferrer">{edit.name}</a> · {edit.title} · {edit.company}</p><p className="document-text">{edit.rationale}</p>{edit.last_feedback&&<p>Previous feedback: {edit.last_feedback}</p>}<label>Decision<select value={edit.decision} onChange={e=>setEdit({...edit,decision:e.target.value})}>{['Approve','Reject','Hold','Needs information'].map(s=><option key={s}>{s}</option>)}</select></label>{edit.decision==='Reject'&&<label>Rejection reason<select required value={edit.reason||''} onChange={e=>setEdit({...edit,reason:e.target.value})}><option value="">Choose reason</option>{['Wrong level','Wrong function','Insufficient scale','Industry mismatch','Geography mismatch','Insufficient evidence','Compensation mismatch','Other'].map(s=><option key={s}>{s}</option>)}</select></label>}<Input label="Comments / requested information" k="notes" edit={edit} setEdit={setEdit} optional={edit.decision==='Approve'}/></>}
 {['mapping-reassign','team-reviewer'].includes(edit.action)&&<People label="Peer reviewer" field="reviewer_id" edit={edit} setEdit={setEdit} people={researchers.filter(p=>p.id!==edit.mapper_id&&p.staff_id!==edit.staff_id&&data.team_members.some((m:R)=>m.team_id===edit.team_id&&m.staff_id===p.staff_id))}/>}
 {edit.action==='mapping-reopen'&&<Input label="Reason for reopening" k="notes" edit={edit} setEdit={setEdit}/>}
 {error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Saving…':edit.action==='brief-publish'?'Publish approved brief':'Save'}</button></form></section></div>}
 </div>;
}
function Input({label,k,edit,setEdit,type='text',optional=false}:any){return <label>{label}<input required={!optional} type={type} min={type==='number'?0:undefined} readOnly={k==='name'&&edit.action==='company-save'&&!!(edit.id||edit.company_id)} value={edit[k]??''} onChange={e=>setEdit({...edit,[k]:e.target.value})}/></label>;}
function People({label,field,edit,setEdit,people}:any){return <label>{label}<select value={edit[field]||''} onChange={e=>setEdit({...edit,[field]:e.target.value})}><option value="">Unassigned</option>{people.map((p:R)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>;}
