import React,{useId,useState} from 'react';
type Role=Record<string,any>;
export const roleDisplayId=(r:Role)=>String(r.external_id||r.id);
export function matchingRoles(roles:Role[],query:string,sort:string){
 const terms=query.trim().toLowerCase().split(/\s+/).filter(Boolean);
 const compare=(a:string,b:string)=>a.localeCompare(b,undefined,{numeric:true,sensitivity:'base'});
 return roles.filter(r=>terms.every(t=>[roleDisplayId(r),r.client,r.title].join(' ').toLowerCase().includes(t))).sort((a,b)=>compare(sort==='company'?a.client||'':roleDisplayId(a),sort==='company'?b.client||'':roleDisplayId(b))||compare(a.title||'',b.title||'')||compare(String(a.id),String(b.id)));
}
export function RolePicker({searches,value,onChange,disabled,allowAll}:{searches:Role[];value:string;onChange:(id:string)=>void;disabled?:boolean;allowAll?:boolean}){
 const [query,setQuery]=useState(''),[open,setOpen]=useState(false),[sort,setSort]=useState('company'),[active,setActive]=useState(0),id=useId();
 const label=(r:Role)=>`${roleDisplayId(r)} · ${r.client} — ${r.title}`,selected=searches.find(r=>r.id===value),results=matchingRoles(searches,query,sort);
 const choose=(r:Role)=>{onChange(r.id);setOpen(false);setQuery('');setActive(0);};
 return <div className="role-picker" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node)){setOpen(false);setQuery('');}}}><div className="role-picker-controls"><label htmlFor={id}>Role<input id={id} role="combobox" autoComplete="off" disabled={disabled} aria-expanded={open} aria-controls={id+'-options'} aria-autocomplete="list" aria-activedescendant={open&&results[active]?id+'-'+active:undefined} placeholder="Type role ID, company or role name" value={open?query:selected?label(selected):''} onFocus={()=>{setOpen(true);setQuery('');setActive(0);}} onChange={e=>{setQuery(e.target.value);setOpen(true);setActive(0);}} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);setQuery('');}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setOpen(true);setActive(n=>Math.max(0,Math.min(results.length-1,n+(e.key==='ArrowDown'?1:-1))));}else if(e.key==='Enter'&&open&&results[active]){e.preventDefault();choose(results[active]);}}}/></label><label>Sort roles<select disabled={disabled} value={sort} onChange={e=>{setSort(e.target.value);setActive(0);setOpen(true);}}><option value="company">Company name</option><option value="id">Role ID</option></select></label>{allowAll&&value&&<button disabled={disabled} onClick={()=>{onChange('');setQuery('');setOpen(false);}}>All roles</button>}</div>{open&&!disabled&&<div className="role-picker-menu"><small>{results.length} matching roles · CRM ID shown when available</small><div id={id+'-options'} role="listbox" aria-label="Roles">{results.map((r,i)=><button type="button" role="option" id={id+'-'+i} aria-selected={r.id===value} className={i===active?'highlighted':''} key={r.id} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(r)}><strong>{roleDisplayId(r)}</strong><span>{r.client} — {r.title}</span></button>)}</div>{!results.length&&<p>No roles match. Try another ID, company or role name.</p>}</div>}</div>;
}
