import React,{useEffect,useState} from 'react';
import {videoEmbed,sectionsFromText} from './role-page';
type R=Record<string,any>;
export function RolePageView({brief,preview=false}:{brief:R;preview?:boolean}) {const p=brief.page||{},sections=p.sections||sectionsFromText(brief.content||''),[play,setPlay]=useState(false);return <article className="role-page"><div className="role-masthead"><img src="/brand/xqtiv-logo.svg" alt="XQtiv"/><span>{preview?'Internal preview':`Prepared for ${brief.candidate_name||'you'}`} · Confidential</span></div><header className="role-hero"><p className="role-kicker">A LEADERSHIP OPPORTUNITY</p><h1>{brief.title}</h1><h2>{brief.client}</h2>{p.subtitle&&<p>{p.subtitle}</p>}{p.location&&<p className="role-kicker">{p.location}</p>}<div className="role-facts">{[['Reports to',p.reports_to],['Team',p.team],['Mandate',p.mandate],['Search led by',p.partner_name]].filter(x=>x[1]).map(([k,v])=><div key={k}><small>{k}</small><strong>{v}</strong></div>)}</div><div className="role-buttons">{p.video&&<a href="#partner-note">Watch the partner note</a>}{p.booking_url&&<a href={p.booking_url} target="_blank" rel="noreferrer">Arrange a conversation ↗</a>}</div></header>{(p.video||p.partner_note)&&<section id="partner-note"><p className="role-kicker">FROM YOUR SEARCH PARTNER</p><h2>{p.partner_name?`A note from ${p.partner_name}`:'Why this opportunity matters'}</h2><div className="partner-note">{p.video&&<div className="partner-video">{play?<iframe title="Partner explains the role" src={videoEmbed(p.video)} allow="fullscreen; picture-in-picture" referrerPolicy="no-referrer" sandbox="allow-scripts allow-same-origin allow-presentation"/>:<button onClick={()=>setPlay(true)}>▶ Watch partner video<small>Loads video from {new URL(p.video).hostname}</small></button>}</div>}{p.partner_note&&<p className="role-prose">{p.partner_note}</p>}</div></section>}{sections.map((s:R,i:number)=><section key={i} id={'section-'+i}><p className="role-kicker">{String(i+1).padStart(2,'0')} / THE OPPORTUNITY</p><h2>{s.heading}</h2><div className="role-prose">{s.body.split(/\n\s*\n/).map((paragraph:string,j:number)=><p key={j}>{paragraph}</p>)}</div></section>)}{p.booking_url&&<section className="role-contact"><h2>Let’s explore the opportunity.</h2><p>A confidential conversation with your search partner.</p><a href={p.booking_url} target="_blank" rel="noreferrer">Arrange a conversation ↗</a></section>}<footer>Prepared by XQtiv · Approved version {brief.revision||'Preview'}<br/>Confidential. Shared for your consideration; please do not distribute.</footer></article>;}
export function CandidateRolePage(){const [brief,setBrief]=useState<R|null>(null),[token]=useState(()=>location.hash.slice(1)),[code,setCode]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const workspace=new URLSearchParams(location.search).get('workspace')||'';
 async function call(path:string,b?:R){const r=await fetch('/api/candidate/'+path+'?workspace='+encodeURIComponent(workspace),b?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...b,workspace,token})}:{});const result=await r.json() as R;if(!r.ok)throw new Error(result.error||'Unable to open invitation.');return result;}
 useEffect(()=>{history.replaceState(null,'',location.pathname+location.search);call('page',{}).then(setBrief).catch(()=>{});},[]);
 if(brief)return <RolePageView brief={brief}/>;
 return <main className="candidate-gate"><img src="/brand/xqtiv-logo.svg" alt="XQtiv"/><h1>Your confidential role invitation</h1><p>Verify access using a code sent to the email address your partner invited.</p>{!token?<p>Please open the original invitation link from your email.</p>:<><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await call('code',{});setSent(true);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>{sent?'Send another code':'Email me a verification code'}</button>{sent&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await call('verify',{code});setBrief(await call('page',{}));setCode('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><label>Six-digit code<input required pattern="[0-9]{6}" maxLength={6} inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)}/></label><button disabled={busy}>View role page</button><p>Codes expire in 10 minutes. Wait one minute between requests.</p></form>}</>}{error&&<p role="alert" className="error">{error}</p>}</main>;
}
