import {SortableTable} from './SortableTable';
import {displayDate,displayDateTime} from './dates';
import React,{useEffect,useState} from 'react';
import {RolePageView} from './RolePageView';
import {sectionsFromText} from './role-page';
type R=Record<string,any>;
export function RoleBriefEditor({data,role,manager,api,reload,onDirty}:{data:R;role:string;manager:boolean;api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;onDirty:(v:boolean)=>void}){
 const records:R[]=data.research?.records||[],doc=records.find(r=>r.kind==='brief'&&r.role_id===role),search=data.searches.find((s:R)=>s.id===role),candidates=records.filter(r=>r.kind==='mapping'&&r.role_id===role);
 const initial=()=>doc?.draft_page||{title:'',client:'',origin:'manual',sections:doc?.draft?sectionsFromText(doc.draft):[{heading:'',body:''}]};
 const canUpload=manager||records.some(t=>t.kind==='task'&&t.role_id===role&&t.owner_id===data.actor.id&&t.task_type==='Role brief'&&t.status!=='Cancelled');
 const [files,setFiles]=useState<R[]>([]),[webPage,setWebPage]=useState(false);
 useEffect(()=>{api('research',{action:'brief-file-list',role_id:role}).then(setFiles).catch(e=>setError(e.message));},[role]);
 async function saveFile(file:File){setBusy(true);setError('');try{if(file.size>5*1024*1024)throw new Error('Upload a file up to 5 MB.');const base64=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});await api('research',{action:'brief-file-save',role_id:role,name:file.name,base64});setFiles(await api('research',{action:'brief-file-list',role_id:role}));setNotice('Original document saved. Publishing a webpage is optional.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function downloadFile(f:R){setBusy(true);try{const r=await api('research',{action:'brief-file-read',role_id:role,file_id:f.id});const u=URL.createObjectURL(new Blob([Uint8Array.from(atob(r.base64),(c:string)=>c.charCodeAt(0))],{type:r.mime}));const a=document.createElement('a');a.href=u;a.download=r.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const [page,setPage]=useState<R>(initial),[editing,setEditing]=useState(false),[preview,setPreview]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[invites,setInvites]=useState<R[]>([]),[candidate,setCandidate]=useState(''),[email,setEmail]=useState(''),[days,setDays]=useState('14');
 useEffect(()=>{onDirty(editing||busy);const f=(e:BeforeUnloadEvent)=>{if(editing||busy){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',f);return()=>{onDirty(false);window.removeEventListener('beforeunload',f);};},[editing,busy]);
 const loadInvites=async()=>{if(manager)setInvites(await api('candidate-invites',{action:'list',role_id:role}));};
 useEffect(()=>{let active=true;if(manager)api('candidate-invites',{action:'list',role_id:role}).then(v=>{if(active)setInvites(v);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[role,manager]);
 async function action(action:string,extra:R={}) {setBusy(true);setError('');setNotice('');try{await api('research',{action,id:doc?.id,version:doc?.version,role_id:role,...extra});await reload();setEditing(false);if(action==='brief-unpublish')await loadInvites();setNotice(action==='brief-save'?'Draft saved. Use Publish page when it is ready to share.':action==='brief-release'?'Page saved, approved and published. Use Send secure invitation below to share it with a candidate.':'Updated.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const showPage=editing?page:doc?.draft_page,hasContent=!!(showPage?.title||showPage?.sections?.some((s:R)=>s.body||s.heading)||doc?.draft);
 async function upload(file:File){if(editing&&!confirm('Replace your unsaved page with this document?'))return;setBusy(true);setError('');setNotice('');try{const {documentPage}=await import('./document-upload');const generated=await documentPage(file);setPage(generated);setEditing(true);setPreview(true);setNotice('Page generated from '+file.name+'. All previous page fields were cleared. Review below, then Save draft or Publish page.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const update=(k:string,v:any)=>{setPage({...showPage,[k]:v});setEditing(true);};
 return <section className="panel role-brief-workspace"><div className="section-head"><div><h2>Role brief</h2><p>Keep the original PDF or Word document. A candidate webpage is optional.</p></div></div>
 <div className="brief-actionbar">{canUpload&&<label className="brief-upload">Save original PDF / Word<input type="file" aria-label="Save original brief document" accept=".pdf,.docx,.doc" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)saveFile(f);e.target.value='';}}/></label>}<button onClick={()=>setWebPage(!webPage)}>{webPage?'Close webpage editor':'Optional: create / edit webpage'}</button></div>
 {files.map(f=><div className="work-row" key={f.id}><strong>{f.name}</strong><button disabled={busy} onClick={()=>downloadFile(f)}>Download original</button></div>)}
 {!webPage&&<>{error&&<p className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}</>}
 {webPage&&<><div className="brief-actionbar" aria-label="Role page actions">
 {manager&&<label className="brief-upload">Upload PDF / Word<input aria-label="Upload PDF or Word document" type="file" accept=".pdf,.docx" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.target.value='';}}/></label>}
 <button disabled={!hasContent||busy} onClick={()=>setPreview(!preview)}>{preview?'Hide preview':'Preview page'}</button>
 {manager&&<><button disabled={!hasContent||busy||!editing} onClick={()=>action('brief-save',{page})}>Save draft</button><button className="primary" disabled={!hasContent||busy||showPage?.origin!=='document'} onClick={()=>{if(confirm('Save, approve and publish this page for invited candidates?'))action('brief-release',{page:showPage||initial()});}}>Publish page</button></>}
 {editing&&<button disabled={busy} onClick={()=>{if(confirm('Discard unsaved page changes?')){setEditing(false);setPage(initial());}}}>Discard changes</button>}
 <span className="fine">{busy?'Processing…':editing?'Unsaved changes':doc?'Saved':'No document uploaded'}</span></div>
 <p className="fine">Published version: {doc?.published_revision||'Not published'}. Publishing keeps the page private; share it through the candidate invitations below.</p>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 {!hasContent&&<div className="brief-empty"><h3>Start with your role document</h3><p>Upload a selectable-text PDF or Word .docx. The app uses the document’s title, headings, paragraphs and lists to build the page. No role metadata or content from previous uploads is added.</p><p className="fine">Up to 10 MB. Scanned PDFs require OCR first.</p></div>}
 {doc?.draft_page?.origin!=='document'&&doc?.draft&&!editing&&<p className="notice">This page was made with the earlier converter. Upload the original document again to rebuild it without inherited role fields and enable publishing.</p>}
 {hasContent&&<><div className="brief-source"><strong>{showPage?.source_name||'Earlier draft'}</strong>{showPage?.source_pages?` · ${showPage.source_pages} document page${showPage.source_pages===1?'':'s'}`:''}{showPage?.origin==='document'&&<span> · Document wording only</span>}</div>
 {manager&&<details className="brief-options"><summary>Optional video, booking link and layout adjustments</summary><div className="role-editor-grid"><label>Partner video URL<input value={showPage?.video||''} onChange={e=>update('video',e.target.value)} placeholder="YouTube or Vimeo link"/></label><label>Booking URL<input value={showPage?.booking_url||''} onChange={e=>update('booking_url',e.target.value)} placeholder="https://…"/></label></div><p className="fine">Video privacy is controlled separately by its host. Uploading a new document clears these links, too.</p>
 <label>Page title<input value={showPage?.title||''} onChange={e=>update('title',e.target.value)}/></label>
 <p className="fine">For document pages, use wording from the uploaded file. Upload a revised document to change the content.</p>
 {(showPage?.sections||[]).map((s:R,i:number)=><details className="role-editor-section" key={i}><summary>{s.heading||'Introduction'}{s.source_page?` · source page ${s.source_page}`:''}</summary><label>Heading<input value={s.heading} onChange={e=>update('sections',showPage.sections.map((v:R,n:number)=>n===i?{...v,heading:e.target.value}:v))}/></label><label>Content<textarea rows={6} value={s.body} onChange={e=>update('sections',showPage.sections.map((v:R,n:number)=>n===i?{...v,body:e.target.value}:v))}/></label></details>)}</details>}
 {showPage?.source_text&&<details className="brief-options"><summary>Compare with extracted document text</summary><pre className="brief-source-text">{showPage.source_text}</pre></details>}
 {preview&&<div className="role-preview"><RolePageView preview brief={{title:showPage?.title||'',client:showPage?.client||'',page:showPage,content:doc?.draft,revision:'Draft'}}/></div>}</>}
 {manager&&doc?.published_revision&&<div className="research-actions"><button disabled={busy} onClick={()=>{if(confirm('Unpublish and revoke all candidate access?'))action('brief-unpublish');}}>Unpublish and revoke access</button><span className="fine">There is no anonymous public link. Each candidate receives their own secure invitation.</span></div>}
 {manager&&!editing&&<><h3>Candidate invitations</h3><p className="fine">Select a mapped candidate and confirm their email. Re-inviting the same candidate revokes their previous invitation. Invitations show the latest published version.</p><form onSubmit={async e=>{e.preventDefault();if(!confirm('Send a role invitation to '+email+'?'))return;setBusy(true);setError('');setNotice('');try{const r=await api('candidate-invites',{action:'send',role_id:role,candidate_id:candidate,email,days});await loadInvites();setNotice(r.emailStatus==='accepted'?'Invitation accepted by the email provider.':'Delivery could not be confirmed. Check the address, then re-invite if needed.');setEmail('');setCandidate('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><div className="sheet-toolbar"><label>Candidate<select required value={candidate} onChange={e=>setCandidate(e.target.value)}><option value="">Select candidate</option>{candidates.map(c=><option key={c.candidate_id} value={c.candidate_id}>{c.name} — {c.company}</option>)}</select></label><label>Candidate email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Expires in days<input type="number" min={1} max={30} required value={days} onChange={e=>setDays(e.target.value)}/></label><button className="primary" disabled={busy||!doc?.published_revision}>Send secure invitation</button></div></form><div className="sheet-scroll"><SortableTable stateKey="RoleBriefEditor.table1" className="sheet-table"><thead><tr><th>Candidate</th><th>Email</th><th>Access expires</th><th>Status</th><th>Action</th></tr></thead><tbody>{invites.map(i=><tr key={i.id}><td>{i.name}</td><td>{i.email}</td><td>{new Date(i.expires).toLocaleString()}</td><td>{i.revoked?'Revoked':i.expires<Date.now()?'Expired':'Active'}</td><td>{!i.revoked&&<button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await api('candidate-invites',{action:'revoke',id:i.id});await loadInvites();}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>Revoke</button>}</td></tr>)}</tbody></SortableTable></div></>}
 {doc&&<details><summary>Version history</summary>{(data.research?.events||[]).filter((e:R)=>e.record_id===doc.id).map((e:R)=><details key={e.id}><summary>{displayDateTime(e.created_at)} · {e.action}</summary><p className="document-text">{e.data.after?.active||e.data.after?.draft}</p></details>)}</details>}</>}</section>;
}
