import React,{useState} from 'react';
import {matchingRoles,roleDisplayId} from './RolePicker';
type R=Record<string,any>;
export function RoleMultiFilter({searches,value,onChange,disabled=false}:{searches:R[];value:string[]|null;onChange:(ids:string[]|null)=>void;disabled?:boolean}) {
 const [query,setQuery]=useState('');
 const shown=matchingRoles(searches,query,'company'),chosen=new Set(value===null?searches.map(s=>s.id):value);
 const toggle=(ids:string[],checked:boolean)=>{const next=new Set(chosen);ids.forEach(id=>checked?next.add(id):next.delete(id));onChange([...next]);};
 const clients=[...new Set(shown.map(s=>s.client||'No client'))];
 return <div className="role-multi-filter"><span className="filter-label">Roles</span><details className="column-filter"><summary aria-label="Filter roles" onClick={e=>{if(disabled)e.preventDefault();}}>{value===null?'All roles':`${value.length} roles selected`} ▾</summary><div className="filter-menu"><input disabled={disabled} type="search" aria-label="Find roles or clients" placeholder="Type client, role or role ID" value={query} onChange={e=>setQuery(e.target.value)}/><div className="row-actions"><button disabled={disabled} onClick={()=>onChange(null)}>All roles</button><button disabled={disabled} onClick={()=>onChange([])}>None</button><button disabled={disabled||!shown.length} onClick={()=>onChange(shown.map(s=>s.id))}>Show matching only</button></div><div className="filter-options">{clients.map(client=>{const roles=shown.filter(s=>(s.client||'No client')===client);return <div key={client}><label className="checkbox role-client"><input type="checkbox" disabled={disabled} checked={roles.every(s=>chosen.has(s.id))} onChange={e=>toggle(roles.map(s=>s.id),e.target.checked)}/><strong>{client}</strong></label>{roles.map(s=><label className="checkbox role-choice" key={s.id}><input type="checkbox" disabled={disabled} checked={chosen.has(s.id)} onChange={e=>toggle([s.id],e.target.checked)}/><span><small>{roleDisplayId(s)}</small> {s.title}</span></label>)}</div>})}{!shown.length&&<p>No matching roles.</p>}</div></div></details></div>;
}
