import React,{useEffect,useState} from 'react';
import {videoEmbed,sectionsFromText} from './role-page';
type R=Record<string,any>;
export function RolePageView({brief,preview=false}:{brief:R;preview?:boolean}) {
 const p=brief.page||{},documentOnly=p.origin==='document',sections=p.sections||sectionsFromText(brief.content||''),[play,setPlay]=useState(false);
 const title=documentOnly?p.title:(p.title||brief.title),client=documentOnly?p.client:(p.client||brief.client);
 return <article className="role-page"><div className="role-masthead"><img src="/brand/xqtiv-logo.svg" alt="XQtiv"/><span>{preview?'Internal preview':`Prepared for ${brief.candidate_name||'you'}`} · Confidential</span></div>
 <header className="role-hero">{title&&<h1>{title}</h1>}{client&&<h2>{client}</h2>}{p.subtitle&&<p>{p.subtitle}</p>}{p.location&&<p className="role-kicker">{p.location}</p>}
 <div className="role-facts">{[['Reports to',p.reports_to],['Team',p.team],['Mandate',p.mandate],['Search led by',p.partner_name]].filter(x=>x[1]).map(([k,v])=><div key={k}><small>{k}</small><strong>{v}</strong></div>)}</div><div className="role-buttons">{p.video&&<a href="#partner-note">Watch partner video</a>}{p.booking_url&&<a href={p.booking_url} target="_blank" rel="noreferrer">Arrange a conversation ↗</a>}</div></header>
 {(p.video||p.partner_note)&&<section id="partner-note">{p.partner_name&&<h2>{p.partner_name}</h2>}<div className="partner-note">{p.video&&<div className="partner-video">{play?<iframe title="Partner video" src={videoEmbed(p.video)} allow="fullscreen; picture-in-picture" referrerPolicy="no-referrer" sandbox="allow-scripts allow-same-origin allow-presentation"/>:<button onClick={()=>setPlay(true)}>▶ Watch partner video<small>Loads video from {new URL(p.video).hostname}</small></button>}</div>}{p.partner_note&&<div className="role-prose"><DocumentBody text={p.partner_note}/></div>}</div></section>}
 {sections.map((s:R,i:number)=><section key={i} id={'section-'+i} className={s.heading?'role-document-section':'role-document-intro'}>{s.heading&&<h2>{s.heading}</h2>}<div className="role-prose"><DocumentBody text={s.body}/></div></section>)}
 {p.booking_url&&<section className="role-contact"><a href={p.booking_url} target="_blank" rel="noreferrer">Arrange a conversation ↗</a></section>}<footer>Prepared by XQtiv · {preview?'Draft preview':'Approved version '+brief.revision}<br/>Confidential. Shared for your consideration; please do not distribute.</footer></article>;
}
function SourceParagraph({text}:{text:string}) {const split=text.indexOf(':');return split>0&&split<65?<><strong>{text.slice(0,split+1)}</strong>{text.slice(split+1)}</>:<>{text}</>;}
export function DocumentBody({text}:{text:string}){
 const paragraphs=String(text||'').split(/\n\s*\n/).filter(Boolean),nodes:React.ReactNode[]=[],list:string[]=[];
 const bullet=/^(?:[•●▪◦‣\-–]|\d+[.)])\s+/;
 const flush=()=>{if(list.length){nodes.push(<ul className={list.length>=4?'role-list-grid':''} key={'list-'+nodes.length}>{list.map((v,i)=><li key={i}><SourceParagraph text={v}/></li>)}</ul>);list.length=0;}};
 for(const p of paragraphs){if(bullet.test(p.trim())){for(const line of p.split(/\n(?=[•●▪◦‣\-–]|\d+[.)]\s)/))list.push(line.trim().replace(bullet,''));}else{flush();nodes.push(<p key={'p-'+nodes.length}><SourceParagraph text={p}/></p>);}}flush();return <>{nodes}</>;
}
export function CandidateRolePage(){const [brief,setBrief]=useState<R|null>(null),[token]=useState(()=>location.hash.slice(1)),[code,setCode]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const workspace=new URLSearchParams(location.search).get('workspace')||'';
 async function call(path:string,b?:R){const r=await fetch('/api/candidate/'+path+'?workspace='+encodeURIComponent(workspace),b?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...b,workspace,token})}:{});const result=await r.json() as R;if(!r.ok)throw new Error(result.error||'Unable to open invitation.');return result;}
 useEffect(()=>{history.replaceState(null,'',location.pathname+location.search);call('page',{}).then(setBrief).catch(()=>{});},[]);
 if(brief)return <RolePageView brief={brief}/>;
 return <main className="candidate-gate"><img src="/brand/xqtiv-logo.svg" alt="XQtiv"/><h1>Your confidential role invitation</h1><p>Verify access using a code sent to the email address your partner invited.</p>{!token?<p>Please open the original invitation link from your email.</p>:<><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await call('code',{});setSent(true);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>{sent?'Send another code':'Email me a verification code'}</button>{sent&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await call('verify',{code});setBrief(await call('page',{}));setCode('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><label>Six-digit code<input required pattern="[0-9]{6}" maxLength={6} inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)}/></label><button disabled={busy}>View role page</button><p>Codes expire in 10 minutes. Wait one minute between requests.</p></form>}</>}{error&&<p role="alert" className="error">{error}</p>}</main>;
}
