import {Check,Minus,PencilSimple,LockSimple} from '@phosphor-icons/react';
import React,{useEffect,useState} from 'react';
import {permissionGroups,activeRoleTemplates as roleTemplates,effectivePermissions,RoleDefinition} from './access-policy';
import {Popup} from './Popup';
export function RolesPanel({api,reload,onDirty,onShowPeople}:{onShowPeople:(role:string)=>void;api:(path:string,body?:unknown)=>Promise<any>;reload:()=>Promise<void>;onDirty:(v:boolean)=>void}){
 const [superAdminUsers,setSuperAdminUsers]=useState(0);
 const [roles,setRoles]=useState<RoleDefinition[]>([]),[loaded,setLoaded]=useState(false),[query,setQuery]=useState(''),[section,setSection]=useState(''),[draft,setDraft]=useState<Partial<RoleDefinition>|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function read(){const r=await api('roles');setRoles(r.roles);setSuperAdminUsers(r.superAdminUsers||0);setLoaded(true);}
 useEffect(()=>{read().catch(e=>setError(e.message));},[]);
 useEffect(()=>{onDirty(!!draft||busy);return()=>onDirty(false);},[!!draft,busy]);
 async function save(action:'save'|'delete'){
  if(action==='delete'&&!confirm(`Delete the role “${draft?.name}”?`))return;
  setBusy(true);setError('');try{await api('roles',{...draft,action});setDraft(null);setMessage(action==='save'?'Role permissions saved. They apply on the next request.':'Role deleted.');await read();await reload();}catch(e:any){setError(e.message);}finally{setBusy(false);}
 }
 const activeRoles=roles.filter(r=>!r.retired),groups=[...new Set(permissionGroups.map(p=>p.group))];
 const permissionsByRole=new Map(activeRoles.map(r=>[r.id,new Set(effectivePermissions([r.id],roles))]));
 const matching=permissionGroups.filter(p=>(!section||p.group===section)&&[p.label,p.description].join(' ').toLowerCase().includes(query.toLowerCase()));
 const marker=(allowed:boolean)=><span className={'permission-mark '+(allowed?'is-allowed':'is-denied')} aria-hidden="true">{allowed?<Check size={13} weight="bold"/>:<Minus size={11}/>}</span>;
 return <section className="panel roles-panel"><div className="section-head"><div><h2>Roles & permissions</h2></div><button className="primary" disabled={!loaded||busy} onClick={()=>{setError('');setDraft({name:'',description:'',permissions:[]});}}>Create role</button></div>
 <div className="role-grid-toolbar"><label className="role-search">Find permission<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search permissions"/></label><label>Section<select value={section} onChange={e=>setSection(e.target.value)}><option value="">All sections</option>{groups.map(g=><option key={g}>{g}</option>)}</select></label><div className="permission-legend"><span>{marker(true)} Allowed</span><span>{marker(false)} Not allowed</span></div></div>
 {error&&!draft&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 {!loaded?<p>Loading roles…</p>:<div className="table-scroll role-permission-grid" tabIndex={0} role="region" aria-label="Role permission comparison"><table className="sheet-table"><thead><tr><th scope="col">Permission</th><th scope="col" className="owner-role"><span className="role-column-name">Super Admin</span><div className="role-header-actions"><button className="role-count-button" title="View people assigned Super Admin" aria-label={`View ${superAdminUsers} people assigned Super Admin`} onClick={()=>onShowPeople('super_admin')}>({superAdminUsers})</button><LockSimple size={12} aria-label="Protected role"/></div></th>{activeRoles.map(r=><th scope="col" key={r.id}><span className="role-column-name">{r.name}</span><div className="role-header-actions"><button className="role-count-button" title={'View people assigned '+r.name} aria-label={`View ${r.users||0} people assigned ${r.name}`} onClick={()=>onShowPeople(r.id)}>({r.users||0})</button><button className="role-edit-button" aria-label={'Edit permissions for '+r.name} onClick={()=>{setError('');setDraft({...r,permissions:[...r.permissions]});}}><PencilSimple size={13}/></button></div></th>)}</tr></thead>{groups.filter(g=>matching.some(p=>p.group===g)).map(group=><tbody key={group}><tr className="permission-group-row"><th scope="rowgroup" colSpan={activeRoles.length+2}><span>{group}</span><small>{matching.filter(p=>p.group===group).length} permissions</small></th></tr>{matching.filter(p=>p.group===group).map(p=><tr className="permission-data-row" key={p.id}><th scope="row" title={p.description}>{p.label}</th><td className="owner-role" aria-label={'Super Admin: Allowed'}>{marker(true)}</td>{activeRoles.map(r=>{const allowed=permissionsByRole.get(r.id)!.has(p.id);return <td key={r.id} title={r.name+' · '+p.label+': '+(allowed?'Allowed':'Not allowed')} aria-label={r.name+': '+(allowed?'Allowed':'Not allowed')}>{marker(allowed)}</td>;})}</tr>)}</tbody>)}</table>{!matching.length&&<p className="sheet-empty">No permissions match. Try another search or section.</p>}</div>}

 {roles.some(r=>r.retired)&&<p className="fine">Retired roles: {roles.filter(r=>r.retired).map(r=>r.name+' ('+(r.users||0)+' people, '+(r.invitations||0)+' invitations)').join('; ')}. Reassign these in People & teams before removal; existing access is retained.</p>}

 
 {draft&&<Popup title={draft.id?'Edit '+draft.name:'Create role'} onClose={()=>{if(!busy&&confirm('Discard unsaved role changes?'))setDraft(null);}}><form className="role-editor" onSubmit={e=>{e.preventDefault();save('save');}}>
 <label>Role name<input autoFocus required maxLength={80} disabled={busy} value={draft.name||''} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>
 <label>Description<input maxLength={500} disabled={busy} value={draft.description||''} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>
 <label>Apply permission template<select disabled={busy} value="" onChange={e=>{const t=roleTemplates.find(t=>t.id===e.target.value);if(t)setDraft({...draft,permissions:[...t.permissions]});}}><option value="">Choose template…</option>{roleTemplates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}<option value="" disabled>Templates replace the selection below</option></select></label>
 {[...new Set(permissionGroups.map(p=>p.group))].map(group=><fieldset key={group} disabled={busy}><legend>{group}</legend>{permissionGroups.filter(p=>p.group===group).map(p=><label className="permission-choice" key={p.id}><input type="checkbox" checked={draft.permissions?.includes(p.id)||false} onChange={e=>setDraft({...draft,permissions:e.target.checked?[...(draft.permissions||[]),p.id]:(draft.permissions||[]).filter(id=>id!==p.id)})}/><span><strong>{p.label}</strong><small>{p.description}</small></span></label>)}</fieldset>)}
 {draft.id&&<p className="fine">Changes affect {draft.users||0} people and {draft.invitations||0} pending invitations using this role.</p>}{error&&<p role="alert" className="error">{error}</p>}
 <div className="row-actions"><button className="primary" disabled={busy}>{busy?'Saving…':'Save role'}</button><button type="button" disabled={busy} onClick={()=>setDraft(null)}>Cancel</button>{draft.id&&<button type="button" disabled={busy||!!draft.users||!!draft.invitations} title={draft.users||draft.invitations?'Reassign people and cancel invitations first':'Delete unused role'} onClick={()=>save('delete')}>Delete role</button>}</div>
 </form></Popup>}
 </section>;
}
