import React,{useEffect,useState} from 'react';
import {RolePageView} from './RolePageView';
import {sectionsFromText} from './role-page';
type R=Record<string,any>;
export function RoleBriefEditor({data,role,manager,api,reload,onDirty}:{data:R;role:string;manager:boolean;api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;onDirty:(v:boolean)=>void}){
 const records:R[]=data.research?.records||[],doc=records.find(r=>r.kind==='brief'&&r.role_id===role),search=data.searches.find((s:R)=>s.id===role),candidates=records.filter(r=>r.kind==='mapping'&&r.role_id===role);
 const initial=()=>doc?.draft_page||{partner_name:search.partner||'',sections:doc?.draft?sectionsFromText(doc.draft):[{heading:'The opportunity',body:''}]};
 const [page,setPage]=useState<R>(initial),[editing,setEditing]=useState(false),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[invites,setInvites]=useState<R[]>([]),[candidate,setCandidate]=useState(''),[email,setEmail]=useState(''),[days,setDays]=useState('14');
 useEffect(()=>{onDirty(editing);const f=(e:BeforeUnloadEvent)=>{if(editing){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',f);return()=>{onDirty(false);window.removeEventListener('beforeunload',f);};},[editing]);
 const loadInvites=async()=>{if(manager)setInvites(await api('candidate-invites',{action:'list',role_id:role}));};
 useEffect(()=>{loadInvites().catch(e=>setError(e.message));},[role,manager]);
 async function action(action:string,extra:R={}) {setBusy(true);setError('');setNotice('');try{await api('research',{action,id:doc?.id,version:doc?.version,role_id:role,...extra});await reload();setEditing(false);if(action==='brief-unpublish')await loadInvites();setNotice(action==='brief-save'?'Draft saved. Review the page, then approve and publish.':action==='brief-publish'?'Approved page published for invited candidates.':'Updated.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const field=(k:string,label:string)=> <label key={k}>{label}<input value={page[k]||''} onChange={e=>setPage({...page,[k]:e.target.value})}/></label>;
 const showPage=editing?page:doc?.draft_page;
 return <section className="panel"><div className="section-head"><div><h2>Candidate role page</h2><p>Upload a Word or PDF, review the generated page, then approve, publish and invite selected candidates.</p></div>{manager&&!editing&&<button onClick={()=>{setPage(initial());setEditing(true);setError('');}}>Edit role page</button>}</div><p className="fine">Draft: {doc?.status||'Not created'} · Approved: {doc?.revision||'—'} · Published: {doc?.published_revision||'—'}. Anonymous sharing links are disabled; candidates must verify their invited email.</p>
 {editing&&<form onSubmit={e=>{e.preventDefault();action('brief-save',{page});}}><label>Generate sections from a document<input disabled={busy} type="file" accept=".docx,.pdf" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(page.sections.some((s:R)=>s.body)&&!confirm('Replace current draft sections with this document? Other page fields will stay.'))return;setBusy(true);setError('');try{const {documentSections}=await import('./document-upload');setPage({...page,sections:await documentSections(f),source_name:f.name});setPreview(true);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}/></label><p className="fine">Text-based PDF or .docx, up to 10 MB. Conversion extracts text into editable sections; it does not preserve document artwork. The original file is not stored. Review headings and content before approval.</p>{page.source_name&&<p>Source: {page.source_name}</p>}<div className="role-editor-grid">{[['subtitle','Introduction / subtitle'],['location','Location / working arrangement'],['reports_to','Reports to'],['team','Team'],['mandate','Mandate'],['partner_name','Partner name'],['video','Partner video: YouTube or Vimeo URL'],['booking_url','Partner booking URL (optional)']].map(([k,l])=>field(k,l))}</div><p className="fine">Use a video you are authorized to share. Its host controls video privacy separately from this invitation-only page.</p><label>Partner’s note<textarea rows={3} value={page.partner_note||''} onChange={e=>setPage({...page,partner_note:e.target.value})}/></label>{page.sections.map((s:R,i:number)=><div className="role-editor-section" key={i}><label>Section heading<input required maxLength={200} value={s.heading} onChange={e=>setPage({...page,sections:page.sections.map((v:R,n:number)=>n===i?{...v,heading:e.target.value}:v)})}/></label><label>Section content<textarea required rows={7} maxLength={20000} value={s.body} onChange={e=>setPage({...page,sections:page.sections.map((v:R,n:number)=>n===i?{...v,body:e.target.value}:v)})}/></label><button type="button" disabled={i===0} onClick={()=>{const sections=[...page.sections];[sections[i-1],sections[i]]=[sections[i],sections[i-1]];setPage({...page,sections});}}>Move up</button> <button type="button" disabled={page.sections.length===1} onClick={()=>setPage({...page,sections:page.sections.filter((_:R,n:number)=>n!==i)})}>Remove section</button></div>)}<div className="research-actions"><button type="button" onClick={()=>setPage({...page,sections:[...page.sections,{heading:'',body:''}]})}>Add section</button><button type="button" onClick={()=>setPreview(!preview)}>{preview?'Hide preview':'Preview page'}</button><button className="primary" disabled={busy}>{busy?'Processing…':'Save draft'}</button><button type="button" disabled={busy} onClick={()=>{if(confirm('Discard unsaved page changes?')){setEditing(false);setPreview(false);}}}>Cancel</button></div></form>}
 {!editing&&doc&&<div className="research-actions"><button onClick={()=>setPreview(!preview)}>{preview?'Hide draft preview':'Preview draft page'}</button>{manager&&doc.status==='Draft'&&<button disabled={busy} onClick={()=>action('brief-approve')}>Approve draft</button>}{manager&&doc.active&&<button disabled={busy} onClick={()=>{if(confirm(`Publish approved version ${doc.revision} to invited candidates?`))action('brief-publish');}}>Publish approved version {doc.revision}</button>}{manager&&doc.published_revision&&<button disabled={busy} onClick={()=>{if(confirm('Unpublish the page and revoke all candidate invitations?'))action('brief-unpublish');}}>Unpublish and revoke access</button>}</div>}
 {preview&&<div className="role-preview"><RolePageView preview brief={{title:search.title,client:search.client,page:showPage,content:editing?page.sections.map((s:R)=>s.body).join('\n\n'):doc?.draft,revision:'Draft'}}/></div>}
 {manager&&!editing&&<><h3>Candidate invitations</h3><p className="fine">Select a mapped candidate and confirm their email. Re-inviting the same candidate revokes their previous invitation. Invitations show the latest published version.</p><form onSubmit={async e=>{e.preventDefault();if(!confirm('Send a role invitation to '+email+'?'))return;setBusy(true);setError('');setNotice('');try{const r=await api('candidate-invites',{action:'send',role_id:role,candidate_id:candidate,email,days});await loadInvites();setNotice(r.emailStatus==='accepted'?'Invitation accepted by the email provider.':'Delivery could not be confirmed. Check the address, then re-invite if needed.');setEmail('');setCandidate('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><div className="sheet-toolbar"><label>Candidate<select required value={candidate} onChange={e=>setCandidate(e.target.value)}><option value="">Select candidate</option>{candidates.map(c=><option key={c.candidate_id} value={c.candidate_id}>{c.name} — {c.company}</option>)}</select></label><label>Candidate email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Expires in days<input type="number" min={1} max={30} required value={days} onChange={e=>setDays(e.target.value)}/></label><button className="primary" disabled={busy||!doc?.published_revision}>Send secure invitation</button></div></form><div className="sheet-scroll"><table className="sheet-table"><thead><tr><th>Candidate</th><th>Email</th><th>Access expires</th><th>Status</th><th>Action</th></tr></thead><tbody>{invites.map(i=><tr key={i.id}><td>{i.name}</td><td>{i.email}</td><td>{new Date(i.expires).toLocaleString()}</td><td>{i.revoked?'Revoked':i.expires<Date.now()?'Expired':'Active'}</td><td>{!i.revoked&&<button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await api('candidate-invites',{action:'revoke',id:i.id});await loadInvites();}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>Revoke</button>}</td></tr>)}</tbody></table></div></>}
 {doc&&<details><summary>Version history</summary>{(data.research?.events||[]).filter((e:R)=>e.record_id===doc.id).map((e:R)=><details key={e.id}><summary>{new Date(e.created_at).toLocaleString()} · {e.action}</summary><p className="document-text">{e.data.after?.active||e.data.after?.draft}</p></details>)}</details>}{error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</section>;
}
