export const identitySchema = `
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,name TEXT NOT NULL,password TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS memberships(user_id TEXT NOT NULL,tenant TEXT NOT NULL,role TEXT NOT NULL,staff_id TEXT,status TEXT NOT NULL DEFAULT 'active',PRIMARY KEY(user_id,tenant));
CREATE TABLE IF NOT EXISTS invites(token TEXT PRIMARY KEY,email TEXT NOT NULL,name TEXT NOT NULL,tenant TEXT NOT NULL,role TEXT NOT NULL,staff_id TEXT,expires INTEGER NOT NULL,used INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS limits(key TEXT PRIMARY KEY,count INTEGER NOT NULL,expires INTEGER NOT NULL);
`;
export const workspaceSchema = `
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS crm_jobs(external_id TEXT PRIMARY KEY,title TEXT NOT NULL,status TEXT NOT NULL,company_slug TEXT NOT NULL,fetched_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS integration_runs(id TEXT PRIMARY KEY,actor TEXT NOT NULL,status TEXT NOT NULL,count INTEGER NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS teams(id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS team_members(team_id TEXT NOT NULL REFERENCES teams(id),staff_id TEXT NOT NULL REFERENCES staff(id),PRIMARY KEY(team_id,staff_id));
CREATE TABLE IF NOT EXISTS team_rosters(team_id TEXT PRIMARY KEY REFERENCES teams(id),version INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS weekly_priorities(search_id TEXT NOT NULL REFERENCES searches(id),week TEXT NOT NULL,disposition TEXT NOT NULL,notes TEXT NOT NULL DEFAULT '',version INTEGER NOT NULL DEFAULT 1,PRIMARY KEY(search_id,week));
CREATE TABLE IF NOT EXISTS staff(id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS staff_profiles(staff_id TEXT PRIMARY KEY REFERENCES staff(id),email TEXT NOT NULL DEFAULT '',archived INTEGER NOT NULL DEFAULT 0,version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS searches(id TEXT PRIMARY KEY,external_id TEXT,client TEXT NOT NULL,title TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Open',start_date TEXT,partner TEXT,notes TEXT NOT NULL DEFAULT '',version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS assignments(id TEXT PRIMARY KEY,search_id TEXT NOT NULL REFERENCES searches(id),team_id TEXT NOT NULL REFERENCES teams(id),work_date TEXT NOT NULL,target INTEGER,partner TEXT,readiness TEXT,link TEXT,notes TEXT NOT NULL DEFAULT '',source_row INTEGER,source_totals TEXT,version INTEGER NOT NULL DEFAULT 1);
CREATE INDEX IF NOT EXISTS assignments_date ON assignments(work_date,team_id);
CREATE TABLE IF NOT EXISTS entries(id TEXT PRIMARY KEY,assignment_id TEXT NOT NULL REFERENCES assignments(id),staff_id TEXT NOT NULL REFERENCES staff(id),mapped INTEGER,peer INTEGER,partner INTEGER,peer_at TEXT,partner_at TEXT,notes TEXT NOT NULL DEFAULT '',flag TEXT,source TEXT NOT NULL DEFAULT 'manual',version INTEGER NOT NULL DEFAULT 1,UNIQUE(assignment_id,staff_id));
CREATE TABLE IF NOT EXISTS reviews(id TEXT PRIMARY KEY,entry_id TEXT NOT NULL REFERENCES entries(id),stage TEXT NOT NULL,approved INTEGER NOT NULL,actor TEXT NOT NULL,created_at TEXT NOT NULL,notes TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS weekly_decisions(id TEXT PRIMARY KEY,search_id TEXT NOT NULL REFERENCES searches(id),week TEXT NOT NULL,disposition TEXT NOT NULL,notes TEXT NOT NULL,actor TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS weekly_search ON weekly_decisions(search_id,week,created_at);
CREATE TABLE IF NOT EXISTS audit(id TEXT PRIMARY KEY,actor TEXT NOT NULL,action TEXT NOT NULL,entity TEXT NOT NULL,before_json TEXT,after_json TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS imports(hash TEXT PRIMARY KEY,created_at TEXT NOT NULL,summary TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS issues(id TEXT PRIMARY KEY,kind TEXT NOT NULL,source_row INTEGER,details TEXT NOT NULL,resolved INTEGER NOT NULL DEFAULT 0);
`;
