import React,{useId,useState} from 'react';
type Search=Record<string,any>;
export const searchDisplayId=(r:Search)=>String(r.search_number??(r.external_id?'CRM '+r.external_id:'Unnumbered'));
export function matchingSearches(searches:Search[],query:string,sort:string){
 const terms=query.trim().toLowerCase().split(/\s+/).filter(Boolean);
 const compare=(a:string,b:string)=>a.localeCompare(b,undefined,{numeric:true,sensitivity:'base'});
 return searches.filter(r=>terms.every(t=>[searchDisplayId(r),r.client,r.title].join(' ').toLowerCase().includes(t))).sort((a,b)=>compare(sort==='company'?a.client||'':searchDisplayId(a),sort==='company'?b.client||'':searchDisplayId(b))||compare(a.title||'',b.title||'')||compare(String(a.id),String(b.id)));
}
export function SearchPicker({searches,value,onChange,disabled,allowAll,label:fieldLabel='Search'}:{searches:Search[];value:string;onChange:(id:string)=>void;disabled?:boolean;allowAll?:boolean;label?:string}){
 const [query,setQuery]=useState(''),[open,setOpen]=useState(false),[sort,setSort]=useState('company'),[active,setActive]=useState(0),id=useId();
 const label=(r:Search)=>`${searchDisplayId(r)} · ${r.client} — ${r.title}`,selected=searches.find(r=>r.id===value),results=matchingSearches(searches,query,sort);
 const choose=(r:Search)=>{onChange(r.id);setOpen(false);setQuery('');setActive(0);};
 return <div className="search-picker" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node)){setOpen(false);setQuery('');}}}><div className="search-picker-controls"><label htmlFor={id}>{fieldLabel}<input id={id} role="combobox" autoComplete="off" disabled={disabled} aria-expanded={open} aria-controls={id+'-options'} aria-autocomplete="list" aria-activedescendant={open&&results[active]?id+'-'+active:undefined} placeholder="Type search ID, company or search name" value={open?query:selected?label(selected):''} onFocus={()=>{setOpen(true);setQuery('');setActive(0);}} onChange={e=>{setQuery(e.target.value);setOpen(true);setActive(0);}} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);setQuery('');}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setOpen(true);setActive(n=>Math.max(0,Math.min(results.length-1,n+(e.key==='ArrowDown'?1:-1))));}else if(e.key==='Enter'&&open&&results[active]){e.preventDefault();choose(results[active]);}}}/></label>{allowAll&&value&&<button disabled={disabled} onClick={()=>{onChange('');setQuery('');setOpen(false);}}>All searches</button>}</div>{open&&!disabled&&<div className="search-picker-menu"><label>Sort searches<select disabled={disabled} value={sort} onChange={e=>{setSort(e.target.value);setActive(0);setOpen(true);}}><option value="company">Company name</option><option value="id">Search ID</option></select></label><small>{results.length} matching searches</small><div id={id+'-options'} role="listbox" aria-label="Searches">{results.map((r,i)=><button type="button" role="option" id={id+'-'+i} aria-selected={r.id===value} className={i===active?'highlighted':''} key={r.id} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(r)}><strong>{searchDisplayId(r)}</strong><span>{r.client} — {r.title}<small>{r.status}</small></span></button>)}</div>{!results.length&&<p>No searches match. Try another ID, company or search name.</p>}</div>}</div>;
}
