import {displayDate} from './dates';
import {compareTableValues} from './table-sort';
import React,{useState} from 'react';
import {effectiveDecision,isWorkingDecision,sourcingEvidence} from './search-decisions';
import {addDays} from './planning';
type R=Record<string,any>;
export function SearchDecisions({data,roles,week,canEdit,onDecide,onAllocate,onReviewPlan}:{data:R;roles:R[];week:string;canEdit:boolean;onDecide:(role:R,week?:string)=>void;onAllocate:(id:string)=>void;onReviewPlan:(id:string,date:string)=>void}){
 const [history,setHistory]=useState(false),[sort,setSort]=useState({key:'client',descending:false});
 const weeks=Array.from({length:8},(_,i)=>addDays(week,(i-7)*7));
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());
 const rows=roles.map(role=>{const p=effectiveDecision(data.priorities,role.id,week),e=sourcingEvidence(data.research?.records||[],role,week,today);const conflicts=data.assignments.filter((a:R)=>a.search_id===role.id&&a.work_date>=week&&a.work_date>=today&&!a.has_work&&!isWorkingDecision(effectiveDecision(data.priorities,role.id,a.work_date))).sort((a:R,b:R)=>a.work_date.localeCompare(b.work_date));const future=data.priorities.filter((d:R)=>d.search_id===role.id&&d.week>today&&d.disposition==='Start').sort((a:R,b:R)=>a.week.localeCompare(b.week))[0];return {role,p,e,conflicts,future};});
 const value=(r:typeof rows[number]):string|number|undefined=>sort.key==='client'?`${r.role.client} ${r.role.title}`:sort.key==='decision'?r.p?.disposition:sort.key==='next'?(r.conflicts.length?`Review ${r.conflicts.length}`:isWorkingDecision(r.p)?'Allocate team':r.p?'No new allocation':'Decide first'):sort.key.startsWith('week:')?effectiveDecision(data.priorities,r.role.id,sort.key.slice(5))?.disposition:(r.e as R)[sort.key];
 rows.sort((a,b)=>compareTableValues(value(a),value(b),sort.descending)||String(a.role.id).localeCompare(String(b.role.id)));
 const heading=(key:string,label:string)=><th key={key} scope="col" aria-sort={sort.key===key?(sort.descending?'descending':'ascending'):'none'}><button className="table-sort-heading" onClick={()=>setSort({key,descending:sort.key===key?!sort.descending:false})}>{label} <span aria-hidden="true">{sort.key===key?(sort.descending?'↓':'↑'):'↕'}</span></button></th>;
 const badge=(p?:R)=><span className={p?'badge priority-'+p.disposition.toLowerCase():'fine'}>{p?.disposition||'Not decided'}</span>;
 return <><div className="decision-heading"><span className="fine">{roles.length} searches · Evidence is current; last-week mappings use the selected week.</span><button onClick={()=>{setHistory(!history);setSort({key:'client',descending:false});}}>{history?'Show evidence':'Show 8-week history'}</button></div><div className="sheet-scroll"><table className={"sheet-table decision-grid"+(history?" decision-history":"")}><thead><tr>{heading('client','Client / role')}{history?weeks.map(w=>heading('week:'+w,'Week of '+displayDate(w))):<>{heading('started','Sourcing started')}{heading('mapped','Mapped')}{heading('approved','Partner approved')}{heading('pending','Awaiting review')}{heading('lastWeek','Mapped last week')}{heading('decision','Sourcing decision')}{heading('next','Next step')}</>}</tr></thead><tbody>{rows.map(({role,p,e,conflicts,future})=>{
 return <tr key={role.id}><th scope="row">{role.client}<small>{role.title}</small><small>CRM: {role.status||'Not set'}</small></th>{history?weeks.map(w=>{const d=effectiveDecision(data.priorities,role.id,w);return <td key={w}>{canEdit?<button className="decision-history-cell" title={d?`${d.week===w?'Reviewed':'Carried from '+d.week}${d.notes?' · '+d.notes:''}`:'Set sourcing decision'} onClick={()=>onDecide(role,w)}>{badge(d)}{d&&d.week!==w&&<small>Carried forward</small>}</button>:badge(d)}</td>}):<><td>{e.started?displayDate(e.started):'Not recorded'}{e.weeks!==null&&<small>{e.weeks} weeks elapsed</small>}</td><td>{e.mapped}</td><td>{e.approved}</td><td>{e.pending}</td><td>{e.lastWeek}</td><td>{badge(p)}{p&&<small>{p.week===week?'Reviewed this week':'Carried from '+displayDate(p.week)}</small>}{p?.notes&&<small>{p.notes}</small>}{canEdit&&<button className="text-button" onClick={()=>onDecide(role)}>{p?'Review':'Decide'}</button>}</td><td>{future&&<small>Scheduled to start week of {displayDate(future.week)}</small>}{canEdit&&isWorkingDecision(p)?<button onClick={()=>onAllocate(role.id)}>Allocate team</button>:<span className="fine">{future?'Plan for the scheduled start':p?'No new allocation':'Decide first'}</span>}{conflicts.length>0&&<button className="decision-warning" onClick={()=>onReviewPlan(role.id,conflicts[0].work_date)}>Review {conflicts.length} unstarted assignments</button>}</td></>}</tr>;
 })}</tbody></table>{!roles.length&&<p className="sheet-empty">No searches match these filters.</p>}</div></>;
}
