import {FilterPopover} from './FilterPopover';
import React,{useState} from 'react';
import {matchingSearches,searchDisplayId} from './SearchPicker';
type R=Record<string,any>;
export function SearchMultiFilter({searches,value,onChange,disabled=false,floating=false}:{searches:R[];value:string[]|null;onChange:(ids:string[]|null)=>void;disabled?:boolean;floating?:boolean}) {
 const [query,setQuery]=useState('');
 const shown=matchingSearches(searches,query,'company'),chosen=new Set(value===null?searches.map(s=>s.id):value);
 const toggle=(ids:string[],checked:boolean)=>{const next=new Set(chosen);ids.forEach(id=>checked?next.add(id):next.delete(id));onChange([...next]);};
 const clients=[...new Set(shown.map(s=>s.client||'No client'))];
 const content=<><input disabled={disabled} type="search" aria-label="Find searches or clients" placeholder="Type client, search or search ID" value={query} onChange={e=>setQuery(e.target.value)}/><div className="row-actions"><button disabled={disabled} onClick={()=>onChange(null)}>All searches</button><button disabled={disabled} onClick={()=>onChange([])}>None</button><button disabled={disabled||!shown.length} onClick={()=>onChange(shown.map(s=>s.id))}>Show matching only</button></div><div className="filter-options">{clients.map(client=>{const roles=shown.filter(s=>(s.client||'No client')===client);return <div key={client}><label className="checkbox search-client"><input type="checkbox" disabled={disabled} checked={roles.every(s=>chosen.has(s.id))} onChange={e=>toggle(roles.map(s=>s.id),e.target.checked)}/><strong>{client}</strong></label>{roles.map(s=><label className="checkbox search-choice" key={s.id}><input type="checkbox" disabled={disabled} checked={chosen.has(s.id)} onChange={e=>toggle([s.id],e.target.checked)}/><span><small>{searchDisplayId(s)}</small> {s.title} <small>· {s.status}</small></span></label>)}</div>})}{!shown.length&&<p>No matching searches.</p>}</div></>;
 return <div className="search-multi-filter"><span className="filter-label">Searches</span>{floating?<FilterPopover label="Filter searches" summary={value===null?'All searches':`${value.length} searches selected`} width={430} disabled={disabled}>{content}</FilterPopover>:<details className="column-filter"><summary aria-label="Filter searches" onClick={e=>{if(disabled)e.preventDefault();}}>{value===null?'All searches':`${value.length} searches selected`} ▾</summary><div className="filter-menu">{content}</div></details>}</div>;
}
