import React,{useState} from 'react';
import {isCRMManaged,searchStatuses} from './search-management';
export function SearchManagement({search,api,reload,onDirty=()=>{}}:{search:any;api:(path:string,body?:unknown)=>Promise<any>;reload:()=>Promise<void>;onDirty?:(dirty:boolean)=>void}){
 const [draft,setDraft]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const open=()=>{setDraft({...search,take_over:false});setError('');};
 const close=()=>{setDraft(null);onDirty(false);};
 const change=(patch:any)=>{setDraft({...draft,...patch});onDirty(true);};
 const crm=draft&&isCRMManaged(draft),editable=draft&&(!crm||draft.take_over);
 async function save(){setBusy(true);setError('');try{await api('mutate',{kind:'search-manage',id:draft.id,version:draft.version,title:draft.title,client:draft.client,status:draft.status,take_over:draft.take_over});await reload();close();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <><button onClick={open}>Search settings</button>{draft&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Search settings"><div className="section-head"><h2>Search settings</h2><button disabled={busy} onClick={close}>Cancel</button></div><p>Managed in: <strong>{crm?'RecruitCRM':'This app'}</strong></p>{crm&&<><label><input type="checkbox" checked={draft.take_over} disabled={busy} onChange={e=>change({take_over:e.target.checked})}/> Manage this search in this app</label>{draft.take_over&&<p>RecruitCRM will stop updating this search. Existing candidates, plans and history stay linked. Candidate history can still be imported separately.</p>}</>}<label>Search name<input value={draft.title} disabled={!editable||busy} onChange={e=>change({title:e.target.value})}/></label><label>Client<input value={draft.client} disabled={!editable||busy} onChange={e=>change({client:e.target.value})}/></label><label>Search status<select value={draft.status} disabled={!editable||busy} onChange={e=>change({status:e.target.value})}>{!searchStatuses.includes(draft.status)&&<option>{draft.status}</option>}{searchStatuses.map(status=><option key={status}>{status}</option>)}</select></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={!editable||busy||!draft.title.trim()||!draft.client.trim()} onClick={save}>{busy?'Saving…':crm?'Switch and save':'Save changes'}</button></section></div>}</>;
}
