import React,{useState} from 'react';
import {effectiveDecision,isWorkingDecision,sourcingEvidence} from './search-decisions';
import {addDays} from './planning';
type R=Record<string,any>;
export function SearchDecisions({data,roles,week,canEdit,onDecide,onAllocate,onReviewPlan}:{data:R;roles:R[];week:string;canEdit:boolean;onDecide:(role:R,week?:string)=>void;onAllocate:(id:string)=>void;onReviewPlan:(id:string,date:string)=>void}){
 const [history,setHistory]=useState(false);
 const weeks=Array.from({length:8},(_,i)=>addDays(week,(i-7)*7));
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());
 const badge=(p?:R)=><span className={p?'badge priority-'+p.disposition.toLowerCase():'fine'}>{p?.disposition||'Not decided'}</span>;
 return <><div className="decision-heading"><span className="fine">{roles.length} searches · Evidence is current; last-week mappings use the selected week.</span><button onClick={()=>setHistory(!history)}>{history?'Show evidence':'Show 8-week history'}</button></div><div className="sheet-scroll"><table className="sheet-table decision-grid"><thead><tr><th>Client / role</th>{history?weeks.map(w=><th key={w}>Week of {w.slice(5)}</th>):<><th>Sourcing started</th><th title="All current role mappings, including drafts">Mapped</th><th>Partner approved</th><th>Awaiting review</th><th>Mapped last week</th><th>Sourcing decision</th><th>Next step</th></>}</tr></thead><tbody>{roles.map(role=>{
 const p=effectiveDecision(data.priorities,role.id,week),e=sourcingEvidence(data.research?.records||[],role,week,today);
 const conflicts=data.assignments.filter((a:R)=>a.search_id===role.id&&a.work_date>=week&&a.work_date>=today&&!a.has_work&&!isWorkingDecision(effectiveDecision(data.priorities,role.id,a.work_date))).sort((a:R,b:R)=>a.work_date.localeCompare(b.work_date));
 return <tr key={role.id}><th scope="row">{role.client}<small>{role.title}</small><small>CRM: {role.status||'Not set'}</small></th>{history?weeks.map(w=>{const d=effectiveDecision(data.priorities,role.id,w);return <td key={w}>{canEdit?<button className="decision-history-cell" title={d?`${d.week===w?'Reviewed':'Carried from '+d.week}${d.notes?' · '+d.notes:''}`:'Set sourcing decision'} onClick={()=>onDecide(role,w)}>{badge(d)}{d&&d.week!==w&&<small>Carried forward</small>}</button>:badge(d)}</td>}):<><td>{e.started||'Not recorded'}{e.weeks!==null&&<small>{e.weeks} weeks elapsed</small>}</td><td>{e.mapped}</td><td>{e.approved}</td><td>{e.pending}</td><td>{e.lastWeek}</td><td>{badge(p)}{p&&<small>{p.week===week?'Reviewed this week':'Carried from '+p.week}</small>}{p?.notes&&<small>{p.notes}</small>}{canEdit&&<button className="text-button" onClick={()=>onDecide(role)}>{p?'Review':'Decide'}</button>}</td><td>{canEdit&&isWorkingDecision(p)?<button onClick={()=>onAllocate(role.id)}>Allocate team</button>:<span className="fine">{p?'No new allocation':'Decide first'}</span>}{conflicts.length>0&&<button className="decision-warning" onClick={()=>onReviewPlan(role.id,conflicts[0].work_date)}>Review {conflicts.length} unstarted assignments</button>}</td></>}</tr>;
 })}</tbody></table>{!roles.length&&<p className="sheet-empty">No searches match these filters.</p>}</div></>;
}
