import React,{useEffect,useState} from 'react';
type R=Record<string,any>;
export function StaffDirectory({data,api,reload,onAdd,onInvite,onDirty}:{data:R;api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;onAdd:()=>void;onInvite:(s:R)=>void;onDirty:(v:boolean)=>void}) {
 const [edit,setEdit]=useState<R|null>(null),[members,setMembers]=useState<R[]>([]),[pending,setPending]=useState<R[]>([]),[showArchived,setShowArchived]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{let cancelled=false;api('staff-directory').then(d=>{if(!cancelled){setMembers(d.members);setPending(d.invitations);}}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[data]);
 useEffect(()=>{onDirty(!!edit);return()=>onDirty(false);},[!!edit]);
 async function save(body:R){setBusy(true);setError('');setMessage('');try{await api('mutate',body);setEdit(null);await reload();setMessage(body.kind==='staff-edit'?'Researcher details saved.':body.archived?'Researcher archived. Past work is retained.':'Researcher restored. Add them to a team when ready.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <section className="panel"><div className="section-head"><div><h2>Researchers</h2><p>Edit names and contact details, including people who do not have an account yet.</p></div><button onClick={onAdd} disabled={!!edit||busy}>Add researcher</button></div>
 <label className="checkbox"><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/>Show archived researchers</label>
 {message&&<p role="status">{message}</p>}{error&&!edit&&<p className="error" role="alert">{error}</p>}
 <div className="table-scroll"><table className="sheet-table"><thead><tr><th>Name</th><th>Contact email</th><th>Account / invitation email</th><th>Actions</th></tr></thead><tbody>{data.staff.filter((s:R)=>showArchived||!s.archived).map((s:R)=>{const linked=members.filter(m=>m.staff_id===s.id),invites=pending.filter(i=>i.staff_id===s.id);return <tr key={s.id}><td>{s.name}{!!s.archived&&' · Archived'}</td><td>{s.email||'Not set'}</td><td>{linked.length?linked.map(m=><div key={m.id}>{m.email} · {m.status==='active'?'Active':'Access revoked'}</div>):invites.length?invites.map(i=><div key={i.email}>{i.email} · Invitation pending</div>):'No account yet'}</td><td><div className="row-actions"><button disabled={busy||!!edit} onClick={()=>{setError('');setEdit({...s});}}>Edit researcher</button>{!s.archived&&!linked.length&&<button disabled={busy||!!edit} onClick={()=>onInvite({...s,email:s.email||invites[0]?.email||''})}>{invites.length?'Replace invitation':'Invite'}</button>}<button disabled={busy||!!edit} onClick={()=>{if(!s.archived&&!confirm(`Archive ${s.name}? This removes them from team rosters. Past work remains. Account access and pending invitations are managed separately.`))return;save({kind:'staff-archive',id:s.id,version:s.version,archived:!s.archived});}}>{s.archived?'Restore':'Archive'}</button></div></td></tr>;})}</tbody></table></div>
 <p className="fine">Contact email is for your staff directory. It does not change sign-in or an existing invitation. Account holders can change their sign-in email in Account settings. To correct a pending invitation, choose Replace invitation; the earlier link will stop working. Archiving does not revoke account access; use Workspace → Manage accounts for that.</p>
 {edit&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="researcher-title"><div className="section-head"><h2 id="researcher-title">Edit researcher</h2><button disabled={busy} onClick={()=>{setEdit(null);setError('');}}>Cancel</button></div><form onSubmit={e=>{e.preventDefault();save({kind:'staff-edit',id:edit.id,version:edit.version,name:edit.name,email:edit.email});}}><label>Researcher name<input required maxLength={100} value={edit.name} disabled={busy} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>Contact email (optional)<input type="email" maxLength={254} value={edit.email||''} disabled={busy} onChange={e=>setEdit({...edit,email:e.target.value})}/></label><p className="fine">The researcher keeps the same record, team memberships and work history. Contact email does not change account sign-in.</p>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy} className="primary">{busy?'Saving…':'Save researcher'}</button></form></section></div>}
 </section>;
}
