import React from 'react';
export function StrategyEvidence({criteria=[],value={},onChange,readOnly=false}:any){
 if(!criteria.length)return null;
 const completed=criteria.filter((c:any)=>value[c.id]?.text?.trim()).length;
 return <section className="fit-evidence"><div className="fit-section-heading"><h3>Fit against search criteria</h3>{!readOnly&&<span>{completed} of {criteria.length} addressed</span>}</div>{!readOnly&&<p className="fine">Explain the candidate’s fit for each requirement. Include examples or sources; explain any exceptions.</p>}<div className="fit-criteria-list">{criteria.map((c:any,i:number)=><article className="fit-criterion" key={c.id}><div className="fit-criterion-heading"><span className="criterion-number">{i+1}</span><strong>{c.label}</strong></div><div className="fit-requirement"><span className="fit-label">Requirement</span><p>{c.requirement||'No specific parameters recorded.'}</p></div><div className="fit-justification">{readOnly?<><span className="fit-label">Researcher justification{value[c.id]?.not_applicable?' · Not applicable':''}</span><p>{value[c.id]?.text||'No justification recorded'}</p></>:<><label>Researcher justification<textarea aria-label={'Justification for '+c.label} rows={3} maxLength={5000} value={value[c.id]?.text||''} onChange={e=>onChange({...value,[c.id]:{...value[c.id],text:e.target.value}})} placeholder="What demonstrates fit? Add relevant experience, examples and sources."/></label><label className="fit-exception"><input type="checkbox" checked={!!value[c.id]?.not_applicable} onChange={e=>onChange({...value,[c.id]:{...value[c.id],not_applicable:e.target.checked}})}/>Not applicable — explain in the justification</label></>}</div></article>)}</div></section>;
}
export function StrategyCriteriaEditor({value=[],onChange}:any){
 const update=(id:string,patch:any)=>onChange(value.map((c:any)=>c.id===id?{...c,...patch}:c));
 return <section className="fit-editor"><div className="fit-section-heading"><h3>Fit criteria</h3><span>{value.length} criteria</span></div><p className="fine">Name each criterion and describe the parameters. Researchers will justify the candidate’s fit against this list.</p>{!value.length&&<p className="fit-empty">No criteria yet. Add a criterion such as location, qualifications or relevant experience.</p>}<div className="fit-criteria-list">{value.map((c:any,i:number)=><article className="fit-criterion" key={c.id}><div className="fit-section-heading"><strong>Criterion {i+1}</strong><button className="text-button" type="button" onClick={()=>onChange(value.filter((v:any)=>v.id!==c.id))} aria-label={'Remove criterion '+(i+1)}>Remove</button></div><label>Criterion name<input required maxLength={150} value={c.label} placeholder="e.g. Relevant industry experience" onChange={e=>update(c.id,{label:e.target.value})}/></label><label>Parameters / requirements<textarea rows={3} maxLength={1500} value={c.requirement} placeholder="e.g. Has led quality operations across multiple pharmaceutical manufacturing sites." onChange={e=>update(c.id,{requirement:e.target.value})}/></label></article>)}</div><button type="button" onClick={()=>onChange([...value,{id:crypto.randomUUID(),label:'',requirement:''}])}>+ Add criterion</button></section>;
}
