import {hasPermission} from './access-policy';
import {SortableTable} from './SortableTable';
import {IconAction} from './IconAction';
import {PencilSimple} from '@phosphor-icons/react';
import {canPlan,hasRole} from './domain';
import React,{useState,useEffect} from 'react';
export function TeamsPanel({data,api,reload,onAdd,onDirty}:{data:any;api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;onAdd:()=>void;onDirty:(v:boolean)=>void}) {
 const [transfer,setTransfer]=useState<any>(null);
 const [edit,setEdit]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [query,setQuery]=useState('');
 useEffect(()=>{onDirty(!!edit||!!transfer||busy);return()=>onDirty(false);},[!!edit,!!transfer,busy]);
 return <section className="panel"><div className="section-head team-directory-toolbar"><label>Find team or member<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Team or researcher name"/></label><div className="row-actions">{hasPermission(data.actor,'teams.assign')&&<button onClick={()=>setTransfer({staff_id:'',from:'',to:''})}>Assign / move researcher</button>}{hasPermission(data.actor,'teams.create')&&<button className="primary" onClick={onAdd}>Add team</button>}</div></div>
 {error&&!edit&&!transfer&&<p className="error" role="alert">{error}</p>}
 <div className="table-scroll"><SortableTable stateKey="Teams.directory" className="sheet-table team-directory"><thead><tr><th>Team</th><th>Members</th><th>Team lead</th><th>Actions</th></tr></thead><tbody>{data.teams.map((t:any)=>{const roster=data.team_members.filter((m:any)=>m.team_id===t.id).map((m:any)=>data.staff.find((s:any)=>s.id===m.staff_id)?.name).filter(Boolean);const current=data.research.records.find((r:any)=>r.kind==='team-reviewer'&&r.team_id===t.id);const people=data.people.filter((p:any)=>hasRole(p,'researcher')&&data.team_members.some((m:any)=>m.team_id===t.id&&m.staff_id===p.staff_id));if(![t.name,...roster].join(' ').toLowerCase().includes(query.toLowerCase()))return null;return <tr key={t.id}><td><strong>{t.name}</strong></td><td>{roster.join(', ')||'No members'}</td><td data-sort-value={data.people.find((p:any)=>p.id===current?.reviewer_id)?.name||''}><select aria-label={'Team lead for '+t.name} disabled={busy||!hasPermission(data.actor,'teams.members')} value={current?.reviewer_id||''} onChange={async e=>{setBusy(true);setError('');try{await api('research',{action:'team-reviewer',id:current?.id,version:current?.version,team_id:t.id,reviewer_id:e.target.value});await reload();}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><option value="">Not assigned</option>{people.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></td><td>{hasPermission(data.actor,'teams.members')&&<IconAction label="Edit team members" accessibleLabel={'Edit members of '+t.name} onClick={()=>{setEdit({...t,staff_ids:data.team_members.filter((m:any)=>m.team_id===t.id).map((m:any)=>m.staff_id)});setError('');}}><PencilSimple size={20}/></IconAction>}</td></tr>})}</tbody></SortableTable></div>
 {!data.teams.length&&<p>No sourcing teams.</p>}
 {transfer&&<div className="modal-backdrop"><section className="modal"><h2>Assign or move researcher</h2><p>Existing work keeps its original team and attribution. Future allocations use the new roster. Change the team lead first if moving the current lead.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('mutate',{kind:'team-transfer',...transfer,from_version:data.teams.find((t:any)=>t.id===transfer.from)?.roster_version||0,to_version:data.teams.find((t:any)=>t.id===transfer.to)?.roster_version||0});await reload();setTransfer(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><label>Researcher<select required value={transfer.staff_id} onChange={e=>setTransfer({...transfer,staff_id:e.target.value,from:''})}><option value="">Choose researcher</option>{data.staff.filter((s:any)=>!s.archived).map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>From team<select value={transfer.from} onChange={e=>setTransfer({...transfer,from:e.target.value})}><option value="">Assign without moving</option>{data.teams.filter((t:any)=>data.team_members.some((m:any)=>m.team_id===t.id&&m.staff_id===transfer.staff_id)).map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>To team<select required value={transfer.to} onChange={e=>setTransfer({...transfer,to:e.target.value})}><option value="">Choose team</option>{data.teams.filter((t:any)=>t.id!==transfer.from).map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{error&&<p className="error">{error}</p>}<button disabled={busy}>Assign / move researcher</button><button type="button" onClick={()=>setTransfer(null)}>Cancel</button></form></section></div>}
 {edit&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="team-title"><div className="section-head"><h2 id="team-title">{edit.name} researchers</h2><button disabled={busy} onClick={()=>setEdit(null)}>Cancel</button></div><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('mutate',{kind:'team-members',id:edit.id,version:edit.roster_version,staff_ids:edit.staff_ids});await reload();setEdit(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>
 <p className="fine">Existing assignments keep their original researchers. Only active accounts with Researcher access can join a team. Invite colleagues in People & access and wait for acceptance first.</p>
 {!data.staff.length&&<p>Enable Researcher for an existing person in People & access first.</p>}
 {data.staff.filter((s:any)=>!s.archived).map((s:any)=><label className="checkbox" key={s.id}><input type="checkbox" disabled={busy} checked={edit.staff_ids.includes(s.id)} onChange={e=>setEdit({...edit,staff_ids:e.target.checked?[...edit.staff_ids,s.id]:edit.staff_ids.filter((id:string)=>id!==s.id)})}/>{s.name}</label>)}
 {error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Saving…':'Save team members'}</button></form></section></div>}
 </section>;
}

