import {canPlan} from './domain';
import React,{useState} from 'react';
export function TeamsPanel({data,api,reload,onAdd}:{data:any;api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;onAdd:()=>void}) {
 const [transfer,setTransfer]=useState<any>(null);
 const [edit,setEdit]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <section className="panel"><div className="section-head"><div><h2>Research teams</h2><p>Choose the researchers in each team. New assignments use this roster.</p></div>{canPlan(data.actor)&&<div className="row-actions"><button onClick={()=>setTransfer({staff_id:'',from:'',to:''})}>Move researcher</button><button onClick={onAdd}>Add team</button></div>}</div>
 {!data.teams.length&&<p>Create your first team, then select its researchers.</p>}
 {data.teams.map((t:any)=><div className="work-row" key={t.id}><strong>{t.name}</strong><span>{data.team_members.filter((m:any)=>m.team_id===t.id).map((m:any)=>data.staff.find((s:any)=>s.id===m.staff_id)?.name).join(', ')||'No members yet'}</span>{canPlan(data.actor)&&<button onClick={()=>{setEdit({...t,staff_ids:data.team_members.filter((m:any)=>m.team_id===t.id).map((m:any)=>m.staff_id)});setError('');}}>Edit members</button>}</div>)}
 {transfer&&<div className="modal-backdrop"><section className="modal"><h2>Move researcher between teams</h2><p>Existing work keeps its original team and attribution. Future allocations use the new roster. Change the team lead first if moving the current lead.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('mutate',{kind:'team-transfer',...transfer,from_version:data.teams.find((t:any)=>t.id===transfer.from)?.roster_version||0,to_version:data.teams.find((t:any)=>t.id===transfer.to)?.roster_version||0});await reload();setTransfer(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><label>Researcher<select required value={transfer.staff_id} onChange={e=>setTransfer({...transfer,staff_id:e.target.value,from:''})}><option value="">Choose researcher</option>{data.staff.filter((s:any)=>!s.archived).map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>From team<select required value={transfer.from} onChange={e=>setTransfer({...transfer,from:e.target.value})}><option value="">Choose team</option>{data.teams.filter((t:any)=>data.team_members.some((m:any)=>m.team_id===t.id&&m.staff_id===transfer.staff_id)).map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>To team<select required value={transfer.to} onChange={e=>setTransfer({...transfer,to:e.target.value})}><option value="">Choose team</option>{data.teams.filter((t:any)=>t.id!==transfer.from).map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{error&&<p className="error">{error}</p>}<button disabled={busy}>Move researcher</button><button type="button" onClick={()=>setTransfer(null)}>Cancel</button></form></section></div>}
 {edit&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="team-title"><div className="section-head"><h2 id="team-title">{edit.name} researchers</h2><button disabled={busy} onClick={()=>setEdit(null)}>Cancel</button></div><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('mutate',{kind:'team-members',id:edit.id,version:edit.roster_version,staff_ids:edit.staff_ids});await reload();setEdit(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>
 <p className="fine">Existing assignments keep their original researchers. Only active accounts with Researcher access can join a team. Invite colleagues in People & access and wait for acceptance first.</p>
 {!data.staff.length&&<p>Enable Researcher for an existing person in People & access first.</p>}
 {data.staff.filter((s:any)=>!s.archived).map((s:any)=><label className="checkbox" key={s.id}><input type="checkbox" disabled={busy} checked={edit.staff_ids.includes(s.id)} onChange={e=>setEdit({...edit,staff_ids:e.target.checked?[...edit.staff_ids,s.id]:edit.staff_ids.filter((id:string)=>id!==s.id)})}/>{s.name}</label>)}
 {error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Saving…':'Save team members'}</button></form></section></div>}
 </section>;
}
