import {displayDate} from './dates';
import React,{useState} from 'react';
import {hasRole} from './domain';
import {addDays,weekDays} from './planning';
import {Popup} from './Popup';
type R=Record<string,any>;
export function TimeOff({data,dates,api,reload,disabled=false}:{data:R;dates:string[];api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;disabled?:boolean}){
 const [open,setOpen]=useState(false),[week,setWeek]=useState(dates[0]),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const days=weekDays(week),admin=hasRole(data.actor,'admin');
 async function save(staff_id:string,work_date:string,pto:boolean){const old=(data.timeOff||[]).find((r:R)=>r.staff_id===staff_id&&r.work_date===work_date);setBusy(true);setError('');try{await api('mutate',{kind:'pto',staff_id,work_date,pto,version:old?.version||0});await reload();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <><button disabled={disabled} onClick={()=>{setWeek(dates[0]);setOpen(true);}}>PTO calendar</button>{open&&<Popup title="PTO calendar" onClose={()=>{if(!busy)setOpen(false);}}><div className="plan-toolbar"><button aria-label="Previous PTO week" onClick={()=>setWeek(addDays(week,-7))}>←</button><strong>{displayDate(days[0])} – {displayDate(days[6])}</strong><button aria-label="Next PTO week" onClick={()=>setWeek(addDays(week,7))}>→</button><input aria-label="Find team member" type="search" placeholder="Find team member…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="table-scroll"><table className="sheet-table pto-calendar"><thead><tr><th>Team member</th>{days.map(d=><th key={d}>{new Intl.DateTimeFormat('en',{weekday:'short',timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'))}<small>{displayDate(d)}</small></th>)}</tr></thead><tbody>{data.staff.filter((s:R)=>!s.archived&&s.name.toLowerCase().includes(query.toLowerCase())).sort((a:R,b:R)=>a.name.localeCompare(b.name)).map((s:R)=><tr key={s.id}><th scope="row">{s.name}</th>{days.map(d=>{const pto=(data.timeOff||[]).some((r:R)=>r.staff_id===s.id&&r.work_date===d&&r.pto);return <td key={d}><button className={pto?'pto-day on-pto':'pto-day'} disabled={busy||(!admin&&data.actor.staffId!==s.id)} aria-label={`${s.name}, ${displayDate(d)}: ${pto?'On PTO':'Not on PTO'}`} aria-pressed={pto} onClick={()=>save(s.id,d,!pto)}>{pto?'PTO':'—'}</button></td>;})}</tr>)}</tbody></table></div><p className="fine">PTO counts as zero person-days across all searches. Team targets remain unchanged.</p>{error&&<p className="error" role="alert">{error}</p>}</Popup>}</>;
}
