import React,{useState} from 'react';
import {canPlan,hasRole} from './domain';
type R=Record<string,any>;
export function TimeOff({data,dates,api,reload,disabled=false}:{data:R;dates:string[];api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;disabled?:boolean}){
 const planner=canPlan(data.actor),canEdit=planner||hasRole(data.actor,'researcher')&&!!data.actor.staffId;
 const [staff,setStaff]=useState(data.actor.staffId||''),[date,setDate]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const day=dates.includes(date)?date:dates[0],rows=(data.timeOff||[]).filter((r:R)=>r.pto&&dates.includes(r.work_date));
 async function save(staff_id:string,work_date:string,pto:boolean){const old=(data.timeOff||[]).find((r:R)=>r.staff_id===staff_id&&r.work_date===work_date);setBusy(true);setError('');try{await api('mutate',{kind:'pto',staff_id,work_date,pto,version:old?.version||0});await reload();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <details className="time-off"><summary>Time off · {rows.length} PTO days this week</summary>{canEdit&&<div className="sheet-toolbar">{planner&&<label>Researcher<select disabled={disabled||busy} value={staff} onChange={e=>setStaff(e.target.value)}><option value="">Choose researcher</option>{data.staff.filter((s:R)=>!s.archived).map((s:R)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<label>Date<select disabled={disabled||busy} value={day} onChange={e=>setDate(e.target.value)}>{dates.map(d=><option key={d}>{d}</option>)}</select></label><button disabled={disabled||busy||!staff} onClick={()=>save(staff,day,true)}>Mark on PTO</button></div>}<p className="fine">PTO counts as zero person-days across all searches. The team’s target stays unchanged.</p>{rows.map((r:R)=><div className="row-actions" key={r.staff_id+r.work_date}><span>{data.staff.find((s:R)=>s.id===r.staff_id)?.name||'Researcher'} · {r.work_date} · On PTO</span>{(planner||hasRole(data.actor,'researcher')&&data.actor.staffId===r.staff_id)&&<button disabled={disabled||busy} onClick={()=>save(r.staff_id,r.work_date,false)}>Remove PTO</button>}</div>)}{error&&<p className="error" role="alert">{error}</p>}</details>;
}
