import {useViewState} from './ViewState';
import {displayDate,displayDateTime} from './dates';
import {planWorkload} from './plan-workload';
import {PlanningTasks} from './PlanningTasks';
import {teamColor} from './team-colors';
import {TimeOff} from './TimeOff';
import {compareTableValues} from './table-sort';
import {SearchDecisions} from './SearchDecisions';
import {effectiveDecision,isWorkingDecision,sourcingDecisions} from './search-decisions';
import {Plus,ArrowsLeftRight} from '@phosphor-icons/react';
import {SearchMultiFilter} from './SearchMultiFilter';
import {hasRole,canPlan,canPartnerReview,roleList,roleLabel} from './domain';
import React,{useEffect,useState} from 'react';
import {addDays,weekStart,weekDays} from './planning';
type Row=Record<string,any>;
type Props={data:Row;api:(path:string,body?:unknown)=>Promise<any>;reload:()=>Promise<void>;initialSearch?:string;initialDate?:string;initialView?:'decisions'|'allocation';onDirty:(dirty:boolean)=>void;onTeams:()=>void;onCandidate:(id:string)=>void};
const label=(date:string)=>displayDate(date);
export function WeeklyPlanner({data,api,reload,initialSearch='',initialDate='',initialView='decisions',onDirty,onTeams,onCandidate}:Props) {
 const [week,setWeek]=useViewState('WeeklyPlanner.week',()=>weekStart(initialDate||new Date().toLocaleDateString('en-CA'))),[mode,setMode]=useViewState<'search'|'team'>('WeeklyPlanner.mode','search');
 const [gridSort,setGridSort]=useViewState('WeeklyPlanner.gridSort',{key:'name',descending:false});
 const [view,setView]=useViewState<'decisions'|'allocation'>('WeeklyPlanner.view',initialView),[decisionFilter,setDecisionFilter]=useViewState('WeeklyPlanner.decisionFilter','');
 const [roles,setRoles]=useViewState<string[]|null>('WeeklyPlanner.roles',initialSearch?[initialSearch]:null);
 const [filter,setFilter]=useViewState('WeeklyPlanner.filter',''),[editor,setEditor]=useState<Row|null>(null),[priority,setPriority]=useState<Row|null>(null),[change,setChange]=useState<Row|null>(null);
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
 const planner=canPlan(data.actor),dates=weekDays(week);
 const onPTO=(staff:string,date:string)=>(data.timeOff||[]).some((r:Row)=>r.staff_id===staff&&r.work_date===date&&r.pto);
 const searches=new Map<string,Row>(data.searches.map((s:Row)=>[s.id,s])),teams=new Map<string,Row>(data.teams.map((t:Row)=>[t.id,t]));
 const tasks=(data.research?.records||[]).filter((t:Row)=>t.kind==='task'&&dates.includes(t.work_date)&&t.status!=='Cancelled');
 const teamBadge=(id:string)=><span className="plan-team-badge" style={{'--team-color':teamColor(teams.get(id)?.name||'',id)} as React.CSSProperties}>{teams.get(id)?.name||'Team'}</span>;
 const assignments=data.assignments.filter((a:Row)=>dates.includes(a.work_date));
 useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function close(){if(dirty&&!confirm('Discard unsaved planning changes?'))return;setEditor(null);setPriority(null);setChange(null);setDirty(false);setError('');}
 function openPair(search_id='',team_id='',clickedDate='') {
  setError('');setEditor(pair(search_id,team_id,clickedDate));setDirty(false);
 }
 function pair(search_id:string,team_id:string,clickedDate='') {
  const days=dates.map(date=>{const old=assignments.find((a:Row)=>a.search_id===search_id&&a.team_id===team_id&&a.work_date===date);return {date,id:old?.id,version:old?.version,enabled:!!old||date===clickedDate,target:old?.target ?? '',notes:old?.notes || '',has_work:old?.has_work,staff_ids:old?data.entries.filter((e:Row)=>e.assignment_id===old.id).map((e:Row)=>e.staff_id):data.team_members.filter((m:Row)=>m.team_id===team_id&&!onPTO(m.staff_id,date)).map((m:Row)=>m.staff_id)};});
  return {search_id,team_id,clickedDate,days,roster_version:teams.get(team_id)?.roster_version || 0};
 }
 function choosePair(search_id:string,team_id:string){if(dirty&&!confirm('Discard edits before changing the search or team?'))return;setEditor(pair(search_id,team_id,editor?.clickedDate));setDirty(false);setError('');}
 function changeDay(index:number,patch:Row){setEditor({...editor,days:editor!.days.map((d:Row,i:number)=>i===index?{...d,...patch}:d)});setDirty(true);}
 async function savePlan(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('mutate',{kind:'week-plan',week,...editor});await reload();setEditor(null);setDirty(false);setNotice('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function savePriority(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('mutate',{kind:'decision',...priority});await reload();setPriority(null);setDirty(false);setNotice('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 function openChange(search_id:string,team_id:string,date='') {
  if(dirty&&!confirm('Discard unsaved edits before moving assignments?'))return;
  const rows=assignments.filter((a:Row)=>a.search_id===search_id&&a.team_id===team_id);
  setChange({search_id,team_id,operation:isWorkingDecision(effectiveDecision(data.priorities,search_id,week))?'move':'unassign',destination_team_id:'',rows,selected:rows.filter((a:Row)=>!a.has_work&&(!date||a.work_date===date)).map((a:Row)=>a.id)});setEditor(null);setPriority(null);setDirty(true);setError('');
 }
 async function transfer(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('mutate',{kind:'plan-transfer',operation:change!.operation,week,search_id:change!.search_id,team_id:change!.team_id,destination_team_id:change!.destination_team_id,roster_version:teams.get(change!.destination_team_id)?.roster_version||0,items:change!.rows.filter((a:Row)=>change!.selected.includes(a.id)).map((a:Row)=>({id:a.id,version:a.version}))});await reload();setNotice(change!.operation==='move'?'Selected daily assignments moved to the new team.':'Selected daily assignments unassigned.');setChange(null);setDirty(false);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const decisionFor=(id:string,w=week)=>effectiveDecision(data.priorities,id,w);
 const eligible=(r:Row)=>decisionFilter==='undecided'?!decisionFor(r.id):!decisionFilter||decisionFilter==='working'||decisionFor(r.id)?.disposition===decisionFilter;
 const decisionRoles=data.searches.filter((r:Row)=>(roles===null||roles.includes(r.id))&&eligible(r));
 const entities=(mode==='search'?data.searches:data.teams).filter((r:Row)=>(mode==='search'?(roles===null||roles.includes(r.id))&&(eligible(r)||tasks.some((t:Row)=>t.role_id===r.id)):(!filter||r.id===filter)));
 const visible=assignments.filter((a:Row)=>entities.some((r:Row)=>r.id===(mode==='search'?a.search_id:a.team_id))&&eligible(searches.get(a.search_id)||{id:a.search_id}));
 const entityValue=(r:Row)=>gridSort.key==='name'?(mode==='search'?`${r.client} ${r.title}`:r.name):visible.filter((a:Row)=>(mode==='search'?a.search_id:a.team_id)===r.id&&(gridSort.key==='total'||a.work_date===gridSort.key)).reduce((n:number,a:Row)=>n+(a.target||0),0);
 const sortedEntities=[...entities].sort((a:Row,b:Row)=>compareTableValues(entityValue(a),entityValue(b),gridSort.descending)||String(a.id).localeCompare(String(b.id)));
 const gridHeading=(key:string,title:string)=><th key={key} scope="col" aria-sort={gridSort.key===key?(gridSort.descending?'descending':'ascending'):'none'}><button className="table-sort-heading" onClick={()=>setGridSort({key,descending:gridSort.key===key?!gridSort.descending:false})}>{title} <span aria-hidden="true">{gridSort.key===key?(gridSort.descending?'↓':'↑'):'↕'}</span></button></th>;
 function editPriority(s:Row,decisionWeek=week){const p=data.priorities.find((p:Row)=>p.search_id===s.id&&p.week===decisionWeek),effective=decisionFor(s.id,decisionWeek);setPriority({search_id:s.id,week:decisionWeek,disposition:effective?.disposition || 'Start',notes:effective?.notes || '',version:p?.version || 0,base_week:effective?.week||'',base_version:effective?.version||0});setError('');setDirty(false);}
 function allocation(id:string,review=false){setView('allocation');setMode('search');setRoles([id]);setDecisionFilter('');if(!review)openPair(id);}

 return <section className="panel weekly-planner">
  <div className="weekly-topbar"><div className="research-tabs"><button className={view==='decisions'?'primary':''} onClick={()=>{setView('decisions');setDecisionFilter('');}}>Search Decisions</button><button className={view==='allocation'?'primary':''} onClick={()=>{setView('allocation');setDecisionFilter('');}}>Team Allocation</button></div><div className="weekly-top-actions"><TimeOff data={data} dates={dates} api={api} reload={reload} disabled={dirty||busy}/>{planner&&<button className="primary" onClick={()=>openPair(mode==='search'&&roles?.length===1?roles[0]:'',mode==='team'?filter:'')}>Plan week</button>}</div></div>
  <div className="plan-toolbar">
   <button aria-label="Previous week" onClick={()=>setWeek(addDays(week,-7))}>←</button>
   <label>Week of Monday<input type="date" value={week} onChange={e=>{if(e.target.value)setWeek(weekStart(e.target.value));}}/></label>
   <button aria-label="Next week" onClick={()=>setWeek(addDays(week,7))}>→</button>
   <button onClick={()=>setWeek(weekStart(new Date().toLocaleDateString('en-CA')))}>This week</button>
   {view==='allocation'&&<label>View<select value={mode} onChange={e=>{setMode(e.target.value as 'search'|'team');setFilter('');}}><option value="search">By search</option><option value="team">By team</option></select></label>}
   {(view==='decisions'||mode==='search')?<SearchMultiFilter searches={data.searches} value={roles} onChange={setRoles} disabled={dirty||busy}/>:<label>Team<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All teams</option>{data.teams.map((r:Row)=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>}
   <label>Sourcing decision<select value={decisionFilter==='working'?'':decisionFilter} onChange={e=>setDecisionFilter(e.target.value)}><option value="">All decisions</option><option value="undecided">Not decided</option>{sourcingDecisions.map(d=><option key={d}>{d}</option>)}</select></label>
  </div>
  {notice&&<p className="notice" role="status">{notice}</p>}
  {!editor&&!priority&&!change&&error&&<p className="error" role="alert">{error}</p>}
  {!data.teams.length&&<p className="source-note">Create teams and add their researchers in Teams before allocating work.</p>}
  {view==='decisions'?<SearchDecisions onCandidate={onCandidate} data={data} roles={decisionRoles} week={week} canEdit={planner} onDecide={editPriority} onAllocate={id=>allocation(id)} onReviewPlan={(id,date)=>{setWeek(weekStart(date));allocation(id,true);}}/>:<div className="plan-scroll"><table className="plan-grid"><thead><tr>{gridHeading('name',mode==='search'?'Search / weekly priority':'Team / researchers')}{dates.map(d=>gridHeading(d,label(d)))}{gridHeading('total','Week target')}</tr></thead><tbody>
   {sortedEntities.map((r:Row)=>{const row=visible.filter((a:Row)=>(mode==='search'?a.search_id:a.team_id)===r.id),p=decisionFor(r.id);return <tr key={r.id}>
    <th scope="row">{mode==='search'?<><strong>{r.client}</strong><span>{r.title}</span><small>Partner: {r.partner || 'Not assigned'}</small><div className="priority-line"><span className={p?`badge plan-priority-badge priority-${p.disposition.toLowerCase()}`:"plan-priority-text priority-text-none"}>{p?.disposition || 'No priority'}</span>{planner&&<button className="plan-priority-edit" aria-label={`${p?'Edit':'Set'} weekly priority for ${r.client} — ${r.title}`} onClick={()=>editPriority(r)}>{p?'Edit':'Set'}</button>}</div>{p?.notes&&<small>{p.notes}</small>}</>:<><strong style={{borderLeft:`4px solid ${teamColor(r.name,r.id)}`,paddingLeft:6}}>{r.name}</strong><small>{data.team_members.filter((m:Row)=>m.team_id===r.id).map((m:Row)=>data.staff.find((s:Row)=>s.id===m.staff_id)?.name).join(', ')||'No members configured'}</small>{canPlan(data.actor)&&<button onClick={onTeams}>Edit team</button>}</>}</th>
    {dates.map(date=>{const cell=row.filter((a:Row)=>a.work_date===date),cellTasks=tasks.filter((t:Row)=>t.work_date===date&&(mode==='search'?t.role_id===r.id:t.team_id===r.id)),cellTeams=[...new Set<string>([...cell.map((a:Row)=>a.team_id),...cellTasks.map((t:Row)=>t.team_id)])];return <td key={date}>
     {cell.map((a:Row)=>{const other=mode==='search'?teams.get(a.team_id)?.name:`${searches.get(a.search_id)?.client} · ${searches.get(a.search_id)?.title}`;const disposition=decisionFor(a.search_id)?.disposition;return <div className="plan-assignment" key={a.id}><button className={`plan-slot priority-${(disposition || 'none').toLowerCase()}`} key={a.id} disabled={!planner} onClick={()=>{setEditor(pair(a.search_id,a.team_id));setError('');setDirty(false);}}>{teamBadge(a.team_id)}{mode==='team'&&<span>{other}</span>}{disposition&&<small>{disposition}</small>}<strong>{a.target??'—'} <small>target</small></strong>{[...new Set<string>(data.entries.filter((e:Row)=>e.assignment_id===a.id&&e.source!=='candidates'&&onPTO(e.staff_id,date)).map((e:Row)=>e.staff_id))].map(id=><small className="plan-warning" key={id}>{data.staff.find((s:Row)=>s.id===id)?.name} · PTO</small>)}</button>{planner&&<button className="plan-icon plan-transfer" title="Move / unassign" aria-label={`Move or unassign ${other} on ${label(date)}`} onClick={()=>openChange(a.search_id,a.team_id,date)}><ArrowsLeftRight size={14}/></button>}</div>;})}
     {cellTasks.length>0&&<details className="plan-other-tasks"><summary>{cellTasks.length} other task{cellTasks.length===1?'':'s'} <span className="plan-team-dots">{[...new Set<string>(cellTasks.map((t:Row)=>t.team_id))].map(id=><span key={id} title={teams.get(id)?.name} style={{background:teamColor(teams.get(id)?.name||'',id)}}/>)}</span></summary><div className="plan-task-popover">{cellTasks.map((t:Row)=><div className="plan-task-mini" key={t.id}>{teamBadge(t.team_id)}<strong>{t.title||t.task_type}</strong><small>{data.people.find((p:Row)=>p.id===t.owner_id)?.name||'Former member'} · {t.status}</small>{mode==='team'&&<small>{searches.get(t.role_id)?.client} · {searches.get(t.role_id)?.title}</small>}</div>)}</div></details>}
     {cellTeams.map(id=>{const warnings=planWorkload(data,date,id);return warnings.length>0&&<details className="plan-load-warning" key={id}><summary>Check workload · {teams.get(id)?.name}</summary>{warnings.map(w=><small key={w.staff}>{w.name}: {w.pto?'work scheduled during PTO':`${w.count} planned items today`}</small>)}</details>;})}
     {planner&&(mode==='team'||isWorkingDecision(decisionFor(r.id)))&&<button className="plan-icon plan-assign-icon" title="Assign" aria-label={`Plan ${mode==='search'?r.title:r.name} on ${label(date)}`} onClick={()=>openPair(mode==='search'?r.id:'',mode==='team'?r.id:'',date)}><Plus size={11}/></button>}
     {!cell.length&&!cellTasks.length&&!planner&&<span className="fine">—</span>}
    </td>;})}<td><strong>{row.reduce((n:number,a:Row)=>n+(a.target||0),0)}</strong>{row.some((a:Row)=>a.target===null)&&<small>Some targets unset</small>}</td></tr>;})}
   {!entities.length&&<tr><td colSpan={9}>No {mode==='search'?'searches':'teams'} match this view.</td></tr>}
  </tbody><tfoot><tr><th>Visible target total</th>{dates.map(date=><td key={date}>{visible.filter((a:Row)=>a.work_date===date).reduce((n:number,a:Row)=>n+(a.target||0),0)}</td>)}<td>{visible.reduce((n:number,a:Row)=>n+(a.target||0),0)}</td></tr></tfoot></table></div>}
  {!editor&&!priority&&!change&&<PlanningTasks data={data} api={api} reload={reload} from={dates[0]} to={dates[6]} roles={mode==='search'?roles:null} teamId={mode==='team'?filter:''} onDirty={onDirty}/>}
  {change&&<div className="modal-backdrop"><section className="modal plan-modal" role="dialog" aria-modal="true" aria-labelledby="transfer-title"><div className="section-head"><h2 id="transfer-title">Move or unassign planned work</h2><button disabled={busy} onClick={close}>Cancel</button></div><p><strong>{searches.get(change.search_id)?.client} · {searches.get(change.search_id)?.title}</strong><br/>Currently planned for {teams.get(change.team_id)?.name}</p><form onSubmit={transfer}><label>Action<select value={change.operation} disabled={busy} onChange={e=>setChange({...change,operation:e.target.value})}><option value="move" disabled={!isWorkingDecision(decisionFor(change.search_id))}>Move to another team</option><option value="unassign">Unassign selected days</option></select></label>{change.operation==='move'&&<label>New team<select required disabled={busy} value={change.destination_team_id} onChange={e=>setChange({...change,destination_team_id:e.target.value})}><option value="">Choose team</option>{data.teams.filter((t:Row)=>t.id!==change.team_id).map((t:Row)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}<div className="row-actions"><button type="button" disabled={busy} onClick={()=>setChange({...change,selected:change.rows.filter((a:Row)=>!a.has_work).map((a:Row)=>a.id)})}>Select all unstarted days this week</button><button type="button" disabled={busy} onClick={()=>setChange({...change,selected:[]})}>Clear selection</button></div><table className="sheet-table"><thead><tr><th>Select</th><th>Day</th><th>Target</th><th>Work status</th></tr></thead><tbody>{change.rows.map((a:Row)=><tr key={a.id}><td><input type="checkbox" aria-label={'Change assignment on '+a.work_date} disabled={busy||a.has_work} checked={change.selected.includes(a.id)} onChange={e=>setChange({...change,selected:e.target.checked?[...change.selected,a.id]:change.selected.filter((id:string)=>id!==a.id)})}/></td><td>{label(a.work_date)}</td><td>{a.target??'—'}</td><td>{a.has_work?'Recorded work — attribution retained':'Not started'}</td></tr>)}</tbody></table><p className="fine">Moving retains daily targets and notes and uses the new team’s current researcher roster. This changes the weekly plan; company ownership is managed separately under the role’s Target companies. Existing candidate work keeps its original attribution.</p>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy||!change.selected.length||change.operation==='move'&&!change.destination_team_id}>{busy?'Saving…':change.operation==='move'?'Move selected assignments':'Unassign selected days'}</button></form></section></div>}
  {(editor||priority)&&<div className="modal-backdrop"><section className="modal plan-modal" role="dialog" aria-modal="true" aria-labelledby="plan-title"><div className="section-head"><h2 id="plan-title">{editor?'Plan the week':'Sourcing decision'}</h2><button disabled={busy} onClick={close}>Close</button></div>
   {error&&<p className="error" role="alert">{error}</p>}
   {editor?<form onSubmit={savePlan}>
    <div className="plan-selectors"><label>Search<select required disabled={busy||editor.days.some((d:Row)=>d.id)} value={editor.search_id} onChange={e=>choosePair(e.target.value,editor.team_id)}><option value="">Choose search</option>{data.searches.filter((s:Row)=>s.id===editor.search_id||isWorkingDecision(decisionFor(s.id))).map((s:Row)=><option key={s.id} value={s.id}>{s.client} · {s.title}</option>)}</select></label>
    <label>Team<select required disabled={busy||editor.days.some((d:Row)=>d.id)} value={editor.team_id} onChange={e=>choosePair(editor.search_id,e.target.value)}><option value="">Choose team</option>{data.teams.map((t:Row)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label></div>
    {editor.days.some((d:Row)=>d.id)&&<button type="button" disabled={busy} onClick={()=>openChange(editor.search_id,editor.team_id)}>Move / unassign this week’s assignments</button>}
    <p className="fine">Partner: {searches.get(editor.search_id)?.partner || 'Not assigned — set on the search'}. Team researchers: {data.team_members.filter((m:Row)=>m.team_id===editor.team_id).map((m:Row)=>data.staff.find((s:Row)=>s.id===m.staff_id)?.name).join(', ')||'none configured'}.</p>

    {editor.days.length>0&&<><div className="row-actions"><button type="button" disabled={busy||!editor.search_id||!editor.team_id} onClick={()=>{setEditor({...editor,days:editor.days.map((d:Row,i:number)=>({...d,enabled:d.enabled||i<5}))});setDirty(true);}}>Select Mon–Fri</button><label>Target to repeat<input type="number" min="0" max="100000" step="1" value={editor.fillTarget ?? ''} disabled={busy} onChange={e=>setEditor({...editor,fillTarget:e.target.value})}/></label><button type="button" disabled={busy||editor.fillTarget===undefined||editor.fillTarget===''||!editor.days.some((d:Row)=>d.enabled)} onClick={()=>{setEditor({...editor,days:editor.days.map((d:Row)=>d.enabled?{...d,target:editor.fillTarget}:d)});setDirty(true);}}>Fill selected days</button></div><p className="fine">Uncheck a day to remove unstarted work. Choose the specific researchers working on each day. Days with recorded work retain their allocation.</p>
    <div className="table-scroll"><table className="plan-editor"><thead><tr><th>Work?</th><th>Day</th><th>Researchers</th><th>Daily approval target</th><th>Notes</th></tr></thead><tbody>{editor.days.map((d:Row,i:number)=><tr key={d.date}><td><input type="checkbox" aria-label={`Work on ${label(d.date)}`} checked={d.enabled} disabled={busy||!editor.search_id||!editor.team_id} onChange={e=>changeDay(i,{enabled:e.target.checked})}/></td><th>{label(d.date)}{d.id&&<small>Existing · {data.entries.filter((e:Row)=>e.assignment_id===d.id).map((e:Row)=>data.staff.find((s:Row)=>s.id===e.staff_id)?.name).join(', ')||'no researchers'}</small>}</th><td>{data.staff.filter((s:Row)=>d.staff_ids.includes(s.id)||data.team_members.some((m:Row)=>m.team_id===editor.team_id&&m.staff_id===s.id)).map((s:Row)=><label key={s.id} style={{display:'flex',gap:6,alignItems:'center'}}><input type="checkbox" style={{width:'auto'}} aria-label={`${s.name} on ${label(d.date)}`} disabled={busy||!d.enabled||d.has_work} checked={d.staff_ids.includes(s.id)} onChange={e=>changeDay(i,{staff_ids:e.target.checked?[...d.staff_ids,s.id]:d.staff_ids.filter((id:string)=>id!==s.id)})}/>{s.name}{onPTO(s.id,d.date)&&' · PTO (0 person-days)'}</label>)}{d.has_work&&<small>Recorded work · allocation retained</small>}</td><td><input aria-label={`Target for ${label(d.date)}`} type="number" min="0" max="100000" step="1" required={d.enabled} disabled={!d.enabled||busy||!editor.search_id||!editor.team_id} value={d.target} onChange={e=>changeDay(i,{target:e.target.value})}/></td><td><input aria-label={`Notes for ${label(d.date)}`} disabled={!d.enabled||busy||!editor.search_id||!editor.team_id} value={d.notes} onChange={e=>changeDay(i,{notes:e.target.value})}/></td></tr>)}</tbody></table></div></>}
    <button className="primary" disabled={busy||editor.days.length!==7||!editor.search_id||!editor.team_id}>{busy?'Saving…':'Save week'}</button>
   </form>:<form onSubmit={savePriority}><p>{searches.get(priority!.search_id)?.client} · {searches.get(priority!.search_id)?.title}</p><p>{displayDate(priority!.week)}</p><label>Sourcing decision<select value={priority!.disposition} disabled={busy} onChange={e=>{setPriority({...priority,disposition:e.target.value});setDirty(true);}}>{['Start','Continue','Recalibrate','Pause','Stop'].map(s=><option key={s}>{s}</option>)}</select></label><label>Reason / notes<textarea value={priority!.notes} disabled={busy} onChange={e=>{setPriority({...priority,notes:e.target.value});setDirty(true);}}/></label><p className="fine">Pause and Stop change the weekly priority. Review the grid to remove any unstarted daily assignments separately.</p><button className="primary" disabled={busy}>{busy?'Saving…':'Save decision'}</button></form>}
  </section></div>}
 </section>;
}
