import {Popup} from './Popup';
import {carryoverAssignments} from './plan-carryover';
import {ColumnFilter} from './ColumnFilter';
import {matchesPlanningSearch,searchStatus,searchStatuses} from './planning-filters';
import {useViewState} from './ViewState';
import {displayDate,displayDateTime} from './dates';
import {workloadIndex} from './plan-workload';
import {PlanningTasks} from './PlanningTasks';
import {teamColor} from './team-colors';
import {TimeOff} from './TimeOff';
import {compareTableValues} from './table-sort';
import {SearchDecisions} from './SearchDecisions';
import {effectiveDecision,isWorkingDecision,sourcingDecisions} from './search-decisions';
import {IconAction} from './IconAction';
import {Plus,ArrowsLeftRight,PencilSimple,WarningCircle} from '@phosphor-icons/react';
import {SearchMultiFilter} from './SearchMultiFilter';
import {hasRole,canPlan,canPartnerReview,roleList,roleLabel} from './domain';
import React,{useEffect,useState,useMemo} from 'react';
import {addDays,weekStart,weekDays} from './planning';
type Row=Record<string,any>;
type Props={data:Row;api:(path:string,body?:unknown)=>Promise<any>;reload:()=>Promise<void>;initialSearch?:string;initialDate?:string;initialView?:'decisions'|'allocation';onDirty:(dirty:boolean)=>void;onTeams:()=>void;onCandidate:(id:string)=>void};
const label=(date:string)=>displayDate(date);
export function WeeklyPlanner({data,api,reload,initialSearch='',initialDate='',initialView='decisions',onDirty,onTeams,onCandidate}:Props) {
 const [week,setWeek]=useViewState('WeeklyPlanner.week',()=>weekStart(initialDate||new Date().toLocaleDateString('en-CA'))),[mode,setMode]=useViewState<'search'|'team'>('WeeklyPlanner.mode','search');
 const [gridSort,setGridSort]=useViewState('WeeklyPlanner.gridSort',{key:'name',descending:false});
 const [view,setView]=useViewState<'decisions'|'allocation'>('WeeklyPlanner.view',initialView),[decisionFilters,setDecisionFilters]=useViewState<string[]|null>('WeeklyPlanner.decisionFilters',null);
 const [statusFilters,setStatusFilters]=useViewState<string[]|null>('WeeklyPlanner.statusFilters',['Open']),[teamFilters,setTeamFilters]=useViewState<string[]|null>('WeeklyPlanner.teamFilters',null);
 const [roles,setRoles]=useViewState<string[]|null>('WeeklyPlanner.roles',initialSearch?[initialSearch]:null);
 const [filter,setFilter]=useViewState('WeeklyPlanner.filter',''),[editor,setEditor]=useState<Row|null>(null),[priority,setPriority]=useState<Row|null>(null),[change,setChange]=useState<Row|null>(null);
 const [copy,setCopy]=useState<Row[]|null>(null),[workload,setWorkload]=useState<{team:string;date:string}|null>(null);
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
 const warningsFor=useMemo(()=>workloadIndex(data),[data]);
 const planner=canPlan(data.actor),dates=weekDays(week);
 const onPTO=(staff:string,date:string)=>(data.timeOff||[]).some((r:Row)=>r.staff_id===staff&&r.work_date===date&&r.pto);
 const searches=new Map<string,Row>(data.searches.map((s:Row)=>[s.id,s])),teams=new Map<string,Row>(data.teams.map((t:Row)=>[t.id,t]));
 const tasks=(data.research?.records||[]).filter((t:Row)=>t.kind==='task'&&dates.includes(t.work_date)&&t.status!=='Cancelled');
 const teamBadge=(id:string)=><span className="plan-team-badge" style={{'--team-color':teamColor(teams.get(id)?.name||'',id)} as React.CSSProperties}>{teams.get(id)?.name||'Team'}</span>;
 const assignments=data.assignments.filter((a:Row)=>dates.includes(a.work_date));
 useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function close(){if(dirty&&!confirm('Discard unsaved planning changes?'))return;setEditor(null);setPriority(null);setChange(null);setDirty(false);setError('');}
 function openPair(search_id='',team_id='',clickedDate='') {
  setError('');setEditor(pair(search_id,team_id,clickedDate));setDirty(false);
 }
 function pair(search_id:string,team_id:string,clickedDate='') {
  const days=dates.map(date=>{const old=assignments.find((a:Row)=>a.search_id===search_id&&a.team_id===team_id&&a.work_date===date);return {date,id:old?.id,version:old?.version,enabled:!!old||date===clickedDate,target:old?.target ?? '',notes:old?.notes || '',has_work:old?.has_work,staff_ids:old?data.entries.filter((e:Row)=>e.assignment_id===old.id).map((e:Row)=>e.staff_id):data.team_members.filter((m:Row)=>m.team_id===team_id&&!onPTO(m.staff_id,date)).map((m:Row)=>m.staff_id)};});
  return {search_id,team_id,clickedDate,days,roster_version:teams.get(team_id)?.roster_version || 0};
 }
 function choosePair(search_id:string,team_id:string){if(dirty&&!confirm('Discard edits before changing the search or team?'))return;setEditor(pair(search_id,team_id,editor?.clickedDate));setDirty(false);setError('');}
 function changeDay(index:number,patch:Row){setEditor({...editor,days:editor!.days.map((d:Row,i:number)=>i===index?{...d,...patch}:d)});setDirty(true);}
 async function savePlan(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('mutate',{kind:'week-plan',week,...editor});await reload();setEditor(null);setDirty(false);setNotice('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function savePriority(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('mutate',{kind:'decision',...priority});await reload();setPriority(null);setDirty(false);setNotice('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 function openChange(search_id:string,team_id:string,date='') {
  if(dirty&&!confirm('Discard unsaved edits before moving assignments?'))return;
  const rows=assignments.filter((a:Row)=>a.search_id===search_id&&a.team_id===team_id);
  setChange({search_id,team_id,operation:isWorkingDecision(effectiveDecision(data.priorities,search_id,week))?'move':'unassign',destination_team_id:'',rows,selected:rows.filter((a:Row)=>!a.has_work&&(!date||a.work_date===date)).map((a:Row)=>a.id)});setEditor(null);setPriority(null);setDirty(true);setError('');
 }
 async function transfer(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('mutate',{kind:'plan-transfer',operation:change!.operation,week,search_id:change!.search_id,team_id:change!.team_id,destination_team_id:change!.destination_team_id,roster_version:teams.get(change!.destination_team_id)?.roster_version||0,items:change!.rows.filter((a:Row)=>change!.selected.includes(a.id)).map((a:Row)=>({id:a.id,version:a.version}))});await reload();setNotice(change!.operation==='move'?'Selected daily assignments moved to the new team.':'Selected daily assignments unassigned.');setChange(null);setDirty(false);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const decisionFor=(id:string,w=week)=>effectiveDecision(data.priorities,id,w);
 const eligible=(r:Row)=>matchesPlanningSearch(r,data.priorities,week,decisionFilters,statusFilters,roles);
 const decisionRoles=data.searches.filter((r:Row)=>eligible(r));
 const entities=(mode==='search'?data.searches:data.teams).filter((r:Row)=>(mode==='search'?eligible(r):(teamFilters===null||teamFilters.includes(r.id))));
 const visible=assignments.filter((a:Row)=>entities.some((r:Row)=>r.id===(mode==='search'?a.search_id:a.team_id))&&eligible(searches.get(a.search_id)||{id:a.search_id}));
 const entityValue=(r:Row)=>gridSort.key==='search_number'?r.search_number:gridSort.key==='status'?searchStatus(r.status):gridSort.key==='name'?(mode==='search'?`${r.client} ${r.title}`:r.name):visible.filter((a:Row)=>(mode==='search'?a.search_id:a.team_id)===r.id&&(gridSort.key==='total'||a.work_date===gridSort.key)).reduce((n:number,a:Row)=>n+(a.target||0),0);
 const sortedEntities=[...entities].sort((a:Row,b:Row)=>compareTableValues(entityValue(a),entityValue(b),gridSort.descending)||String(a.id).localeCompare(String(b.id)));
 const gridHeading=(key:string,title:string)=><th key={key} scope="col" aria-sort={gridSort.key===key?(gridSort.descending?'descending':'ascending'):'none'}><button className="table-sort-heading" onClick={()=>setGridSort({key,descending:gridSort.key===key?!gridSort.descending:false})}>{title} <span aria-hidden="true">{gridSort.key===key?(gridSort.descending?'↓':'↑'):'↕'}</span></button></th>;
 function editPriority(s:Row,decisionWeek=week){const p=data.priorities.find((p:Row)=>p.search_id===s.id&&p.week===decisionWeek),effective=decisionFor(s.id,decisionWeek);setPriority({search_id:s.id,week:decisionWeek,disposition:effective?.disposition || 'Start',notes:effective?.notes || '',version:p?.version || 0,base_week:effective?.week||'',base_version:effective?.version||0});setError('');setDirty(false);}
 function allocation(id:string,review=false){setView('allocation');setMode('search');setRoles([id]);if(!review)openPair(id);}

 return <section className="panel weekly-planner">
  <div className="weekly-topbar"><div className="research-tabs"><button className={view==='decisions'?'primary':''} onClick={()=>{setView('decisions');}}>Sourcing Decisions</button><button className={view==='allocation'?'primary':''} onClick={()=>{setView('allocation');}}>Team Allocation</button></div><div className="weekly-top-actions">{planner&&view==='allocation'&&<button disabled={busy||dirty} onClick={()=>{setError('');setCopy(carryoverAssignments(data,week).filter((a:Row)=>eligible(searches.get(a.search_id)||{id:a.search_id})&&(mode!=='team'||teamFilters===null||teamFilters.includes(a.team_id))));}}>Copy previous week</button>}<TimeOff data={data} dates={dates} api={api} reload={reload} disabled={dirty||busy}/></div></div>
  <div className="plan-toolbar">
   <button aria-label="Previous week" onClick={()=>setWeek(addDays(week,-7))}>←</button>
   <label>Week of Monday<input type="date" value={week} onChange={e=>{if(e.target.value)setWeek(weekStart(e.target.value));}}/></label>
   <button aria-label="Next week" onClick={()=>setWeek(addDays(week,7))}>→</button>
   <button onClick={()=>setWeek(weekStart(new Date().toLocaleDateString('en-CA')))}>This week</button>
   {view==='allocation'&&<label>View<select value={mode} onChange={e=>{setMode(e.target.value as 'search'|'team');setFilter('');}}><option value="search">By search</option><option value="team">By team</option></select></label>}
   {<SearchMultiFilter searches={data.searches.filter((s:Row)=>statusFilters===null||statusFilters.includes(searchStatus(s.status)))} value={roles} onChange={setRoles} disabled={dirty||busy}/>}{view==='allocation'&&mode==='team'&&<div><span className="filter-label">Teams</span><ColumnFilter label="teams" options={data.teams.map((t:Row)=>t.id)} selected={teamFilters} onChange={setTeamFilters} optionLabel={id=>teams.get(id)?.name||id}/></div>}
   <div><span className="filter-label">Sourcing decisions</span><ColumnFilter label="sourcing decisions" options={['Not decided',...sourcingDecisions]} selected={decisionFilters} onChange={setDecisionFilters}/></div>
   <div><span className="filter-label">Search status</span><ColumnFilter label="search status" options={[...new Set<string>([...searchStatuses,...data.searches.map((s:Row)=>searchStatus(s.status))])]} selected={statusFilters} onChange={setStatusFilters}/></div>
  </div>
  {notice&&<p className="notice" role="status">{notice}</p>}
  {!editor&&!priority&&!change&&error&&<p className="error" role="alert">{error}</p>}
  {!data.teams.length&&<p className="source-note">Create teams and add their researchers in Teams before allocating work.</p>}
  {view==='decisions'?<SearchDecisions onCandidate={onCandidate} data={data} roles={decisionRoles} week={week} canEdit={planner} onDecide={editPriority} onAllocate={id=>allocation(id)} onReviewPlan={(id,date)=>{setWeek(weekStart(date));allocation(id,true);}}/>:<div className="plan-scroll"><table className={'plan-grid allocation-compact '+(mode==='search'?'allocation-by-search':'allocation-by-team')}><thead><tr>{mode==='search'&&<>{gridHeading('search_number','Search ID')}{gridHeading('status','Status')}</>}{gridHeading('name',mode==='search'?'Search / weekly priority':'Team / researchers')}{dates.map(d=>gridHeading(d,label(d)))}{gridHeading('total','Week target')}</tr></thead><tbody>
   {sortedEntities.map((r:Row)=>{const row=visible.filter((a:Row)=>(mode==='search'?a.search_id:a.team_id)===r.id),p=decisionFor(r.id);return <tr key={r.id}>
    {mode==='search'&&<><td>{r.search_number??'—'}</td><td>{searchStatus(r.status)}</td></>}<th scope="row">{mode==='search'?<><strong>{r.client}</strong><span>{r.title}</span><small>Partner: {r.partner || 'Not assigned'}</small><div className="priority-line"><span className={p?`decision-state decision-state-${p.disposition.toLowerCase()}`:"plan-priority-text priority-text-none"}>{p?.disposition || 'No priority'}</span>{planner&&<IconAction label={`${p?'Edit':'Set'} sourcing decision`} accessibleLabel={`${p?'Edit':'Set'} weekly priority for ${r.client} — ${r.title}`} onClick={()=>editPriority(r)}><PencilSimple size={16}/></IconAction>}</div>{p?.notes&&<small>{p.notes}</small>}</>:<><strong style={{borderLeft:`4px solid ${teamColor(r.name,r.id)}`,paddingLeft:6}}>{r.name}</strong><small>{data.team_members.filter((m:Row)=>m.team_id===r.id).map((m:Row)=>data.staff.find((s:Row)=>s.id===m.staff_id)?.name).join(', ')||'No members configured'}</small>{canPlan(data.actor)&&<button onClick={onTeams}>Edit team</button>}</>}</th>
    {dates.map(date=>{const cell=row.filter((a:Row)=>a.work_date===date),cellTasks=tasks.filter((t:Row)=>t.work_date===date&&(mode==='search'?t.role_id===r.id:t.team_id===r.id)&&eligible(searches.get(t.role_id)||{id:t.role_id}));return <td key={date}>
     {cell.map((a:Row)=>{const other=mode==='search'?teams.get(a.team_id)?.name:`${searches.get(a.search_id)?.client} · ${searches.get(a.search_id)?.title}`;const disposition=decisionFor(a.search_id)?.disposition,warnings=warningsFor(date,a.team_id);return <div className={`plan-assignment priority-${(disposition||'none').toLowerCase()}`} key={a.id}><button className="plan-slot" disabled={!planner} onClick={()=>{setEditor(pair(a.search_id,a.team_id));setError('');setDirty(false);}}>{teamBadge(a.team_id)}{mode==='team'&&<span>{other}</span>}<strong>{a.target??'—'} <small>target</small></strong></button><div className="allocation-actions">{planner&&<><IconAction label="Add assignment" accessibleLabel={`Add assignment for ${mode==='search'?r.title:r.name} on ${label(date)}`} onClick={()=>openPair(mode==='search'?r.id:'',mode==='team'?r.id:'',date)}><Plus size={16}/></IconAction><IconAction label="Move / unassign" accessibleLabel={`Move or unassign ${other} on ${label(date)}`} onClick={()=>openChange(a.search_id,a.team_id,date)}><ArrowsLeftRight size={16}/></IconAction></>}{warnings.length>0&&<span className="allocation-overload"><IconAction label="Allocation conflict" accessibleLabel={`View allocation conflicts for ${teams.get(a.team_id)?.name} on ${label(date)}`} onClick={()=>setWorkload({team:a.team_id,date})}><WarningCircle size={17} weight="fill"/></IconAction></span>}</div></div>;})}
     {cellTasks.length>0&&<details className="plan-other-tasks"><summary>{cellTasks.length} other task{cellTasks.length===1?'':'s'} <span className="plan-team-dots">{[...new Set<string>(cellTasks.map((t:Row)=>t.team_id))].map(id=><span key={id} title={teams.get(id)?.name} style={{background:teamColor(teams.get(id)?.name||'',id)}}/>)}</span></summary><div className="plan-task-popover">{cellTasks.map((t:Row)=><div className="plan-task-mini" key={t.id}>{teamBadge(t.team_id)}<strong>{t.title||t.task_type}</strong><small>{data.people.find((p:Row)=>p.id===t.owner_id)?.name||'Former member'} · {t.status}</small>{mode==='team'&&<small>{searches.get(t.role_id)?.client} · {searches.get(t.role_id)?.title}</small>}</div>)}</div></details>}

     {planner&&!cell.length&&(mode==='team'||isWorkingDecision(decisionFor(r.id)))&&<button className="plan-icon plan-assign-icon" title="Assign" aria-label={`Plan ${mode==='search'?r.title:r.name} on ${label(date)}`} onClick={()=>openPair(mode==='search'?r.id:'',mode==='team'?r.id:'',date)}><Plus size={16}/></button>}
     {!cell.length&&!cellTasks.length&&!planner&&<span className="fine">—</span>}
    </td>;})}<td><strong>{row.reduce((n:number,a:Row)=>n+(a.target||0),0)}</strong>{row.some((a:Row)=>a.target===null)&&<small>Some targets unset</small>}</td></tr>;})}
   {!entities.length&&<tr><td colSpan={mode==='search'?11:9}>No {mode==='search'?'searches':'teams'} match this view.</td></tr>}
  </tbody><tfoot><tr><th colSpan={mode==='search'?3:1}>Visible target total</th>{dates.map(date=><td key={date}>{visible.filter((a:Row)=>a.work_date===date).reduce((n:number,a:Row)=>n+(a.target||0),0)}</td>)}<td>{visible.reduce((n:number,a:Row)=>n+(a.target||0),0)}</td></tr></tfoot></table></div>}
  {view==='allocation'&&!editor&&!priority&&!change&&<PlanningTasks data={data} api={api} reload={reload} from={dates[0]} to={dates[6]} roles={decisionRoles.map((r:Row)=>r.id)} teamIds={mode==='team'?teamFilters:null} onDirty={onDirty}/>}
  {workload&&<Popup title={`Allocation conflicts · ${teams.get(workload.team)?.name} · ${label(workload.date)}`} onClose={()=>setWorkload(null)}>{warningsFor(workload.date,workload.team).map(w=><p key={w.staff}><strong>{w.name}</strong> · {w.pto?'Scheduled during PTO':w.count+' planned items'}</p>)}<h3>Search allocations</h3>{data.assignments.filter((a:Row)=>a.work_date===workload.date&&a.team_id===workload.team).map((a:Row)=><p key={a.id}>{searches.get(a.search_id)?.client} · {searches.get(a.search_id)?.title}</p>)}<h3>Other tasks</h3>{tasks.filter((t:Row)=>t.work_date===workload.date&&t.team_id===workload.team&&t.status!=='Completed').map((t:Row)=><p key={t.id}>{t.title||t.task_type} · {data.people.find((p:Row)=>p.id===t.owner_id)?.name}</p>)}</Popup>}
  {copy&&<div className="modal-backdrop"><section className="modal plan-modal" role="dialog" aria-modal="true" aria-label="Copy previous week"><div className="section-head"><h2>Copy previous week</h2><button disabled={busy} onClick={()=>setCopy(null)}>Cancel</button></div><p>{copy.length} allocations for the week of {displayDate(week)}. Existing allocations are kept. Closed or paused searches, past days and people on PTO are excluded.</p><div className="table-scroll"><table className="sheet-table"><thead><tr><th>Search ID</th><th>Search</th><th>Team</th><th>Date</th><th>Researchers</th><th>Target</th></tr></thead><tbody>{copy.map(a=><tr key={a.source_id}><td>{searches.get(a.search_id)?.search_number??'—'}</td><td>{searches.get(a.search_id)?.title}</td><td>{teams.get(a.team_id)?.name}</td><td>{displayDate(a.work_date)}</td><td>{a.staff_ids.map((id:string)=>data.staff.find((s:Row)=>s.id===id)?.name).join(', ')}</td><td>{a.target??'—'}</td></tr>)}</tbody></table></div>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy||!copy.length||copy.length>500} onClick={async()=>{setBusy(true);setError('');try{await api('mutate',{kind:'week-copy',week,items:copy});await reload();setNotice(copy.length+' allocations copied.');setCopy(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>{busy?'Copying…':'Copy '+copy.length+' allocations'}</button></section></div>}
  {change&&<div className="modal-backdrop"><section className="modal plan-modal" role="dialog" aria-modal="true" aria-labelledby="transfer-title"><div className="section-head"><h2 id="transfer-title">Move or unassign planned work</h2><button disabled={busy} onClick={close}>Cancel</button></div><p><strong>{searches.get(change.search_id)?.client} · {searches.get(change.search_id)?.title}</strong><br/>Currently planned for {teams.get(change.team_id)?.name}</p><form onSubmit={transfer}><label>Action<select value={change.operation} disabled={busy} onChange={e=>setChange({...change,operation:e.target.value})}><option value="move" disabled={!isWorkingDecision(decisionFor(change.search_id))}>Move to another team</option><option value="unassign">Unassign selected days</option></select></label>{change.operation==='move'&&<label>New team<select required disabled={busy} value={change.destination_team_id} onChange={e=>setChange({...change,destination_team_id:e.target.value})}><option value="">Choose team</option>{data.teams.filter((t:Row)=>t.id!==change.team_id).map((t:Row)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}<div className="row-actions"><button type="button" disabled={busy} onClick={()=>setChange({...change,selected:change.rows.filter((a:Row)=>!a.has_work).map((a:Row)=>a.id)})}>Select all unstarted days this week</button><button type="button" disabled={busy} onClick={()=>setChange({...change,selected:[]})}>Clear selection</button></div><table className="sheet-table"><thead><tr><th>Select</th><th>Day</th><th>Target</th><th>Work status</th></tr></thead><tbody>{change.rows.map((a:Row)=><tr key={a.id}><td><input type="checkbox" aria-label={'Change assignment on '+a.work_date} disabled={busy||a.has_work} checked={change.selected.includes(a.id)} onChange={e=>setChange({...change,selected:e.target.checked?[...change.selected,a.id]:change.selected.filter((id:string)=>id!==a.id)})}/></td><td>{label(a.work_date)}</td><td>{a.target??'—'}</td><td>{a.has_work?'Recorded work — attribution retained':'Not started'}</td></tr>)}</tbody></table><p className="fine">Moving retains daily targets and notes and uses the new team’s current researcher roster. This changes the weekly plan; company ownership is managed separately under the role’s Target companies. Existing candidate work keeps its original attribution.</p>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy||!change.selected.length||change.operation==='move'&&!change.destination_team_id}>{busy?'Saving…':change.operation==='move'?'Move selected assignments':'Unassign selected days'}</button></form></section></div>}
  {(editor||priority)&&<div className="modal-backdrop"><section className="modal plan-modal" role="dialog" aria-modal="true" aria-labelledby="plan-title"><div className="section-head"><h2 id="plan-title">{editor?'Plan the week':'Sourcing decision'}</h2><button disabled={busy} onClick={close}>Close</button></div>
   {error&&<p className="error" role="alert">{error}</p>}
   {editor?<form onSubmit={savePlan}>
    <div className="plan-selectors"><label>Search<select required disabled={busy||editor.days.some((d:Row)=>d.id)} value={editor.search_id} onChange={e=>choosePair(e.target.value,editor.team_id)}><option value="">Choose search</option>{data.searches.filter((s:Row)=>s.id===editor.search_id||isWorkingDecision(decisionFor(s.id))).map((s:Row)=><option key={s.id} value={s.id}>{s.client} · {s.title}</option>)}</select></label>
    <label>Team<select required disabled={busy||editor.days.some((d:Row)=>d.id)} value={editor.team_id} onChange={e=>choosePair(editor.search_id,e.target.value)}><option value="">Choose team</option>{data.teams.map((t:Row)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label></div>
    {editor.days.some((d:Row)=>d.id)&&<button type="button" disabled={busy} onClick={()=>openChange(editor.search_id,editor.team_id)}>Move / unassign this week’s assignments</button>}

    {editor.days.length>0&&<>
    <div className="table-scroll"><table className="plan-editor"><thead><tr><th>Work?</th><th>Day</th><th>Researchers</th><th>Daily approval target</th><th>Notes</th></tr></thead><tbody>{editor.days.map((d:Row,i:number)=><tr key={d.date}><td><input type="checkbox" aria-label={`Work on ${label(d.date)}`} checked={d.enabled} disabled={busy||!editor.search_id||!editor.team_id} onChange={e=>changeDay(i,{enabled:e.target.checked})}/></td><th>{label(d.date)}{d.id&&<small>Existing · {data.entries.filter((e:Row)=>e.assignment_id===d.id).map((e:Row)=>data.staff.find((s:Row)=>s.id===e.staff_id)?.name).join(', ')||'no researchers'}</small>}</th><td>{data.staff.filter((s:Row)=>d.staff_ids.includes(s.id)||data.team_members.some((m:Row)=>m.team_id===editor.team_id&&m.staff_id===s.id)).map((s:Row)=><label key={s.id} style={{display:'flex',gap:6,alignItems:'center'}}><input type="checkbox" style={{width:'auto'}} aria-label={`${s.name} on ${label(d.date)}`} disabled={busy||!d.enabled||d.has_work} checked={d.staff_ids.includes(s.id)} onChange={e=>changeDay(i,{staff_ids:e.target.checked?[...d.staff_ids,s.id]:d.staff_ids.filter((id:string)=>id!==s.id)})}/>{s.name}{onPTO(s.id,d.date)&&' · PTO (0 person-days)'}</label>)}{d.has_work&&<small>Recorded work · allocation retained</small>}</td><td><input aria-label={`Target for ${label(d.date)}`} type="number" min="0" max="100000" step="1" required={d.enabled} disabled={!d.enabled||busy||!editor.search_id||!editor.team_id} value={d.target} onChange={e=>changeDay(i,{target:e.target.value})}/></td><td><input aria-label={`Notes for ${label(d.date)}`} disabled={!d.enabled||busy||!editor.search_id||!editor.team_id} value={d.notes} onChange={e=>changeDay(i,{notes:e.target.value})}/></td></tr>)}</tbody></table></div></>}
    <button className="primary" disabled={busy||editor.days.length!==7||!editor.search_id||!editor.team_id}>{busy?'Saving…':'Save week'}</button>
   </form>:<form onSubmit={savePriority}><p>{searches.get(priority!.search_id)?.client} · {searches.get(priority!.search_id)?.title}</p><p>{displayDate(priority!.week)}</p><label>Sourcing decision<select value={priority!.disposition} disabled={busy} onChange={e=>{setPriority({...priority,disposition:e.target.value});setDirty(true);}}>{['Start','Continue','Recalibrate','Pause','Stop'].map(s=><option key={s}>{s}</option>)}</select></label><label>Reason / notes<textarea value={priority!.notes} disabled={busy} onChange={e=>{setPriority({...priority,notes:e.target.value});setDirty(true);}}/></label><p className="fine">Pause and Stop change the weekly priority. Review the grid to remove any unstarted daily assignments separately.</p><button className="primary" disabled={busy}>{busy?'Saving…':'Save decision'}</button></form>}
  </section></div>}
 </section>;
}

