import {SortableTable} from './SortableTable';
import React,{useState} from 'react';
import {workflowSummary} from './workflow-summary';
type R=Record<string,any>;
export function WorkflowMonitor({data,onOpen}:{data:R;onOpen:(role:string,tab:string)=>void}) {
 const [query,setQuery]=useState(''),[onlyBlocked,setOnlyBlocked]=useState(false);
 const rows=workflowSummary(data).filter((r:R)=>[r.role.client,r.role.title].join(' ').toLowerCase().includes(query.toLowerCase())&&(!onlyBlocked||r.bottlenecks.length));
 const sum=(key:string)=>rows.reduce((n:number,r:R)=>n+r[key],0);
 return <section className="panel workflow-monitor"><div className="section-head"><div><h2>Search delivery progress</h2><p>See what has been mapped, how much company research is complete, and where work is waiting.</p></div></div><div className="sheet-toolbar"><label>Find client or role<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="All searches"/></label><label className="checkbox"><input type="checkbox" checked={onlyBlocked} onChange={e=>setOnlyBlocked(e.target.checked)}/>Only searches needing attention</label></div><div className="metrics">{[['Mappings submitted',sum('submitted')],['Partner approved',sum('approved')],['Companies completed',`${sum('completed')} / ${sum('targets')}`],['Awaiting team / partner',`${sum('peer')} / ${sum('partner')}`]].map(([k,v])=><div className="metric" key={k}><p>{k}</p><strong>{v}</strong></div>)}</div>
 <div className="sheet-scroll"><SortableTable stateKey="WorkflowMonitor.table1" className="sheet-table"><thead><tr><th>Search ID</th><th>Client / search</th><th>Mapping progress</th><th>Company coverage</th><th>Review queues</th><th>Needs attention</th><th>Open details</th></tr></thead><tbody>{rows.map((r:R)=><tr key={r.role.id}><td>{r.role.search_number??'—'}</td><td><strong>{r.role.client}</strong><small>{r.role.title}</small></td><td><strong>{r.submitted} submitted · {r.approved} approved</strong><small>{r.drafts} drafts{r.direct>0?` · ${r.direct} submitted outside the target-company list`:''}</small></td><td><strong>{r.completed} / {r.targets} companies complete</strong><small>{r.noTalent} complete — no relevant talent found</small><small>{r.withMappings} / {r.targets} companies with submitted mappings</small></td><td>{r.peer} team · {r.partner} partner<small>{r.peer+r.partner?`Oldest waiting: ${r.oldest} days`:'No reviews waiting'}</small></td><td>{r.bottlenecks.length?r.bottlenecks.map((b:string)=><div key={b}>{b}</div>):'No blockers recorded'}</td><td><div className="row-actions"><button onClick={()=>onOpen(r.role.id,'Target companies')}>Coverage & assignments</button><button onClick={()=>onOpen(r.role.id,'Candidate mappings')}>Candidate mappings</button></div></td></tr>)}</tbody></SortableTable></div>{!rows.length&&<p>No searches match these filters.</p>}
 <p className="fine">Company completion means its research scope is marked Completed or No relevant talent. A company with mapped candidates is not automatically complete. Drafts do not count as submitted output. Detailed companies and candidates stay in the search repository.</p></section>;
}
