import React,{useEffect,useState} from 'react';
type R=Record<string,any>;
const labels:Record<string,string>={searches:'Searches / jobs',staff:'Researcher records',teams:'Teams',assignments:'Daily allocations and targets',entries:'Output and assignment records',reviews:'Legacy reviews',weekly_priorities:'Weekly priorities',weekly_decisions:'Decision history',research_records:'Companies, candidates, mappings and role documents',crm_jobs:'CRM preview jobs',crm_partners:'Saved CRM partner selections',effort_records:'Recorded effort',time_off:'PTO records'};
export function WorkspaceReset({api,reload,onDirty}:{api:(p:string,b?:unknown)=>Promise<any>;reload:()=>Promise<void>;onDirty:(v:boolean)=>void}){
 const [preview,setPreview]=useState<R|null>(null),[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<R|null>(null),[backups,setBackups]=useState<R[]>([]),[baselineMessage,setBaselineMessage]=useState('');
 useEffect(()=>{api('workspace-reset',{action:'backups'}).then(setBackups).catch(()=>{});},[result,baselineMessage]);
 useEffect(()=>{onDirty(!!preview);return()=>onDirty(false);},[!!preview]);
 async function download(id:string){setBusy(true);setError('');try{const backup=await api('workspace-reset',{action:'backup',id});const url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`workspace-backup-${id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <details className="panel"><summary>Reset workspace test data</summary><p>Clear all searches, companies, candidates, mappings, teams, targets, plans, actuals, PTO and saved CRM selections. Keep your owner account, its permissions and password, and the RecruitCRM connection. RecruitCRM itself is unchanged.</p><p className="fine">A recovery snapshot is saved before clearing records. Audit history remains private. Recovery requires administrator assistance; there is no automatic undo.</p>
 <p><button disabled={busy||backups.some(b=>b.kind==='clean-baseline')} onClick={async()=>{setBusy(true);setError('');try{await api('workspace-reset',{action:'save-baseline'});setBaselineMessage('Clean baseline saved. No working data was changed.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>Save clean baseline</button></p>
 {baselineMessage&&<p role="status">{baselineMessage}</p>}
 <button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{setPreview(await api('workspace-reset',{action:'preview'}));setEmail('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>Preview full reset</button>
 {error&&<p className="error" role="alert">{error}</p>}
 {result&&<div role="status"><p>{result.ok?'Workspace reset complete. Only your account remains.':result.error}</p><p>Recovery snapshot: {result.backupId}</p><button disabled={busy} onClick={()=>download(result.backupId)}>Download recovery snapshot</button></div>}
 {backups.length>0&&<details><summary>Saved recovery snapshots ({backups.length})</summary>{backups.map(b=><p key={b.id}><strong>{b.label||'Before reset'}</strong> · {new Date(b.created_at).toLocaleString()} <button disabled={busy} onClick={()=>download(b.id)}>Download snapshot</button></p>)}</details>}
 {preview&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="workspace-reset-title"><h2 id="workspace-reset-title">Reset workspace</h2><p>Keep <strong>{preview.people.keep.name} — {preview.people.keep.email}</strong>.</p><p>Remove {preview.people.remove.length} other workspace accounts and cancel {preview.people.invitations} invitations.</p><ul>{preview.people.remove.map((p:R)=><li key={p.id}>{p.name} — {p.email}</li>)}</ul><table className="sheet-table"><thead><tr><th>Records to clear</th><th>Count</th></tr></thead><tbody>{Object.entries(labels).map(([key,label])=><tr key={key}><td>{label}</td><td>{preview.counts[key]||0}</td></tr>)}</tbody></table><p>Related ownership, sharing and import records are also cleared. Old candidate invitation links stop working. A recovery snapshot is retained before deletion.</p><label>Type your sign-in email to confirm<input value={email} disabled={busy} onChange={e=>setEmail(e.target.value)}/></label>{error&&<p className="error">{error}</p>}<div className="row-actions"><button disabled={busy} onClick={()=>setPreview(null)}>Cancel</button><button className="danger" disabled={busy||email.trim().toLowerCase()!==preview.people.keep.email} onClick={async()=>{setBusy(true);setError('');try{const r=await api('workspace-reset',{action:'reset',signature:preview.signature,peopleSignature:preview.people.signature,confirmEmail:email});setResult(r);setPreview(null);await reload();}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>{busy?'Resetting…':'Clear test data and keep my account'}</button></div></section></div>}
 </details>;
}
